### ISSUE TITLE
Kaizen ceph cluster upgrade from 3.x to 4.x

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#1]
@naved001 as discussed during the devops meeting

**Comment by naved001** [comment]
upgrading the cluster to 4.x would also allow us to use ceph iscsi gateways (required for ESI).

https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/block_device_guide/the-ceph-iscsi-gateway#prerequisites_7

**Comment by msdisme** [comment]
Stuck machine in engage1 ceph - boot looping

**Comment by msdisme** [comment]
- [x] Stand up 3.x on engage

- [ ] upgrade engage to 4.x

- [ ] notification to all users of ceph upgrade - 1 week in advance

- [ ] upgrade kaizen ceph to 4.x

**Comment by naved001** [comment]
I upgraded the engage1 ceph cluster using ceph-ansible scripts. However, it did not upgrade 3 OSD nodes, the rgw servers and unset a bunch of flags since it failed to run in its entirety. I then upgraded the rest the of nodes manually. Because we already have one broken OSD server, the upgrade process caused some more issues when the OSD nodes were being upgraded. The cluster has since then been slowly recovering.
```
  cluster:
    id:     6e054e7a-295a-4760-b4d5-17797e18c82b
    health: HEALTH_WARN
            1 pools have many more objects per pg than average
            Degraded data redundancy: 48478/19801812 objects degraded (0.245%), 176 pgs degraded, 176 pg
s undersized
            6 slow ops, oldest one blocked for 802 sec, osd.90 has slow ops

  services:
    mon: 3 daemons, quorum ceph-quanta01,ceph-quanta02,ceph-quanta03 (age 16h)
    mgr: ceph-quanta01(active, since 16h), standbys: ceph-quanta03, ceph-quanta02
    osd: 90 osds: 71 up (since 16h), 71 in (since 16h); 336 remapped pgs
    rgw: 2 daemons active (e1-radosgw-01, e1-radosgw-02)

  task status:

  data:
    pools:   15 pools, 4256 pgs
    objects: 6.32M objects, 18 TiB
    usage:   55 TiB used, 203 TiB / 258 TiB avail
    pgs:     48478/19801812 objects degraded (0.245%)
             92640/19801812 objects misplaced (0.468%)
             3740 active+clean
             336  active+clean+remapped
             176  active+undersized+degraded
             3    active+clean+scrubbing+deep
             1    active+clean+scrubbing
```

**Comment by msdisme** [comment]
Proposed Letter:
Dear MOC User,

The primary storage for the MOC clusters is on a ceph based cluster of computers and storage.  While ceph is fault-tolerant, you should always regularly make backups of your information. 

Next week, on Tuesday, December 8th, we plan to upgrade the ceph software to a more recent version.   

While this should be invisible to you, we urge you to make sure you perform backups of your information (data, program files, anything you cannot afford to lose) and store it someplace other than on the MOC.

Regards,  

Mass Open Cloud

**Comment by naved001** [comment]
@msdisme looks good to me.

**Comment by naved001** [comment]
About the enage1 ceph cluster.

On host `ceph-lenovo08` all OSD were down and the respective OSD service were masked. So I unmasked and started those; then all OSDs on that host came up. 

On host `ceph-lenovo04`, once osd is still down `osd.43`. This is what I see:
```
[root@ceph-lenovo04 ~]# systemctl status ceph-osd@43.service
● ceph-osd@43.service - Ceph object storage daemon osd.43
   Loaded: loaded (/usr/lib/systemd/system/ceph-osd@.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2020-12-02 10:35:07 EST; 1min 0s ago
 Main PID: 547657 (code=killed, signal=ABRT)

Dec 02 10:35:07 ceph-lenovo04 systemd[1]: Unit ceph-osd@43.service entered failed state.
Dec 02 10:35:07 ceph-lenovo04 systemd[1]: ceph-osd@43.service failed.
Dec 02 10:35:23 ceph-lenovo04 systemd[1]: start request repeated too quickly for ceph-osd@43.service
Dec 02 10:35:23 ceph-lenovo04 systemd[1]: Failed to start Ceph object storage daemon osd.43.
Dec 02 10:35:23 ceph-lenovo04 systemd[1]: ceph-osd@43.service failed.
Dec 02 10:35:49 ceph-lenovo04 systemd[1]: [/usr/lib/systemd/system/ceph-osd@.service:15] Unknown lvalue 'LockPersonality' in section 'Service'
Dec 02 10:35:49 ceph-lenovo04 systemd[1]: [/usr/lib/systemd/system/ceph-osd@.service:16] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
Dec 02 10:35:49 ceph-lenovo04 systemd[1]: [/usr/lib/systemd/system/ceph-osd@.service:19] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Dec 02 10:35:49 ceph-lenovo04 systemd[1]: [/usr/lib/systemd/system/ceph-osd@.service:21] Unknown lvalue 'ProtectKernelModules' in section 'Service'
Dec 02 10:35:49 ceph-lenovo04 systemd[1]: [/usr/lib/systemd/system/ceph-osd@.service:23] Unknown lvalue 'ProtectKernelTunables' in section 'Service'
```
Still trying to figure out what's going on; though there's no degraded data at this point.

And then there's this warning
```
1 pools have many more objects per pg than average
```

**Comment by naved001** [comment]
Kaizen ceph cluster has been upgraded to nautilus (`ceph version 14.2.8-111.el7cp (2e6029d57bc594eceba4751373da6505028c2650) nautilus (stable)`)

I have also raised the minimum client versions allowed to luminous (it was set to firefly). 

Also set [CRUSH tunables to optimal](https://docs.ceph.com/en/latest/rados/operations/crush-map/#warning-when-tunables-are-non-optimal)
