### ISSUE TITLE
Gather OpenShift Billing Data for June

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1005]
Using standards from [Billing Requirements](https://docs.google.com/document/d/1SHCMidWQmazACGqzYOlRHQqnsg4KjmeW8ShGiEptR2Q/edit?pli=1#heading=h.ggr79xagepw4), specifically Monthly Billing Data CSV we need a CSV that provides the following data.
Project | Manager (PI) | Institution | Billing Type | Billing Type Hours | Billing Price | Cost
-- | -- | -- | -- | -- | -- | -- 

Billing Type is broken into 4 types (CPU SU, A100 GPU SU, A2 GPU SU, and Storage). Billing Type Multiplier represents SUs for the SUs and Storage size for Storage. Storage is charged separately at a granularity of KB/hr.

We can use the OpenShift billing tool created [here](https://github.com/CCI-MOC/ops-issues/issues/907).

Until we find a better way we will need to make sure we backup the data every 2 weeks so that we have a full month's worth of data.

**Comment by joachimweyl** [comment]
@naved001 the data you were using for the sample data you showed in your spreadsheet when was that pulled? was that less than 2 weeks ago? Is there a way to get more than 2 weeks from the backend similar to how @knikolla did with Nova?

**Comment by naved001** [comment]
I don't remember when I pulled that. But how can we rely on that data when we hadn't even settled on the math(fractional SU etc) ?

As far as I know there is no database to go into to look for this historical data.

**Comment by joachimweyl** [comment]
When you pulled the data for the spreadsheet the data was not saved. I misunderstood, I assumed the data was an export of some sort. Is there a way to export that data so that we can process 2 weeks' worth of data with the next 2 weeks' worth of data for July?

**Comment by joachimweyl** [comment]
@naved001 are any of the current projects in OpenShift potentially customers, or are they all currently people testing like Milson, Nathan, and I?

**Comment by joachimweyl** [comment]
@msdisme for the email to our users about June usage. Are we looking for exact numbers or would ballpark figures be adequate? We can sum up from the 7th and calculate what it would be like from the data we do have.

**Comment by joachimweyl** [comment]
@msdisme agrees we can extrapolate approximate June usage based on the data that we do have.

**Comment by joachimweyl** [comment]
@naved001 can we add a link to the csv here? Private google sheet or csv.

**Comment by naved001** [comment]
@joachimweyl okay, I have updated the sheet with new columns,

the memory and cpu hours are extrapolated for the whole month, and then SU hours for the month are calculated based on the new memory and cpu hours.
