### ISSUE TITLE
Run Dell Information Generation Script against Two Sigma Donation 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1009]
The Asset Ids are located here: https://docs.google.com/spreadsheets/d/1WkVlHszMLPzIGOs2VV8nyJKn_GJdrQQG/edit?usp=drive_link&ouid=111874645414752393627&rtpof=true&sd=true

**Comment by joachimweyl** [comment]
@hakasapl what are the next steps for this since the original script you had is no longer compatible?

**Comment by hmccanne** [comment]
Shipment received by Flax.  We scanned all Service Tags/Serial numbers that arrived.   Result in attached file.
Summary of discrepancies:

**Not Received:**

- 24 Cisco 3064
- 5 FX2 Chassis
- 25 R620/R630

**Received but not in manifest:**

- 23 FC630
- 1 FX2 Chassis


[Two-Sigma-Deprecated-Equipment-July.xlsx](https://github.com/CCI-MOC/ops-issues/files/12650455/Two-Sigma-Deprecated-Equipment-July.xlsx)
