### ISSUE TITLE
Flax: Pricing for upgrading FX2 chassis to 25GB

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1010]

**Comment by msdisme** [comment]
Needed for research rack; other racks will likely be as needed.  Cabling should support both 25 and 10 to minimize upgrade costs

**Comment by joachimweyl** [comment]
@hakasapl I have assigned this to you to help keep track of it and keep on Flax so we know how things are going.

**Comment by msdisme** [comment]
$125 per server for NIC.   Break out cable pricing, pending Scott's saved cables.

**Comment by hakasapl** [comment]
These have been purchased and installed at this point
