### ISSUE TITLE
Zenhub Access for Flax team members

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1011]
Erik is open to having his team look at Zenhub since it will allow a higher level view into some of our planning (Epics.) 

Do we have any concerns about this?  if not the folks it makes sense to add are: Harlan, Shannon and Erik and then @joachimweyl would do a brief overview with them.   At that point we would probably also want to add them as collaborators on ops-issues

**Comment by joachimweyl** [comment]
My initial concern is that giving them access to Zenhub means they have access to changing the workspace. My first instinct is to create a new linked workspace.
@er1p what would your team find most useful about ZenHub access? Ability to see the prioritization of Flax-related issues? Get an export of prioritized Flax-related issues to import into your Project Management software?

**Comment by joachimweyl** [comment]
it does not seem like Flax has much interest in ZenHub. I will close this until they show more interest and then we can reopen it.
