### ISSUE TITLE
Move hardware out of R3-PB odd side

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1017]
There is various things that need to be moved. We need to send communication for any downtime (indicated below):

* Production CEPH - No Downtime
* neu-03-30, neu-05-30 ISCSI Server - **Downtime**
* OVirt Cluster - No Downtime
* NEU Peter Cache Servers - **Downtime**
* neu-19-10 maas VM host - **Downtime**

The downtime will be during the week of the 10th for those indicated, but will likely only last a few hours per host.

@joachimweyl could you send notices for the caches servers? @naved001 does anyone else need notice for the maas VM host and the iscsi servers?

The 2 10G cisco switches will be the top-of-rack on the even side. We will uplink to OCT while the ESI core is built up.

**Comment by joachimweyl** [comment]
For the NEU @pjd-nu Cache Servers do we have a more specific time than the week of the 10th?

**Comment by hakasapl** [comment]
Let's say any time on the 10th, we'll plan to move those first.

**Comment by joachimweyl** [comment]
Do we have a list of users of Peter's Cache Servers?

**Comment by hakasapl** [comment]
Split into different issues
