### ISSUE TITLE
Move Production Ceph

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1019]
Various spots of R3-PB odd side to R3-PB even side. This will not require downtime, we will move OSDs one by one.

**Comment by naved001** [comment]
@hakasapl let's start by moving a monitor node first (neu-19-14 or 17-14 or -5-14), then we can do the OSDs.

**Comment by naved001** [comment]
This was successfully completed after some switchport configuration for all the servers. One of the nvme drive on the OSD server has failed which we should plan to replace soon.

```
[root@kzn-mon1 ~]# ceph osd tree down
ID    CLASS WEIGHT   TYPE NAME               STATUS REWEIGHT PRI-AFF
-1002       72.99988 root performance
  -33        7.29999     host kzn-osd07-nvme
  274   ssd  7.29999         osd.274           down        0 1.00000
```
