### ISSUE TITLE
Move OVirt cluster and ovirt storage hosts (title edited by naved)

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1023]
4 hosts will move to R3-PB even side. This should be able to occur without downtime by moving VMs between hosts while the physical hardware is moved.

**Comment by naved001** [comment]
There are 3 ovirt hosts (U40 of Cage 3,5, and 15). The 2 hosts at U40 of Cage 17 and 19 provide SSD storage to the ovirt cluster so they also need to be moved. 

Also, no need to move the MaaS VM host for now since HL/BMI is being decommissioned anyway. 

So, in total there are 5 hosts to be moved.
