### ISSUE TITLE
Deploy Netgate Firewall Appliance

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1024]
This will go in R3-PB even side, along with where the ESI core switching will live once that is deployed later.

**Comment by hakasapl** [comment]
It has arrived at the loading dock but I haven't picked it up yet. Moving this to next sprint.

**Comment by joachimweyl** [comment]
@hakasapl is this planned to be completed before this sprint is over or shall we push it out a sprint?

**Comment by hakasapl** [comment]
Firewall is installed in R6-PB-C02-U21
