### ISSUE TITLE
Select Hardware for new ESI Server location & plan how long the ESI move will take

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1025]
R640 in R6-PB-C02 are the old operate first controllers, which will now house the openstack controllers for ESI.

**Comment by naved001** [comment]
The controllers are: OCT10-04, OCT10-05 and OCT10-06 in U33, U32 and U31 respectively.

**Comment by naved001** [comment]
The controllers are: OCT10-04, OCT10-05 and OCT10-06 in U33, U32 and U31 respectively.

**Comment by naved001** [comment]
| U number | Host | Switchport (Left) core-1 | Switchport (Right) core-2 |
|----------|------|--------------------------|---------------------------|
|U31 | OCT10-06 | twentyFiveGigE 1/2/2 | interface TenGigabitEthernet 1/2/2 |
|U32 | OCT10-05 | twentyFiveGigE 1/2/1 | interface TenGigabitEthernet 1/2/1 |
|U33 | OCT10-04 | twentyFiveGigE 1/1/4 | interface twentyFiveGigE 1/1/4 |


I gathered this from the core switches based on the interface descriptions. Why are 2 of the ports TenGigabit?

Also what are the switchport for the R440 racked in U37? I am going by the cage diagram from netbox

<img width="358" alt="image" src="https://github.com/CCI-MOC/ops-issues/assets/20113064/13134a5f-4e8a-4576-89a1-a17b2d579a35">

**Comment by tzumainn** [comment]
Orthogonal question - will there also be a new undercloud machine?

**Comment by naved001** [comment]
@tzumainn yes, the the R440 racked in U37.

**Comment by joachimweyl** [comment]
@naved001 what is the current expected completion date for this task?

**Comment by naved001** [comment]
@tzumainn how long do you think it'll take us to deploy ESI once the undercloud and overcloud hosts are ready?

**Comment by tzumainn** [comment]
@naved001 I'd say 1-3 weeks:

* we have the esi-pilot repository that should be sufficient to do a deployment, with an update to parameters; however there'll be some time needed to adjust parameters, and a deployment can take a LONG time, so if something goes wrong it may not be obvious for a while
* we'll need to run the post-install scripts, and perhaps update them for the new environment as well
* various $things will almost definitely go wrong and need to be adjusted

**Comment by joachimweyl** [comment]
@naved001 with a 1-3 week time for ESI what time frame do we have for the under/overcloud?
