### ISSUE TITLE
Verify that everything remaining in R3-PB odd side is ready to be deprecated

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1031]
After moving everything, we need to verify that everything else is ready to be deprecated.

**Comment by naved001** [comment]
Everything besides the servers at U41 in all racks is ready to be deprecated. Hakan has communicated this to flax.

" In U41 of all 5 racks there is a supermicro 1U node. Those machine are the only ones we want to keep, so if you could just put them on one of the “keep” pallets in the back. There are 5 1U supermicros total"
