### ISSUE TITLE
Create Communication and Status update for downtime on July 10th

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1032]
Draft
---
Subject:
MOC Alliance outage July 10th - 11th, 2023
---
We will be performing upgrades to some of our hardware. Most of our
services will be down for a large part of July 10th, 2023. This upgrade
has the potential of extending to the 11th.

We will notify you when MOC services are available by updating the
MOC status [website][status].

Please be aware of the following outages:

1. NEU Cache Servers
1. SSO service, this means you will be unable to authenticate
1. Kaizen HIL/BMI service
   1. If your system is booted using BMI it will need to be
   powered off because the iSCSI servers will be powered off and moved.
1. ESI development servers will be cut off (kumo environment)
1. ESI production servers
1. Research Ceph Cluster
1. Due to Network interdependencies other systems may also be unreachable

Once services are back online, you will be responsible for restarting
any containers or other systems.

If you need access to any MOC-hosted data during this outage, please
obtain copies of your data before Monday, July 10th. During the outage,
the data center will be entirely without power, and access to MOC-hosted
services will be impossible.

As always, if you have questions, open a [support ticket][ticket].
The ticketing system will be available throughout the outage.

[ticket]: https://support.massopen.cloud
[status]: https://status.massopen.cloud/

**Comment by joachimweyl** [comment]
[Status page update](https://github.com/CCI-MOC/moc-status/pull/39) for this topic.

**Comment by joachimweyl** [comment]
- [ ] @naved001
- [ ] @msdisme
- [ ] @knikolla 
- [ ] @rob-baron 
Please review at your earliest convenience.

**Comment by msdisme** [comment]
@naved001 Is the assumption that it will just be on the 10th?

**Comment by naved001** [comment]
@msdisme depends, much of the outage will be caused by the public network becoming unavailable. If we move that first, then things will go down in small batches.

**Comment by joachimweyl** [comment]
@msdisme updated to include the possibility of the 11th. Letting them know that the status page will be updated to let them know if it is resolved.

**Comment by joachimweyl** [comment]
sent at 4:08
