### ISSUE TITLE
Two sets of rails need to be delivered from castaway - we think they got used for another groups servers.

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1036]
send photos to Jay

**Comment by msdisme** [comment]
vendor sending them

**Comment by joachimweyl** [comment]
@hakasapl have we recieved these rails?

**Comment by hakasapl** [comment]
Do we have a tracking number? And a shipping address that they used?

**Comment by msdisme** [comment]
I think they planned to come on site - I will dig through some old mail and check status.

**Comment by msdisme** [comment]
delivery planned for sept. 7.   @naved001 or @msdisme can let them into room.

**Comment by naved001** [comment]
The servers were racked today. One in each rack.
