### ISSUE TITLE
Test Lenovo A100 machine to see how it works in OpenShift when splitting resources between Pods

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1039]
Updated to accommodate new desired outcome
# Testing
Justin, Milson, and (RHODS & IBM)?
- [x] Confirm MIG works using a live CD
- [ ] Test Pods with 1/7th of the A100 GPU
- [ ] Test 28 pods each with 1/7th of an A100
- [ ] Test that we can reserve a specific amount for a GPU "SU" and use the rest of the resources without taking that from the reserved GPU resources
   - For example, the whole system has 4 GPU, 96 CPU, 384 GB RAM, and your "SU" is 1 GPU, 4 CPU, 16 GB RAM which leaves 80 CPU and 320 GB RAM
      - Can we then use up to 80 CPU and 320 GB RAM for other Pods?
      - If we do how do we make sure the last 16 CPUs and 64 GB RAM do not get taken so the GPUs can always be used
- [ ] Other tests to help understand how best to charge for GPU systems within OpenShift

**Comment by msdisme** [comment]
R8-PA-C23 - BU half of rack is fully populated & NEU half is empty (coordinate w Greg S. on exact location for node install)

**Comment by naved001** [comment]
I guess this is what we are talking about: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/openshift/mig-ocp.html

**Comment by msdisme** [comment]
@hpdempsey @okrieg - confirming that RHODS and IBM are queued up to do testing once the A100 is connected to the test cluster.   I think the details above may no longer be accurate based on discussion jul 17, 2023 - please update in a comment and we will update above.

**Comment by joachimweyl** [comment]
@jtriley How much of the testing listed in the Testing section of this Issue were we able to squeeze in during the time we had the A100 system?

**Comment by joachimweyl** [comment]
did not expect the node to be removed a week earlier than anticipated. We were unable to do much testing.
A100 MIG will not allow us to limited usage in OpenShift so this is not something we will be able to use
OpenStack will not work with MIG

**Comment by msdisme** [comment]
reopening for dec 2023 install

**Comment by joachimweyl** [comment]
blocked by https://github.com/nerc-project/operations/issues/468

**Comment by joachimweyl** [comment]
replaced by https://github.com/nerc-project/operations/issues/481
