### ISSUE TITLE
Document upcoming Rack moves

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1040]
Create a table of upcoming racks that will be added to our network.

Rack | Date ready for networking | Expected networking date | Hardware
-|-|-|-
R4-PA-C21 | 07/12 | 07/14 | 2 z9100, s3048, FC430s, FC630s, 2-4 modern systems
R3-PB-C03 | 07/31 | 08/14 | 2 z9100, s3048, FC430s, FC830s |
R3-PB-C05 | 07/31 | 08/14 | 2 z9100, s3048, FC430s, FC830s |
R3-PB-C15 | 07/31 | 08/14 | 2 z9100, s3048, FC430s, FC830s |
R3-PB-C17 | 07/31 | 08/14 | 2 z9100, s3048, FC430s, FC830s |
R3-PB-C19 | 07/31 | 08/14 | 2 z9100, s3048, FC430s, FC830s |
R6-PB-C02 | 07/31 | 08/14 | 2 z9100, s3048, FC430s, FC830s |

**Comment by joachimweyl** [comment]
@hakasapl if you have a better way to organize this table feel free to make any changes you wish.

**Comment by joachimweyl** [comment]
@hakasapl where does this issue fall in your priorities list currently?

**Comment by hakasapl** [comment]
I've edited your original post on this issue, these are estimated dates, but it somewhat depends on the facility's timeline as well.

**Comment by joachimweyl** [comment]
@hakasapl are the R4-PA-C21 dates still accurate?

**Comment by hakasapl** [comment]
That rack is networked now yes, with a temporary uplink to the cisco switches.

**Comment by joachimweyl** [comment]
@hakasapl for R6-PB-C02 are you referring to [this issue](https://github.com/CCI-MOC/ops-issues/issues/1025)?
