### ISSUE TITLE
Add Flax team members to new github team with access to ops-issues

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1043]
As a person who works with flax I would like them to be part of a github team with access to the ops-issues items so that we may assign and ask questions of them.

- [x] create flax github team
- [ ] add flax folks via email

**Comment by msdisme** [comment]
@er1p - who should we add other than you?

**Comment by hmccanne** [comment]
Hi,  
You can add me,
--Harlan

**Comment by msdisme** [comment]
done - thanks!
