### ISSUE TITLE
Rack NVMe Supermicro Cache Servers

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#1051]
*Updated description 10/17 - Hakan*

5x supermicro 1U nodes are located on the top of a cabinet in the back of the machine room labeled "FXMOC-2". The rails for these nodes are tied up together above the stack as well.

All 5x should be deployed in R4-PA-C02, right above the existing servers there.

Connect all IPMI ports to the netgear switch in the top of the rack, ports don't matter.

Because we have limited 40G port capacity in that rack for now, connect 2x of the nodes to the top of rack cisco with 2x40G each (4x 40G links total). You can find 40G DACs in the MOC cage in one of the top boxes closest to the cage door. Otherwise I can replenish your stock later on. Indicate which ports go to which servers.

It would be great if these could be racked anytime the week of the 16th.

**Comment by joachimweyl** [comment]
R4-PA-C21 is a possible destination.

**Comment by joachimweyl** [comment]
@msdisme do we have a desired turnaround time for this?

**Comment by msdisme** [comment]
Can we bump the priority on this, what can I do to help?

**Comment by msdisme** [comment]
adding @mosayyebzadeh so he may track

**Comment by hakasapl** [comment]
Our plan is to deploy these in each of the 5x FX2 racks. They require 2x40G connections each so the 100G switches in those racks would be sufficient. And it would be better to deploy them there rather than at the core. The primary delay on this is that we only have 3 of 6 racks in the pod at this point. It would help to understand a timeline for these nodes. If these are required soon @mosayyebzadeh we can find a temporary home for them.

**Comment by mosayyebzadeh** [comment]
@hakasapl Thanks for explaining the situation. Yes, it would be great to know the timeline for them since we have started to need them. It is not critical yet but it will be soon.

**Comment by joachimweyl** [comment]
@hakasapl do we still plan to put these in the 5 FX2 racks? If so we will need to spin up less of the nodes already in these racks, is that accounted for in our plans in those racks?

**Comment by hakasapl** [comment]
We don't plan to put them in initial FX2 racks, I think we will put the first 2 in R4-PA-C02, and then we'll find a place for the other 3.

**Comment by imstof** [comment]
I'm finding lots of 100g dac, a couple of 10g, but the only 40g dac I can see are ones that split from 40g -> 4x10g connections. Is it possible the aren't 40g dac in the cage? I can go look harder if you're sure they are there somewhere.

**Comment by imstof** [comment]
This is done other than locating and connecting the 40g cables

**Comment by hakasapl** [comment]
Thanks @imstof , I thought they were there but no need to keep looking. I will check for FLAX to see what they did with the cables that the nodes used to have. I'll ping you again when I know where they are. Thanks!

cc: @er1p

**Comment by imstof** [comment]
There were only 2 free ports in the cisco switch. I connected the topmost nvme host to those ports.

**Comment by hakasapl** [comment]
Thanks @imstof. @naved001 do you see the IPMIs for these nodes?

**Comment by naved001** [comment]
@hakasapl yes, IPMI controller of all 5 hosts is now reachable.

**Comment by hakasapl** [comment]
@imstof could you let me know which server (by its serial number or ipmi mac) has its 40G ports connected?

**Comment by imstof** [comment]
should be sn: WO44657L01S040 that is connected

**Comment by hakasapl** [comment]
Thanks! @naved001 could you make this one available?

**Comment by naved001** [comment]
@mosayyebzadeh neu-19-41 is now available at `172.16.96.119` via `kumo-hil-client.infra.massopen.cloud`

**Comment by mosayyebzadeh** [comment]
@naved001 Great, thank you!

**Comment by hakasapl** [comment]
Let's close this, I will open a different issue for the remaining nodes as there is some switching to figure out there
