### ISSUE TITLE
nvme drive on production ceph host kzn-osd07 has failed

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#1056]
```
[root@kzn-mon1 ~]# ceph osd tree down
ID    CLASS WEIGHT   TYPE NAME               STATUS REWEIGHT PRI-AFF
-1002       72.99988 root performance
  -33        7.29999     host kzn-osd07-nvme
  274   ssd  7.29999         osd.274           down        0 1.00000
  ```
  
related: https://github.com/CCI-MOC/ops-issues/issues/576

service tag for this machine: 2ZD8V52
looks like it's at C04-U7

**Comment by joachimweyl** [comment]
Look into TechSquared doing this work for us.

**Comment by joachimweyl** [comment]
@hakasapl see if TechSquare can grab that serial number for us before you are at MGHPCC next.

**Comment by joachimweyl** [comment]
@naved001 please add the model for this drive. @hakasapl if it is not in the cage please order a new one.

**Comment by naved001** [comment]
The model number of these drives is INTEL SSDPEDKX080T7. These are 8TB drives.

**Comment by hakasapl** [comment]
Drive swapped by techsquare

**Comment by naved001** [comment]
osd was created, and now the cluster is rebalancing.
