### ISSUE TITLE
decommission MOC ocp-prod cluster

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#1057]
Disable project access, turn off machines etc, backup whatever we need etc.

**Comment by joachimweyl** [comment]
deconfigure SSO would remove access.
Where to put netbox?
Wait (a month or until we have a new home for netbox) then turn off.
@hakasapl would it be problematic if netbox went away for a week as we move this?

**Comment by naved001** [comment]
I disabled the SSO client, so users cannot login anymore.

**Comment by joachimweyl** [comment]
@naved001 are we still waiting on Netbox getting a new home?

**Comment by hakasapl** [comment]
Netbox has been moved off. Is there anything else we need to save/backup from ocp-prod before shutting it down?

**Comment by naved001** [comment]
i wiped the drives of the controllers.
