### ISSUE TITLE
Allocation of OpenShift based VMs for a course

### ISSUE THREAD

**Issue by reihl** [CCI-MOC/ops-issues#1066]
Hi,
I would like your help with the allocation of 25 OpenShift based VMs.
The VMs are needed for a course taking place next week. It is a course similar to the previous ROSE course, where a similar allocation was done several months ago.
I'm attaching a link for a discussion regarding the previous ROSE allocation:
[#450](https://github.com/CCI-MOC/ops-issues/issues/450)
This request is same to [#620](https://github.com/CCI-MOC/ops-issues/issues/620) apparently the server from the last week was deleted yesterday.
Thanks in advance,
Rei

**Comment by naved001** [comment]
@reihl Do you specifically need OpenShift based VMs? Do OpenStack VMs work for you?

**Comment by reihl** [comment]
@naved001 We are agnostic to the infrastructure, any linux machine that have connection to the Internet with the ports we mentioned works for us

**Comment by sleviim** [comment]
@reihl The students currently work in the env mentioned above, don't they?
The course is about to end on next Thursday.

**Comment by reihl** [comment]
Thanks for your help

**Comment by msdisme** [comment]
@reihl, could you clarify the course schedule? Specifically, is it starting next week and lasting one week, or does it extend beyond that duration? Understanding the exact timeline is crucial for us to efficiently identify a suitable MOC alternative for you.

**Comment by reihl** [comment]
Hi @msdisme , Yes, it'll happening on next week till 10th August. We refer to save the systems for the students cause in the last year we extend the course for additional time in the year.

**Comment by idanlv** [comment]
Hi @msdisme,
I'll try to help with some more details.
We'll need the resources for the course, starting next week, Sun-Thursday (6-10 Aug). We have everything ready in the current environment, and we would like to maintain it.
If we could retain the environment until Aug 13, so the students will also have the weekend - it would be a nice bonus.
Otherwise, please retain the environment until Aug 11 morning, US time.

As a long-term solution,
We would love to migrate the machines' images to any new environment so we'll be able to use them for the next round (currently expected next year).

**Comment by naved001** [comment]
@idanlv @reihl We will keep this environment online until August 13th. After that please turn off the VMs and then I can power down the cluster.

> We would love to migrate the machines' images to any new environment so we'll be able to use them for the next round (currently expected next year).

How many images are there? You'll have to map the pvc name to the ceph rbd image name, which would remain undeleted in our ceph cluster until we figure out a long term solution. 

This is how I got the rbd image name for one of the PVCs
```
naved@computer ~ % oc get pv -n summer2022-virtualrose pvc-c1d28c76-3696-44b3-8652-ae78d2dcb36d -o yaml | yq .spec.csi.volumeAttributes.imageName
"csi-vol-3008c881-fde4-11ec-81a1-0a580a830996"
```

cc: @larsks

**Comment by reihl** [comment]
Servers shutoff, some of them are stuck.

**Comment by dankenigsberg** [comment]
Thanks @naved001 .  Do you plan to have a replacement for this cluster? E.g. some other MOC-operated bare-metal OpenShift that can run VMs, too?

**Comment by joachimweyl** [comment]
@dankenigsberg, are VMs required or could this work be done in containers?

**Comment by dankenigsberg** [comment]
@joachimweyl yes, I am asking specifically about VMs.

**Comment by joachimweyl** [comment]
@dankenigsberg and to ensure we are checking all our options would OpenStack VMs work for this project?

**Comment by joachimweyl** [comment]
@dankenigsberg double checking on my question above.

**Comment by msdisme** [comment]
closing since I think this is resolved.
