### ISSUE TITLE
Power & Heat testing on R4-PA-C21

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1067]
- [ ] @hakasapl schedule a time to run testing with @waygil & John Goodhue, reach out at least 1 week in advance of when you wish to test
- [ ] At the scheduled time run a staged test so that we do not blow out a fuse in the PDU

**Comment by hakasapl** [comment]
Moved it to the next sprint - thanks!

**Comment by hakasapl** [comment]
Initial results [here](https://docs.google.com/spreadsheets/d/1E-uHeDuMx5k8-w5c-s6mqUOdS5e74zbDzYVWDvcLlWk/edit#gid=0)

**Comment by joachimweyl** [comment]
@hakasapl can you give a brief translation of what the results are telling us? Does it look like we will need to reduce the number of nodes per rack?

**Comment by hakasapl** [comment]
Most likely - but I wanted to talk about it in a meeting more. 26kW peak load from the FC830s alone is a lot. With the FC430s we're definitely over what we should be.

**Comment by joachimweyl** [comment]
The desired peak for the whole rack is 25kW.

**Comment by joachimweyl** [comment]
@hakasapl can you add to the results the memory and thread count for the FC430s and FC830s, please?

**Comment by hakasapl** [comment]
Testing done, spreadsheet updated with FC430 data as well

**Comment by waygil** [comment]
@hakasapl do we have an idea of the number of threads (or cores) and memory for each of the FC830s and FC430s?  We're trying to get an idea of number of each we may want to power on to provide a good mix of threads and memory to the community.

**Comment by hakasapl** [comment]
Sorry, I missed Kim's note earlier - I just added that info in the spreadsheet @waygil

**Comment by hakasapl** [comment]
@waygil I just filled in that info in the sheet as well:

FC830	4x Xeon E5-4669 v4 (22 Cores, 44 Threads)
FC430	2x Xeon E5-2640 v4 (10 Cores, 20 Threads)
