### ISSUE TITLE
Do we have a couple of large memory machines that could be set aside for some virtualization testing?

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#1084]
It is occasionally useful to spin up virtual openshift clusters, particularly for folks who are just starting out or if we need to test something specific and we don't require the performance of bare metal hardware.

The machines that are/were in MAAS were great for this.

Do we have a couple of machines that are available now that could be set aside for this purpose? They don't need to have any particular network configuration other than that there is a way to ssh into them from outside, and they don't need to be particularly recent as long as they support recent RHEL-based distributions.

**Comment by naved001** [comment]
Right now there are no machines available as far as I can tell. We are still waiting on the new hardware to come online. Once it's setup those will be available to be leased via ESI.

@joachimweyl Should this request be a part of https://github.com/CCI-MOC/ops-issues/issues/1074 ?

**Comment by joachimweyl** [comment]
@naved001 I have added with the stipulation that if all the FC830s are taken we might need to wait for one of the next 5 racks that are being brought up over the next few weeks.

**Comment by joachimweyl** [comment]
Resolved for now, will reopen if needed.
