### ISSUE TITLE
replace/check PSU on ceph monitor

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#1085]
<img width="740" alt="image" src="https://github.com/CCI-MOC/ops-issues/assets/20113064/bdf9a387-3580-4ccd-98dc-53a684680954">

The machine is a PowerEdge R330, service tag HC73GK2, hostname is kzn-mon2, idrac name is neu-17-14mon2.

The front panel should be displaying a message about the PSU.

**Comment by hakasapl** [comment]
@naved001 did we fix this?

**Comment by naved001** [comment]
@hakasapl just checked the idrac and it look like it is now resolved.

<img width="1520" alt="image" src="https://github.com/user-attachments/assets/70e68a04-2d6b-4065-a575-28dfd8a1a9f7">
