### ISSUE TITLE
Connect and provision TORS in FX2 Rack 1

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1088]
- [ ] Connect uplink to ESI core (both mgmt and data)
- [ ] Update firmware on 3 Dell os9 TORS
- [ ] Initial switch configuration on os9 TORS

**Comment by joachimweyl** [comment]
@hakasapl please provide an update on where we are on this issue.

**Comment by hakasapl** [comment]
Switch configuration is complete in FX2 rack 1
