### ISSUE TITLE
Provision CMC, iDracs, Firmware updates in FX2 rack 1

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1089]
Order of operations:

- [x] Factory reset CMC and enable DHCP (FLAX)
- [x] Initial configuration for CMC
- [x] Factory reset all iDracs and apply initial configuration
- [x] Firmware update all components of all nodes on Dell OME

**Comment by joachimweyl** [comment]
@hakasapl please provide an update on where we are on this issue.

**Comment by hakasapl** [comment]
FC430s are done. 830s still need bios options set

**Comment by hakasapl** [comment]
Initial configuration is done
