### ISSUE TITLE
Enroll nodes to ESI in FX2 rack 1

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1091]
PR nodelist in json format is a PR to esi-pilot. ESI team will enroll the nodes.

**Comment by hakasapl** [comment]
PR submitted: https://github.com/CCI-MOC/esi-pilot/pull/43

**Comment by hakasapl** [comment]
Enrolled and in ESI. Some cleans have failed which we'll clean up later

**Comment by joachimweyl** [comment]
@hakasapl do we have a list of the cleans that failed? Can we open an issue with those listed?

**Comment by hakasapl** [comment]
I've opened an issue [here](https://github.com/CCI-MOC/ops-issues/issues/1209)
