### ISSUE TITLE
The management url in onboarding notification emails is incorrect

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/ops-issues#11]
Link says `management/tasks/`, it should just be `management/`. [Code](https://github.com/openstack/adjutant/blob/b35fdcc6aba6db0d4a22f7e1ee6a2900bdea49af/adjutant/notifications/v1/email.py#L98)

- [ ] We are a few commits behind on `adjutant-ui`, check if this is something that changed recently

**Comment by larsks** [comment]
What generates the onboarding emails?

**Comment by knikolla** [comment]
Adjutant, specifically here https://github.com/openstack/adjutant/blob/b35fdcc6aba6db0d4a22f7e1ee6a2900bdea49af/adjutant/notifications/v1/email.py#L98
