### ISSUE TITLE
Connect and provision TORS in FX2 Rack 3 (R4-PA-C10)

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1107]
There may already be a dell mini pc and some unneeded cables connected to it in the rack left there from Flax. Please take those out and put them on top of the cardboard boxes in the back of the machine room for flax to pick up if so.

- [ ] Plug in and update the firmware of all dell switches to the latest OS9 version, and factory reset the switches
- [ ] Connect uplinks to Port 32 of each Z9100-ON, connects to Port 4 of each Z9100 in R4-PA-C12 (Shared system keyed cabinet). 100G Active cables that are long enough can be found in the MOC cage, in the long FS.com box closest to the cage door.
- [ ] Connect management uplink to Port 48 of S3048-ON, connects to port 5 of the S3048-ON in R4-PA-C12. Long CAT6 cables can be found in the MOC cage in a different FS box. If it's not there it's likely in the shipping cage in "Hakan Saplakoglu"'s name from FS.com.
- [ ] Connect port 46 of the 3048-ON to the managment port of the top Z9100, and port 47 to the bottom Z9100-ON. CAT6 cables should be in the plastic bin at the bottom of the MOC cage.
- [ ] Initial switch config - run these commands on each switch
    * ### Z9100-ON Setup
    * `conf`
    * `enable password ######`
    * `username admin password ######`
    * `ip ssh server enable`
    * `interface managementethernet 1/1`
    * `no shut` (when in intf conf)
    * `ip address 10.80.3.4X/20` X = 1 for top Z9100, X = 2 for bottom Z9100
    * ### S3048-ON Setup
    * `conf`
    * `enable password ######`
    * `username admin password ######`
    * `ip ssh server enable`
    * `interface vlan 930`
    * `no shut`
    * `ip address 10.80.3.45/20`
    * `interface range gigabitethernet 1/46-1/47`
    * `no shut`
    * `switchport`
    * `interface vlan 930`
    * `tagged interface gigabitethernet 1/48`
    * `untagged interface gigabitethernet 1/46-1/47`
- [ ] Test switch remote access by pinging `10.80.0.1` from each switch and verifying replies. The uplinks are already configured in R4-PA-C12
- [ ] Remaining switch config once switches are remotely accessible. @hakasapl will do this

**Comment by yani4** [comment]
I have updated the os firmware, factory reset and updated the indicated configs on all three switches.
I used a /16 subnet mask but if a different subnet is required I can go back and change them.

I am just waiting on the port confirmation before adding the uplinks

**Comment by hakasapl** [comment]
I apologize for the delay - I was traveling and missed it. Yes, I mean port 32 - I've updated the description.

Sorry for not indicating the subnet mask - it should be a `/20`. I've updated the description.

**Comment by yani4** [comment]
It's all good. I corrected the initial config and am working on the cabling.
One guestion about the flax equipment, would I be correct in presuming the netgear Gs305in r4-pa-c08 is part of that? It was just a little odd of an additon and I thought I'd ask

**Comment by hakasapl** [comment]
Yes, the netgear switch is not part of our hardware. That's part of the FLAX gear.

For the 3048 ports, use port 48 and port 47 in that case. I'll update the description.

**Comment by yani4** [comment]
Sorry I forgot to update this last week.
I have cabled and just finished troubleshooting an issue with the start up config. Each switch in the cabinet is pinging 10.80.0.1 so remote access should be available.

The old Flax stuff is in the back of the machine room on a table since there weren't any convenient boxes available at the time.

**Comment by hakasapl** [comment]
Thank you so much!
