### ISSUE TITLE
Connect and provision TORS in FX2 Rack 4 (R4-PA-C08)

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1108]
There may already be a dell mini pc and some unneeded cables connected to it in the rack left there from Flax. Please take those out and put them on top of the cardboard boxes in the back of the machine room for flax to pick up if so.

- [ ] Plug in and update the firmware of all dell switches to the latest OS9 version, and factory reset the switches
- [ ] Connect uplinks to Port 32 of each Z9100-ON, connects to Port 5 of each Z9100 in R4-PA-C12 (Shared system keyed cabinet). 100G Active cables that are long enough can be found in the MOC cage, in the long FS.com box closest to the cage door.
- [ ] Connect management uplink to Port 48 of S3048-ON, connects to port 6 of the S3048-ON in R4-PA-C12. Long CAT6 cables can be found in the MOC cage in a different FS box. If it's not there it's likely in the shipping cage in "Hakan Saplakoglu"'s name from FS.com.
- [ ] Connect port 46 of the 3048-ON to the managment port of the top Z9100, and port 47 to the bottom Z9100-ON. CAT6 cables should be in the plastic bin at the bottom of the MOC cage.
- [ ] Initial switch config - run these commands on each switch
    * ### Z9100-ON Setup
    * `conf`
    * `enable password ######`
    * `username admin password ######`
    * `ip ssh server enable`
    * `interface managementethernet 1/1`
    * `no shut` (when in intf conf)
    * `ip address 10.80.3.5X/20` X = 1 for top Z9100, X = 2 for bottom Z9100
    * ### S3048-ON Setup
    * `conf`
    * `enable password ######`
    * `username admin password ######`
    * `ip ssh server enable`
    * `interface vlan 930`
    * `no shut`
    * `ip address 10.80.3.55/20`
    * `interface range gigabitethernet 1/46-1/47`
    * `no shut`
    * `switchport`
    * `interface vlan 930`
    * `tagged interface gigabitethernet 1/48`
    * `untagged interface gigabitethernet 1/46-1/47`
- [ ] Test switch remote access by pinging `10.80.0.1` from each switch and verifying replies. The uplinks are already configured in R4-PA-C12
- [ ] Remaining switch config once switches are remotely accessible. @hakasapl will do this

**Comment by yani4** [comment]
Is this referring to the switches in R4-PA-C08?

**Comment by yani4** [comment]
I finished cabling and restoring factory defaults to the switches in the cabinet. All of the switches are pinging 10.80.0.1. The firmware for OS9 was updated too so this should be all set. 

If anything else needs to be fixed up, don't hesitate to let me know @hakasapl .

**Comment by hakasapl** [comment]
Thank you so much!
