### ISSUE TITLE
Discrepancies in Hardware Counts between MOCA and FLAX

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1118]
In this spreadsheet: [MOC Alliance Combined Nodes](https://docs.google.com/spreadsheets/d/1wsrwPlGDqvKA_aePr8yUEJCv7tqhlzSWnwU3lEAP5P8/edit?usp=drive_link) there are tabs called [Addendum to Donate](https://docs.google.com/spreadsheets/d/1wsrwPlGDqvKA_aePr8yUEJCv7tqhlzSWnwU3lEAP5P8/edit#gid=193631887) and [moc-machine-valuation-summary-30august](https://docs.google.com/spreadsheets/d/1wsrwPlGDqvKA_aePr8yUEJCv7tqhlzSWnwU3lEAP5P8/edit#gid=2131637010).

Added a new tab, [Discrepancies sep 5](https://docs.google.com/spreadsheets/d/1wsrwPlGDqvKA_aePr8yUEJCv7tqhlzSWnwU3lEAP5P8/edit#gid=1717094875) which captures the discrepancies in row K for @hakasapl and msd to discuss. 

Personal notes to be deletd once story completed.  
_I noticed discrepancy, want to figure it out and true up numbers
1. Check on counts on moc-machine-valuation-summary-30august[24].pdf and our count sheet
2. true up the valuations from the moc-machine-valuation with what is ~~left~~
2. Check on valuation discrepancies - is it hdd/ssd?
3. FX2 chassis?  Did Flax take any?_

**Comment by hakasapl** [comment]
I've filled in comments about the discrepancies that were major. Some appear to be single digit miscounts - others are higher.
