### ISSUE TITLE
Disposition of ~30 P100s

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1119]
We have an addtional 30 p100 gpu’s  - do we have hardware for them to go in (probably a topic for Hakan?).  

Getting the value of them so we may validate using them vs. selling them.  May need to hold back hardware which will also have a cost. 

Confirming these are P100 and not A100

**Comment by er1p** [comment]
fwiw - one creative suggestion for these GPUs would be to place them inside Dell R730xd servers that we removed, but are still in our warehouse at the moment - there are ~30 units and they have dual 1100W power supplies - so should be able to support even 2x P100 cards each server + few storage drives + networking

unless you have additional R740xd available, but the 730s would do fine hosting the GPU setup

**Comment by hakasapl** [comment]
@msdisme do we have a decision on this?

**Comment by joachimweyl** [comment]
@msdisme I believe the decision was to have Flax process all of these correct? That should close out this issue, do we need a new one to track the Flax processing?
