### ISSUE TITLE
Deploy link between Harvard networking and MOC & Test

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1122]
Steps for deployment:

- [x] Verify that the ports on at least one side are down
- [x] Deploy cables/optics
- [x] Deploy switch configuration and light up one link at a time
- [x] Verify NERC vlan communication with a vlan interface

**Comment by hakasapl** [comment]
Link is up, LAG is up on both sides, LACP active.

We still need to verify VLAN config

**Comment by joachimweyl** [comment]
@hakasapl how is the VLAN config going, any other steps left for this?

**Comment by hakasapl** [comment]
We tested an IP on the moc side on a NERC vlan, everything seems to work, closing this.
