### ISSUE TITLE
Identify 5 brocade switches for purchase by Flax client

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1125]
Identify 5 known good switches, potentially flash, and identify in bitwarden the associated licenses.    Communicate information to flax.

**Comment by naved001** [comment]
Let's start with any 5 out of these: `rbr-01`, `rbr-02`, `rbr-03`, `rbr-05`, `rbr-06`, `rbr-07`, `rbr-08`. 

These will need to powered on to match the hostname and then to get the serial number of the switch (maybe that's printed on the chassis) to retrieve the licenses.

**Comment by joachimweyl** [comment]
@msdisme who do we need to provide these model numbers to?

**Comment by joachimweyl** [comment]
Flax already grabbed 5 others that are known working.
