### ISSUE TITLE
Update Storage Invoicing with new headers, updated SU Types, Rate/Cost, & Combine similar SU Types

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1133]
Please update the headers to match the header names we are using for the CSV.  The header list can be found in the [NERC August Invoice](https://docs.google.com/spreadsheets/d/1wE8BxMqIew300ex-YqoKcrec4NiRg6IPjH7A0KMx2Dw/edit#gid=536769863&range=1:1). 
The `SU type` and `Rate` are described [here](https://github.com/CCI-MOC/epics/issues/65#issuecomment-1688686685). 
Cost can be calculated by multiplying `Rate` by `SU Hours (GBhr or SUhr)`
Combine OpenStack Volume GB Quota & OpenStack Swift Quota in Gigabytes as one row, it is okay to combine after creating the breakdown as it is now so we don't lose that coding as we may eventually want it broken into 2 but for billing we currently want it to just be one line item.

**Comment by knikolla** [comment]
This should be moved to https://github.com/nerc-project/coldfront-plugin-cloud

**Comment by joachimweyl** [comment]
duplicate of https://github.com/nerc-project/coldfront-plugin-cloud/issues/116
