### ISSUE TITLE
ESI acceptable use document presented to users

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1149]
This is an acceptable use document, loosely based on the cloud lab document, for use of ESI. This isssue is for presenting it to end users once it has been reviewed by legal.

The document lives here: https://docs.google.com/document/d/1RVh0vNwukkbhfzf5XIBYM6mzyNq0tv2EhTS7Hn_pxq4/edit. 

Need to identify a way to present the acceptable use documents to ESI users; will take feedback from Legal.

**Comment by joachimweyl** [comment]
@msdisme please add link to document.

**Comment by msdisme** [comment]
Expectation that this will be folded into EULA.

**Comment by msdisme** [comment]
Meeting was planned for May 6 and is being rescheduled.  Likely outcome is EULA with a few minor additions.  Will follow up via email to see if this may be addressed without a meeting.

**Comment by joachimweyl** [comment]
Added to new EULA
