### ISSUE TITLE
Expose entire ESI VLAN range to controllers

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#1153]
In converations with @tzumainn this week, it turns out that the only manual step required to enable floating ip access on new private ESI networks is to configure the switch to pass the appropriate VLANs to the controller.

We could eliminate this step by exposing the entire ESI VLAN range to the controllers. This would allow people to create new private networks and enable external access without waiting for one of us to perform a manual step.

I spoke with @naved001 and @hakasapl on a call today and nobody has any technical objection to this change. Naved wondered if security-conscious users would be concerned about having their VLANs exposed to a system outside of their control, but we ultimately decided that was a minor concern (in the event of a compromise on the controllers, whether or not the vlans are exposed there by default, the controllers have the switch credentials necessary to make those changes).

With @tzumainn's agreement, let's go ahead and implement this change.

**Comment by tzumainn** [comment]
I'm all for it! The vlans available for tenant networks are 351-399, 520-622, and 624-630. Who wants to make this change?

**Comment by larsks** [comment]
@tzumainn as part of this, I would also like to tear down all the per-project interfaces that have been created on the controllers, since they don't appear to be necessary. Is there any reason to wait on that?

**Comment by tzumainn** [comment]
I don't think so - I'd just be extra cautious with the ones that are currently using an external floating IP and ping those IPs afterwards to make sure things still work as a courtesy.

**Comment by tzumainn** [comment]
Okay, the project interfaces are gone! the one other task is: after we add the vlans for the tenant networks to the controller switchports, I'll need to update some of the MOC ESI documentation that references talking to an operator in order to finish network setup.

**Comment by joachimweyl** [comment]
@tzumainn it looks like the documentation issue is closed. What are the next steps for this issue?

**Comment by tzumainn** [comment]
Adding all the aforementioned VLANs to the controllers' switchports. @naved001 do you know if there's a scripted way to do that, or do the commands have to be run manually?

**Comment by naved001** [comment]
@tzumainn We have [this repo](https://github.com/CCI-MOC/ansible-switches/) to manage switches using ansible and I think that's where we could add all the VLANs to controller switchports. But I think we'll still need to script something to produce the appropriate yaml which then ansible can apply 😆. Though, I'd defer to @hakasapl on how he wants to handle this.

**Comment by hakasapl** [comment]
@tzumainn @naved001 what are the ports for this change on the oct4 switch?

**Comment by tzumainn** [comment]
> @tzumainn @naved001 what are the ports for this change on the oct4 switch?

1/13, 1/14, and 1/17

**Comment by hakasapl** [comment]
This is all set
