### ISSUE TITLE
Do an automatic update for the fc430 NICs firmware in the Research Rack

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#1154]
The firmware is available here: https://www.dell.com/support/home/en-in/drivers/driversdetails?driverid=d4n9t

1. Install an OS on the host (I used centos) and then installed the firmware with 
```
sudo ./Network_Firmware_D4N9T_LN64_16.10.04_A00-00_01.BIN
```

2. Force the update if it says that it's already on the same version. This is important because we want to force install the update manually.

3. Then reboot the machine.

```
[centos@nice-chow ~]$ sudo !!
sudo ./Network_Firmware_D4N9T_LN64_16.10.04_A00-00_01.BIN
Collecting inventory...
..
Running validation...

BCM57810 10 Gigabit Ethernet rev 10 (eno1)

The version of this Update Package is the same as the currently installed version.
Software application name: BCM57810 10 Gigabit Ethernet rev 10 (eno1)
Package version: 16.10.04
Installed version: 16.10.04

BCM57810 10 Gigabit Ethernet rev 10 (eno2)

The version of this Update Package is the same as the currently installed version.
Software application name: BCM57810 10 Gigabit Ethernet rev 10 (eno2)
Package version: 16.10.04
Installed version: 16.10.04



Continue? Y/N:y
Y entered; update was forced by user
Executing update...
WARNING: DO NOT STOP THIS PROCESS OR INSTALL OTHER PRODUCTS WHILE UPDATE IS IN PROGRESS.
THESE ACTIONS MAY CAUSE YOUR SYSTEM TO BECOME UNSTABLE!
```

Context here: https://github.com/CCI-MOC/ops-issues/issues/1131

The hosts that this needs to be done on:
* `10.2.10.161-168`
* `10.2.10.171-178`
* `10.2.10.181-188`
* `10.2.10.191-198`

Feel free to host images to boot off of on the techsquare VM. Note that the current version of the firmware on all of these will match the firmware of the one being manually applied. The current version installed is a version installed from dell OME, which while the version matches, doesn't work correctly for some reason. The driver downloaded manually works, and is not able to be applied through OME.

**Comment by joachimweyl** [comment]
@msdisme did Mike want to take this on?

**Comment by msdisme** [comment]
did not respond, lets get techsquare on it

**Comment by hakasapl** [comment]
Yes, we can figure that out. @naved001 can you update the description of this issue with the relevant links and what you did on a single node to update the firmware to the non-OME version?

**Comment by naved001** [comment]
@hakasapl I have updated the description with what needs to be done to update the firmware.

**Comment by hakasapl** [comment]
I'm going to make a VM in ovirt such that techsquare can access these nodes IPMI. Then I will pass it over to them.

**Comment by joachimweyl** [comment]
@hakasapl are you tracking the creation of the VM in this issue or another issue?

**Comment by hakasapl** [comment]
Sent to techsquare

cc: @imstof

**Comment by joachimweyl** [comment]
@hakasapl do we expect TechSquared to complete this by the end of the sprint or shall we push this to the next sprint?

**Comment by hakasapl** [comment]
I don't think it will happen in this sprint

**Comment by joachimweyl** [comment]
@imstof do we have an eta for the completion of this issue?

**Comment by imstof** [comment]
I will work on this today and update by end-of-day.

**Comment by imstof** [comment]
@hakasapl is the vpn running? I've got no ping to techsquare.massopen.cloud

**Comment by imstof** [comment]
@joachimweyl I'm still not able to reach the techsquare vpn. Can someone make sure it is running?

**Comment by joachimweyl** [comment]
@imstof @hakasapl is working on that now. It did not come up properly after a power event we had.

**Comment by imstof** [comment]
@hakasapl I can reach the vm now but am unable to authenticate. If you need public key again it is:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDiLUwrhH8b2iGO55Xbm7MrJ6mZCeyRfAbr2j4XCSe4cMejiy9NVyRWZFACu1g3Y7sbc9a+muuvCCEz3GB/StBtBOLkaWOC+A6bXuNq5SrUkbfrNqtefPCPmHS3sr9RSdCRWUy8e+b1/8/bllB7j8HD94eZQiKfooJt8TXuEWE5oMhfFOXVrHoP57Gg/t0it2A69d989AG2oJXi8bb9fqBwBns2C6X0ajjosM50gC7ZjvK3a4iWGpZzh2gJ1o/Clv02zJFBZbGzg/xsG+0QSwpVWqTZza+J0PE/pR9WanLd96hH1tUhuAQE9hV1qlBqJomTW/R3hQIZ7j9rOi6vXSr8B4kDO4R0Jsj9H3+Dbb2R3HYU5emI+RL2cZv3Mlh4tcjzrq6q5WlvT4B4LWAWWGIlNAdCpNHuwYv7fuMoYLizKDDMqhIoRUUHUUCBzyvV/+tOS90yi6N2W8dFsoGITHNcoMOk5R1Wsv7OCpSMzMPW41ipj8o9yEb7EgDRDfEp9OoIVYUqHJswMepKuRAJeEQ9pBDmRPvzUX8dEGz+ZkgB6L60khzLWDiW1YZBLQvhuEefFSi2i/mmlqmESzcqDkXNjcSd7WILiG2zIv1IbAmb5leWQ85wPqi3udqYJjo/3aZatppVkfca3wNu0FiAOBiJwCiKX5Eg66DSXyQJGk29Qw== cehnstrom@techsquare.com

**Comment by hakasapl** [comment]
@imstof we had to reinstall the vm due to a disk issue. I've re-added your key so you should be able to get in now.

**Comment by imstof** [comment]
@hakasapl are there a few ips we can use for the machines we install so we can upload firmware to them? They are not getting anything from dhcp.

**Comment by naved001** [comment]
@imstof you could use `10.2.0.{5-9}`. Though the DHCP should work (it's up and running with plenty of available IPs), so I suspect something else may be going on.

**Comment by imstof** [comment]
@naved001 your suspicion is correct. dhcp is requests time out and setting static won't ping in or out
10.2.10.171 is installed (root:foo) if you want to take a look.

**Comment by hakasapl** [comment]
@imstof just to confirm, you're just looking for an internet connection on the 430s in-band to download the firmware on each machine? The ports aren't configured on any vlan right now but we can put them on a natted one with dhcp?

**Comment by imstof** [comment]
@hakasapl that would work. we just need to get the fw on to the installed system in order to run/force the update according to the issue description

**Comment by imstof** [comment]
We've installed most of the machines. There are few with issues: crash during post, won't stay powered on, etc, that we'll list. At this point we just need to get them on a network so we can upload the firmware. It would also be easier to use ssh rather than the idrac virtual console.

If network is a problem, or not worth the time, we can just use usb-sneakernet and the virt console.

**Comment by hakasapl** [comment]
@imstof Sorry for the delay - lot of moving networking parts right now, I've just configured port 1 of each of those machines on a vlan that should have dhcp and is natted. Let me know if that works for you.

**Comment by joachimweyl** [comment]
@imstof what is the status of this issue?

**Comment by imstof** [comment]
@joachimweyl Got the response about network while I've been out sick. I'll resume work on this and other moc issues today and tomorrow.

**Comment by joachimweyl** [comment]
@imstof Sorry to hear you were sick, hope you are feeling better. Thank you for the heads up and letting us know you will be working on this today and tomorrow. Is there another team member of yours we should include when we reach out via GH so we avoid the issue of you being out of the office?

**Comment by hakasapl** [comment]
@imstof No worries, I hope you are feeling better! The switchports were shutdown, I just turned them on. You should get an IP on those interfaces now if DHCP is enabled.

**Comment by imstof** [comment]
thanks @hakasapl I am back in for a full day now.
It looks like the techsquare vm is not on the same network as the nodes?
They are getting 172.16. /19 addresses from dhcp, ts vm is only on 10. /19 for the ipmi interfaces

**Comment by imstof** [comment]
These are done except for two nodes.
There were several problem nodes, mostly ones that kept powering off during post. I managed to troubleshoot most of them.
There are still 2 that refuse to stay powered on: 10.2.10.194 and 197

**Comment by joachimweyl** [comment]
@hakasapl I assume the next step is to replace those two units with 430s from our backstock? or since they are wired up is it worth trying to trouble shoot what is wrong with them?

**Comment by joachimweyl** [comment]
@naved001 are we ready to add all but the 2 that failed to ESI?

**Comment by hakasapl** [comment]
@joachimweyl At the moment I'm not worrying about swapping dead hardware, just keeping track of them in [this issue](https://github.com/CCI-MOC/ops-issues/issues/1075). I will work on getting them added to ESI

**Comment by hakasapl** [comment]
Thanks for your help @imstof!

**Comment by joachimweyl** [comment]
@hakasapl do we have an issue tracking the adding of these nodes to ESI?
