### ISSUE TITLE
please review and update MOC A rack utilization spreadsheet

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1155]
As an administrator of MOC hardware in shared computing spaces it is necessary to have a summary of MOC A rack usage to allow negotiation about MGHPCC resources with other partner institutions.

please review and update MOC A rack utilization spreadsheet tab, [MOC A Overall](https://docs.google.com/spreadsheets/d/1dEl6H34nhb-XDjiZas3Tzlsna3rtWoSugpw_lLQcwZY/edit#gid=0) to make sure the information is current. 

Acceptance: all racks listed in tab, current state of rack up to date.

- [x] @joachimweyl 
- [x] @hakasapl 
- [x] @naved001

**Comment by hakasapl** [comment]
I added the fx2 racks and added note for neu racks

**Comment by naved001** [comment]
I added R4-PA-C02 and R4-PA-C04 where the current MOC stuff is racked (Cisco switches, ceph cluster, ovirt, some more hardware).
