### ISSUE TITLE
Clear out 4x Misc racks and 2x FX2 racks

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1159]
4x Misc racks are: ITR-R4, ITR-R5, ITR-R6, ITR-R17

In the Misc racks, FLAX will take everything except:
* All the Dell R740
* All the HP DL380 Gen10
Those 2 should be 11 nodes total.

In addition, FLAX will take 2x of the normal FX2 racks in the back of the machine room, but not:
* FXMOC-1 and FXMOC-2 (the ones with other stuff in them besides FX2)

We are keeping the 3x FX2 racks back there that are already cabled. Those have locations, and are pending deployment.

**Comment by joachimweyl** [comment]
@er1p what is the status of this move?

**Comment by joachimweyl** [comment]
@hakasapl has techsquared already racked the DL380s and R740s?

**Comment by hakasapl** [comment]
These racks have been cleared
