### ISSUE TITLE
Figuring out Costs to associate with cloud course based on coldfront project 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1162]
The cloud computing course NERC projects are 2023 Fall 528-974542.    The ECE department is willing to pay for NERC usage, but it may be at a discounted rate.  Goal of this issue is to make sure we capture costs even though we are not currently sending a bill so that we may explore how to handle charges for courses using this as an example.

**Comment by knikolla** [comment]
I don't think there's anything to do for this issue. We already generate bills for all projects and then filter out the ones that are non-billable from that list. So the initial unfiltered list will contain costs for this project too.

**Comment by joachimweyl** [comment]
This means we will need to save the unfiltered list somewhere. @msdisme who will be billing these projects and how?

**Comment by msdisme** [comment]
If the simplest thing is to generate a report on the non-billable then that makes sense for now.  I think the data on what it costs to run the service will be valuable as well. As part of the next billing work we should prepare for more classes.

**Comment by joachimweyl** [comment]
@naved001 how much effort would it be to also generate a second csv for projects not billed for?

**Comment by naved001** [comment]
Should be simple enough I think.

**Comment by joachimweyl** [comment]
@naved001 Please see the new [issue](https://github.com/CCI-MOC/non-billable-projects/issues/4) for this.
@msdisme I will create a second sheet for October that includes only non-billable projects.

**Comment by msdisme** [comment]
thank- we'll use that to come up with actual charges

**Comment by joachimweyl** [comment]
October's numbers can be found [here](https://docs.google.com/spreadsheets/d/1vvE2F88PJp_En2ZDb_7vp8yEnuh_ObsR_m8173_JQvk/edit?pli=1#gid=430235760). Find the Project - Allocation 2023 Fall 528-974542, there should be two of them.
@msdisme I will create this new Non-Billable tab on the future worksheets. We will need to make sure our long-term solution includes non-billed as well.
Is there anything more you would like to do for this issue or is it closed?

**Comment by msdisme** [comment]
Looks good

**Comment by msdisme** [comment]
Is there any easy way to see if the numbers are curving up in the next 2 weeks?  Context is we want to give the department an estimate.  We plan to say that we assume between $1500 and $2000 for NERC for the course, but I don't want to surprise ourselves if we can avoid it.  Here is a spreadsheet with the project which should be associated with the course: https://docs.google.com/spreadsheets/d/1TK6y0Jkff81a-98T8RgAodsYn8awJfaGMbPxoJdmb5M/edit?usp=sharing in case we want to cross check.

**Comment by joachimweyl** [comment]
@msdisme As this course only has billed information for October and no other month it is hard to track growth but on December 1st we can calculate for November and then provide a comparison. Not really a curve with only 2 points but more than 1 point.
[Here](https://docs.google.com/spreadsheets/d/1cu4jD8c-f7ubVlRnVU6pH2uJ07zqT2UTyBrjo_naK_k/edit?usp=sharing) is the table awaiting November data. Are we done with this piece of the issue, would you like a new issue to track adding values to the sheet?

**Comment by joachimweyl** [comment]
I am going to close this issue as we have the work done and ready for next month. If we decide we need a new issue to track values just let me know and I will create it.
