### ISSUE TITLE
Deploy Rack controller in R3-PB-C07 responsible for FPGA JTAG Control

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1163]
Node will be a Dell R440.

USB Hub connected to that node, then to all 16 JTAGs

**Comment by hakasapl** [comment]
JTAG brackets are installed, awaiting shipment of new USB hub

**Comment by joachimweyl** [comment]
@hakasapl is this planned to be completed before this sprint is over or shall we push it out a sprint?

**Comment by hakasapl** [comment]
This is installed
