### ISSUE TITLE
Spike: Gather and Share MIG Data captured for A100's

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1168]

**Comment by joachimweyl** [comment]
@msdisme I see this is part of the current sprint but has nobody assigned to it, can you assign this to somebody?

**Comment by joachimweyl** [comment]
@msdisme is this a duplicate of https://github.com/CCI-MOC/ops-issues/issues/1039

**Comment by msdisme** [comment]
Yep
