### ISSUE TITLE
Add old OKD nodes to ESI

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1171]
The initial CHA1 and CHA2 in OCT4 OKD are no longer using so they can be added to ESI.

**Comment by joachimweyl** [comment]
@hakasapl is this planned to be completed before this sprint is over or shall we push it out a sprint?

**Comment by hakasapl** [comment]
Node uplinks changed to new ESI switch ports 49,50,51,52

**Comment by hakasapl** [comment]
PR Created: https://github.com/CCI-MOC/esi-pilot/pull/49

**Comment by hakasapl** [comment]
@tzumainn a portion of these nodes are failing inspection. It gets as far the iPXE prompt (`iPXE 1.20.1+`) and then just fails and falls back to the hard drive. Have you seen that behavior before?

**Comment by tzumainn** [comment]
@naved001 this sounds familiar - didn't we run into a similar iPXE version issue before?

**Comment by hakasapl** [comment]
I didn't run firmware update on these - I thought that issue was just with the OME firmware for the NICs?

**Comment by naved001** [comment]
@tzumainn the version of ipxe we boot does say 1.20.1. The version we get if we hit CTRL+B is 1.0.0+. But since @hakasapl didn't update the firmware on these NICs and I am not sure what could be the issue. 

I would try to get the "other" ipxe shell with CTRL+B and then try to manually complete the boot process (`dhcp`, and then I think `chain https://our-controller/boot.ipxe`) to see what happens.

**Comment by tzumainn** [comment]
I opened up the console and tried inspection on oct4-cha1-1c  again, and I'm seeing that behavior - at first PXE seems to work, grabbing the correct IP address from DHCP. Then it brings up `iPXE 1.0.0+`, loads `ipxe.lkrn`, goes to `iPXE initialising devices... ok` and then exits

**Comment by tzumainn** [comment]
Okay, I think there may be multiple things going on here. I took a look at node `oct4-cha2-3d`; it failed to get an IP from DHCP. It has switch port `tengigabitethernet 1/54/4`; however, when I went onto the switch to check the port configuration, I got an error (I'm including the successful check of 1/52/2 as a comparision).

```
OCT4-SW-ESIDEV#show running-config interface tengigabitethernet 1/52/2
!
interface TenGigabitEthernet 1/52/2
 no ip address
 mtu 9216
 switchport
 spanning-tree rstp edge-port 
 no shutdown
OCT4-SW-ESIDEV#show running-config interface tengigabitethernet 1/54/4
                                                                ^
% Error: In configuration  at "^" mark
```

**Comment by hakasapl** [comment]
Sorry, there must have been a typo there. I only spotted 2 nodes that had that typo and submitted a [PR](https://github.com/CCI-MOC/esi-pilot/pull/51). It seems like some nodes have correct assignments but still run into this issue.

**Comment by tzumainn** [comment]
Thanks! That fixed those nodes.

I'm testing `oct4-cha2-3b`. Its port is registered as `e0:d8:48:e4:65:dd`; however the NIC appears to have the mac address `34:17:eb:eb:03:ee` (which also matches what I see in the BIOS). I think there may be some incorrect port information?

**Comment by joachimweyl** [comment]
@tzumainn is this issue resolved?

**Comment by tzumainn** [comment]
the port mapping issue is not yet resolved as far as I can tell

**Comment by joachimweyl** [comment]
@tzumainn what are the next steps to resolving this?

**Comment by tzumainn** [comment]
Ah, I was hoping @hakasapl would be able to confirm the port mapping issue; sometimes the answer is to update the ports on the Ironic side, but I've also seen cases where it's been changed on the switch side.

**Comment by hakasapl** [comment]
Yeah this is blocked on me right now, I'll try to PR the fix today

**Comment by joachimweyl** [comment]
If you don't get to it please push it to the next sprint.

**Comment by hakasapl** [comment]
Port mapping confirmed to be correct, 3 nodes are in a bad state which I will troubleshoot later on
