### ISSUE TITLE
Organize Slack channels

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1176]
## Motivation
Clean up and organize our Slack channels.

## Completion Criteria
prepare a list that Michael can review.

## Description
- [x] Create a [list](https://docs.google.com/spreadsheets/d/1UbgJnqXPUKoaaYEehRaSPmDKbb7MxtrcsETXscsOV0A/edit?usp=sharing) of all channels (currently only public)
   - [x] do first pass on what we should remove
- [x] provided the list to Michael

## Completion dates
Desired - 2023-11-29
Required - 2024-01-24

**Comment by joachimweyl** [comment]
Hello @msdisme, as I do not have access to all private channels I will not be able to suggest cleaning up private channels other than the ones I am in. Do you have access to provide private channel lists from the [channel list](https://massopencloud.slack.com/admin/stats#channels)?

**Comment by msdisme** [comment]
I do, but don't worry about those for now, except for the ones you are already part of.  Some are made by researchers or for similar reasons.

**Comment by msdisme** [comment]
once cleaned up we may want to create a pinned list to simplify folks finding the right ones
