### ISSUE TITLE
Purchase and install 2 modern single-thread research servers from Flax

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1178]
## Motivation
Researchers require 2 modern servers for research they are doing that requires modern servers.

## Completion Criteria
1 AMD and 1 Intel modern server are installed in MGHPCC and networked and accessible by the researchers.

## Description
- [x] Confirm Quotes
- [x] Order Servers
- [x] install servers (TechSquared?)
- [ ] Network servers

## Completion dates
Desired - 2023-12-13
Required - TBD

**Comment by joachimweyl** [comment]
@msdisme what is the next step in ordering these nodes?

**Comment by msdisme** [comment]
@taramoran already started this; she is out this week so @neclinton may have more details - will ask

**Comment by msdisme** [comment]
@er1p have you already seen BU paperwork on these?

**Comment by msdisme** [comment]
checking on status of order on BU side.

**Comment by hakasapl** [comment]
@er1p do you have a tracking number for these?

**Comment by er1p** [comment]
we will bring them out to the data center in the usual way

let us know where you want us to rack them

**Comment by hakasapl** [comment]
@er1p let's put them in R4-PA-C04, just find some open Us on top of the existing FX2s. Also, we need an extra pair of FX2 rails for the top FX2 in that rack

**Comment by hakasapl** [comment]
Flax has installed the servers, but missing the rails for now.

**Comment by msdisme** [comment]
@er1p did these ever get put into the right place?

**Comment by er1p** [comment]
we had trouble with one of the networking card, so waited for a replacement - they should be on-site by Monday On Mar 6, 2024, at 10:03 AM, msdisme ***@***.***> wrote:﻿
@er1p did these ever get put into the right place?

**Comment by joachimweyl** [comment]
@er1p is the network card replaced?

**Comment by er1p** [comment]
sorry - yes

the network card replacement was something we did during integration testing

these two servers were delivered on 11 March and are in place in R4-PA-C04

![image](https://github.com/CCI-MOC/ops-issues/assets/11774546/e9f16e2e-5aef-4c5d-a68a-2e55afc2fa0c)

**Comment by joachimweyl** [comment]
@hakasapl what are next steps.

**Comment by hakasapl** [comment]
New issue here for the rest of the work: https://github.com/CCI-MOC/ops-issues/issues/1277
