### ISSUE TITLE
Disable Integrated NICs for FC830s in R4-PA-C24 and C22

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1180]
The `qlogic` NIC in each FC830 needs to be disabled (integrated card) because it interferes when PXE booting.

In the system bios (F2 during boot), Settings > Integrated Devices has the option to do so.

I have not found a way to automate this. If you do, please let me know!

The following iDracs need this change:
* `10.2.11.21`
* `10.2.11.22`
* `10.2.11.31`
* `10.2.11.32`
* `10.2.11.41`
* `10.2.11.42`
* `10.2.11.51`
* `10.2.11.52`
* `10.2.11.61`
* `10.2.11.62`
* `10.2.11.71`
* `10.2.11.72`
* `10.2.11.81`
* `10.2.11.82`
* `10.2.11.91`
* `10.2.11.92`
* `10.2.11.101`
* `10.2.11.102`
* `10.2.11.111`
* `10.2.11.112`
* `10.2.11.121`
* `10.2.11.122`
* `10.2.11.131`
* `10.2.11.132`
* `10.2.11.141`
* `10.2.11.142`
* `10.2.11.151`
* `10.2.11.152`
* `10.2.12.21`
* `10.2.12.22`
* `10.2.12.31`
* `10.2.12.32`
* `10.2.12.41`
* `10.2.12.42`
* `10.2.12.51`
* `10.2.12.52`
* `10.2.12.61`
* `10.2.12.62`
* `10.2.12.71`
* `10.2.12.72`
* `10.2.12.81`
* `10.2.12.82`
* `10.2.12.91`
* `10.2.12.92`
* `10.2.12.101`
* `10.2.12.102`
* `10.2.12.111`
* `10.2.12.112`
* `10.2.12.121`
* `10.2.12.122`
* `10.2.12.131`
* `10.2.12.132`
* `10.2.12.141`
* `10.2.12.142`
* `10.2.12.151`
* `10.2.12.152`

**Comment by imstof** [comment]
If there is time left today we will start to look at this. If not it will be tomorrow 11/30/23

**Comment by yani130** [comment]
I started looking at this today for 10.2.11.21.

As there appears to be two integrated NICs, I wanted to know if both of them needed to be disabled.

As for automation, the only idea I have for that is to maybe use racadm to send the command from the vm but I still need to double-check the doc [here](https://raw.githubusercontent.com/wiki/radiasoft/devops/manuals/dell-racadm-bios-nic-techsheet.pdf) to be sure if it's viable.

**Comment by hakasapl** [comment]
Both integrated NICs should be disabled. Let me know if racadm ends up working, I didn't spend too much time looking into it

**Comment by yani4** [comment]
@hakasapl  To my utter dismay racadm is not working despite my syntax looking correct.
I disabled both nics for 10.2.11.21 but one of my coworkers noticed something with regards to those machines. 

It looks like there are only the 'integrated' nics and not an embedded nic present. On top of that, when taking a look inside the rack I found that the switches the nics are going to aren't giving out link. The uplink looked ok so I'm guessing this is a config problem.

**Comment by hakasapl** [comment]
@yani4 the switch on the chassis is just a passthrough, not a switch, since the FC830s (the nodes in this issue) don't have those connected, no link is normal. The FC830s have 25G mellanox addon cards which we use for their links. Those switchports also aren't configured yet on the switch so no link is okay. I'm not sure what you mean by integrated vs embedded? I always assumed they were the same.

We want to disable the integrated NICs because despite setting a PXE boot order, the PXE boot seems to fail on those NICs (since they don't have a connection), and then falls back to the hard drive without trying the other NICs. Disabling these NICs on other nodes worked for us getting a reliable PXE boot. Unfortunately I don't think we can just remove the passthrough module in the chassis, as there are still internal NICs in each blade

**Comment by yani4** [comment]
@hakasapl maybe i got my terminology wrong. I disabled the two for one but as the system was not picking up any other cards for pxe I assumed that there was something else cooking. 

But if the switch ports aren't set up yet then that explains why that's not working on the one I changed.

Really not sure why racadm fails claiming syntax since all the docs suggest it should be right but I guess it is what it is.

**Comment by hakasapl** [comment]
Yes, a failing pxe boot is expected right now, as long as it's trying to pxe boot using the mellanox card (flex boot), we should be set. I haven't looked into racadm too much for bios options, maybe it worked in a previous version? The idracs should have the most up-to-date firmware on these machines.

**Comment by yani4** [comment]
Maybe? I was using a lot of get commands to make sure I had the syntax correct but racadm keeps calling the option to disable valid. I won't keep burning time on trying to automate it with racadm since that looks like a dead end or at least more trouble than its worth.

I'll go back to doing it the long hand way.

**Comment by hakasapl** [comment]
Apologies - I was playing with STP configs today so that must have interrupted the connection, they should be reachable now. I'll let you know if I plan to do that in the future, but we should be set for now.

Also, if you could power off these nodes after disabling the NICs, that would be great, they consume a lot of power at idle.

**Comment by yani4** [comment]
Glad it was something that simple then. I do have access again so that's good to go.

I will make sure to shut them off after each one then. Do the nodes that we needed to force firmware updates on also need to be off when not in use?

**Comment by hakasapl** [comment]
Thank you for your help! I'll check out those nodes a bit later.
