### ISSUE TITLE
Are these NESE allocations still in use?

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1183]
query from @jtriley Justin in: https://github.com/CCI-MOC/ops-issues/issues/974

Are these still in use: 

quotas for pool 'moc_infra_rbd':
  max objects: 262.14k objects
  max bytes  : 1 TiB
quotas for pool 'moc-rbd-general-erasure':
  max objects: N/A
  max bytes  : 1 GiB
quotas for pool 'moc-rbd-general-erasure-data':
  max objects: 262.14k objects
  max bytes  : 1 TiB
quotas for pool 'moc-rbd-general-replicated':
  max objects: 262.14k objects
  max bytes  : 1 TiB

**Comment by naved001** [comment]
`moc_infra_rbd` is no longer needed as the openshift cluster `moc-infra` was shutdown a while ago. I suspect the other pools were probably related to either `moc-infra` or the `smaug` cluster which was also deprecated. @larsks can confirm.

**Comment by joachimweyl** [comment]
@msdisme do we need NESE to do this work?

**Comment by msdisme** [comment]
@naved001 Are there any we want to hold onto for future moc-infra etc?

**Comment by naved001** [comment]
@msdisme The plan is to go for all local storage for the moc-infra cluster so it has least external dependencies.

However, if we needed a pool in the future from NESE would it be a problem to get one allocated?

**Comment by msdisme** [comment]
Can you identify which one we want to keep and we will part with the rest, concern being just the delay we might incur to get a new one.

**Comment by naved001** [comment]
@msdisme Let's keep `moc_infra_rbd` then for some future use case.

**Comment by msdisme** [comment]
great- thanks!  making a new issue and closing this one https://github.com/CCI-MOC/ops-issues/issues/1210
