### ISSUE TITLE
Date Drive requirement - 1-3 systems available Amin for configuration as soon as possible  

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1185]
original reference this document:https://docs.google.com/document/d/18MZPltHas18fXejhspZMFRzLqHUGEqZRNnLe_C8wxNc/edit

Short term high priority which must is tied to a visit by IBM head of storage (msd added):
We need hardware to periodically stand up small/disposable Ceph clusters for development with up-to-date Ceph OSDs (preferably by the end of this week 12/1/23). We can deploy the software ourselves.  The requirements are: 
At least one machine , up to three machines
Each machine should have at least two HDDs up to 4 HDDs.
The machine should be on network that can be reached neu-19-41 (the machine with SSD on it).

For Now let's do FC430's.  @mosayyeb@bu.edu @okrieg if 256 GB SSDs are ok then we can do it sooner.  If 512GB SSD's are needed we need to move some hw around.  Please let us know ASAP as @hakasapl will be at the MGHPCC tomorrow and we will prioritize adding the 512GB systems' to make them avaialbe if ncessary.

**Comment by mosayyebzadeh** [comment]
@msdisme yes, for this week, 256GB works. We need the system ASAP. Thanks!

**Comment by naved001** [comment]
@mosayyebzadeh For the short-term stuff do you need connectivity to the cache nodes? If yes, on what VLANs? 

I would recommend that you look at this [ESI usage document](https://esi.readthedocs.io/en/latest/usage/new_user_guide.html) while we work on making the machines available via ESI

**Comment by mosayyebzadeh** [comment]
@naved001 yes we need the connectivity. But I don't have any clue about VLANs.

**Comment by naved001** [comment]
@mosayyebzadeh can you tell me the subnet(s)? I can look at the node to figure out the vlans from it.

**Comment by mosayyebzadeh** [comment]
@naved001 is the node neu-19-41 available to use? Can you point me to the documentation on the new ESI infra?

**Comment by naved001** [comment]
@mosayyebzadeh info about neu-19-41 is here: https://github.com/CCI-MOC/ops-issues/issues/1051#issuecomment-1821224061

We'll get you access to ESI.

**Comment by joachimweyl** [comment]
@naved001 what are the next steps for this issue?

**Comment by naved001** [comment]
@joachimweyl the machines have been made available to @mosayyebzadeh. When Amin sets those machines up I can help him connect those to the cache server.

**Comment by naved001** [comment]
I can this can be closed now that @mosayyebzadeh have access to those machines.

**Comment by mosayyebzadeh** [comment]
@naved001 I have provisioned all three, assigned a floating IP address, and have been able to ssh into them. I used research-storage network. 
But I am not able to see the instances in ESI OpenStack environment.

**Comment by tzumainn** [comment]
@mosayyebzadeh Are you using the web UI to try and see them? If so, that won't work; Ironic isn't integrated into the web UI (we only use it for initial credential generation).

https://esi.readthedocs.io/en/latest/usage/new_user_guide.html#viewing-your-nodes has the best information on how to view the status of your nodes, with `openstack esi node network list` being the best for viewing the current network information (floating IPs and the like).

**Comment by naved001** [comment]
@mosayyebzadeh do you need to assign floating IPs to all 3 hosts? Can't one host be used as a gateway?

**Comment by mosayyebzadeh** [comment]
@naved001 I have assigned two IP addresses to ensure I have access to the nodes. But, now that I have access to the nodes and they are connected, one IP will suffice. I will release one of them.

**Comment by naved001** [comment]
the cache server now has an interface on the network as the other 3 machines.
