### ISSUE TITLE
Test new spanning tree topology on dev switches

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1187]
OCT5 switches can be used for development deployments. Test deployment on an isolated spanning tree island of
* OCT5-SW-TORS-A
* OCT5-SW-TORS-B
* OCT5-SW-MGMT

**Comment by joachimweyl** [comment]
@hakasapl is this the last piece to complete spanning tree for ESI/OCT?

**Comment by hakasapl** [comment]
Yeah this is deployed in production now so we can close this
