### ISSUE TITLE
Demo of ESI and CloudLab for Open Cloud WorkShop February 28-29, 2024

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1193]
The demo scenario is as follows:
A full rack of servers is available through ESI (TBD: is there a reservation system on top of ESI like ColdFront or are we using bare ESI?)
The full rack of nodes is leased from ESI to CloudLab (lease creation is done through the offer mechanism)
The offers are accepted by CloudLab and the nodes are enabled in the CloudLab database to be available to CloudLab users
We can see in the CloudLab interface that the new resources are available and they are no more available in ESI
Finally the nodes are returned to ESI by disabling the nodes in the CloudLab database and canceling the leases.
We can see that the nodes are no longer available in CloudLab but are back in ESI.

The demo will be recorded as it will take too much time to wait for leases to be created, databases to be activated and interfaces to be refreshed. We are proposing to have 3 phases described in the following sections to manage risks as a large portion of the software is untested at scale at this point. The demo can be recorded as soon as phase 1 is completed. Phase 2 and 3 are for our internal goals but won’t prevent the demo from being performed if they are not fully completed by the workshop.

More details live in this doc: https://docs.google.com/document/d/1ssjJvq6nwkwNU75zG-vb9fuLdXdNofL8GqTu3bhc76k/edit .  Details will likely move to this and related issues.

**Comment by msdisme** [comment]
The demo scenario is as follows:
A full rack of servers is available through ESI (TBD: is there a reservation system on top of ESI like ColdFront or are we using bare ESI?)
The full rack of nodes is leased from ESI to CloudLab (lease creation is done through the offer mechanism)
The offers are accepted by CloudLab and the nodes are enabled in the CloudLab database to be available to CloudLab users
We can see in the CloudLab interface that the new resources are available and they are no more available in ESI
Finally the nodes are returned to ESI by disabling the nodes in the CloudLab database and canceling the leases.
We can see that the nodes are no longer available in CloudLab but are back in ESI.

The demo will be recorded as it will take too much time to wait for leases to be created, databases to be activated and interfaces to be refreshed. We are proposing to have 3 phases described in the following sections to manage risks as a large portion of the software is untested at scale at this point. The demo can be recorded as soon as phase 1 is completed. Phase 2 and 3 are for our internal goals but won’t prevent the demo from being performed if they are not fully completed by the workshop.

More details live in this doc: https://docs.google.com/document/d/1ssjJvq6nwkwNU75zG-vb9fuLdXdNofL8GqTu3bhc76k/edit .  Details will likely move to this and related issues.

**Comment by hakasapl** [comment]
I will make other issues for this during this week.

* The 16x original OKD nodes which were not added to ESI will be used
* Dell S4048-ON will be deployed there as a dedicated cloudlab - esi dev switch
* That switch should be added to both CloudLab and ESI
* The 16 nodes should be added to both CloudLab and ESI

Target is 3 weeks from today worst case

**Comment by hakasapl** [comment]
Issues added for [adding nodes to esi](https://github.com/CCI-MOC/ops-issues/issues/1171) and [adding switch]()

**Comment by msdisme** [comment]
Nice job Emmanuel!
