### ISSUE TITLE
Security group rule: specifying remote security group as source does not allow traffic to pass

### ISSUE THREAD

**Issue by tsachleben** [CCI-MOC/ops-issues#12]
Original Bug Report from Tim Scully:
> When creating a security group rule (in this case ingress), specifying the remote security group as the source
> of traffic for that rule does not allow traffic to pass.  Using the same security group rule but specifying either
> ALL CIDR or the specific CIDR block of the source host works.
>
> In my tests:
> 
> Creating a rule to allow all TCP (or UDP) from a remote security group does not work.
> 
> Creating a rule to allow all TCP (or UDP) from CIDR 0.0.0.0/0 works.
> 
> Creating a rule to allow all TCP (or UDP) from CIDR 172.16.14.0/24 (the CIDR block of the host) works.
> 
> Up until about a week ago specifying the remote security group in the rule worked.  Therefore, this appears to
> be a change within the past week if that aligns with any maintenance on your end.
>
> Was an update applied or other maintenance performed which could impact how security group rules behave
> with respect to the definition of the traffic source?

@larsks Opened Bug Report with RH on 8/3/2020

Last Note from RH Support:
> Red Hat associate comment Link, Anthony Fri, Aug 28, 2020, 2:23:43 PM CDT
> Hello,
> 
> The package[1] was referenced by an engineer working your case and may provide a possible fix.
> 
> Tony
> 
> [1] openstack-neutron-12.1.1-28.el7ost

Assigning: @larsks 
External Links: 
[1] https://osticket.massopen.cloud/scp/tickets.php?id=620

**Comment by larsks** [comment]
I have verified that this bug has been resolved by the recent updates in the kaizen environment. The [linked repository](https://github.com/larsks/verify-ops-issues-12) provides a playbook that verifies things are functioning correctly.
