### ISSUE TITLE
Create list of Invoice After Processing Features so that we can automate them

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1207]
## Motivation
After the OpenShift, OpenStack, and storage invoice data is pulled it is then combined together. Then the next step is that it is processed in a few ways in Google Sheets. We would like to automate this after processing as much of the last step as we can easily.
We are not trying to automate all of the steps, just the steps leading up to what we send to MGHPCC. The other steps such as updating PDF's, Rollups, Orran course charges, and Utilized billed and non billed can wait as @joachimweyl has automated them mostly in Google Sheets and they are not on the same time crunch.

## Completion Criteria
Provide details of the steps of the Invoice after-process

## Description
- [x] List the steps of the after-processing.
- [x] Provide substeps for each of the main steps to reproduce
- [x] Get feedback about what else is needed to automate the After-Processing Steps
   - More details about any of the steps?
   - examples?
- [x] Get feedback if it is worth automating any of the other steps

## After Processing Steps
1. Add 3 new columns, Credit, Credit Code, and Balance to billable CSV
 1. Add Credits for new PI
   1. Compare a list of all PIs that have used OpenStack and OpenShift in the past, find out if there are any new PIs this month, and if there are add the current Cost value (up to $1k across the whole project) to the Credit column of the billable CSV 
      1. this means that if there are 4 projects and they sum up to 1.5k we only add up to 1k in the Credit column and the rest will be invoiced directly
   1. Add 0002 to the Credit code field for all rows that are given New PI Credits
   1. Set the Balance column for all rows to be Cost minus Credit
      1. this means for non-credit rows balance will equal cost and for credit rows it will be the difference.
1. Create a CSV of only the HU rows named NERC-YYYY-MM-Harvard-Invoice.csv where YYYY is the year and MM is the month
1. create a CSV of HU and BU only named NERC <Month> Invoice - HU&BU.csv where <Month> is the name of the month of the data processed.
1. Save 2 CSVs above to the [CSV folder](https://drive.google.com/drive/folders/1ybuc7hTSP5CkxQNQ5HkBsC_MZcjXVGYC?usp=drive_link) or to a shared drive that @joachimweyl has access to

## Steps I realized are not needed for sending files to MGHPCC but worth looking into automating at some point
1. Create a worksheet
   1. Create Google Sheet NERC <Month> Invoice
   1. Add billable as a sheet and name it Combined
   1. Add non-billable as a sheet and name it Non-Billed
   1. Add NERC-YYYY-MM-Harvard-Invoice.csv as a new sheet NERC-YYYY-MM-Harvard-Invoice
   1. Add NERC <Month> Invoice - HU&BU.csv as a new sheet HU&BU
   1. Alternating Colors for all the sheets
   1. Create the Institutional RollUp, example [here](https://docs.google.com/spreadsheets/d/1v7I0cpwI9M5s_nnVNYi7Cc2K58udzHZL4erGGYE4qvM/edit?pli=1#gid=1546928881).
      1. Rows - Institution, Manager (PI), Project - Allocation
      1. Columns - SU Type
      1. Values - Cost, Credit, Balance (Summarize by SUM)
      1. Remove SUM of from row 3
      1. Collapse Manager (PI) and Institution
      1. Resize columns D-X so they fit the Balance value
      1. Resize columns Y-AA so they fit the Balance column
1. Update [Orran Course Usage data](https://docs.google.com/spreadsheets/d/1cu4jD8c-f7ubVlRnVU6pH2uJ07zqT2UTyBrjo_naK_k/edit?pli=1#gid=0)
   1. Point to a new IMPORTAGE location for the next month
1. update [NERC Billed Utilization](https://docs.google.com/spreadsheets/d/1bEUD1KDsC21HG6i8nlnTG8ogq2JqVv-nv-A65Pl705w/edit?pli=1#gid=2125580024)
   1. Point to a new IMPORTAGE location for the month sheet
   1. add a new 3 columns to the Combined sheet and pull from the new month's sheet
1. Create PDFs
   1. Create tabs for each PI
      1. same format as the Combined table
   1. print each tab to PDF
   1. save to [PDFs](https://drive.google.com/drive/folders/1COv3MeYLRGGnG2RbVnKsn9Y4hNh47Idh?usp=drive_link) folder.

## Completion dates
Desired - 2023-12-22
Required - TBD

**Comment by joachimweyl** [comment]
@knikolla please review After Processing Steps and let me know where you would like more detail.

**Comment by knikolla** [comment]
@joachimweyl Thanks, that's helpful. After-processing steps seem automatable for an end of January time-frame.
