### ISSUE TITLE
Identify Lenovo installation Details and coordinate with data center 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1211]

**Comment by msdisme** [comment]
This was delivered on aug 30th and apparently sent to BU cage.

**Comment by hakasapl** [comment]
Installation is complete, minus the one missing node. Should we keep this open until that node arrives?

**Comment by joachimweyl** [comment]
we are tracking that last one [here](https://github.com/nerc-project/operations/issues/417).
