### ISSUE TITLE
Write up job description for Junior Project Manager

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1214]
## Motivation
Assistance in organizing ZenHub so that it is more PI-friendly.

## Completion Criteria
Job Description passed off to @msdisme 

## Description
- [x] Gather previous job descriptions @msdisme 
- [x] Assign the issue back to @joachimweyl 
- [x] @joachimweyl Create a new job description based on old ones
- [x] @msdisme review
- [x] @joachimweyl apply suggestions
- [ ] @msdisme approve final draft

## Completion dates
Desired - 2024-01-10
Required - 2024-01-24

**Comment by msdisme** [comment]
Shared with Nancy as well

**Comment by msdisme** [comment]
@joachimweyl apologies,  I made changes directly in the doc, but version control is on.

**Comment by joachimweyl** [comment]
@msdisme As I only made a grammatical update I would say this is probably ready to close.

**Comment by msdisme** [comment]
made some adjustments to tech project manager.  inviting wayne/stephen/-nancy to review- will make a new issue for that .
changed order of importance on position description
rewrote some of request summary to be more about expanding our capacity
