### ISSUE TITLE
Swap breakout cable in R6-PB-C02

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1216]
This is a UMass keyed rack with MOC gear in it.

We are having an issue with one part of a x4 breakout cable in this rack. The problem cable is connect to the left side interface of the node in U31 (3 on the breakout) in this rack. If there is nothing obvious wrong with the connection, please try to replace the cable.

The switch is facing the front of the cabinet, at the topmost U. The breakout cable attached to port 2 is the problematic one. You can find other 4x25G breakout cables in a box full of breakout cables in the MOC cage. 3M cable is the minimum length required for this connection. It is okay to disconnect 1 and 2 from the existing breakout while the cable is replaced. 1 should go to U33, and 2 U32 (both on the left side NIC) on the cable.

**Comment by yani4** [comment]
Took some doing, but I swapped out the bad cable. Lights look good from this side now thankfully.

 Am I good to just dispose of it or do you need it in a specific place?

**Comment by hakasapl** [comment]
Feel free to dispose the bad cable. Sorry for the cabling in there and thanks for your help!

**Comment by naved001** [comment]
this resolved the networking issues.
