### ISSUE TITLE
Verify who has acesss to MGHPCC

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#122]
Make sure that we have more than one person with full access to MGHPCC

**Comment by msdisme** [comment]
Feedback from Manny:
I need a picture (headshot) from Peter Desnoyers and Robert Bartlett Baron before I can renew their access.
 
I need to create new profiles for:
Mike Zink
Emmanuel Cechet
picture (headshot)  
Email address
address
city
state,
zip,
mobile phone,

**Comment by msdisme** [comment]
Current list: 
Name | BADGE
-- | --
Orran Krieger | No
Peter Desnoyers |Need photo
Michael Daitzman | No
Robert Bartlett Baron | Need Photo
Kristi Nikolla | No
Mike Zink | Via UMass
Emmanuel Cechet | Via UMass
Hakan Saplakoglu | Not sure
Naved Ansari | Do form

**Comment by pjd-nu** [comment]
![Untitled 14](https://user-images.githubusercontent.com/3903147/106166607-5838cb00-615a-11eb-9690-a7a99fb1c552.png)

**Comment by msdisme** [comment]
Thanks Peter!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by msdisme** [comment]
All done except needc Peter's address @pjd-nu
