### ISSUE TITLE
Install moc infra OpenShift cluster  

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#1220]
A basic openshift install on the old ocp-prod controllers (the OCT10 R640s which are now on moc-core switches)

**Comment by joachimweyl** [comment]
@naved001 what are the next steps for this?

**Comment by naved001** [comment]
The basic install is done. The post deploy config (captured here: https://github.com/CCI-MOC/ops-issues/issues/1222) is what will take more time.
