### ISSUE TITLE
Prepare and deliver talk about current state of ESI

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1230]
Will require some details from Orran on the talk he is giving to make this a bit more unified with the conferences sections goals.
apx. 15 minute talk, leaving 10 minutes for the talk Hakan will give about switch control.

- [ ] schedule time with Orran to review his goals with the speakers for the workshop, first week of February or this Thursday(1/25)
- [ ] current state of ESI, 
- [ ] future plans
- [ ] possible call for action

**Comment by tzumainn** [comment]
Added initial draft of my part of presentation; will need to add details, but feel free to leave feedback on the overall content!
