### ISSUE TITLE
Update ESI Epic titles to "why" format

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1234]
We are changing epics from statements (eg. ESI SDK) to “Why’s” (eg. Implement an ESI SDK to centralize various services and simplify scripting to clarify their purpose. )  

For ESI we need some assistance.   This is a [link to the spreadsheet](https://docs.google.com/spreadsheets/d/1pqAmYppD3j1PQYvq9ueZyKgxpxjwT_-ulZagTEFXvYg/edit?disco=AAABFyxTg3k) section we are using for renaming.  Please make updates in place.

**Comment by tzumainn** [comment]
I've updated the development-focused ESI epics (and left any operational ones alone). Let me know if there should be additional iteration!
