### ISSUE TITLE
Talk on OPE 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1245]
The goals of this talk are:  
1. describe the courses that are using NERC now
2.Identify challenges encountered and future improvements we plan to make/hope to see to make OpehShift AI more "classroom friendly"
3. call to action for a. additional users and b. features people particularly want

Some details from the Epic:

# Description
[The workshop](https://massopen.cloud/2024-workshop/) is Feb 28 and Feb 29.  We want to make sure that we highlight the work we have been doing and focus areas going forward.
1. [workshop agenda](https://docs.google.com/document/d/1gHTjU2c_Qazu4KLkdqSmvC6RfJc8iGXraARCT4E2biI/edit)
2. [tracking issue for epic](https://github.com/CCI-MOC/epics/issues/)

**Comment by msdisme** [comment]
@hpdempsey I am not convinced I got the correct people for this - search as I might I could not find our discussion :-(.  Also, should Jonathan be a part of this?

**Comment by hpdempsey** [comment]
Yes, Jonathan and Danni are doing it.

**Comment by msdisme** [comment]
Nice Job Danni!
