### ISSUE TITLE
Create a VM and deploy Grafana and Prometheus on it for Network Monitoring

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1246]
VM will live in ovirt and run Prometheus and Grafana. Initially we will trunk vlan 930 which is the MOC switch management to the VM, in addition to a NATted vlan.

**Comment by joachimweyl** [comment]
holding off for this sprint to see how fast we can get Openshift ready to avoid creating this on a VM.

**Comment by msdisme** [comment]
Is there a reason to have this Grafana and Prometheus seperate from the one being used in Metrics Logging & Observability?  If so, can we feed the data there?  I expect we may be duplicating effort, or about to get a query about gathering network data as researchers have an interest.  If in the other cluster then we can apply ACLs.

**Comment by hpdempsey** [comment]
+1000   I don't see any reason for yet another version of Prometheus and Grafana.  In addition, if we did do that, the data would be unavailable to researchers, and we already know of researchers who want this data in the MOC telemetry  data trove.
