### ISSUE TITLE
Install 2x new FPGA build machines from FLAX

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1250]
They should have arrived. They will go in R3-PB-C05 and C07

**Comment by hakasapl** [comment]
These have been installed, awaiting cabling

**Comment by joachimweyl** [comment]
@hakasapl how are we tracking the cabling?

**Comment by hakasapl** [comment]
Tracking the entire rack's cabling here: https://github.com/CCI-MOC/ops-issues/issues/1251
