### ISSUE TITLE
Cable up new FPGA rack R3-PB-C05

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1251]
Starting with the FPGA ports, from the bottom up in the rack, each port on the fpga should connect to a 100G port on a top of rack Z9100-ON. So the bottom most FPGA would be port 1 and 2 on the bottom Z9100-ON. Use up to port 16 for FPGAs (8 FPGAs on each switch), then move on to populating the other switch with the remaining 16 FPGAs (not all the FPGAs have network ports, fill as much as they do).

Only the new servers (Dell R760) will have 100G cards in them. Those that do, connect them starting at port 21 on each switch. ie. port 21 on the bottom z9100-ON corresponds to ports 1 and 2 on that switch that go to the FPGA in the same node. Skip interfaces where the node doesn't have a 100G nic (we're ordering them).

1G idracs / mgmt interfaces should connect sequentially from the bottom up to the s3048-ON in the rack. In addition, each server should have one of their normal 1G interfaces connected to the S3048-ON starting at port 25 and going sequentially from the bottom up in the rack.

The uplink to the z9100-ONs should be 2x100G for each of them. All 4 uplinks go to the switch labeled "oct-hub-3" in R1-PC-C12. Let me know what ports you use there, just pick the next available one.

Don't worry about an uplink to the s3048-on for now. You can look at the neighboring FPGA rack R3-PB-C07 to see a model of the port descriptions above (although that rack also has some extra NICs so not everything matches perfectly, but the FPGAs and internal nics will).

**Comment by joachimweyl** [comment]
@hakasapl what are the next steps on this issue?

**Comment by hakasapl** [comment]
The cabling can be partially done by @imstof, I believe he has it on his list.

We are waiting on the PDU swap in this rack to complete the power cables as well.

**Comment by hakasapl** [comment]
@imstof do you have a timeframe for this? We would like to get at least the older hardware (9x HP and 2x Dell R740) online by the end of April, so you can ignore the new R760s for now

**Comment by imstof** [comment]
@hakasapl I'm away on emergency leave this week. I'll be back on monday and this is the first (and right now only) thing on my list.

**Comment by imstof** [comment]
@hakasapl forgot to update this before going away again. I got all of the fpgas, ipmi, and 1g eth cables in place. I have not yet run the uplinks.
Does moc have a stash of c13/14 power cables? the hp machines will need some.
I am away again dealing with a family emergency. I should be back next week but if there is a time crunch I can get another techsquare person on it.

**Comment by hakasapl** [comment]
@imstof the C13/14 cables should be in the plastic bin at the bottom of the front side of the MOC cage. No worries on doing it next week - I hope everything is okay!

**Comment by hakasapl** [comment]
@imstof do you have the uplink cables in place for this rack?

**Comment by hakasapl** [comment]
@imstof I installed the remaining cables so the cables in the rack are done. Any chance you have time to run the 4x uplinks between R1-PC-C12 and R3-PB-C05 before Wednesday this week?

Thank you!

**Comment by imstof** [comment]
@hakasapl I'll have the uplinks done today

**Comment by imstof** [comment]
Links are:
R1-PC-C12 oct-hub-3 port 23   to   R3-PB-C05-U41 port 31
R1-PC-C12 oct-hub-3 port 24   to   R3-PB-C05-U41 port 32
R1-PC-C12 oct-hub-3 port 25   to   R3-PB-C05-U40 port 31
R1-PC-C12 oct-hub-3 port 26   to   R3-PB-C05-U40 port 32
