### ISSUE TITLE
H100 Rough pricing

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1254]
So that Researchers may include pricing in grant proposals we need to provide a rough estimate of costs for H100 class systems for LLM training.   

- [x] get pricing from Lenovo - provided air cooled and water cooled
- [x] clarify differences in performance
- [ ] forward looking rack availability with @waygil
- [x] compare to pricing for current A100's
- [x] calculate estimated costs 
- [x] #1269
- [ ] review with NERC ' decide how public to make since we have none at this time
- [ ] share with Yannis

**Comment by joachimweyl** [comment]
rough estimates [here](https://docs.google.com/spreadsheets/d/1LHEmoi08FUOsbhB4mIOOZoy69RaNa76g/edit?pli=1#gid=1467172973&range=M5:M7).

**Comment by joachimweyl** [comment]
@msdisme are the values we calculated [here](https://docs.google.com/spreadsheets/d/13CU2r0AQ9U_MMdx7n-WWenYtI8mOJ2bSIZYQPm7MsVU/edit?pli=1#gid=1058321663&range=E58) accurate enough? or do we need more in-depth calculations?

**Comment by msdisme** [comment]
H200 is difficult due to varied pricing details from NVIDIA.    There appear to be some errors in the V4 sheet (added comment and duplicated to V5.  We should also have a copy of the page we are currently using with "actual charges" in it.

**Comment by joachimweyl** [comment]
Actual charges are listed under New Offering Cost row 59 B-G. I have unlocked V4 for you.

**Comment by joachimweyl** [comment]
Should I break this out into 2 issues 1 for H100 and 1 for H200 since it sounds like we will not be offering prices for H200 for a while yet?

**Comment by msdisme** [comment]
Had a discussion with Orran about this - he observes that we are overthinking this.  Proposed for Yannis's needs we can look at H100 node costs, compare to A100 and apply a small additioanl % and move on.

**Comment by joachimweyl** [comment]
@msdisme the % that @syockel originally suggested was 260% based on the price of the original unit. What percentage did Orran suggest?

**Comment by joachimweyl** [comment]
@msdisme we have rough pricing for the H100, do we know the percentage more that the H200 would cost above the H100s?
