### ISSUE TITLE
Give IPMI access for Peter FD332 machines

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1256]
These hosts are connected but the switchports need to be mapped and potentially redone in R4-PA-C04. Then a VM will be made in ovirt to be a jump host for the IPMI connections.

**Comment by hakasapl** [comment]
Added to dnsmasq and switchports are setup

**Comment by hakasapl** [comment]
Network ports have been moved to the new dell switch, CMCs are available remotely now

**Comment by joachimweyl** [comment]
@hakasapl is this ready to be closed?

**Comment by hakasapl** [comment]
Yes, these are reachable now
