### ISSUE TITLE
Install NVMe and 40G NICs in 5x FC830s

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1258]
We will take the NVMe cards and the 40G cards from the existing supermicro nodes and add them to the topmost FC830 in each rack (assuming it's available).

We then need to update the ESI manifests to include the 40G ports on the new NICs.

**Comment by joachimweyl** [comment]
@hakasapl is this for discussions going on in [finding-local-rgw](https://massopencloud.slack.com/archives/C06J7C9RYJ0) slack room?

**Comment by msdisme** [comment]
Note - each fc830 we enable means we shut off 3 FC430's in each rack due to power requirements. @okrieg

**Comment by joachimweyl** [comment]
@hakasapl just want to double check is it 4 FC430s consume the same power as 1 FC830 or 3?

**Comment by hakasapl** [comment]
Roughly 4, it's not exact, it's a little less than 4.

**Comment by msdisme** [comment]
@hakasapl eta on this?  Should we lean on techsquare?

**Comment by hakasapl** [comment]
ETA is today. I didn't have time last Friday.

**Comment by hakasapl** [comment]
Each server U29-S1 in each of the 5 racks have 2x NVMe drives each and 1x 2 port 40G mellanox connectx-3 cards. The 40G ports go to port 17 of each Z9100 TORS. Next step is to add the 40G ports to the ESI manifest, then the servers should be ready to go

**Comment by joachimweyl** [comment]
@hakasapl have we added the 40G ports to the ESI manifest?

**Comment by hakasapl** [comment]
Locally, for a portion of the nodes, yes. I have 2 to go that I'm working on this week

**Comment by hakasapl** [comment]
Nodes are ready, PR opened to merge relevant changes to ESI: https://github.com/CCI-MOC/esi-pilot/pull/54

**Comment by tzumainn** [comment]
All five nodes are re-added to ESI, inspected and verified to properly provision. Just a reminder: before we create a lease, I think we're supposed to ask for a time frame for the lease.

**Comment by joachimweyl** [comment]
@tzumainn as these are part of an ongoing research project and we don't currently have a way to extend leases let's make this lease not end, that being said once we have the ability to extend leases we can discuss changing the lease on these with Orran.

**Comment by hakasapl** [comment]
Pending closing this until researchers confirm they have access

**Comment by hakasapl** [comment]
The nodes have been made available via esi
