### ISSUE TITLE
Lenovo GPU node in R8-PA-C23-U27 doesn't have a console

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1259]
No console output on this node, IPMI is not reachable / can't log in. I will troubleshoot in person, we will go to lenovo if I can't find a fix.

**Comment by msdisme** [comment]
@hakasapl any update?

**Comment by hakasapl** [comment]
Console sometimes appears after forced reboot but freezes after a few minutes

**Comment by hakasapl** [comment]
Reseated

**Comment by hakasapl** [comment]
BMC reset fixed this issue
