### ISSUE TITLE
Pricing for different classes of bare metal machines shared under ESI

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1271]
## Motivation
We require pricing for bare metal machines so that we can start to include bare metal in our offerings.

## Completion Criteria
A pricing guide for bare metal decided upon.

## Description
- [x] Calculate the pricing model for our bare metal machines
- [x] Review with Monday Strategy Meeting
- [ ] Provide information to @joachimweyl & @Milstein for [Documentation](https://github.com/CCI-MOC/ops-issues/issues/1272).

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by tzumainn** [comment]
Related issue: https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/issues/gh/cci-moc/esi/509

**Comment by joachimweyl** [comment]
@msdisme at the base level this is just (purchase price + expenses)/5/360/24 but I assume we have more complexity we plan to include?

**Comment by msdisme** [comment]
The propose a cost for fc430 and fc830 should be sooner so we may communicate it to RH OKDMOCA so they may consider including in FY2025 budget.

**Comment by joachimweyl** [comment]
@joachimweyl provide a price based on SU count * CPU SU Cost for FC430 & FC830

**Comment by joachimweyl** [comment]
FC430 - 128 GB RAM / 96 GB RAM Threads 20*2=40, 24 SU for 96 GB RAM and 32 SU for 128 GB RAM with some unused CPU 16 for 96 GB RAM and 8 for 128 GB RAM or if you calculate by threads it is 40 SU
24 SU = $0.312/hr
32 SU = $0.416/hr
40 SU = $0.52/hr

FC830 - 2,048 GB RAM Threads 36*4= 144 SU, with a lot of unused RAM 1,472 GB or if you calculate by RAM 2,048/4 = 512 SU
144 SU = $1.872/hr
512 SU = $6.656/hr

Clearly, we can't charge full SU without either RAM or Threads to back it up but we need to charge for the extra resource so it is somewhere between the values provided.
maybe in the high $3 range for the FC830 and .39 for the 96 RAM 430 and .45 for the 128 RAM?

**Comment by msdisme** [comment]
FC430:   96  at .35
FC430: 128 at .45
FC830:  evaluate vs. commercial
compare to commercial pricing for all of these, as well (discount against that.)   
price for equivalent machine to price them out

**Comment by msdisme** [comment]
re. commercial pricing look at aws, google, and a few of the lower cost providers of bare metal:
[Liquid Web](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-1-liquid-web)
[Cherry Servers](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-2-cherry-servers)
[Hivelocity](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-3-hivelocity)
[Scaleway](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-4-scaleway)
[Amazon](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-5-amazon)
[INAP](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-6-inap)
[RedSwitches](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-7-redswitches)
[OpenMetal](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-8-openmetal)
[Oracle](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-9-oracle)
[Vultr](https://www.liquidweb.com/blog/bare-metal-cloud-providers/#h-10-vultr)

**Comment by joachimweyl** [comment]
| Company | Name | RAM (GB) | Threads | Price $/hr |
| - | - | - | - | - |
| Amazon | x2idn.metal | 2048 | 128 | 13.338 |
| OpenMetal | none | 1024 | 128 | $2.784 |
| Vultr | none | 512 | 64 | 2.344 |
| Vultr | none | 2048 | 256 | 8.185 |

Still looking up
1. Liquid Web
1. Cherry Servers
1. Hivelocity
1. Scaleway
1. INAP
1. RedSwitches
1. Oracle

**Comment by msdisme** [comment]
thanks, turns out cut and paste from github goes [smoothly into google sheets ](https://docs.google.com/spreadsheets/d/1RTJy7WhmMkwlDkr9ZPIbyFZmYote5r6hqMHPNwJa9MA/edit?usp=sharing)so we are good.

**Comment by joachimweyl** [comment]
Based on this data it looks like around $3.789 would be a fair price since none of the low-end BM listed in the table have as much RAM and the higher-end options are clearly higher than we want to go. Also keep in mind what we could make off of this node if we sold it as a bunch of high-ram SUs we would be making closer to $6.656/hr.
@msdisme thoughts?

**Comment by joachimweyl** [comment]
@joachimweyl add FC430 commercial comparison as a new table.

**Comment by joachimweyl** [comment]
## FC430 comparable BM machines
Company | Name | RAM (GB) | Threads | Price $/hr | Price if Enough threads | Price if enough ram for 96 | Price if enough ram for 128 | Average for 96 | Average for 128
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Vultr | none | 128 | 16 | 0.521 | 1.3025 | 0.39075 | 4.168 | 0.846625 | 2.73525
Vultr | none | 256 | 48 | 1.079 | 0.8991666667 | 0.404625 | 2.877333333 | 0.6518958333 | 1.88825
Google | n2-standard-32 | 128 | 32 | 2.032486 | 2.5406075 | 1.5243645 | 8.129944 | 2.032486 | 5.33527575
Google | n2-standard-16 | 64 | 16 | 1.016243 | 2.5406075 | 1.5243645 | 8.129944 | 2.032486 | 5.33527575
Cherry Servers | none | 64 | 32 | 0.8986 | 1.12325 | 1.3479 | 3.5944 | 1.235575 | 2.358825
Cherry Servers | none | 256 | 48 | 1.0486 | 0.8738333333 | 0.393225 | 2.796266667 | 0.6335291667 | 1.83505

**Comment by msdisme** [comment]
seem reasonable - I will communicate this to the folks using it even if we are not yet ready to bill for it.

**Comment by joachimweyl** [comment]
@msdisme just to confirm bare metal pricing for GPU systems are calculated by multiplying the number of GPUs in the node by the SU price for that GPU, correct?
