### ISSUE TITLE
Replace OCT netgear switches with Dell S3048-ON

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1279]
There are currently 4x switches remaining in OCT that is netgear:

* 2x in OCT1
* 1x in OCT2
* 1x in OCT4

All need to be replace with a Dell S3048-ON

**Comment by cecchet** [comment]
If you don't have any use for the Netgear switches, I need more switches for the hardware I got from OCT5 if we can recycle them.

**Comment by hakasapl** [comment]
@cecchet yes we also have extra netgears in the cage I can give you. How many do you need?

**Comment by hakasapl** [comment]
2 of the switches are replaced, the remaining 2 are dummy switches with no config so they will stay netgears
