### ISSUE TITLE
Add redundant PSUs to various S3048-ON switches in MOCA

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1280]
Locations that need a 2nd PSU:

R1-PC-C08-U43 (PSU to I/O Airflow)
R1-PC-C10-U41 (PSU to I/O Airflow)
R1-PC-C12-U35 (PSU to I/O Airflow)
R1-PC-C16-U44 (PSU to I/O Airflow)
R1-PB-C02-U27 (PSU to I/O Airflow)
R3-PB-C07-U42 (PSU to I/O Airflow)
R6-PB-C02-U42 (PSU to I/O Airflow)

We should aquire 2x PSU to I/O airflow PSU and 1x I/O to PSU airflow PSU as extras

**Comment by hakasapl** [comment]
@ljohnsonsesame @er1p

**Comment by hakasapl** [comment]
@er1p can you put the PSUs for the cabinets that are locked in the MOC cage? I'll install them the next time I'm there

**Comment by hakasapl** [comment]
@er1p adding two switches that I forgot:

* `R4-PA-C04-U41` (PSU to I/O)
* `R4-PA-C02-U41` (PSU to I/O)

**Comment by er1p** [comment]
updating here after additional deliveries today

R1-PC-C08-U43 (PSU to I/O Airflow) - PLACED PSU-to-IO & powered - fully redundant
R1-PC-C10-U41 (PSU to I/O Airflow) - PLACED PSU-to-IO & powered - fully redundant
R1-PC-C16-U44 (PSU to I/O Airflow) - PLACED PSU-to-IO & powered - fully redundant
R1-PB-C02-U27 (PSU to I/O Airflow) - PLACED PSU-to-IO & powered - fully redundant
R4-PA-C04-U41 (PSU to I/O Airflow) - PLACED PSU-to-IO & powered - fully redundant
R4-PA-C02-U41 (PSU to I/O Airflow) - PLACED PSU-to-IO & powered - fully redundant

R1-PC-C12-U35 (PSU to I/O Airflow) - cabinet locked, left one unit PSU-to-IO in box in MOC storage cage

R3-PB-C07-U42 (PSU to I/O Airflow) - PLACED IO-to-PSU to match existing PSU - NOT powered 
                                                                     cabinet front door is locked, so cannot reach power cords
                                                                     NOTE that the switch NEEDS two PSU-to-IO, but I chose to
                                                                     place a second IO-to-PSU rather than have mismatched PSUs
                                                                     so once power cable is placed, the PSUs will be redundant, but 
                                                                     will not have optimal airflow  

R6-PB-C02-U42 (PSU to I/O Airflow) - cabinet locked, left PSU-to-IO in box in MOC storage cage
                                                                    NOTE that in this same cabinet, the switch at R6-PB-C02-U39 
                                                                    has two PSUs with PSU-to-IO airflow, but needs IO-to-PSU, so PSUs are
                                                                    redundant now, but airflow is not optimal
                                   
left a total of three (3) units of PSU-to-IO and three (3) units of IO-to-PSU power supplies in the MOC storage cage

total of twelve (12) PSUs delivered so far in total for this upgrade

**Comment by er1p** [comment]
clarifying here with a second message to be clear what is undone - previous message summarized what is done

== switches still without redundant power

R1-PC-C12-U35 (PSU to I/O Airflow) - power not redundant, necessary PSU onsite

R6-PB-C02-U42 (PSU to I/O Airflow) - power not redundant, necessary PSU onsite

R3-PB-C07-U42 (PSU to I/O Airflow) - power not redundant, necessary PSU in place, but not cabled
   both PSUs are also not optimal airflow, but this does not affect redundancy

== switch with not optimal airflow (minor issue)

new issue identified during the upgrades, not on the original list

switch at R6-PB-C02-U39 - power redundant, with PSU-to-IO airflow
    the mounting of the switches should have IO-to-PSU airflow, so not optimal as currently configured,
    but this does NOT affect redundancy
    two PSUs to adjust the airflow are onsite
    this adjustment could be done without downtime with a staged double PSU swap if desireable

**Comment by hakasapl** [comment]
Thank you! I'll install the remaining ones next week

**Comment by hakasapl** [comment]
Everything is redundant now
