### ISSUE TITLE
Deploy Grafana instance for Power Monitoring visualization in OCT

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1283]
This will be deployed on the OCT head node, may be moved to MOCA infra later on. This should present a public read-only dashboard where the user can select their node, and be presented with:

* Plot of IPMI reported power consumption
* Plot of A bus power consumption
* Plot of B bus power consumption
* Plot of A + B bus power consumption

**Comment by joachimweyl** [comment]
@hakasapl check with @schwesig about power usage data.

**Comment by hakasapl** [comment]
This interface is deployed, I will create an epic for extending this kind of monitoring to NERC
