### ISSUE TITLE
Provision and make Firewall reachable, deploy transfer switch

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1284]
Firewall only has 1 PSU so we also purchased a transfer switch to make sure if can run off a/b power at MGHPCC. I will deploy this an make it available so we can poke around

**Comment by hakasapl** [comment]
Transfer switch is deployed and firewall is powered. Firewall is pending being reachable until BU network gets pulled over

**Comment by msdisme** [comment]
We'd like to do this before data center outage.  Checking with @waygil and @aabaris about whether we should ping  Chuck directly.

**Comment by msdisme** [comment]
Called Techweb, they gave me a contact in Network engineering.  Sent an email to them requesting a priority bump.

**Comment by hakasapl** [comment]
Firewall is setup and reachable remotely
