### ISSUE TITLE
Factory Reset iDracs on 5x Dell R440 in R2-PB-C20

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1290]
There are 5x Dell R440s in this rack that need their idracs to be factory reset and then network config redone. The 5x servers are:

```
U32 - 10.30.1.7
U31 - 10.30.1.8
U30 - 10.30.1.9
U29 - 10.30.1.10
U28 - 10.30.1.11
```

When redoing the network:

Subnet is `10.30.0.0/22`
Gateway is `10.30.0.1`

**Comment by yani4** [comment]
These are all set now.

**Comment by hakasapl** [comment]
Thank you!
