### ISSUE TITLE
GoDaddy: Prove that you own the domain before we can issue your SSL 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1295]
Note from GoDaddy.  Needs to be completed by April 28
Action required:
Prove that you own the domain before we can issue your SSL.

We're working on creating your Standard SSL for *.massopen.cloud, but we need you to take care of something first.

What do you need to do?

Verify that you have control over the domain using one of two options listed below. Read [these detailed instructions](https://www.godaddy.com/help/verify-domain-ownership-dns-or-html-for-my-ssl-certificate-7452?isc=gdbb4518) if you need a little more insight.

Unique id in email - will share with dev team via a different channel.

**Comment by naved001** [comment]
@msdisme we don't use godaddy certificates anymore. Don't renew with them.

**Comment by msdisme** [comment]
@pjd-nu  we do not use godaddy certs anymore.  I checked with godaddy, no reason to validate with them if we are not using SSL.
