### ISSUE TITLE
Establish a mechanism for filing support requests with Northeastern

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#13]
The Northeastern service portal (https://service.northeastern.edu/tech) requires a Northeastern login in order to open issues. Can we get a "group account" (e.g., something linked to `ops@lists.massopenc.loud`)? Or is there an email address we can use to open support issues?

This is not just, "who do we contact?", this is "how do we get an issue number for future reference and follow-up?'

**Comment by larsks** [comment]
A fallback option would simply be to establish neu.edu accounts for MOC operations staff.

**Comment by msdisme** [comment]
I've opened a ticket with them and will add more details once I hear back.  I did it via email.

**Comment by msdisme** [comment]
The right way to interact is to use rchelp@northeastern.edu.  Moving to closed, but making new issue in ops-docs to create a directory and file with partner contact information.   Discuss with team whether this needs to be private or not.
