### ISSUE TITLE
University Explorer AI Chatbot: LLM based Text-to-SQL Application

### ISSUE THREAD

**Issue by tssala23** [CCI-MOC/ops-issues#1304]
The Text-to-SQL project has the goal of using LL-Ms and chat bots to turn normal text queries into SQL queries. This project is being worked on by Northeastern Students and their professor, Hema Seshadri, Ph.D. They were running into issues while developing with students having differing machines and coding environments. Deploying and developing their application on NERC solves this issue for them.

This issue is being used as a larger tracking issue to record an overview of what needs to be done in order to help Hema and her students continue their work on this project on NERC. Their project repo will contain smaller more specific and detailed issues which will be linked here. The work done in helping them deploy everything will be recorded in Jupyter notebooks to allow for reproducibility. 

Tasks (No particular order):
- [ ] Deploy PostgreSQL
- [ ] Discuss storage, data migration, environment variables, secrets and config maps for the micro services they want to deploy.
- [ ]  Deploy MongoDB
- [ ]  Deploy text to SQL app [issue](https://github.com/hemadataworksai/ipedsllm/issues/3)
- [ ]  Deploy service to connect to chat GPT

**Comment by joachimweyl** [comment]
@tssala23 I have created an Epic to track this. We can use Issues to track the effort that our team uses to assist with the Text-to-SQL Application. Please update this issue to represent the first step of the work our team will be doing for this Epic. For example, are we going to deploy PostgreSQL for them, or will the students be doing this? If the students will be doing this work we can create an issue to track effort we will provide to help them with the deploy, if not we do not require an issue for this and we can make it the next item in the list.

**Comment by joachimweyl** [comment]
replaced by epic
