### ISSUE TITLE
Copy of Create PI account for MOC engineer usage on NERC

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1305]
So that MOC engineers have a simple method for creating VM or OpenShift instances for research and learning we should create a MOC PI for approving engineers usage and track those projects in the "do not charge by PI" list.

**Comment by joachimweyl** [comment]
@msdisme is there a reason for a copy of this? or can we close this as a duplicate of https://github.com/CCI-MOC/ops-issues/issues/1265
