### ISSUE TITLE
Refactor Project Code Base

### ISSUE THREAD

**Issue by tssala23** [CCI-MOC/ops-issues#1308]
The current GitHub Repo for their project is an amalgamation of all the work that the student have done on the project. This has result in a lot of unnecessary directories, code, and requirements being retained in the repo.
We will provide the students with guidance so that they are able to make the necessary changes.

**Comment by joachimweyl** [comment]
@tssala23 do you have documentation you will provide or will you walk them through it via meetings?

**Comment by tssala23** [comment]
We walked them through it on a call with them, I would love to be able to provide the repo but they have it as a private repo for now. For the most part I think this issue is completed, will confirm, with them in meeting on Monday.

**Comment by tssala23** [comment]
Meetings got moved to today

**Comment by tssala23** [comment]
The students say they have completed this task creating a new Repository for the project. Unfortunately they have decided to keep it private for the time being.
