### ISSUE TITLE
Reset CMCs in R1-PC-C14

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1315]
Each one of the chassis controllers in this rack needs to be reset. To do so:

1. Remove management module and apply jumper to password reset pin
2. Slide CMC back into the chassis
3. Serial into it (`115200 8N1`)
4. Login with `root`/`calvin`
5. `racadm racresetcfg` to factory reset the CMC
6. _Wait for reset_
7. `racadm setniccfg -d` to enable dhcp
8. `racadm getmacaddress` to get the mac address of the CMC (save that and leave on this issue for each CMC corresponding to U number)
9. Remove management module and remove jumper from it, then slide it back in.

A couple chassis are not powered in that rack. It would be great if you could temporarily power them to do this operation, they require C20 cables, otherwise you can just ignore them.

**Comment by hakasapl** [comment]
Can you also add a link between the first 1G interface on the R440 in this rack to the 1G netgear switch? (any port)

**Comment by imstof** [comment]
@hakasapl I assume there are cables in the moc cage I can use for that connection?

I should be starting on this tomorrow (6/5)

**Comment by hakasapl** [comment]
Yes, should be in boxes in the shelf (open top in the middle)

**Comment by imstof** [comment]
@hakasapl for some reason the front of this rack is on moc keyring, but the back is on umass keys. You might want to ask mghpcc to fix that up for you. I have access to both sets so it just took a bit of sleuthing

**Comment by imstof** [comment]
cable is in place on the r440

otherwise small problem:
what looks like a jumper on the pw reset pins is actually a jumper plug, not a 2pin jumper. see:
https://www.dell.com/support/manuals/en-us/dell-chassis-management-controller-v2.0-poweredge-fx2/cmc_fx2fx2s_2.0_ug/resetting-forgotten-administrator-password?guid=guid-89a87153-ad73-4b64-a6d9-82f74506a485&lang=en-us
usually when there are jumper pins, there is a jumper to be used parked somewhere on the board, not so here. I looked in a few modules, and opened up one of the unpowered boxes to see if I could find one. no luck.
I think there are some olde servers down in the recycling room, when mghpcc staff is here tomorrow I'll have them let me in and see if I can scavenge one.

**Comment by hakasapl** [comment]
Sounds good, let me know and I can order a jumper plug you can use on it if you don't find one.

**Comment by imstof** [comment]
@hakasapl this is done except for two.
one had an error light when I pulled it, and stayed dark after putting it back in.
the second one had the pins come off with the jumper plug. if we want to make a heroic effort I could probably improvise a jump directly on the board.

I left the 2 bad modules for the unpowered machines. all the machines with power are done. macs are:

U01 - F4:8E:38:C1:44:A0                                                                       
U03 - F4:8E:38:C7:4A:2C
U05 - 58:8A:5A:FA:12:F8
U07 - 54:48:10:F0:F3:CC
U09 - F4:8E:38:C1:49:D0
U11 - F4:8E:38:C7:4B:C2
U13 - 58:8A:5A:FA:14:E2
U15 - 50:9A:4C:AC:C9:04
U17 - F4:8E:38:C7:72:24
U19 - 
U21 - 
U23 - F4:8E:38:C1:40:1E
U25 - 58:8A:5A:F2:2F:10
U27 - F4:8E:38:C1:41:CE
U29 - F4:8E:38:C1:41:8C
U31 - F4:8E:38:C1:44:1C
U33 - F4:8E:38:C1:3D:10
U35 - F4:8E:38:C1:3F:98
U37 - F4:8E:38:C7:77:E0

**Comment by hakasapl** [comment]
Thanks! we have other CMCs we can use to replace them.

**Comment by joachimweyl** [comment]
@hakasapl it sounds like the issue is done, shall we close this and open a new issue to replace the CMCs?

**Comment by hakasapl** [comment]
No, I want to figure out the last 2 cmcs before closing

**Comment by hakasapl** [comment]
U19 and U21 will be spare parts machines, closing this
