### ISSUE TITLE
Acquire hardware for Second OCP Test Cluster

### ISSUE THREAD

**Issue by tssala23** [CCI-MOC/ops-issues#1317]
## Motivation
There are a lot of different people trying to use to test cluster which will in time create conflicts.

## Completion Criteria
8 ESI nodes leased for new test cluster

## Description
- [x] Lease 8 ESI nodes
- [ ] Test and confirm all nodes are accessible and working

**Comment by tssala23** [comment]
Investigating whether we can use nodes managed by ESI (i.e. are we able access NESE subnets via the ESI switch), if not use NERC nodes.

**Comment by tssala23** [comment]
@tzumainn could I please get 8 nodes assigned to start building this cluster

cc @larsks

**Comment by tzumainn** [comment]
@tssala23 what project should these go to?

@naved001 is there a certain resource class of nodes that can be assigned?

**Comment by naved001** [comment]
@tzumainn Probably the FC430s.  Basically any small/regular sized nodes

**Comment by tssala23** [comment]
@tzumainn I don’t think there is an existing project for these, they’re for a new cluster being built (identical to the current test cluster)

**Comment by tzumainn** [comment]
okay! what would you like the new project name to be then? are there others I should add to the project?

**Comment by tssala23** [comment]
@tzumainn nerc-test-2? Not sure if there are any naming conventions we follow for ESI projects and Dylan and Lars

**Comment by joachimweyl** [comment]
@tssala23 why are we requesting 4 nodes, I thought the plan was for 3 FC430s and 3FC830s?

**Comment by tssala23** [comment]
@joachimweyl When the epic was created I initially just copied over all the issues that you had asked to be in the epic from the examples you provided. This issue was initally just a copy of [this one](https://github.com/nerc-project/operations/issues/483).

**Comment by naved001** [comment]
@joachimweyl why the FC830s? Aren't they the big machines that consume too much power? cc: @hakasapl

**Comment by joachimweyl** [comment]
@naved001 that was the initial request, I am happy to go with just 6 FC430s it is less power and resource intensive, if we think that 3 FC430s will provide enough worker power.

**Comment by hakasapl** [comment]
We are mostly running out of FC430s at this point, and for an openshift cluster (especially a test one), 830s might be useful because that is what is planned to be compute in ocp prod eventually.

**Comment by tzumainn** [comment]
well, i just saw all these comments after assigning a bunch of leases:

```
| MOC-R4PAC22U35-S3C |                   | nerc-test-2           | fc430                | available       | False       |                                      | e00f1565-9c94-4542-a0ff-b51836acc9d3 |
| MOC-R4PAC22U35-S3D |                   | nerc-test-2           | fc430                | available       | False       |                                      | f73f113d-7e74-4b40-a52b-6600494f7f42 |
| MOC-R4PAC22U33-S1B |                   | nerc-test-2           | fc430                | available       | False       |                                      | 06d5066b-e256-4a8e-986d-85a7f8f13c61 |
| MOC-R4PAC22U33-S1C |                   | nerc-test-2           | fc430                | available       | False       |                                      | 2a12310b-fc25-4ac1-b960-89e2e9e19c7f |
| MOC-R4PAC22U33-S3A |                   | nerc-test-2           | fc430                | available       | False       |                                      | f33542ec-8146-4c69-add0-e56795b968db |
| MOC-R4PAC22U33-S3C |                   | nerc-test-2           | fc430                | available       | False       |                                      | 3a99e501-112e-4533-ab7a-9c1743276fe0 |
| MOC-R4PAC22U31-S1B |                   | nerc-test-2           | fc430                | available       | False       |                                      | 8f611d05-1cb6-4990-af5a-83bcd7cb75e0 |
| MOC-R4PAC22U31-S1C |                   | nerc-test-2           | fc430                | available       | False       |                                      | 65db7235-af1d-41c2-b7b9-23c7febfcaf4 |
```

Let me know what changes I should make, I guess?

@tssala23, you and Lars and Dylan should all have access to the nerc-test-2 project

**Comment by hakasapl** [comment]
These are fine if the NERC team is okay with it

**Comment by naved001** [comment]
sorry @tzumainn! I didn't know that there was an initial request for specific kinds of node. I'll defer to @joachimweyl on what should be allocated in that case.

**Comment by joachimweyl** [comment]
@larsks what would you prefer 3 FC830 workers or 5 FC430 workers? The 3 FC830 workers will provide more resources if that helps the decision.

**Comment by larsks** [comment]
I think we want the FC430s for the test cluster. Let's save the 830's for production use (or for if we start getting more into virtualization).
