### ISSUE TITLE
Machine Config Operator Reporting Node Pool is Degraded on Test Cluster

### ISSUE THREAD

**Issue by tssala23** [CCI-MOC/ops-issues#1323]
Machine config operator is reporting that "11 nodes are reporting degraded status on sync".
Same error message being reported for all 11 worked nodes:

`"Node wrk-0 is reporting: \"unexpected on-disk state validating against rendered-worker-b3781acdbdddc152410caa6227a86206: mode mismatch for file: \\\"/var/lib/kubelet/seccomp/allow-personality.json\\\"; expected: -rw-r--r--/420/0644; received: Lrwxrwxrwx/134218239/01000000777\",`

**Comment by tssala23** [comment]
Similar issue https://access.redhat.com/solutions/5598401

**Comment by joachimweyl** [comment]
@tssala23 What is the status of this issue? Do we have a PR to link it to?

**Comment by tssala23** [comment]
@joachimweyl This is in progress will move it over now

**Comment by tssala23** [comment]
@joachimweyl  There no PR linked as the changes made to the test cluster which caused the issue were made on the fly and not in the GH repo, likely just quickly testing a deployment. 
I removed the machine conrfig that was causing the issue and that seems to have resolved the issue.

**Comment by tssala23** [comment]
@joachimweyl  There no PR linked as the changes made to the test cluster which caused the issue were made on the fly and not in the GH repo, likely just quickly testing a deployment. 
I removed the machine conrfig that was causing the issue and that seems to have resolved the issue.
