### ISSUE TITLE
Figure out a way to automate charging for ESI leased Bare Metal machines

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1332]
## Motivation
We do not want to have to manually calculate billing for bare metal usage.

## Completion Criteria
Decide on a format for a way to track ESI leasing of Bare Metal machines. Decide how we wish to calculate charge for the lease time based on Bare Metal costs, and generate a csv output.

## Description
- [x] Decide what repo to store script in, would [process_csv_report](https://github.com/CCI-MOC/process_csv_report) work?
   - this is fine for now, we can always move it
- [x] Decide how we know what project to associate leases with
    - currently, the only option is to base it on the Lessee column
    - we might be able to include the owner as a possible field
- [x] Decide how to display the data, should it be a copy of our MGHPCC csv?
   - It should retain the same headers but not use all of them so it is easy to paste into the same table
   - `Invoice Month` is the previous month in this format "2024-10"
   - we will need a table to generate `Project - Allocation` value from
      - for example ESI project "Noodles" becomes "Noodels BM Usage" links from
   - `Project - Allocation ID` becomes "ESI Bare Metal"
   - The same table as above should have a column for PI that we can add to `Manager (PI)` column
   - `Invoice Email` is "nclinton@bu.edu" for now
   - `Institution` will also need to be in that table
   - `SU Hours (GBhr or SUhr)` is based on ESI column Resource Class
      - fc430 = BM FC430
      - fc830 = BM FC830
      - lenovo-sd650nv2-a100 & sd650nv2 = BM GPUA100SXM4
      - make this table easy to edit since BM GPUH100 are on the way
   - `Rate` pricing below
   - `Cost` Rate * SU Hours
   - `Balance` Cost-Credit (which is zero so basically just cost again)
   - Project Table
      - ESI Lessee
      - Invoice Project name (<Project> BM Usage)
      - PI
      - Institution
- [x] Decide how to calculate usage, is it time leased or does ESI have a way to calculate usage?
   - Lease time as we need to charge them for when others can't use it
- [x] Create Issues to develop what is decided upon

## Pricing
H100 - $24.16
A100SXM - $8.312
FC830 - $3.97
FC430 - $0.75

## Old Hardware Pricing (if we ever move it to BM)
A100 - $7.212
V100 - $1.214
K80 - $1.852

## Completion dates
Desired - 2024-10-31
Required - 2024-11-13

**Comment by joachimweyl** [comment]
I have been using something like this to manually gather ESI usage.
`openstack esi lease list --status any --project nerc-test-2 --long -c Resource -c 'Resource Class' -c 'Start Time' -c 'Expire Time' -c 'End Time' -f csv`
this might be helpful.

**Comment by joachimweyl** [comment]
@tzumainn for ESI I know we can check lease time based on the above script or something like it. Does ESI have any way to know when the Hardware is in use?

**Comment by tzumainn** [comment]
@joachimweyl other than the lease, nope - there may be a way to gather that data by seeing when a node is `active`, but I'm unsure if Ironic even stores that data.

**Comment by joachimweyl** [comment]
As long as it is not available to others I guess we don't want to worry about usage anyways. So for Bare Metal, we would need to collect lease data, updating the description above.

**Comment by joachimweyl** [comment]
@tzumainn are users able to start and stop their own leases or do we have to do it for them? I ask because this would allow them to some degree to manage their own costs if they know to remove the lease whenever they are not using it.

**Comment by tzumainn** [comment]
@joachimweyl yep! users can delete their own leases

**Comment by joachimweyl** [comment]
@tzumainn can they add them back themselves?

**Comment by tzumainn** [comment]
@joachimweyl they can re-claim an offer for a single day lease; they cannot re-create a deleted lease if it was initially created by an admin.

**Comment by joachimweyl** [comment]
@msdisme & @hpdempsey 
in response to the question if ESI allows users to remove and add new leases this was Mainn's response
> yep! users can delete their own leases
> they can re-claim an offer for a single day lease; they cannot re-create a deleted lease if it was initially created by an admin.

due to this, I don't see a good way to allow users an easy way to grab and release nodes only when they use them.
the last hope is if Ironic tracks active state

@tzumainn how long would it take to test if we are able to see usage data by tracking active status?

**Comment by tzumainn** [comment]
@joachimweyl I'd have to look into Ironic events, which may take a while.

I should add - I have the firm impression that the plan was always to look at the lease time, *not* the node active time, since a lease essentially reserves a node and makes it unavailable for others to use. For example, we've had A100s leased out before but not active; it doesn't make sense to me to not charge for the time when the A100s were unavailable for others to use.

If a user only wants a node for a specified amount of time, we can create a lease for that amount of time. If they get angry when the lease is released and they lose data on the node - then they should probably have asked for an additional amount of time. I don't see a good reason to break away from this model, because the alternatives sound a bit like users wanting to game the system a bit.

**Comment by joachimweyl** [comment]
@tzumainn very good point, and we can't give users the ability to just add themselves because we need to control access. It sounds like currently the way ESI works we can't easily add and remove access for BM access.
@hpdempsey & @msdisme thoughts?

**Comment by joachimweyl** [comment]
@tzumainn can you image ways to allow the release and renewal of leases to be faster and more user controlled? Obviously, there would be the risk of releasing something and then someone else takes it and it is no longer available.

**Comment by tzumainn** [comment]
@joachimweyl This is already theoretically possible. Projects can delete their own leases and have it reflected nearly instantaneously; when an offer is claimed, ESI will lease it to the project within a minute. In addition, offers can be targeted towards a specific project, making it impossible for other projects to claim.

The big limitation here is that the leases created by user-claimed offers are limited to a 24 hour duration. This is a policy decision, and not a limitation of ESI.

**Comment by joachimweyl** [comment]
@tzumainn correct me if I am wrong, but I believe the 24-hour nodes do not include the GPU nodes correct?

**Comment by tzumainn** [comment]
@joachimweyl correct!
