### ISSUE TITLE
Determine how expensive licenses for OS10 would be given our network size

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1337]
We should reach out to Dell to determine how expensive OS10 licensing would be to upgrade all our Dell switches. In addition, it would be worth getting a trial OS to test our drivers on.

**Comment by hakasapl** [comment]
Dell is still working on a quote

**Comment by hakasapl** [comment]
Some complications with dell, blocked on their response

**Comment by joachimweyl** [comment]
@hakasapl any update from Dell? if not can we poke them, 2 weeks is a long time for a response.

**Comment by hakasapl** [comment]
They have responded a while ago. Basically only some of the switches can get on a support contract, others need their ownership transferred. So I'm working on ownership transfers which requires knowing the original owner for now. I am going to ask dell for a price as well for a support contract so this issue can be closed out

**Comment by hakasapl** [comment]
We have a quote for this now, closing.
