### ISSUE TITLE
Post Status Update on massopen.cloud site

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1341]
---
title: CSAIL network redesign may affect ESI and MAAS users on July 15, 2024
state: active
severity: 1

# Prevent template from getting published. Remove this
# line when copying the template.
published: false
---
CSAIL will make changes to its network configuration on July 15, 2024. This change may affect users of ESI and MAAS and may affect their public IP addresses.

**Comment by msdisme** [comment]
@hakasapl  @joachimweyl any changes you want to see? I plan to post around 3pm July 3

**Comment by joachimweyl** [comment]
Do we want a timeframe or just date?

**Comment by hakasapl** [comment]
Is there a PR somewhere with the message?

**Comment by hakasapl** [comment]
This already happened
