### ISSUE TITLE
Create list of priority items to keep an eye on while Kim is on Vacatiaon

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1343]
## Motivation
priorities kept in once place. This will be shorter than past years because I will use epics instead of individual issues for most items.

## Completion Criteria
Kim returns

## time critical
- [ ] update [Status page](https://github.com/CCI-MOC/moc-status/pull/57) severity from 0 to 1 on the 15th
- [ ] the night of 15th or morning of 16th update to remove the status row

## List
- [ ] [SAIL creating a spreadsheet of PI matched to Allocation](https://docs.google.com/document/d/1jA1C5lCUW7cp7qXXi1Ou4jJ0fcLbPJ18F3gcnKCDcio/edit)
- [ ] [RH Lenovo Loaner GPU usage](https://docs.google.com/document/d/1a87qr67h4Uugln4SEGk7fIDBLM1w8FXgH796sCadefI/edit?usp=sharing)
- [ ] [RHELAI GPUs](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTk4MjU0)
   - most of the moves will be backup, create new project under PI restore, no need for migration
   - Jeff generating spreadsheet, will reach out to Milson if they have any VM migration questions
   - Jeff to provide goahead to have 1 of the projects transition PI owner
- [ ] [Kruise Cluster](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTk4MjU1)
   - make sure not to move any GPUs until approved by Heidi
- [ ] [InstructLab GPUs](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTk4MjU2)
   - make sure not to move any GPUs until approved by Heidi
- [ ] [Course Invoice reporting](https://github.com/nerc-project/operations/issues/374)
- [ ] [Prepaid documentation](https://github.com/nerc-project/operations/issues/590)
   - Document updated based on last meeting, need engineers to confirm, they will let you know when they have reviewed it
   - then Wayne and Scott to review
- [ ] [Hypershift](https://github.com/nerc-project/operations#workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTg0Njc3)
- [ ] all the things in the Wed NERC meeting
   - speaking of which I plan to prep all my meeting agenda's Fri 12th so they are ready for the next week I am out.

## PRs I am trying to get closed out
- [ ] [nerc-rates](https://github.com/nerc-project/coldfront-plugin-cloud/pull/169) - needs review
- [ ] [ESI into Coldfront](https://github.com/nerc-project/coldfront-plugin-cloud/pull/146) - Kristi asked for a change on 2nd
- [ ] [Active (Needs Renewal)](https://github.com/nerc-project/coldfront-nerc/pull/121) - needs Kristi's review
- [ ] [SU Flavor logic](https://github.com/CCI-MOC/openstack-billing-from-db/pull/64) - awaiting Quans changes
- [ ] [Account manager merging into plugin](https://github.com/nerc-project/coldfront-plugin-cloud/pull/134) - requires Kristi to look at Quan's answer
- [ ] [device authorization grant flow](https://github.com/nerc-project/coldfront-plugin-api/pull/28) - awaiting Kristi's approval
- [ ] [refactoring of process_report](https://github.com/CCI-MOC/process_csv_report/pull/54) - awaiting Kristi's approval
- [ ] [Billable Invoice refactor](https://github.com/CCI-MOC/process_csv_report/pull/61) - open question to Lars and Kristi
- [ ] [requirements.txt update esi-leap](https://github.com/CCI-MOC/esi-leap/pull/157) - waiting for merge
- [ ] [Update timed_projects](https://github.com/CCI-MOC/non-billable-projects/pull/28) - waiting to find out if RH plans to pay for Smart village and we should leave it open
- [ ] [10TiB object storage for prod](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/458) - Waiting on 2nd approval

## Completion dates
Desired - 2024-07-19
Required - 2024-07-22

**Comment by msdisme** [comment]
Closing as vacation is done
