### ISSUE TITLE
Review HW gift from 2 Sigma

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#136]
- [x] Review HW being offered - will be in google dock link
- [x] Review with Mike Zink, Hakan,
- [x] Review with Wayne Scott
- [x] decide what we want 

List here: https://docs.google.com/spreadsheets/d/1jfaqQ52e8OJ4YM9njSFzfPcmfnsZZyt-/edit

From note: . Larry recently reached out to us to ask if had any servers that could possibly be donated to the MOC. I’ve attached a list of manufacturer, models, and rough specs of what we have available.
 
There could be more we would be able to donate such as “blade” **type SuperMicro servers with 4 nodes in a 4U chassis but wasn’t sure if you folks would be interested in them.** They’re not currently on this list, though let us know if you would be interested in them. Some other things to note similarly to our last donation (I think it was 2 years ago?), they may or may not come with 10G cards (we do have loose Solarflare 10G cards if you also would like them), they won’t come with any drives, they will however come with rails.
 
We also have some new in **packaging multimode fiber that doesn’t meet TS’s labeling requirements that we also could donate if you are interested.**

**Comment by larsks** [comment]
I've replaced the link in the description with a google sheet, and I've added some totals by category to it.

**Comment by msdisme** [comment]
Doc to capture this and two sigma planning/discussions here: https://docs.google.com/document/d/1XETWipGQKGzR8pmALTwjIg4A3KS9oj68uLetjVKjUhY/edit

**Comment by msdisme** [comment]
Doc to capture this and two sigma planning/discussions here: https://docs.google.com/document/d/1XETWipGQKGzR8pmALTwjIg4A3KS9oj68uLetjVKjUhY/edit
