### ISSUE TITLE
H100 Deployment: Develop Plan for Networking, Evaluate with IBM and confirm BOM

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1374]
As part of the planning with Lenovo we need to confirm the bill of materials with them. This involves confirming the plan for networking.

- [x] Develop initial plan for networking
- [x] Revise plan as necessary during talks with IBM research
- [ ] Confirm with Lenovo the BOM or any changes required

**Comment by hakasapl** [comment]
Initial plan is covered in this diagram:

<img width="1300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG12Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--682be5eae6b4a77cec2c5c64b0561dd11dd985a7/MOCA%20Network%20Diagrams%20-%20H100s.png" alt="MOCA Network Diagrams - H100s.png" />

**Comment by msdisme** [comment]
Updated date estimates:

- CDU (Coolant Distribution Unit)is Oct 22
- Racks will be best case Oct 15
- We are chasing Ethernet cables and switches (unknown date)

**Comment by hakasapl** [comment]
Diagrams are here: https://lucid.app/lucidchart/81c8e90f-f892-48b1-94ce-e45315b70d8a/edit?viewport_loc=-476%2C-501%2C2222%2C1469%2C2zM~299fSVqR&invitationId=inv_500bd179-8f26-4899-9eec-14ba92f00b91

There are 3 diagrams: First is the MOCA network as it stands today, second is the MOCA network with NERC core switches when they are fully set up. The third is the H100s only and how it connects back to the main diagram.

Some context for the existing network:

The existing MOCA network is split into 3 distinct "islands", where each island belongs to an entity, such as NERC. As the MOC alliance is involved in several projects, this method proved to keep the largely L2 network organized as it grows. Each island is its own spanning tree instance with its own core. The cores connect to each other to share any traffic that needs to traverse islands. This is designed as a hub and spoke topology. The H100 deployment is planned to be a spine leaf topology, which was brought up as a requirement to improve inter-rack bandwidth between GPUs. 

To fit this topology into our existing network the plan is to treat the NERC core switches as border leafs in the H100 spine leaf topology. This way the H100 network can behave like a spine leaf while also interacting with the existing network. The main limitation with this approach is bandwidth to the core, which sits at 400G at its current state. This should be enough initially because the NESE (Northeast Storage Exchange) storage being offered externally does not comsume very much bandwidth. This may become an issue later down the road depending on whether new storage offerings will consume more throughput, although at that point it is also possible to add any new external storage to the H100 spine leaf topology directly.

**Comment by hakasapl** [comment]
PDFs for the diagrams:
[MOCA Network Diagrams - H100s.pdf](https://github.com/user-attachments/files/17030222/MOCA.Network.Diagrams.-.H100s.pdf)
[MOCA Network Diagrams - MOCA-NERC-NEWCORE.pdf](https://github.com/user-attachments/files/17030223/MOCA.Network.Diagrams.-.MOCA-NERC-NEWCORE.pdf)
[MOCA Network Diagrams - MOCA-NERC-1.pdf](https://github.com/user-attachments/files/17030225/MOCA.Network.Diagrams.-.MOCA-NERC-1.pdf)

**Comment by joachimweyl** [comment]
@hakasapl is the plan developed or is there more needed for this issue?

**Comment by hakasapl** [comment]
I would like to complete the design review before closing this. @hpdempsey is scheduling

**Comment by hpdempsey** [comment]
Design review is scheduled for 9AM EDT Thurs 10/3.

**Comment by hakasapl** [comment]
Design review was completed. Open questions from the review:
* Should we be connecting one link up to each switch for redundancy?
    * Unless there are objections, we do not plan to do this for a few reasons: because we run L2, we'd need peer links between the switches which will use up ports, reducing the total inter-rack bandwidth. Also ESI doesn't currently support this configuration. That being said, changing this in the future is a matter of recabling, we wouldn't have to purchase anything additional.

**Comment by hpdempsey** [comment]
I think we will need to reconsider the dual-link per switch option sooner than we expected.   Will open a new issue for this, as another incoming project is likely to require this.
