### ISSUE TITLE
Define baseline experiments and use cases for Storage Optimization experiments

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/ops-issues#1384]
## Motivation
We need to define the use cases / experiments for which we are going to measure performance of storage.

## Completion Criteria
Document defining a list of use cases / experiments and detailed steps to reproduce measurements and the key metrics.

## Description
- [x] Define outline of experiments, steps and key metrics
- [x] Fill in details in the document
- [x] Create issues for each of them tracking the execution and measurements
- [ ] Finish writing document with full experiments run, results and recommendations

## Completion dates
Desired - 2024-09-20

**Comment by joachimweyl** [comment]
@knikolla can we link to the draft document mentioned in last Wednesday's meeting?

**Comment by knikolla** [comment]
@joachimweyl I believe the document currently has link sharing enabled only for Red Hat https://docs.google.com/document/d/1p5qjCH3B4Etyz2t5vuUElhyk_xgjIlzzSKOj2MAzMMg/edit?usp=sharing

Will ask Anastasia to get broader sharing turned on. 

In the meanwhile marking this as closed.

**Comment by hpdempsey** [comment]
This issue is not closed, as there are still sections of the draft that are not completed.  @knikolla to review and address, as the use case is now late.

**Comment by knikolla** [comment]
As the document linked above became of larger scope than the task in this issue, I have split out the what's required by this task (definition, explanation and results of the experiments) into a GitHub repo https://github.com/cci-moc/storage-benchmarks

**Comment by knikolla** [comment]
I am splitting out the *recommendations* aspect of this issue into a separate issue https://github.com/CCI-MOC/storage-benchmarks/issues/10

The experiments and results are published in https://github.com/cci-moc/storage-benchmarks and demoed in the Red Hat Research Weekly meetings and MOC Sprint Demoes. 

Marking this as closed. The above linked Google document is not part of the deliverables of this issue as defined.
