### ISSUE TITLE
Come up with a consistent set of firewall rules for managing SSH access to various hosts

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#14]
The way we guard our SSH servers from unwanted access has been too confusing and the behavior is rather unpredictable. 

There are a bunch of custom `iptables` rules that get a list of whitelisted IPs from `wl.massopen.cloud` (this host is running on our ovirt cluster). It works as follows:
1. If you SSH from a known whitelisted IP, then you are allowed to SSH.
2. If you SSH from a new non-whitelisted IP then you can't SSH on the standard port. So you have SSH to a non-standard port, and after a day or so that IP will be whitelisted and you'll be able to SSH on the standard port.

In addition to that, we also have [denyhosts](https://github.com/denyhosts/denyhosts) that blocks people after a certain number of failed attempts.

We pretty much only allow access via public keys (no password auth) so that's good. But we should straighten out the firewall rules.

**Comment by larsks** [comment]
For hosts that actually require public ssh access (are there any?):

- Disable password authentication
- Get rid of the whitelist/blacklist machinery
- Just use a single standard port
- Consider maybe a simple rate-limiting iptables rule to cut down on the log traffic from ssh brute force attempts

For everything else:

- Disable password authentication
- Restrict ssh access to MOC-managed vpns and/or specific bastion hosts

The bastian hosts shouldn't have privileged access to anything else. E.g., I use kzn-ipmi-gw (aka i1.massopen.cloud and i2.massopen.c.oud) as a bastion host, but that also has direct access to the kaizen IPMI environment. That's a bad combination.

**Comment by naved001** [comment]
Things we discussed:
*  This is  not a task that can be accomplished in one sprint.
* We will have to go host by host to figure out if a host requires any special firewall rules and then build a configuration that way for all our hosts.
* We agree that it is okay to have root logins allowed as long as password auth is disabled.

**Comment by larsks** [comment]
Creating a standard configuration sshd will probably be simple: we can probably create a single configuration and then just copy it to all the hosts we care about.

Fixing the firewall rules will probably have to happen host-by-host, since individual hosts may have firewall rules that are required for their proper operation.

**Comment by larsks** [comment]
I would like to (a) prioritize this work and (b) start with the following hosts:

- [ ] sso1.massopen.cloud
- [ ] sso2.massopen.cloud
- [ ] mail.massopen.cloud

The firewall rules involved in these hosts was breaking @knikolla's code that interacts with the mailserver.

**Comment by larsks** [comment]
I think we have the framework in place; the next step will be to deploy it, which I think will be a new issue.
