### ISSUE TITLE
MGHPCC: Replace (or check/fix) failed PSU on neu-19-8

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#140]
![image](https://user-images.githubusercontent.com/20113064/105789305-2fdd8080-5f50-11eb-892e-04bf3b7d228b.png)

The second power supply seems to have failed. The server is running on 1 PSU at the moment.

This is a 2U Intel Server (S2600WTT) at R3-PB Cage 19 Unit 8-9.

@msdisme we may need to order compatible PSU for this server. Not sure what type yet, but I'll find out.

**Comment by hakasapl** [comment]
This node was deprecated
