### ISSUE TITLE
OpenShift Virtualization testing - Consider if it's advantageous to build a separate cluster to provide VMs

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#1402]
## Motivation
We are discussing creating OpenShift Virtualization functionality for our users. Would it be best if this was on its own cluster? This would allow it to be worked on and only affect virtualization users.

## Completion Criteria
Decide if we are going to run OpenShift virtualization on the Prod cluster or if we should create a new cluster for virtualization use.

## Description
Evaluate:

- Optimizations
- Reduced downtimes
- Complexity
- Upgrade pains

Steps:
- [ ] Wait for initial Virtualization testing to provide enough data
   - [x] https://github.com/nerc-project/operations/issues/723
   - [ ] https://github.com/nerc-project/operations/issues/728
- [ ] Open Discussion and tag those who need to be part of the discussion
- [ ] Decide if we will create a new cluster or not

## Completion dates
Desired - 2024-12-04
Required - TBD

**Comment by larsks** [comment]
@joachimweyl does this belong in nerc-project/operations?

**Comment by joachimweyl** [comment]
@larsks that feels more organized with the other issues associated with it. replaced by https://github.com/nerc-project/operations/issues/764
