### ISSUE TITLE
DHCP with Trunk Ports in ESI

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1413]
Currently, for two networks in ESI DHCP does not work for trunk ports: `nese-storage` and `nerc-infra-routed`. This is due to neutron expecting a request from the physical port MAC, which can change with a trunk port on the machine.

In this issue we should figure out the best way to resolve this. Options that were briefly discussed today:

1. Externally managed DHCP server that grants an IP to any MAC
    1. Do we lose neutron mapping?
2. Figure out how to allow neutron to grant an IP to any MAC
3. Allow users to register additional port mappings/macs with ESI?
    1. Is this possible?
4. Tenants host their own dhcp instance
    1. These are shared vlans so this would cause conflicts. Is there a way to treat these private IPs like floating IPs (I guess the controllers NAT floating IPs?) so that we can control what IPs tenants can actually allocate?

**Comment by tzumainn** [comment]
I'm not 100% sure I understand the situation. For reference, let me explain what currently happens with a provisioned node and a trunk port:

* I create a trunk port with network A as the native network and network B as a tagged network
      * A separate Neutron port is created for each network. Each port has its own fixed IP and a temporary MAC address ("fa*")
      * When the Neutron port is created, an entry is also added in each network's dhcp configuration, mapping that temporary MAC address to that fixed IP
* I attach the trunk port to a node
      * Behind the scenes, neutron DHCP updates the dhcp configuration for native network A, mapping the fixed IP to the MAC address of the node
      * However, the neutron DHCP for the tagged network B is not updated

Is the ideal solution for the tagged network port to end up with the same mac address? Or is there an unknown mac address in play?

**Comment by hakasapl** [comment]
@tzumainn the fundamental issue is that we need to be able to DHCP give out IPs for tagged networks.

If the mac address of the trunk port is the same as the physical port then it should just work, but that's not usually the case. In addition, there's the case where a user might want to consume more than one IP on the network (for example if they setup multiple VMs).

**Comment by tzumainn** [comment]
> [@tzumainn](https://github.com/tzumainn) the fundamental issue is that we need to be able to DHCP give out IPs for tagged networks.
> 
> If the mac address of the trunk port is the same as the physical port then it should just work, but that's not usually the case. In addition, there's the case where a user might want to consume more than one IP on the network (for example if they setup multiple VMs).

From my perspective, I'm most curious about the mac address. Neutron will not let you have two ports with the same mac address on the same subnet. However, if they're always different, there may be a way to allow users to create/modify the mac addresses of ports on subnets that they own. I just want to be sure that this would actually solve the problem.

**Comment by hakasapl** [comment]
I'm okay with a solution where users define this stuff, will the ports be project-based? ie. a port a user creates shouldn't exist for a different project if the node was transferred. Also, users usually don't own these subnets right? So does that mean it's not possible to do this?

**Comment by tzumainn** [comment]
Oh, users - more precisely projects - do own their own subnets. I'll create an issue to investigate if we can set the mac address of neutron ports on subnets that they own. I thiiiiiink this should be safe, since if the node is moved elsewhere it shouldn't end up on the first user's vlan anyway.

**Comment by tzumainn** [comment]
https://github.com/CCI-MOC/esi/issues/633

**Comment by hakasapl** [comment]
@tzumainn but this is mainly for shared networks, like the storage-nese network where everyone who uses that network is on the same vlan

**Comment by tzumainn** [comment]
In that case, I don't think we can allow users to set the mac addresses on the ports, as that could lead to mac address spoofing.

**Comment by hakasapl** [comment]
@tzumainn could we treat those networks similar to how we treat floating IPs and have the controller act as an intermediary so that each project has their own network?

**Comment by tzumainn** [comment]
I don't think I understand - are you asking if we can replace a shared network with multiple tenant networks, all with the same vlan?

**Comment by hakasapl** [comment]
@tzumainn I think I don't know the proper terminology here.

* How do floating IPs currently work? My understanding is that ESI controllers get exposed a single vlan with many available IPs
* When a user requests an IP they get a private IP that gets routed to through the controllers so when they attach the floating IP they can't mess with the original vlan (is that right?)
* Can we do the same with these shared networks, treat the vlan as a "floating ip vlan" and allow users to attach a different IP to it that will route through the controllers?
    * Though now that I type this out I'm realizing that this is often for storage and we probably don't want to plumb storage through controllers, that's a lot of bandwidth
  
So I guess the best option for us is to use an external DHCP server that just gives an IP for any MAC on the network instead of using the neutron one

**Comment by naved001** [comment]
> When a user requests an IP they get a private IP that gets routed to through the controllers so when they attach the floating IP they can't mess with the original vlan (is that right?)

Correct. The baremetal hosts' nics don't connect to the floating ip vlan.

> Can we do the same with these shared networks, treat the vlan as a "floating ip vlan" and allow users to attach a different IP to it that will route through the controllers? 

In theory, yes. But you basically have to add each of those as "external networks" in ESI with their own floating IP pool and would be a bit messy overall. And like you said, it's not a good idea to put all that storage traffic through the controllers.

> So I guess the best option for us is to use an external DHCP server that just gives an IP for any MAC on the network instead of using the neutron one

That's probably the simplest solution.

**Comment by hakasapl** [comment]
This is setup as external DHCP now - closing this issue.
