### ISSUE TITLE
Add EC528 to do not bill 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1420]
Since students and mentors are managers they may add allocations so I may end up adding ataturk owned projects with a deadline.  

Will we still be able to evaluate cost per project if I do it that way?

List of projects is: 

ID Sort ID asc Sort ID desc	PI Sort PI asc Sort PI desc	Title	Field of Science Sort Field of Science asc Sort Field of Science desc	Status Sort Status asc Sort Status desc
435	ataturk@bu.edu	hybrid-tx-analytical-epoxy	Computer Systems Architecture	New
441	ataturk@bu.edu	orchestrating-ai-app-cloud	Other	New
442	ataturk@bu.edu	github-bot-kata-ci	Other	New
443	ataturk@bu.edu	ansible-wrangler	Other	New
444	ataturk@bu.edu	async-batch-cloud-llms	Other	New
445	ataturk@bu.edu	autopilot-dashboard	Other	New
446	ataturk@bu.edu	container-native-fs-interposer	Other	New
447	ataturk@bu.edu	automation-snowflake-harness	Other	New
448	ataturk@bu.edu	phone-pay-budget-tracker	Other	New

**Comment by joachimweyl** [comment]
@msd created [this](https://github.com/CCI-MOC/non-billable-projects/pull/39) for you
