### ISSUE TITLE
Addition A100 for ilab on RHOAI (Beta cluster)

### ISSUE THREAD

**Issue by tssala23** [CCI-MOC/ops-issues#1423]
The team working on ilab on RHOAI have requested an additional A100.
Ryan:
"would there be a way to get an additional gpu node we can set a hard limit of two weeks but it will help us with the race towards openshift commons"

**Comment by tzumainn** [comment]
@hpdempsey hi! could you confirm?

@tssala23 which project is this exactly? is this `rhelai` or `research_rhelai`?

**Comment by tssala23** [comment]
project OpenshiftBeta

**Comment by joachimweyl** [comment]
`MOC-R8PAC23U26`, `MOC-R8PAC23U28`, `MOC-R8PAC23U32`, & `MOC-R8PAC23U33` are currently available.

not sure if it matters but they have used U28 before.

**Comment by hpdempsey** [comment]
OK to provide an additional A100 for the OpenshiftBeta project for 2 weeks.

**Comment by tzumainn** [comment]
I've assigned them `MOC-R8PAC23U25` (`MOC-R8PAC23U28` is actually in use by `research_rhelai`; I believe they were previously assigned `U25`, but there was a hardware issue that was only recently fixed).

The lease will expire at the end of 11/15. @tssala23 please let them know that!

**Comment by tssala23** [comment]
Thank, it's been added to the cluster and I've told them about the expiring lease
