### ISSUE TITLE
Communication Plan for NERC Core Network Upgrade

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#1424]
In case users are impacted by the network upgrade we should have a communication plan to notify them that the upgrade Is happening, identify any areas they may be imacted, steps to mitigate the issue and who to contact if they require assistance. 

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Communication Plan for NERC Core Network Upgrade**
  - Given a communication plan is in place for the network upgrade
  - When the upgrade is occurring so they may identify whether it is what impacted them
  - Then the plan should notify them about the upgrade, identify potential impacts, provide steps to mitigate issues, and include contact information for assistance

**Comment by joachimweyl** [comment]
moved to nerc-project/operations https://github.com/nerc-project/operations/issues/798
