### ISSUE TITLE
A100 Running RHEL AI 1.3

### ISSUE THREAD

**Issue by tssala23** [CCI-MOC/ops-issues#1441]
## Motivation
Ryan is looking for a RHEL AI 1.3 server with one or two GPUs for people to work on the UI to support InstructLab GUI work.

## Completion Criteria
One A100 assigned to a ESI project running RHEL AI 1.3

## Description
- [x] Assign A100 to ESI project
- [x] Build 1.3 RHEL AI image
- [x] `bootc switch` to new image
- [x] Give Ryan access to node (add ssh key)
- [x] Verify that Ryan is able to access node

## Completion dates
Desired - 2024-12-06
Required - TBD

**Comment by tssala23** [comment]
@joachimweyl Mentioning you here for visibility.

**Comment by tssala23** [comment]
@tzumainn This ESI project can be call RHELAI-GUI

**Comment by hpdempsey** [comment]
I approve funding for this.

**Comment by tzumainn** [comment]
I've assigned MOC-R8PAC23U26  to the project - I think that should be it!

**Comment by joachimweyl** [comment]
@tssala23 have we confirmed if Ryan can access this, if so are we ready to close this issue?

**Comment by tssala23** [comment]
@joachimweyl Sorry about that, yes he has been using the node
