### ISSUE TITLE
Add a single R740XD to ESI with new AMD GPUs

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#1444]
The node in question should be in `R2-PC-C06-U33`. Make sure the service tag matches before pulling it:

```
Service Tag: 4VZ81S2 
OBM mac: d0:94:66:8c:2c:37 
```

Please remove the NVIDIA V100 GPU from this node and replace it with 2x AMD GPUs (These GPUs are in the right side of the MOC cage above the plastic drawers). If you need PCIe power cables for the GPU there should be ones for the R740 in a bag of them in a plastic bin in the bottom of the MOC cage (could be sitting loose, I don't 100% remember), let me know if you have trouble finding it.

You can leave the cables dangling, but install blanks in the old rack.

The node should be installed into `R4-PA-C02`. Find the next available U, it doesn't matter.

Connect the iDRAC port to the 1G switch in that rack, port doesn't matter, make sure iDRAC is set to DHCP. Let me know the port after.

Connect 2x10G NICs to the TORS, let me know which ports you use, I'll configure the switch remotely.

**Comment by Jperez3313** [comment]
Hi Hakan,

We have swapped in the two new AMD GPUs and racked the machine in its new home.  We will get this all cabled up and ready for you tomorrow morning then send email with the ports being used.

Cheers,
Jackson.

**Comment by dclyon** [comment]
Hi Hakan, 

Just to add, these two GPU's each have two 8-pin molex power sockets. The previous GPU only had the one 8-pin socket. 

The only compatible molex connectors we could find have one 8-pin connector and one 6-pin connector, leaving two pins on each GPU vacant. I don't foresee a problem with this configuration but I want to be sure you are aware before powering anything on.

Please let me know if you have any questions or reservations.

Thank you,
Chase

**Comment by hakasapl** [comment]
@dclyon You mean the GPU has two 2x4 pin sockets for power? The cables in the cage one end is the smaller pin proprietary dell board socket and the other side is two 2x4 right? What's the PSU rating on this machine again?

**Comment by dclyon** [comment]
Good morning, 

You are correct, each GPU has two 2x4 pin power sockets. In the cage we managed to find molex connectors with the proprietary Dell board socket on one end and on the other end a 2x4 pin and 2x3 + an optional 2x1 (6 total pins). This leaves two vacant pins in one of the 2x4 sockets on each GPU. 

The card in riser slot 1 is configured to pull power from the riser card itself via the onboard Dell small pin socket. The card in riser slot 2 is to pull power from the 225W motherboard riser 2 socket.

According to AMD specs, the Alveo V80 has a 190W TDP, so we should be in good shape.  Each GPU should receive 225W from riser power and 75W from the PCIe slot itself, leaving plenty of headroom.

I can also provide pictures if helpful, I realize my explanation may be a confusing read.

Cheers,
Chase

**Comment by hakasapl** [comment]
Hi @dclyon, apologies, I needed to be more specific. The cards should be AMD Mi210 cards. The V80 cards are compute accelerators for a different project, it would be great to return those to the MOC cage.

Are there any other AMD stuff in the cage? They arrived a while ago so it's not in my memory. If it's not there I will look for it the next time I'm on-site

**Comment by hakasapl** [comment]
I think their TDP is also okay, 225 from the smaller pin dell port and 75 from the socket if I understood that correctly?

**Comment by dclyon** [comment]
Correct, that is my understanding.

**Comment by hakasapl** [comment]
@dclyon let me know if you are able to find the Mi210 cards. It's possible they are still in the loading dock if not in the cage. It would be in my name "Hakan Saplakoglu"

**Comment by dclyon** [comment]
Ah ok, I'll check with shipping -- we didn't see any other AMD cards in the locker. Jackson and I are also happy to meet via Zoom at 4p.

Thank you,
Chase

**Comment by Jperez3313** [comment]
This is all set.  We have enabled DHCP in the Idrac settings.
- The 1G is connected to port 29.
- The two 10G connections are connected to ports 33 & 34.
Let me know if you have any issues.

Cheers,
Jackson.

**Comment by hakasapl** [comment]
@Jperez3313 and @dclyon I can reach the node's idrac but I believe the NIC on this node may be having issues. Could you add a discrete NIC into this node? There are tons of extra 10G nics at the bottom shelf of the MOC cage. Ideally an intel NIC if you find one. I think most are lenovo

**Comment by Jperez3313** [comment]
@hakasapl This should be all set, and all indicator lights on the new NIC are showing green.  Let me know if you have any issues.

**Comment by hakasapl** [comment]
@Jperez3313 I'm not seeing the NIC in pxe boot menu at all and no device settings option for it. Maybe it's not compatible. In the MOC cage in one of the plastic drawers there are a bunch of SFPs. If there is a RJ45 SFP in there could you use that to connect one port on the node to one of the regular 1G ports? Hopefully those work.

**Comment by hakasapl** [comment]
BTW I am also getting a `The storage BP2 Signal cable is not connected, or is improperly connected.` in the iDrac - did that get loose or something?

**Comment by Jperez3313** [comment]
@hakasapl We used the RJ45 SFP and connected in to one of the regular 1G ports want to give that a shot and let me know what you see? 

Also checked if any cables were loose and they all seemed okay, can you give it a shot now and see if you are still seeing the BP2 Signal Cable warning in iDrac.

Thanks,
Jackson.

**Comment by hakasapl** [comment]
@Jperez3313 is that port 33 still on the 5048 switch?

**Comment by Jperez3313** [comment]
@hakasapl Oops it is in port 35 now.

**Comment by hakasapl** [comment]
@Jperez3313 ahh I think I know where we're going wrong. Sorry I should have been more specific, I forget these racks have two switches. Could you connect up to the Dell 5048-ON in that rack instead of the Cisco switch? Let's keep the same RJ45 SFP configuration, just move it up to the dell switch instead (assuming you connected to the cisco at the moment)

**Comment by Jperez3313** [comment]
@hakasapl Ahh that makes sense.  The original transceivers say "Cisco compatible" so I figured it was that switch.  I will check the cage now and see if you have any SFP RJ45 Dell compatible gbics and update you when that is complete.

**Comment by hakasapl** [comment]
@Jperez3313 the cisco one should be okay in the dell switch, I think the SFPs are usually okay in each other, I've usually only had issues with 40G + optics with mismatches.

**Comment by Jperez3313** [comment]
@hakasapl 

We tried the RJ45 SFP Adapter in port 36 but are not seeing any signs of link on the switch.  I also put the original 10G twin ax connections into port 33 & 34 on the dell switch.  Can you give that a shot and let me know if you see any of them?

Thanks,
Jackson.

**Comment by hakasapl** [comment]
@Jperez3313 we are all set, thank you for your help!
