### ISSUE TITLE
MGHPCC: Replace memory in neu-19-34

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#148]
This is a dell server running OCP/CNV. Slot is DIMM B1.

![image](https://user-images.githubusercontent.com/20113064/106473318-a6f3a700-6471-11eb-9c5d-69657c4af2d4.png)

I have heard that reseating may also help, but not sure about that.

@larsks we will have to turn off this host when we get to replacing the memory.

**Comment by hakasapl** [comment]
I'm on-site on Saturday, the 6th. I will take care of this then - we also have a bunch of spare memory in the MOC cage, I'll have to see if they are the same. Naved, are you available to turn off the machine on Saturday before I dig into it?

**Comment by naved001** [comment]
Yes, I can do that.

**Comment by hakasapl** [comment]
Memory replaced
