### ISSUE TITLE
Setup for Peter's Class on OpenShift.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/ops-issues#155]
Depending on timing for Peter's class 

if 3.11:
- [ ] Get list of project name, admin users: mentor user email, teachers and ta email. students
- [ ] add to notification mailing lists
- [ ] if any need power 9, same data plus their ssh key

if 4.0:

- [ ] new tool, will create account for initial admin by TA or Peter via horizon 
- [ ] invite students via horizon UX

**Comment by msdisme** [comment]
dup of #166
