### ISSUE TITLE
Create network diagram for OCT/MOC/NESE connectivity

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#156]
- As a network engineer I need to know the network architecture to help plan new connections and ensure a reliable network service.
- As a MOC operator I need to understand how devices are connected in order to diagnose networking problems.
- As a NERC operator I want to understand the rack location of current and incoming  gear to help determine who may be involved in and who has access to, the gear.

**Comment by larsks** [comment]
https://lucid.app/lucidchart/invitations/accept/9452757b-7601-473f-b011-a9821a1c22f1

**Comment by larsks** [comment]
Switch port details and rack locations are in https://docs.google.com/spreadsheets/d/1kKNx2HKtuTL_UZFDsOMfKqk-9KJ3Yd46lvJRn6P-3Zc/edit#gid=0

**Comment by msdisme** [comment]
lucid chart - nice template:  https://lucid.app/lucidchart/invitations/accept/e501bf29-018c-4861-bca4-18e6cfd77a35?viewport_loc=-1985.8222593296098%2C-533.0064539395122%2C6456.040673342341%2C3704.3948548796093%2C0_0

**Comment by msdisme** [comment]
@naved001 should this be in done?

**Comment by naved001** [comment]
Maybe, in that case I should open a different issue since my aim is to draw a network diagram of our brocade fabric and how we connect to kumo and engage1 hardware.

**Comment by naved001** [comment]
Here's MOC's network diagram: https://lucid.app/lucidchart/955179f6-59dc-4851-b00a-0735c603f7cd/view?page=0_0#

I have also shared the editable lucid char link with the team.

**Comment by naved001** [comment]
Here's a diagram that @hakasapl had made which covers how MOC, OCT and NESE are/will-be connected.
https://lucid.app/lucidchart/4664ad52-160e-42a1-b933-14e1a6f29a6b/edit?page=0_0#

**Comment by naved001** [comment]
Based on our discussion:

1. We have now created a [networking diagram](https://lucid.app/lucidchart/955179f6-59dc-4851-b00a-0735c603f7cd/view?page=0_0#) that explains how are switches are connected and shows connections between Kumo, Engage1 and Kaizen. 

2. We have a [diagram](https://lucid.app/lucidchart/4664ad52-160e-42a1-b933-14e1a6f29a6b/edit?page=0_0#) that explains the connections between MOC, OCT and NESE.

3. We need a way note down how are our switchports used, and if there are any available switch ports for future connections. I think that is best solved by an inventory system, and not a diagram. Created a new issue for that: #233
