### ISSUE TITLE
Check Brocade fabric for free 40Gb port

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#158]

**Comment by naved001** [comment]
@hakasapl There's no free 40G port on the brocade switch in cage 15 u 43.

**Comment by hakasapl** [comment]
Okay, is there another 40 or 100G switch that has these VLANs we can hook up to?

**Comment by msdisme** [comment]
if I understand correctly, this is tied to the option A or B in this diagram: https://lucid.app/lucidchart/4664ad52-160e-42a1-b933-14e1a6f29a6b/edit?shared=true&page=0_0#?folder_id=home&browser=icon  and this means we have to connect Row 6 directly to Row 3 to enable NESE and MOC access.

And the implication is we have to go with option B - connecting Row 6 and 3

**Comment by naved001** [comment]
I mapped our usage of 40G ports here: 

https://docs.google.com/spreadsheets/d/1kKNx2HKtuTL_UZFDsOMfKqk-9KJ3Yd46lvJRn6P-3Zc/edit#gid=1581716051

and we are thinking of running another 40G cable from our end to OCT for a total of 80G between OCT and MOC, and then a direct 100G link between OCT and R6.
