### ISSUE TITLE
Rubicon Power 9 information needed from them

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#16]
- [x] buy additional bitwaren seats
- [x] invite to bitwarden
- [x] Rubicon team finish accepting bitwarden invites
- [x] Create github/gitlab access to appropriate things including our backlog and sprints. 

Needed from:  Rubicon  - ssh keys, email addresses,

**Comment by YonatanGolick** [comment]
Accepting bitwarden invites - Waiting for the last invite from @Michael Daitzman. Will update when it happens.
 

Razmaabari@rubicone.co.il | ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1AipWFUuKpp92TNIqkSVxddb314bnWN/Li+N2RoVu6AQrPiA/WJgqlm1feToiwZdfsPTpAQPgX1GOrIPOd0aMuV3rsK1A9ifUmo9M2j7ND44RlPHV5+1PMr18FedDdG0mXMz2IYpYP9G7qz4NUXwWWoeJTSMjOaBmZRGAsRcpCzzgOSAXn+LtHl82SPL3/zW5OUyIqhCK/LKyBQsg/KlVqpLFiiCawomjnX7IBSHbo/lZI71YHTrczOaWsL/kdRqwDYdFolFCJMfZDUzaNm+5Jau1As5lNSqeDC0Cexx8MDl5r6Er++D3khRI8RaY0fQH7GyiQeuaZHbHgahjoLTr user@DESKTOP-DR6HEO7

nirlevy@rubicone.co.il | ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0Mez4644SdWHP6L7iGxqhaHLxdnUpxFkhgzZ7IqpCnfd3k5o7Wx67U2rh4R00Mqefdo95toqor4jkf457gS1g5zlITPwALq4FcpzWgNElx0pje/1qC3sDbI4JVDCv94f+HPNKS6S2US+tYStgKNtV2IMvzr7I49bwRzgj9M/EPSXZXJwBGmdnPvtipUybB0Vn8SXJH6KScNWjSo3Ocl3ebGEfiPspj0mBZCU7aRmB7zu6qzmcrjB3e53mMTzWlL1hvMfyOTWc+ag3+mRJuSe0xIVWQQRm8bjGskbuwySfpqE363SetP1fPH8EkOo3ddkcDfyCkBED4Gl9kBM3bZId nir@DESKTOP-IIJDJV1

yonatangolick@rubicone.co.il | ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu824gI6+NzWUy8koCpF5fW4WkUBnNSyA480LywpaqCqSqtEH3seIQRf4dsxGFewMnW3sdNAKSlKPobQgwWbVmqsqqWqMYDdCNVy3vS44tkD9RAJEUwLOGQzCIFvdZ4dvlvBitTNHPriK/EoDrjSyaOl+iUGnYG+ikG3scOqrh3KBPmywY5h3UuvwHMdTX0vUqxlmOm9zGYaJ1GIgXgTqYzlsPh2vv++51AuBp/NTlccjVH1n9MNL3foJFB11NjHo4yz6LBn6paUvnRzaRLdacsB7mTyExf7SPZsd4iwG2M5Zr4dx+mCfmHj8rr1WvK6X4aNppiM/241YjGNBtZreh yg199@DESKTOP-74P4F95
