### ISSUE TITLE
Reach out to hakan and Nerc people to see what information they are gathering to put into netbox

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#160]

**Comment by naved001** [comment]
@hakasapl: I would like to know what information you plan to put into netbox; it would be helpful for us when we do our deployment.

**Comment by hakasapl** [comment]
Basic info about the machine (brand, purpose, owner, and U-size), and networking info like VLANs, which switches they are at, etc. The more important thing for us is to see where rack space is occupied and what that occupation is - UMass has too many private clusters for us to fill in all the data that netbox has fields for, and we can't expect those customers to keep netbox maintained, so it will be easier for us to keep the minimal info we need. This may be different for you, but that's your choice.

**Comment by msdisme** [comment]
Need info from Augustine on what capturing.  Send mail now.

**Comment by msdisme** [comment]
From Augutine in November 2020:
We are tracking:

devices (including PDUs and patch panels) - name, location (rack+u+slot), serial number, warranty expiration date, power draw, ports (network and power)

cables - ethernet, power, mgmt..etc.

I am experimenting with IPAM features, but that's down the road after I complete moving ALL of our inventory.

- Augustine

**Comment by msdisme** [comment]
@naved001 - is this essentially completed?
