### ISSUE TITLE
Deploy Netbox

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#161]
- [x] Figure out where we're going to host the Netbox instance
  - deploy in openshift -- production (ocp?) or infra cluster?
- [x] k8s manifests in a github repository deployed via argocd
- [ ] arrange for backups of netbox data (e.g. db dumps to s3 endpoint)
- [ ] is there value in having access to this when the datacenter is down? e.g. can we run a local copy from backup data, or do we need this to be hosted outside of mghpcc?

**Comment by larsks** [comment]
Let's plan on putting this on the production OCP cluster once that is up and running.

**Comment by naved001** [comment]
I am going to bump this up on the backlog now.

**Comment by naved001** [comment]
this is now deployed; we have separate issues open for other netbox tasks.
