### ISSUE TITLE
MGHPCC: replace memory in neu-17-2

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#163]
![image](https://user-images.githubusercontent.com/20113064/107291311-ff104780-6a35-11eb-8e47-05f1651d6332.png)

Memory needs replacement. Requires a 32 GIG stick at slot A10.

this is an openstack compute node, so we'll have to vacate that host before we can power it off.

cc: @larsks, @msdisme

**Comment by hakasapl** [comment]
Ram replaced
