### ISSUE TITLE
Which switches allow copying config at scale time priority

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#164]
Naved, can you follow up with the Ansible folks about whether Ansible can copy config at scale (instead of serially) to switches and whether the proposed switches for the new racks will work?
 cc:emmanuel cechet and Hakan

q1: Ansible question: can Ansible work on multiple switches in parallel.  
q2: do we have to serialize access to individual switches or can the changes be made on switch in parallel 
q3: Requirements for the switches to take into account? 

Orran also following up with a contact at Dell.

**Comment by hakasapl** [comment]
In UMass OCT Racks:
s4048-ON
s5048f-ON <= not yet deployed
z9100 <= not yet deployed

**Comment by larsks** [comment]
W/r/t to the question of parallelism on Ansible's part, that's something we can test ourselves as long as we have more than one or two switches. We should be able to put together a test case faily

**Comment by naved001** [comment]
Did not get any response on the irc channel nor did I get an email response.

@tzumainn's response this matter:

> I am going to guess that depends on neutron, since that's the one that actually uses ansible-networking - so it depends on how neutron handles those API requests
> but that is just blatant speculation
>

**Comment by larsks** [comment]
From Dan Radez:

> It serializes requests to a particular switch and runs multiple switches in parallel.
