### ISSUE TITLE
Power 9 3.11 nodes decrease to 3

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#17]
As part of rubicon work, decrease 3.11 cluster to 3 

1. notify power 9 users first
2. Method for distinction between 3.11 ans 4.x access.
3.what  else?

**Comment by msdisme** [comment]
Did this get resolved?

**Comment by naved001** [comment]
Nodes that got freed up are:  bu-21-5, bu-21-6, bu-21-7.
