### ISSUE TITLE
Create mailing list for cnv openshift users, send out notification re: cluster issues and remediation plan

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#171]

**Comment by larsks** [comment]
@msdisme do you have any thoughts/preferences on whether this should live on the massopen.cloud domain vs. the openinfralabsl.org domain?

**Comment by msdisme** [comment]
my instinct is openinfra because it’s operate first, but if MOC is simpler that’s good too.

________________________________

**Comment by larsks** [comment]
It looks like the openinfra mailing list is hosted on opendev.org. We can create a list by [making a pull request](https://docs.opendev.org/opendev/system-config/latest/lists.html), but automation would require `root` access to the mailman server and it seems unlikely we can get that. I'm going to look at setting a list up on the the MOC list server for now.

**Comment by msdisme** [comment]
+1

________________________________

**Comment by larsks** [comment]
https://github.com/open-infrastructure-labs/mailing-lists is a playbook that will create the mailing list, populate it with email addresses from OpenShift, and configure the list to allow posting from  a small group of non-members.
