### ISSUE TITLE
Order switch and connecting cables for OCT 3/Row 6 (details in smartsheet linked in comment)

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#172]
- [ ] write quote
- [ ] order new funded from moc gift include cables to connect to second which will be a refurbished one

**Comment by naved001** [comment]
[details in smartsheet](https://app.smartsheet.com/sheets/rP7MjWjHHJhR4PcVh9f3prV9P289r8VV34HMG651?view=gantt)

**Comment by naved001** [comment]
Clickable link: https://app.smartsheet.com/sheets/rP7MjWjHHJhR4PcVh9f3prV9P289r8VV34HMG651?view=gantt

I am going to edit the title to not have the link in it.

**Comment by msdisme** [comment]
@hakan - this is all ordered, yes?
