### ISSUE TITLE
Pxe server for Jonathan Appavoo

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#173]
To provision the intel nodes. 

I have suggested using MaaS to put a new OS and then manually install a custom kernel; waiting to hear back on that suggestion.

**Comment by msdisme** [comment]
https://support.massopen.cloud/scp/tickets.php?id=844

**Comment by naved001** [comment]
they seem to be happy with using maas since it has ubuntu 20.04 images; so need of a pxe server.
