### ISSUE TITLE
MGHPCC: replace drive in neu-5-21

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#181]
Replace drive in neu-5-21. Needs a 600Gig drive. According to iDRAC it is "Physical Disk 0:1:6, Slot 6". Should be hot swappable.

It's a seagate drive.

neu = R3 Pod B.
5-21 = Cage 5 Unit 21. It's a dell poweredge server (1U).

![image](https://user-images.githubusercontent.com/20113064/108764409-8f638780-7520-11eb-872a-7e917943be09.png)

@hakasapl

**Comment by naved001** [comment]
I will create the OSD on that drive once new drive is in. after that I'll close this issue.

**Comment by hakasapl** [comment]
Scheduled for 2/27

**Comment by hakasapl** [comment]
Drive replaced

**Comment by naved001** [comment]
I'll keep it open until I work on recreating the OSD on it.

**Comment by naved001** [comment]
I created the OSD on that drive.
