### ISSUE TITLE
MGHPCC: replace drive in neu-19-15

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#182]
This is a 2U server Dell R730xd.

Failed drive is in Slot 8 (Physical Disk 0:1:8)

![image](https://user-images.githubusercontent.com/20113064/109010262-92c05580-767d-11eb-8660-3d46d92c25d9.png)

needs a 10TB drive.

This is part of our production ceph cluster so I'll recreate the OSD once it is replaced.

**Comment by msdisme** [comment]
Let me know how many extra drives of that type we have so I know whether I need to order more.


---
Michael Daitzman (He/Him)
msd@bu.edu
cell:978-201-9965

**Comment by naved001** [comment]
I think we have 3 X 10TB HDD according to @hakasapl (he posted about that in the infra channel).

**Comment by hakasapl** [comment]
Yes, I'm going to keep that post updated with inventory changes (it's pinned in the infra channel)

**Comment by naved001** [comment]
@hakasapl please let me know when you plan to take care of this. thanks!

**Comment by hakasapl** [comment]
On-site tomorrow I'll take care of it then

**Comment by naved001** [comment]
I created the OSD on the drive, ceph cluster is happy.
