### ISSUE TITLE
https://p9-openshift.osh.massopen.cloud:8443/ has bad certificate

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#183]
<img width="1321" alt="Screen Shot 2021-02-24 at 3 47 38 PM" src="https://user-images.githubusercontent.com/6126065/109064142-05e6bd80-76b8-11eb-87c0-86808ebcdb39.png">
https://p9-openshift.osh.massopen.cloud:8443/ reporting an expired certificate

Seems to work now (14-APR) as I replaced certificates about a 1.5 months ago ish.

**Comment by larsks** [comment]
https://p9-openshift.osh.massopen.cloud:8443/ has an expired certificate

**Comment by rob-baron** [comment]
ok, the certificates have been updated, they are due to expire in august, though the warning will start appearing in july.
