### ISSUE TITLE
Need Help setting up VM image for OCT

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#184]
Suranga (handagala.s@husky.neu.edu - invited to CCI-MOC, not sure he has accepted yet) has a curated VM with the FPGA tools, and needs help figuring out how to turn it into a VM image. We’ve solved the basic problem - turning a snapshot into an image - but now he needs to figure out how to get it to accept SSH keypairs from OpenStack. Do you mind if I pester Kristi about this? Or is there anyone else you’d recommend?

**Comment by msdisme** [comment]
Suranga has something he is going to try, but wanted this in as a placeholder in case he needs an assist.

**Comment by larsks** [comment]
The short answer is "install `cloud-init`". I can help out if necessary.
