### ISSUE TITLE
GPU monitoring  on production cluster process to get them monitored in OCP 4.x

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#186]
As an organization running a production cluster with GPUs, we want to have monitoring for the GPUs in the cluster so that we receive notifications when the GPUs are not operational so that we can address the issues before they impact our user community.

Depends on #185

**Comment by larsks** [comment]
Nvidia profiling only supports two specific models (https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-user-guide/feature-overview.html#profiling-support)

**Comment by larsks** [comment]
Ideally, wait for https://github.com/CCI-MOC/ops-issues/issues/185 and adopt the same solution.

**Comment by joachimweyl** [comment]
This will be on the NERC by the time we could get to work on this.
