### ISSUE TITLE
Configure RGW correctly so we have object storage for OCP 4.7 cluster

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#189]
Some rgw meta pool needs to be created for OCS to correctly use rgw for object store.

**Comment by naved001** [comment]
open case: https://access.redhat.com/support/cases/#/case/02889471

**Comment by naved001** [comment]
still waiting on redhat support.

**Comment by naved001** [comment]
Most recent update from redhat support:

> As we mentioned in our previous updates the issue at Ceph and not OCS here. The issue would be fixed by the next z-stream release of Ceph, RHCS 4.2z1.
> We're awaiting the release of RHCS 4.2z1.

**Comment by naved001** [comment]
In order to upgrade the ceph cluster, I needed to make sure our repo server has the latest packages. So I had register the repo server with my account (because I think Rado's account stopped working) and now it's downloading the new packages, then the ceph hosts will be able to download the latest rhceph4.2

**Comment by naved001** [comment]
In rhceph 4.2 filestore is no longer supported for production (they would work, but not supported), and our 4 performance hosts are still using filestore. 

The way to migrate to bluestore is to basically remove some OSDs and recreate them as bluestore and wait for things to rebalance, and continue to do so until everything is migrated. So instead of doing that I started the process of migrating to performance pool to nVmes. For that I simply had to provision OSDs on the nVmes and add them to the `performance` root of ceph. Now I am waiting for things to rebalance, and once that's done I will start marking the old OSDs in performance root `out`, one host at a time until things are migrated.

Having the pg autoscaler is helpful in this case since we are migrating from 140 OSDs to 10 OSDs.

**Comment by larsks** [comment]
@naved001 we're already using bluestore for the non-performance storage?

**Comment by naved001** [comment]
Yes, for the `size` root (i.e. non-performance) we are using bluestore.

```
[root@kzn-mon1 ~]# ceph osd metadata 152 |grep -e hostname -e osd_objectstore
    "hostname": "kzn-osd05.kzn.moc",
    "osd_objectstore": "bluestore",
[root@kzn-mon1 ~]# ceph osd metadata 164 |grep -e hostname -e osd_objectstore
    "hostname": "kzn-osd06.kzn.moc",
    "osd_objectstore": "bluestore",
```

here's what I see for the performance root
```
[root@kzn-mon1 ~]# ceph osd metadata 0 |grep -e hostname -e osd_objectstore
    "hostname": "kzn-osd01",
    "osd_objectstore": "filestore",
[root@kzn-mon1 ~]# ceph osd metadata 38 |grep -e hostname -e osd_objectstore
    "hostname": "kzn-osd02.kzn.moc",
```

**Comment by naved001** [comment]
Over the weekend I accomplished the following:

* Migrated the performance root to SSDs.
* Removed the old hardware once things were rebalances.
* Upgraded the ceph cluster to the most recent rh 4.2

I will post the details about the migration process on issue #83 

I can now begin to point OCT to the newly upgraded external rhceph.

**Comment by naved001** [comment]
Still blocked on redhat support.

Associated bugzilla that I don't have access to is here: https://bugzilla.redhat.com/show_bug.cgi?id=1931329
