### ISSUE TITLE
Identify paid osticket hosting providers

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#192]
Part of https://github.com/CCI-MOC/ops-issues/issues/134

- [x] identify provider
- [x] As part of the migration, it would be great it we can ensure that for new tickets, the ticket id == the id in the url.
- [x] contact to ask about how migration of existing works
- [x] get answer

**Comment by msdisme** [comment]
https://supportsystem.com/pricing/

**Comment by msdisme** [comment]
Hi Michael-

Thank you for your email and interest in SupportSystem. Yes, we can assist you with migrating your data from your osTicket installation to SupportSystem. Let us set up a preliminary call to go through the process and steps to migrate. On the preliminary call we will connect you with our development team to review the following regarding your osTicket installation:


The current version you are running
Any plugins you have installed
Language packs you may have installed
Any customizations or modifications to the code base
For them to complete preliminary call, you will need to have full access to the database you have osTicket installed. This call will last about 10 minutes and they can then set up the next steps. The goal is to extract a dump of your osTicket database to merge into your SupportSystem trial account; if you haven't yet, please start a trial today by clicking here. 

Once we have the data, our team will also go through the steps necessary to shut down your osTicket installation once your data has been migrated over to SupportSystem. Our hours are Monday-Friday 8:00am-5:00pm CDT. Please let me know what time and day works best for you and I will schedule the call accordingly. 

As for discount pricing, our cloud hosted SupportSystem is fairly priced at $9/$12/$16 per agent per month. An agent is anyone who is currently in your help desk that has access to the tickets to respond or resolve the issue. You can add or delete agents at any time in the billing cycle. The subscription is renewed automatically based on your selected billing frequency. We do offer a slight discount for annual renewals which brings the per agent per month rate to $8/$11/$14 when paying in advance via automatic credit card renewal. 

Please don't hesitate to reply if you have further questions.Thanks again and I look forward to your response,




-- 
Karen Moreau 
Happy Customer Concierge

Enhancesoft
parent company of 


osTicket & SupportSystem
Alexandria, Louisiana, USA
phone: +1 (318) 290-3674
fax: +1 (318) 542-7958

image

**Comment by larsks** [comment]
As part of the migration, it would be great it we can ensure that for new tickets, the ticket id == the id in the url.

**Comment by msdisme** [comment]
- [ ] Identify a place to store dump of database
- [ ] email users of potential osticket outage
- [ ] Created a trial account in support system - send them email
- [ ] schedule Meeting with Naved and Karen to do  Database dump - they will run  mysql commands- hop on goto meeting (we may want to insist on zoom?) - keyboard and mouse control and do stuff via our screen.  Plan for it to take 2 hours:
2 hours.  
- [ ] DNS change while in process.  

Next steps - start trial - cloud hosted, once happy redirect.  Typically hard cut over - Osticket offline, disable email, once in cloud, go live.

**Comment by larsks** [comment]
If we're going to have this operating by the aug. 10 outage, we should plan on having the database migration *finished* by the end of next week at the latest. We pick a date (and confirm it with osticket) for the migration today or tomorrow.

**Comment by naved001** [comment]
I am meeting them today at 3pm to do the migration.

**Comment by naved001** [comment]
We have migrated our stuff.

These were the instructions they sent after the migration

> The data migration was a success! You should now be able to login to your [helpdesk] using your local osTicket username and password. Once logged in you will need to do the following:
> - Re-enter your email credentials, IMAP/POP info, and SMTP info for all helpdesk emails under Admin Panel > Emails > Emails.
> - Set your default email under Admin Panel > Emails > Settings > Default MTA.
> - Configure some Agents to be Administrators and configure some (minimum of one) to have Account Panel Access. The Account Panel is where the billing info, etc. is located so make sure they are trusted.
> - Add your custom domain (if you have one) under Account Panel > Account > Domains > Add Domain.
> 

I have done that. We have 2 custom subdomains pointing to it (osticket.massopen.cloud and support.massopen.cloud) can't have more than that apparently.

Don't know why but I did not get an email response from it when I created an account.

**Comment by naved001** [comment]
Their response about the email situation: 


> It appears your Email's SMTP configuration is set to use Port 25 which means it will try to relay mail. I see in your System Logs that your mailserver is rejecting the relay and is asking for "Proper Authentication". This means you should change your Email's SMTP configuration to use a port like 587 or 465 with Authentication Required Enabled so it authenticates and sends the mail.

**Comment by larsks** [comment]
The mailserver already listens on port 465. The ostickets folks are correct that we shouldn't be relaying unauthenticated email from anywhere.

**Comment by msdisme** [comment]
changing ports to 465 ;  if that is not enough I will go hunting passwords


_____________
Michael Daitzman (He/Him/His)
***@***.***
978-201-9965
________________________________

**Comment by msdisme** [comment]
Looks like it needs passwords, which I am not spotting in bitwarden.  so manana.

_____________
Michael Daitzman (He/Him/His)
***@***.***
978-201-9965
________________________________

**Comment by msdisme** [comment]
Did further research - possible weirdness with roundcube mail.  @naved001 and @larsks working to resolve

**Comment by larsks** [comment]
@msdisme to be clear, there were no problems with roundcube. We were debugging SMTP authentication issues, and we were able to resolve things this morning. I believe everything is working as intended at the moment, although I've asked @naved001 to confirm as well so that we're both confident.

**Comment by msdisme** [comment]
ahh, I misundestood the discussion earlier about sendmail,  apologies and thanks for clarification

**Comment by larsks** [comment]
This is a good resource on configuring authentication in sendmail: https://access.redhat.com/solutions/6876

**Comment by larsks** [comment]
@naved001 can you ask the osticket folks about making the display ticket id match the id in the url? So instead of having ticket 942 at https://osticket.massopen.cloud/scp/tickets.php?id=956, we have ticket 956 at https://osticket.massopen.cloud/scp/tickets.php?id=956 instead? It's okay if it only affects new tickets without fixing existing tickets.

**Comment by larsks** [comment]
I thought I would leave a note here about how I diagnosed the problem.

I wanted to see exactly how osticket was interacting with the SMTP service, but since we're using SMTP-over-SSL a simple `tcpdump` wouldn't work; the traffic is encrypted. I used `haproxy` to set up a MITM proxy that would allow me to capture unencrypted traffic.

The haproxy configuration looks like this (this is modified from the
default `haproxy.cfg` provided by the package; I didn't explicitly set
those `timeout` values, for example).

```
global
    log         /dev/log local2 debug

    pidfile     /var/run/haproxy18.pid
    maxconn     4000
    user        haproxy
    group       haproxy

defaults
    mode                    tcp
    log                     global
    option                  tcplog
    option                  dontlognull
    option                  redispatch
    retries                 3
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

frontend  fe1
    bind *:2228 ssl crt /etc/letsencrypt/live/mail.massopen.cloud/combined.pem
    default_backend nossl

backend be1
    server s1 127.0.0.1:4651

frontend fe2
    bind *:4651
    default_backend realsmtps

backend be2
    server s1 127.0.0.1:465 ssl verify none
```

The frontend `fe1` listens on port 2228 because this port happened to
be exposed in the AWS security configuration for the mailserver. The
way it works is:

- osticket connects to port 2228 using SSL
- haproxy creates an unencrypted connection to port 4651
- which is just another haproxy frontend, which then passes the
  traffic using SSL to the real SMTP service on port 465

With this in place, I can run `tcpdump -i lo -s0 -w packets port 4651`
to capture the unencrypted SMTP traffic. With all this in place, we
were able to capture the following SMTP session (`>` is traffic sent
from mail.massopen.cloud to osticket; `<` is traffic received by
mail.massopen.cloud):

```
> 220 mail.massopen.cloud ESMTP Sendmail 8.14.7/8.14.7; Fri, 23 Jul 2021 10:40:28 -0400
< EHLO localhost
> 250-mail.massopen.cloud Hello localhost [127.0.0.1], pleased to meet you
> 250-ENHANCEDSTATUSCODES
> 250-PIPELINING
> 250-8BITMIME
> 250-SIZE
> 250-DSN
> 250-ETRN
> 250-AUTH GSSAPI DIGEST-MD5 CRAM-MD5
> 250-STARTTLS
> 250-DELIVERBY
> 250 HELP
< AUTH DIGEST-MD6
> 334 bm9uY2U9IjJ1Vi96RjJVVEFPNmxVMzcxeGtxWW93dGdqeDhYREJvQk8zekxjNTVwdDg9IixyZWFsbT0ibWFpbC5tYXNzb3Blbi5jbG91ZCIscW9wPSJhdXRoLGF1dGgtaW50LGF1dGgtY29uZiIsY2lwaGVyPSJyYzQtNDAscmM0LTU2LHJjNCxkZXMsM2RlcyIsbWF4YnVmPTgxOTIsY2hhcnNldD11dGYtOCxhbGdvcml0aG09bWQ1LXNlc3M=
dXNlcm5hbWU9Im9zdGlja2V0IixyZWFsbT0ibWFpbC5tYXNzb3Blbi5jbG91ZCIsbm9uY2U9IjJ1Vi96RjJVVEFPNmxVMz< cxeGtxWW93dGdqeDhYREJvQk8zekxjNTVwdDg9Iixjbm9uY2U9InhKTVB5MEVOdXBlUmhiOVg5Q1FTNTRSRzNuWTlUWDBqUFJJc01ZRzd3Zzg9IixuYz0wMDAwMDAwMSxxb3A9YXV0aCxkaWdlc3QtdXJpPSJzbXRwL3NzbDovL21haWwubWFzc29wZW4uY2xvdWQiLHJlc3BvbnNlPTEyYjMyYTdiYjBkMTczYjgwOTFhNDI0ZTA2MGRmMTAxLG1heGJ1Zj04MTky
> 535 5.7.0 authentication failed
```

Here, we see that osticket was attempting to use `DIGEST-MD5`
authentication, but that's won't work on our system; `DIGEST-MD5`
requires the server to know the unencrypted password, but since we're
authenticating against the PAM backend we only have access to the
encrypted password.

The problem was our sendmail configuration, which was advertising
support for a number of authentication methods.  The lines of interest
are in `/etc/mail/sendmial.mc`:

```
TRUST_AUTH_MECH(`EXTERNAL DIGEST-MD5 CRAM-MD5 LOGIN PLAIN')dnl
define(`confAUTH_MECHANISMS', `EXTERNAL GSSAPI DIGEST-MD5 CRAM-MD5 LOGIN PLAIN')dnl
```

I modified these lines so that we only support `PLAIN` authentication:

```
TRUST_AUTH_MECH(`PLAIN')dnl
define(`confAUTH_MECHANISMS', `PLAIN')dnl
```

**Comment by naved001** [comment]
I asked them if it's possible to have the ticket ID and the ID in the URL be the same for new tickets. Also, I think the email works good, I wanted to try to reset my osticket "user" account that I setup using my gmail, and I got my password reset email on gmail too. so looks like all parts work.

**Comment by naved001** [comment]
@msdisme 

Is this the panel you are talking about?


![image](https://user-images.githubusercontent.com/20113064/126832490-a30fe6ca-681b-4d26-9980-0f32e1c4b541.png)

**Comment by msdisme** [comment]
moved paying them to a diff. ticket.
