### ISSUE TITLE
Update AWS IAM configuration

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#199]
We should ensure that our AWS account is properly configured:

- Change password for root account
- Remove "radonm" IAM user
- Create new IAM users for current staff
- Etc.

**Comment by knikolla** [comment]
Investigate also if there are places where we're using Rado's credentials in automation. Probably not.

**Comment by larsks** [comment]
@msdisme it looks like we have *two* amazon accounts. We have root account credentials for one in Bitwarden, but not for the second. The second is the one we appear to actually be using, and it's associated with your email address. As part of this issue we need to locate or reset the credentials for that account and move it into Bitwarden.

**Comment by larsks** [comment]
For the account to which we have access I've created a new `mocops` user to replace the existing `radonm` user and added it to Bitwarden; this grants administrative access to the account.

**Comment by larsks** [comment]
Worked with @msd to get credentials for second account into bitwarden, so I think we're all set.
