### ISSUE TITLE
Mail Server Needs for hosted or NERC

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#202]
We need the following email related services:

- Outbound SMTP service so that applications like our onboarding tools can send out email
- An inbound SMTP service that will receive email for the *.massopen.cloud domain and forward it to configured alias destination
- A service for managing mailing lists

In cases, the service must provide an API we can use for configuration automation (e.g., tasks such as creating new credentials for outbound email access, creating/deleting/managing email aliases, creating/deleting/managing mailing lists, etc).

**Comment by msdisme** [comment]
@jstacy28 this may be relevent to you -eg. managing mailing lists

**Comment by msdisme** [comment]
Given that the issue was actually spam concern and I missed the mail, and that we have addressed added a security mail list on AWS, is this still an issue?

**Comment by larsks** [comment]
@msd I thought the issue "why are we hosting our own mailserver rather than having somebody host it for us", which is unrelated to the recent spam issue with AWS.

**Comment by larsks** [comment]
We have access to some email services through siteground. Do we want to take advantage of those?

**Comment by joachimweyl** [comment]
will be delt with when we deal with mail in a larger scale.
