### ISSUE TITLE
DNS Service Requirements for hosted or NERC

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#203]
We're currently hosting DNS servers in multiple locations, including at least:

- tld.massopen.cloud, which manages the top-level massopen.cloud domain
- dns.massopen.cloud, which manages:

  - be.massopen.cloud
  - mocapps.cloud
  - openapp.cloud
  - osh.massopen.cloud
  - test.massopen.cloud

- cnv-dhcp1.massopen.cloud, cnv-dhcp2.massopen.cloud, which manage dns
  for our recent openshift clusters. We have these because we needed
  to "fake" the reverse dns for 192.12.185.0/24.

These should all collapse to a single service, and we should get
necessary delegation for our CIDR ranges so that we can handle reverse
DNS ourselves in a sane fashion.

Our requirements are going to be:

- An API for programmatic management of records
- A UI for managing records manually if necessary
- A well defined point of contact and SLA for support requests

Additionally, we will need to arrange delegation of reverse DNS with the organizations that provide our public CIDR ranges. I've opened up a [separate issue](https://github.com/CCI-MOC/ops-issues/issues/205) for this, since it's unrelated to the solution to this issue.

**Comment by larsks** [comment]
Our life will be easiest if we pick one the [dns providers supported by cert-manager](https://cert-manager.io/docs/configuration/acme/dns01/#supported-dns01-providers):

> ## Supported DNS01 providers
> 
> A number of different DNS providers are supported for the ACME Issuer. Below is a listing of available providers, their .yaml configurations, along with additional Kubernetes and provider specific notes regarding their usage.
> 
>     ACMEDNS
>     Akamai
>     AzureDNS
>     CloudFlare
>     Google
>     Route53
>     DigitalOcean
>     RFC2136
> 
> ## Webhook
> 
> cert-manager also supports out of tree DNS providers using an external webhook. Links to these supported providers along with their documentation are below:
> 
>     AliDNS-Webhook
>     cert-manager-webhook-civo
>     cert-manager-webhook-dnspod
>     cert-manager-webhook-dnsimple
>     cert-manager-webhook-gandi
>     cert-manager-webhook-infomaniak
>     cert-manager-webhook-inwx
>     cert-manager-webhook-oci (Oracle Cloud Infrastructure)
>     cert-manager-webhook-scaleway
>     cert-manager-webhook-selectel
>     cert-manager-webhook-softlayer
>     cert-manager-webhook-ibmcis
>     cert-manager-webhook-loopia

**Comment by larsks** [comment]
I would probably just vote for Route53, because pretty much any tooling that interacts with dns apis will have support for it. DNS is [cheap](https://aws.amazon.com/route53/pricing/):

- $0.50/zone/month
- $0.40/mllion queries/month

**Comment by larsks** [comment]
@msd adding you to this issue since it will (probably) ultimately involve money.

**Comment by rob-baron** [comment]
It seems that having access to modify dns is critical for our service, for example, in order to get wildcard certificates let's encrypt. I though one of our long standing goals was to set up cloud services using open source tooling.

**Comment by msdisme** [comment]
Rules to decide if a service must be hosted/offered as part of Open Infra Labs/MOC
1. Is the service critical to running an open source cloud
1. is using a closed source hosted provider compatible with our mission? (API)
1. Is hosting it ourselves an effective use or our resources
1. tied to the one above, is it an interesting problem that needs solving?



How do we make this generalizable?

**Comment by joachimweyl** [comment]
will be delt with when we deal with mail in a larger scale.
