### ISSUE TITLE
Investigate options for reverse delegation of reverse DNS

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#205]
We currently make use of public CIDR ranges from multiple providers. We need to arrange to have reverse DNS for these CIDR ranges delegated to our servers so that reverse lookups of ip addresses return the correct hostnames.

- [x] 192.12.185.0/24 (BU)
- [x] 129.10.5.0/24 (NEU)
- [x] 128.31.28.0/24 (CSAIL)
- [x] 128.31.24.0/22 (CSAIL)
- [x] 128.31.20.0/22 (CSAIL)
- [ ] 128.52.60.0/22 (CSAIL)

**Comment by larsks** [comment]
Opened request INC13168159 with BU IS&T to ask about delegation for 192.12.185.0/24.

**Comment by larsks** [comment]
@naved001 do you want to open a similar request with NEU and MIT?

**Comment by naved001** [comment]
Sure.

**Comment by larsks** [comment]
This is the initial response from BU:

> This is the latest in an ongoing discussion about your request.
> This is only a snippet which I'm copy and pasting here.
> Please feel free to comment on any of:
> 
> Hi Lars. Just an Update here.
> The following is an excerpt of a discussion concerning this.
> Thought you might find interesting and may like to comment on:
> 
> Well, we do have the reverse zone defined. It looks like the only forward record we have on subnet 192.12.185.0/24 is for the gateway (192.12.185.1 – mocnet-gw.bu.edu). So there's a reverse record for that.
> 
> Does the MOC not have access to our campus DNS servers? Do they have some sort of service whereby they're doing their own DNS "stuff"?
> 
> Can we solve their problem by simply populating forward records for them (which will generate the reverse) in BU DNS servers? Maybe they don't know that they can request us to create DNS records for them?
> 
> Anyhow, I don't believe we have any NS records delegating authority for reverse zones to anyone else's servers.

**Comment by larsks** [comment]
And my reply:

> Here are some responses to the question raised in your last comment. It might be easier if I were able to discuss this directly with the engineers involved. If folks have any free time in their schedule tomorrow or Friday, let me know.
> 
> "Does the MOC not have access to our campus DNS servers?" I'm not sure what the question is here: we don't have the ability to *update* the campus DNS servers, which is really what we're asking about.
> 
> "Do they have some sort of service whereby they're doing their own DNS "stuff"? We do run forward DNS for the massopen.cloud domain (and subdomains thereof). This is something of an inherited configuration, and we're considering transitioning these services to a hosted provider somewhere rather than running them ourselves, but we have a fundamental requirement for a service that provides a robust API allowing us to integration DNS changes with our operations automation.
> 
> "Can we solve their problem by simply populating forward records for them (which will generate the reverse) in BU DNS servers?" This would be a great solution if there is a robust, non-interactive API through which we can make these changes. We're not looking for a legacy request-changes-via-tickets workflow.
> 
> "Anyhow, I don't believe we have any NS records delegating authority for reverse zones to anyone else's servers." We're happy to be a guinea pig! I don't think there's anything particularly unusual about reverse delegation, and we're always happy to work out the kinks in a new process that empowers the community.

**Comment by larsks** [comment]
Good news, the BU IS&T folks seem willing to perform the delegation. I think we need to wait for responses from MIT and NEU *and* we need to resolve https://github.com/CCI-MOC/ops-issues/issues/203 before making any changes.

**Comment by naved001** [comment]
> Those last two could in theory be part of a single 128.52.60.0/22 network.

I put a machine on VLAN 10 and ran dhclient, and the IP I got is in the range `128.52.60.0/22` so that confirms that it is a single network. And that also means that it has 1024 IPs intead of 256+256 (/22 > two /24s )

It's worth noting that we don't even get to run DHCP on this network, it's managed by CSAIL.

**Comment by naved001** [comment]
It's possible for CSAIL networks. This was their response

> It's absolutely possible.  We would make two requests:
> 
> 1) That you run DNSsec for the zones delegated to you.
> 
> 2) That the inverse mapping targets be limited to names clearly
> associated with MOC.

**Comment by naved001** [comment]
Here's the NEU ticket number: INC0803527

**Comment by pjd-nu** [comment]
Feel free to add me to the NU ticket. Use p.desnoyers@northeastern.edu as the email if you do.

**Comment by msdisme** [comment]
@pjd-nu hope vacation was great!  @naved001 is out sick, do you know if he added you to the ticket?

**Comment by pjd-nu** [comment]
@msdisme I don't see it. However I can't be sure, as I've never found a reliable way to enter the NU incident system other than clicking on a link in an email from them. (there seem to be several copies of the same incident handling system, or at least ones that generate similar-looking incident IDs, used for different administrative purposes)

**Comment by naved001** [comment]
I don't have an NU account so I can't visit the ticket to add you to it.

I opened the ticket via email.

**Comment by pjd-nu** [comment]
If you can forward me the email from the system I should be able to ask to be put on it.

**Comment by naved001** [comment]
NEU has approved our request to perform the delegation.

> 06/04/2021 09:30:45 PM EDT - Johnson, Matthew Additional comments (Customer Viewable Field)
> Hello Naved,
> 
> We approve this request and will send this ticket over to Networking to provide you the appropriate access.
> 
> Thank you,
> 
> Matt

With that all of our network providers are willing to do that.

**Comment by naved001** [comment]
The NEU ticket (INC0803527) has been put on hold until we select our hosting provider (or figure out a way to host is ourselves).
