### ISSUE TITLE
Purchase Nvidia BlueField 2 DPUs

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#212]
Based on discusions with Nvidia and Red Hat we are planning to purchase 20 [MBF2H332A-AEEOT ](https://store.mellanox.com/products/nvidia-mbf2h332a-aeeot-bluefield-2-smartnic-p-series-dpu-25gbe-dual-port-sfp56-pcie-gen4-x8-crypto-enabled-16gb-on-board-ddr-1gbe-oob-management-tall-bracket-hhhl.html) [BlueField 2 DPUs](https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/documents/datasheet-nvidia-bluefield-2-dpu.pdf). These are HHHL cards (half height, half length) with dual 25Gb ports.

**Comment by larsks** [comment]
After not hearing back from Nvidia since our initial conversation on March 1, I reached out to multiple folks on Friday (3/19) and Monday (3/22). I heard back from Brandon Hathaway:

> Hi Lars – Checking on this and will circle back.  I think it got held up.

**Comment by larsks** [comment]
Today we finally received the quote from CDW. I have the quote and I have forwarded a copy to @msdisme .

**Comment by msdisme** [comment]
I spoke with the salesperson - he is not allowed to sell to the University.  I will get the name of BU's salesperson and see if they can honor the quote, else it may need to be sent to the new salesperson by Nvidia.

**Comment by msdisme** [comment]
Got correct salesperson, forwarded the contact info to Lars.   Please ask that they make it for 20 DPU's.

Thanks!

**Comment by msdisme** [comment]
Have a current quote and expect to place an order by March 31st, 2021.

**Comment by msdisme** [comment]
Order placed.

**Comment by larsks** [comment]
I've tried following up on this a couple of times with Nvidia and CDW, but no luck so far. I've just sent the following message to everyone involved:

> I think that DPU purchase has become lost in bureaucratic limbo between Nvidia, CDW, and BU. The complicating factor is that the quote was generated for Red Hat but BU is trying to make the purchase, which threw everything off. I've been unable to get any response from the folks at CDW or Nvidia, so maybe our best bet is to have Michael cancel the purchase and start from scratch (or re-evaluate the purchase to see if folks are still interested in this equipment, since it's been so long since we originally tried to purchase things).

**Comment by msdisme** [comment]
Moving out of sprint 27 and 28 until the cards purchased/scheduled.  @msdisme  to create a new card for specifying machines for GPU and DPU

**Comment by msdisme** [comment]
Any update on the DPU order?  We have the machines in smaug cluster, we have the 100GB connections....

**Comment by msdisme** [comment]
Closing until it comes up again.
