### ISSUE TITLE
Set up security contact for AWS account

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#214]
Set up a bu majordomo mailing list to use as the security contact for the AWS account.

- [x] make naved secondary owner
- [x] add dev team and PI's and Jen
- [x] add to AWS account
- [x] add majordomo details to moc bitwarden

**Comment by larsks** [comment]
Is this a contact email linked to the MOC AWS account? Or is this for another purpose?

**Comment by msdisme** [comment]
This is as the security contact on the AWS account
