### ISSUE TITLE
Clarify rules of use for hardware in OCT/MGHPCC/MOC

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#215]
During stand-up this morning we discussed the fact that the "zero" cluster currently allows anyone with a Google account to run arbitrary code on the cluster via the open JupyterHub instance. We should clarify what it means to run a production or production-like service vs. a  "wide open" service.

**Comment by larsks** [comment]
This is part of a larger issue related to the new EULA, etc.

**Comment by hpdempsey** [comment]
Michael and Bill have taken over working on this issue, which will return when they have some agreement with BU and Red Hat, so it would be more appropriate to move it to BackLog, instead of done.

**Comment by larsks** [comment]
@hpdempsey because this seemed like a very small subset of the larger issue (especially with most services getting ready to move to the NERC), we figured it was more appropriate to close this one during our planning meeting this morning.

**Comment by hpdempsey** [comment]
@larsks if that means Michael is planning to make a new one when it comes back, then that makes sense.  Thanks for the note.

**Comment by msdisme** [comment]
That’s the plan ☺.

---
Michael Daitzman (He/Him)
***@***.***
cell:978-201-9965



From: Heidi Picher Dempsey ***@***.***>
Date: Tuesday, February 22, 2022 at 2:08 PM
To: CCI-MOC/ops-issues ***@***.***>
Cc: Daitzman, Michael S ***@***.***>, Assign ***@***.***>
Subject: Re: [CCI-MOC/ops-issues] Clarify rules of use for hardware in OCT/MGHPCC/MOC (#215)

@larsks<https://github.com/larsks> if that means Michael is planning to make a new one when it comes back, then that makes sense. Thanks for the note.
