### ISSUE TITLE
MGHPCC: Replace failed drive

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#22]
Replace drive in neu-15-39. Needs a 600Gig drive. According to iDRAC it is "Physical Disk 0:1:1, Slot 1". Should be hot swappable.

neu = R3 Pod B.
15-39 = Cage 15 Unit 39. It's a dell poweredge server (1U).

@hakasapl

**Comment by hakasapl** [comment]
Drive replaced.
