### ISSUE TITLE
Create an OCP 4 cluster for staging/dev for onboarding

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#220]
discuss in next standup

**Comment by naved001** [comment]
Source: https://docs.google.com/spreadsheets/d/1V4_24MEQvpQaEIWOY9CT3zMeu_7llBagkYRxAIsJ1a4/edit#gid=748212895

**OCT4 (Row 1, Pod C, Cage 16)**

Besides the Intel nodes used by Jonathan appavoo and Parul, this rack has 18 nodes that are racked. Out of which 1 node is broken. That leaves us with 17 nodes, out which I could not login to 6 nodes' IPMI. Then out of the remaining 11 nodes, only 3 had a single 1TB drive.

**OCT3 (Row 1 Pod C Cage 14)**

This rack is dedicated for operate first use cases. 

The new hardware from Dell will be racked in Row 6 and then linked to the switch in this rack.

**Comment by naved001** [comment]
@hakasapl can you switch over the OCT3 nodes management VLAN to MOC at some point so we can start poking with the operate first nodes? Thanks!

**Comment by naved001** [comment]
@knikolla is happy with the 2 CRC nodes so far (and CRC on VM in kaizen openstack).
