### ISSUE TITLE
Problems reaching Amazon AWS addresses from the MOC

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#224]
We've had multiple reports of problems accessing AWS-hosted services from within the MOC 192.12.185.0/24 address space.  For example, nvidia hosts Docker images at `nvcr.io`, which is hosted on AWS:

```
/ # host -t a nvcr.io
nvcr.io has address 35.164.215.17
nvcr.io has address 34.214.191.219
/ # whois 35.164.215.17 | grep OrgName
OrgName:        Amazon Technologies Inc.
OrgName:        Amazon.com, Inc.
```

Accessing this from my local system works just fine:

```
local$ wget -O- -T 20 https://nvcr.io
--2021-04-06 12:50:16--  https://nvcr.io/
Resolving nvcr.io (nvcr.io)... 35.164.215.17, 34.214.191.219
Connecting to nvcr.io (nvcr.io)|35.164.215.17|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

But trying the same thing on e.g. a host in the zero cluster fails:

```
/ # wget -O- -T 20 https://nvcr.io
Connecting to nvcr.io (34.214.191.219:443)
wget: download timed out
```

It looks as if this also impacts https://upload.pypi.org/ (which is also hosted on AWS).

```
/ # host upload.pypi.org
upload.pypi.org has address 3.12.224.191
upload.pypi.org has address 13.59.222.73
upload.pypi.org has address 18.224.42.42
/ # whois 3.12.224.191 | grep OrgName
OrgName:        Amazon Technologies Inc.
/ #
```

**Comment by larsks** [comment]
From #209 we know that there are multiple routes between the MOC and AWS. I wonder if that is somehow impacting this particular issue? Access to the above addresses all appears to be via I2:

```
/ # traceroute 3.12.224.191
traceroute to 3.12.224.191 (3.12.224.191), 30 hops max, 46 byte packets
 1  mocnet-gw.bu.edu (192.12.185.1)  0.568 ms  0.540 ms  0.522 ms
 2  bu-re-nox-mghpcc-gw1.nox.org (18.2.8.201)  0.765 ms  0.571 ms  0.421 ms
 3  192.5.89.57 (192.5.89.57)  2.268 ms  2.269 ms  2.270 ms
 4  i2-re-nox300gw1.nox.org (192.5.89.222)  6.944 ms  6.970 ms  6.916 ms
 5  ae-3.4079.rtsw.wash.net.internet2.edu (162.252.70.138)  12.163 ms  12.149 ms  12.139 ms
 6  ae-0.4079.rtsw2.ashb.net.internet2.edu (162.252.70.137)  90.336 ms  12.582 ms  12.474 ms
 7  99.82.179.34 (99.82.179.34)  12.586 ms  12.534 ms  12.787 ms
[...]
```

Or:

```
/ # traceroute 34.214.191.219
traceroute to 34.214.191.219 (34.214.191.219), 30 hops max, 46 byte packets
 1  mocnet-gw.bu.edu (192.12.185.1)  0.554 ms  0.498 ms  0.487 ms
 2  bu-re-nox-mghpcc-gw1.nox.org (18.2.8.201)  0.734 ms  0.578 ms  0.562 ms
 3  nox-mghpcc-gw1-i2-re-chic.nox.org (192.5.89.254)  2.023 ms  2.005 ms  1.953 ms
 4  et-3-1-0.4079.rtsw.clev.net.internet2.edu (162.252.70.93)  10.622 ms  10.648 ms  10.564 ms
 5  ae-3.4079.rtsw3.eqch.net.internet2.edu (162.252.70.131)  17.352 ms  17.101 ms  16.986 ms
 6  ae-5.4079.rtsw.eqch.net.internet2.edu (162.252.70.162)  17.153 ms  141.646 ms  20.010 ms
 7  ae-0.4079.rtsw.minn.net.internet2.edu (162.252.70.107)  24.502 ms  24.506 ms  24.510 ms
 8  ae-1.4079.rtsw.seat.net.internet2.edu (162.252.70.172)  57.055 ms  58.205 ms  56.879 ms
 9  99.82.179.40 (99.82.179.40)  56.823 ms  56.951 ms  99.82.179.38 (99.82.179.38)  56.900 ms
10  52.95.52.182 (52.95.52.182)  58.225 ms  52.95.52.46 (52.95.52.46)  57.686 ms  52.95.52.252 (52.95.52.252)  57.325 ms
11  52.95.52.25 (52.95.52.25)  57.262 ms  52.95.53.137 (52.95.53.137)  56.981 ms  52.95.53.143 (52.95.53.143)  56.798 ms
[...]
```

Access to https://mail.massopen.cloud, which is also AWS-hosted, works fine.

**Comment by larsks** [comment]
I've reached out to Jenny Sears at Nvidia to see if she can put us in touch with someone who manages the Nvidia image registry at nvcr.io (to see if they can confirm this isn't an explicit policy on their part, for example).

**Comment by naved001** [comment]
I had opened a ticket with nvidia enterprise about this issue and their response was that nvidia is not blocking traffic from US based IPs. It started to work just fine around the time when you opened a ticket about firewall, so I was like, sweet, this works.

> As per my discussion with Engineering team, we are not actually blocking any IP in USA. 

I had also opened a ticket with BU IS&T and they said that did not notice anything wrong. This was their response:


> nslookup for "nvcr.io: resolved to different IPs than the ones you provided.  Not sure if these are dynamic DNS and values change.
> 
> nslookup nvcr.io
> Server:         128.197.253.183
> Address:        128.197.253.183#53
> 
> Non-authoritative answer:
> Name:   nvcr.io
> Address: 54.153.106.117
> Name:   nvcr.io
> Address: 52.9.18.116
> Name:   nvcr.io
> Address: 52.9.7.167
> Name:   nvcr.io
> Address: 52.9.248.62
> Name:   nvcr.io
> Address: 52.8.237.68
> 
> It does not appear to be a routing issue at MGHPCC, traffic is directed  properly to the NOX and Internet2 to access these AWS hosts.  IPs can not be pinged from  the MOC gateway (192.12.185.1)
> 
> Thanks,

and they posted an image:
![image](https://user-images.githubusercontent.com/20113064/113754346-20f81480-96dd-11eb-86ef-cb334c9ac4d2.png)

**Comment by pjd-nu** [comment]
Google thinks that nvcr.io is on a 35.* address:
```
$ nslookup nvcr.io 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	nvcr.io
Address: 35.164.215.17
Name:	nvcr.io
Address: 34.214.191.219
```

**Comment by larsks** [comment]
@pjd-nu yes, that's what you see in my initial comment.

**Comment by pjd-nu** [comment]
Yup. Just pointing out the origin of the dueling DNS records. BU, Northeastern, and Comcast DNS servers resolve to the 52.* address list, while Google's 8.8.8.8 and 1.1.1.1 resolve to 35.whatever and 34.whatever.

**Comment by larsks** [comment]
I see the same problem using either the 35.* or the 52.* addresses from inside the MOC.

**Comment by naved001** [comment]
I think they are both owned by aws; and neither works.

@larsks I had made a router to get around this issue; not an elegant solution but it worked to install operators and all

```
sudo ip route add 35.163.209.0/24 via 192.12.185.179 dev br-ex
sudo ip route add 54.213.8.0/24 via 192.12.185.179 dev br-ex
sudo ip route add 52.218.136.0/24 via 192.12.185.179 dev br-ex
```

**Comment by naved001** [comment]
The router puts it through an neu ip (129.10.5.130).

**Comment by larsks** [comment]
I've also posted a message to a random internal technical discussion list to see if anyone has clever ideas about diagnosing this, or figuring out who to contact if this is an AWS issue, etc.

**Comment by msdisme** [comment]
Probably not the perfect place to ask, but I found this: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-contact-support.html  @larsks sent an invite for 4pm, doe this work for you?

**Comment by larsks** [comment]
I've opened case INC13184498 with BU IS&T. @naved001 and @msdisme are also listed on the ticket.

**Comment by goern** [comment]
is there some update on this? its still breaking our release processes... thx!

/priority critical-urgent

**Comment by larsks** [comment]
@goern no updates yet. I'm pestering BU IS&T right now to see if I can get some attention on the ticket we've opened with them.

**Comment by larsks** [comment]
Our current ticket with IS&T is INC13184498, which has been open for about 22 days with effectively no response.

**Comment by larsks** [comment]
@msdisme have you had the chance to connect with folks about this issue yet?

**Comment by msdisme** [comment]
bumped Wayne and ticket.   :-(

**Comment by larsks** [comment]
Update from BU IS&T on this issue: 

> I have crafted  CHG051957 to resolve the Asymmetric routing issue
> which we believe is the root cause of your problem.  I will try to
> push the change to be reviewed next week by a peer engineer if it
> passes we will try to implement the Change by the second week of
> June.

**Comment by tumido** [comment]
Hey folks, it just occurred to me, may this be also related to Let's Encrypt failed validations via ACME operator?

https://github.com/operate-first/support/issues/237
https://github.com/tnozicka/openshift-acme/issues/159

We're getting weird validation errors.

Which may indicate the challenge url is not reporting the same content to different clients in different parts of the network:
https://community.letsencrypt.org/t/authorization-issues/116615

https://acme-v02.api.letsencrypt.org/acme/authz-v3/13838625360

```json
{
  "identifier": {
    "type": "dns",
    "value": "test-opf-dashboard.apps.zero.massopen.cloud"
  },
  "status": "invalid",
  "expires": "2021-06-16T13:58:21Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "During secondary validation: Invalid response from http://test-opf-dashboard.apps.zero.massopen.cloud/.well-known/acme-challenge/K6S5oZ0kigxlz2d7HzFIeBjkJAvvU5GZ6lNJRZTx-80 [192.12.185.105]: 408",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13838625360/XtkOOg",
      "token": "K6S5oZ0kigxlz2d7HzFIeBjkJAvvU5GZ6lNJRZTx-80",
      "validationRecord": [
        {
          "url": "http://test-opf-dashboard.apps.zero.massopen.cloud/.well-known/acme-challenge/K6S5oZ0kigxlz2d7HzFIeBjkJAvvU5GZ6lNJRZTx-80",
          "hostname": "test-opf-dashboard.apps.zero.massopen.cloud",
          "port": "80",
          "addressesResolved": [
            "192.12.185.105"
          ],
          "addressUsed": "192.12.185.105"
        }
      ],
      "validated": "2021-06-09T13:58:44Z"
    }
  ]
}
```

**Comment by larsks** [comment]
@tumido I'm not sure what mechanism would be involved in different *content* getting served out. So far, all the problems we've seen are binary in nature -- either the traffic passes, or it doesn't.

**Comment by tumido** [comment]
@larsks I really have no idea what can be causing the issue above, so I'm grasping at straws here and hoping I can tie it to any existing problem and be able to point to that direction... I just hoped your answer would be "Yes, definitely, same issue", lol :smile:

**Comment by larsks** [comment]
It sounds like the fix discussed [earlier](https://github.com/CCI-MOC/ops-issues/issues/224#issuecomment-852214699) will be implemented tomorrow morning:

> Hello Lars,
> 
> Tomorrow Morning will implement the change at 5.00 AM  chg051957
> 
> Thanks
> 
> Beck

**Comment by larsks** [comment]
The change was implemented this morning, but doesn't appear to have had any impact on the connectivity problems.

**Comment by larsks** [comment]
Beck says:

> We are able to find the route cause of this problem after further investigation .  I will implement the missing configuration on Sunday June 13th   at 5.00Am.

**Comment by naved001** [comment]
looks like they applied the fix,

I can rech nvcr and pypi from a host on that network.

```
[kni@neu-5-3 ~]$ ip r
default via 192.12.185.1 dev baremetal proto dhcp metric 426 
10.0.0.0/19 via 192.12.185.101 dev baremetal proto dhcp metric 426 
172.22.0.0/24 dev provisioning proto kernel scope link src 172.22.0.1 metric 425 
192.12.185.0/24 dev baremetal proto kernel scope link src 192.12.185.150 metric 426 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
[kni@neu-5-3 ~]$ curl https://nvcr.io
<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

**Comment by tumido** [comment]
cc fyi @harshad @fridex

**Comment by harshad16** [comment]
Thanks @tumido , i will check this with our systems

**Comment by tumido** [comment]
@larsks that networking change seem to have fixed the acme operator as well :slightly_smiling_face:

![](https://thumbs.gfycat.com/UniformTintedCaiman-size_restricted.gif)

**Comment by larsks** [comment]
@tumido excellent!

I think I'm declaring this issue (finally) resolved.
