### ISSUE TITLE
MGHPCC: Check server in BU cages (engage 1 environment)

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#23]
In the BU pod we have 4 cages. BU = R4 Pod A

Cage 2, 4, 23 and 21. 23 and 21 is what we call `kumo`, while 2 and 4 are `engage1`.

- [ ] In cage 2, we have a 2U lenovo server at Unit 11-12. Its IPMI controller is not responding, so that needs to be checked out.
- [ ] We have network access to cage 4 PDUs, but don't know the passwords.
- [ ] Map out what's connected to the cage 4 PDUs.
- [ ] See if the PDUs in cage 2 connect to our IPMI switches (1G switch). If yes, then we need to figure set ipmi ip/password and know about the connections.

@hakasapl

**Comment by hakasapl** [comment]
> * [ ]  We have network access to cage 4 PDUs, but don't know the passwords.
> * [ ]  See if the PDUs in cage 2 connect to our IPMI switches (1G switch). If yes, then we need to figure set ipmi ip/password and know about the connections.

I will need to factory reset the PDUs in both cabinet 2 and 4 for this. They have a hardware reset button, but I need to confirm with Kevin to make sure power connections won't be cut during the reset. Pushing this for my next visit.

> * [ ] In cage 2, we have a 2U Lenovo server at Unit 11-12. Its IPMI controller is not responding, so that needs to be checked out.

I tried to get into its bios setup, but the system is stuck on a boot loop. First: `System initializing`, then `System initializing memory`, then it goes back to the first message and repeats. I've left it powered off but plugged in.

> * [x]  Map out what's connected to the cage 4 PDUs.

Pictures of cabinet 4 are attached (Front and Back). I can get a more specific inventory next time - I ran out of time today.

![PXL_20201108_214320832](https://user-images.githubusercontent.com/40907639/98485456-7db1da80-21e4-11eb-97e7-2bf61ccbc581.jpg)
![PXL_20201108_214316457](https://user-images.githubusercontent.com/40907639/98485457-7ee30780-21e4-11eb-9e6d-59d851472ce3.jpg)
![PXL_20201108_214323330](https://user-images.githubusercontent.com/40907639/98485458-7f7b9e00-21e4-11eb-8ebb-a7029158be4e.jpg)
![PXL_20201108_214148261](https://user-images.githubusercontent.com/40907639/98485459-7f7b9e00-21e4-11eb-86c1-d2a8faecb8c3.jpg)
![PXL_20201108_215148766](https://user-images.githubusercontent.com/40907639/98485460-80143480-21e4-11eb-8aa7-0918935a7232.jpg)
![PXL_20201108_214328029](https://user-images.githubusercontent.com/40907639/98485461-80accb00-21e4-11eb-9155-d8503a6ba320.jpg)
![PXL_20201108_214325880](https://user-images.githubusercontent.com/40907639/98485462-81456180-21e4-11eb-836b-8459600648f2.jpg)

**Comment by hakasapl** [comment]
@naved001 are the PDUs in question on a DHCP server? If so, Mark Izzo from MGHPCC just factory reset both PDUs in C2 and C4, so you may be able to reach them assuming the default IP is DHCP. If not, I'll hook up to them the next time I'm on-site.
