### ISSUE TITLE
Decide on definition of done for GitHub Issues

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#231]
DOD for this card is: 

- [x] start
- [ ] create documentation
- [ ] create a pull request in [ops-docs](https://github.com/CCI-MOC/ops-docs)
- [ ] gather feedback from team
- [ ] update documentation based on feedback
- [ ] upload to repo

**Comment by joachimweyl** [comment]
@msdisme I have a version of this as part of my `GitHub Issue MOC Practices` I have been working on. Should I pull that section out for earlier review as part of this issue as it is or convert this issue to review that whole document once we get our 50% more programmers added to the team?

**Comment by joachimweyl** [comment]
If this comes up again we can recreate or reopen.
