### ISSUE TITLE
Updated info on hw donation

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#234]
https://docs.google.com/spreadsheets/d/1zD5DK7AehbBqAnS_A5HkW6NfJS90losYAaT1_j5_J0E/edit#gid=533000860

**Comment by larsks** [comment]
@msdisme do you have any information about the supermicro systems listed in that document (such as processor model, speed, or amount of memory)?

**Comment by msdisme** [comment]
@larsks the details we have are in the spreadsheet.  There will be updated information soonish.

**Comment by pjd-nu** [comment]
I'm planning to meet Hakan out at MGHPCC tomorrow, and will get some more info then.
