### ISSUE TITLE
MGHPCC: Check NICs on neu-15-36

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#237]
This node is an openstack compute and one of the nics has no networking.

The problem nic is connected to switchport 31 of brocade switch in cage 15 unit 43.

The switch detects link, but there's still connectivity issue. I toggled the switchport (shut/no shut) but that didn't fix it.

Next thing to try would be to reinsert the cables, and maybe reseat or replace the NIC.

cc: @larsks

**Comment by naved001** [comment]
Similar issue showed up on a HIL node, `neu-15-28`. Its second NIC also has no connectivity but the link is detected.

**Comment by hakasapl** [comment]
I can't seem to get these cables out, they're stuck in there. Can you give more details on the connectivity problem?

**Comment by larsks** [comment]
@hakasapl pretty much as described: the systems detect a link, but we're not receiving any frames over these interfaces. E.g., running `netstat -in` shows:

```
Iface             MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
p3p2             9050        0      0      0 0       1420512      0      0      0 BMRU
```

Note that all of the `RX` values are `0`.

**Comment by hakasapl** [comment]
Going to check on this on-site again tomorrow (thursday)

**Comment by hakasapl** [comment]
I reseated the NIC on the node and switch side.

**Comment by naved001** [comment]
> The problem nic is connected to switchport 31 of brocade switch in cage 15 unit 43.

@hakasapl Do you think it's possible to move the cable to different free switchport so I can test for connectivity? I think port 10 is free on that switchport. 

If that doesn't work, we would like to swap cable and then maybe the nic.

**Comment by hakasapl** [comment]
I can't go to MGHPCC this week because I'm out of town, but I will schedule for next.

**Comment by naved001** [comment]
We don't have any free switchport in cage 15 (on either switches). So Hakan swapped the cables between the 2 nics, and then the "problem" nic started to work. So it looks like the the NIC and the cable is good, something is wrong with that switchport.

> Similar issue showed up on a HIL node, neu-15-28. Its second NIC also has no connectivity but the link is detected.

This node is also connected to the same brocade switch. 

Could it be the case that the switch is going bad? at least 2 switchports are not working.

**Comment by naved001** [comment]
I moved all the VLANs over to the other functioning NIC. openstack sees this controller, but the compute service is disabled. 

When can we call this ticket done?

**Comment by naved001** [comment]
power cycling the switch (during the mghpcc shutdown) has fixed it.
