### ISSUE TITLE
delete old pools from production ceph

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#245]
The PIs are okay deleting the ceph pools that we used for our older kaizen openstack.

```
[root@kzn-mon1 ~]# ceph df |grep -E "POOL|production-|performance-"
POOLS:
    POOL                          ID      STORED      OBJECTS     USED         %USED     MAX AVAIL 
    production-cinder-volumes      87      25 TiB       6.48M       74 TiB     10.38       212 TiB 
    production-ephemeral-vms       88     990 GiB     255.54k      2.9 TiB      0.45       212 TiB 
    production-glance-images       89     1.2 TiB     492.54k      3.5 TiB      0.55       212 TiB 
    performance-volumes           136     1.1 TiB     577.98k      3.3 TiB      9.20        11 TiB 
```

@larsks I want to confirm that these are the pools used for old kaizen openstack, and that they are not used in the current deployment.

**Comment by larsks** [comment]
These are the pools used by the kaizen environment:

- CinderRbdPoolName: ostack2
- CinderRbdExtraPools: performance2
- GlanceRbdPoolName: ostack2
- GnocchiRbdPoolName: ostack2
- NovaRbdPoolName: ostack2

It looks like you're okay to go ahead and delete the ones you're
asking about.

**Comment by naved001** [comment]
Cool, I got rid of those. they had too many PGs doing nothing.
