### ISSUE TITLE
Policy and Procedure for NESE

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#246]
- [ ] find out rules for usage by MOC users
- [ ] find out rules rules for usage by Operate First projects
- [ ] clarify how shared
- [ ] fiscal component for multiple storage pools

**Comment by msdisme** [comment]
@durandom, @bill do you have a sense of how much storage we'll need for Operate First?

Feedback from Scott : At this point what is easiest is to purchase a server to add capacity to the system, then be prepared for an operational cost to manage the server.

	• Per Server = $23,607 → 202 TB usable space
		• NESE Operations sets the server type each year
			• Dell 740xd2, 24 x 16TiB, 2x25 Gbps
			• 5 yr maintenance required
		• Annual hosting costs = $3,004 / server
		• Asset tracking
		• Start of 5th year - plan to replace
		• End of 5th year - removal of old hardware

**Comment by larsks** [comment]
@msdisme is the model that the server gets added to the general NESE pool, and we get access to that amount of storage but not necessarily hosted on that specific server (and we don't need to worry about maintaining the server itself)?

**Comment by hpdempsey** [comment]
We don't have a storage estimate for Operate First now.  It is of course a bit hard to predict, because we aren't sure what projects we will attract, but we can make some assumptions and do one.  If, as Lars asked, the model is that we need to contribute a server to have access to 202 TB of space, then it seems clear that we would need to add a server for Operate First right away, and then track usage and predict when we'd need more.  I think there is some AI software for that...   ;-)  So there might not be much point in a manual estimate at this stage.

**Comment by pjd-nu** [comment]
How do we expect to use NESE? Both RBD and S3/RGW? I assume we're not using CephFS?

**Comment by larsks** [comment]
@pjd-nu I'm still trying to figure out what our access options are. I *suspect* the bulk of our use will be via RBD, possibly re-exported as NFS into our environment, but I have questions: 

- Is it possible to point OCS (OpenShift Container Storage) directly at a ceph pool for which we have non-administrative access?

- W/r/t to s3 access, will we be able to create our own AWS-style credentials for making the s3 service available to multiple tenants? Or will this just be another case of "consume RBD storage and re-export it as something else" instead?

I think answers to those questions will help determine exactly how we end up consuming the storage.

**Comment by pjd-nu** [comment]
I'm not an expert on Ceph permissions, but my understanding is:

RBD - if they give us an RBD pool and a user with 'profile rbd' permissions scoped to that pool we should be able to create and mount images.
RGW - again they'll need to make the pools, and I think we'll need 'profile simple-rados-user' scoped to those pools, then we can run our own RGW on top and do whatever we want for auth.

Each of these seems similar to the permissions that they must be handing out to clusters that are using CephFS.

Note that this has to be reviewed by someone who actually knows what they're talking about before being used as the basis for talking to NESE.

**Comment by larsks** [comment]
@msdisme do we have answers for the questions posed in the description? If not, should we modify #285 to be a general overview of NESE storage and policies, rather than being focused on tape storage?

**Comment by msdisme** [comment]
closed and migrated to https://github.com/CCI-MOC/ops-issues/issues/285
