### ISSUE TITLE
update mellanox switches used by power9 cluster.

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#248]
that's what IBM support recommends that we do before we purchase new cables.

**Comment by naved001** [comment]
@ipolonsk @YonatanGolick I am in the process of doing this right now. Will take a few hours to upgrade all our switches.

**Comment by YonatanGolick** [comment]
@naved001, if the update will fix the old nodes as well, is there any chance we can receive the two old nodes for the installation? 
We have encountered an issue and the Red Hat support said that the errors are because we are trying to install an AllInOne installation of openshift. We would like to check if the same procedure will work on a regular architecture of 3 masters.

**Comment by naved001** [comment]
Sure, I think we can arrange that. 
Why are you having to do an AllInOne install when you have 3 nodes? What are the other 2 nodes being used for?

**Comment by YonatanGolick** [comment]
For an openshift installation, you need one bastion node (a server used to orchestrate the process), a bootstrap server (only used during the installation itself), and 3 master nodes. This whole time we tried to trick the procedure somehow to do it with only one master node but with no luck.

**Comment by naved001** [comment]
Is there a reason why the foreman host can't act as the bastion and bootstrap server?

**Comment by YonatanGolick** [comment]
Yes, the foreman has a different architecture - x86-64 instead of the ppc64 architecture of the nodes. The openshift installation needs to have the same architecture on all of the components.

**Comment by naved001** [comment]
The switch OS has been upgraded (which also updates the firmware) but that hasn't fixed the link issues. Working on getting new types of cables now.


The 2 Mellanox Ethernet switches (MSX1710) are now running version MLNX-OS 3.6.8012 which is the highest supported version by these model (latest MLNX-OS is 3.9.something). The OS is now called `Onxy` instead of `MLNX-OS`.

I did not upgrade the Mellanox IB switch since it has been running fine and I am bit wary about firmware upgrades when things aren't broken.

```
bu-21-21 [standalone: master] # sh ver
Product name:      Onyx
Product release:   3.6.8012
```

```
bu-21-23 [standalone: master] # sh ver
Product name:      Onyx
Product release:   3.6.8012
```
