### ISSUE TITLE
Validating Octavia SSL Certificates

### ISSUE THREAD

**Issue by tsachleben** [CCI-MOC/ops-issues#25]
Luis from RH Big Data requested load balancing in Octavia on 3/11/20 [1]. Following @larsks doing the recommended setup in [2], Luis began having some LB provisioning issues that resulted in a case being opened with RH Support [3]. Following discussion with Dave Hill, @larsks seems to have found the root issue to be an expired CA cert w/i Octavia. 

Points for this ticket:
- Has the core issues raised in [1] been resolved? Ie. Should Luis be able to create LBs for Octavia?
- WRT the SSL CAs expiring, can/should a validation test be encoded into a Zabbix Monitor to preempt user failures? 

OS Project: BigDataStack BigDataStack EU research project e34555572f9549e1bac3e9d923a895b3 
Assigning: @larsks 
External Links: 
[1] https://osticket.massopen.cloud/scp/tickets.php?id=486
[2] https://docs.openshift.com/container-platform/4.3/installing/installing_openstack/installing-openstack-installer-kuryr.html#installation-osp-default-kuryr-deployment_installing-openstack-installer-kuryr
[3] https://access.redhat.com/support/cases/#/case/02610590

**Comment by larsks** [comment]
Resolved by updating Octavia ssl certificates with new ones with a distant expiration date.
