### ISSUE TITLE
ns2.massopen.cloud is running out of space

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#252]
Saw the alert on zabbix.

```
[root@ns2 ~]# ls -lh /var/log/suricata/eve.json
-rw-r--r-- 1 suricata suricata 4.2G May 11 11:44 /var/log/suricata/eve.json
```

That file is taking up too much space.

I dont know what it is, so didn't want to just clear it up.

**Comment by larsks** [comment]
suricata is an IDS system that records file metadata and can alert on any changes. I don't think we're running it anywhere else. I would just disable suricata and remove the file.

**Comment by naved001** [comment]
thanks! I did that.
