### ISSUE TITLE
Reinstall production OCP cluster

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#254]
Just the base installation.

**Comment by larsks** [comment]
Requires #283

**Comment by larsks** [comment]
Support case for failed install: https://access.redhat.com/support/cases/#/case/02966517

**Comment by naved001** [comment]
From @larsks's comment

"since we last tried the ocp install, ocp has gone from 4.7.13 to 4.7.16, and now the install seems to work w/o a problem!"
I am going to close this.
