### ISSUE TITLE
Report of usage for all  projects to be migrated to NERC OpenStack

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#255]
- [ ] quota for amount total and in use (from projs)
- [ ] memory
- [ ] disk
- [ ] network Floating IPs(projs)
- [ ] total number of users
- [ ] total number of projs
- [ ] users/per proj
- [ ] cpus per flavor
- [ ] information about cpu/memory overcommit

**Comment by larsks** [comment]
Depends on #141

**Comment by msdisme** [comment]
Here is a spreadsheet that lists fields that we have data for.  We had put in a bunch of ideas of fields we wanted to calculate, but we just didn't have the data to do so.

(https://drive.google.com/drive/u/1/my-drive)

**Comment by rob-baron** [comment]
https://docs.google.com/spreadsheets/d/1wGprxH1Cltev2VdcgmHg-1TG2YsCA0YNoUmG-ahxzWY/edit#gid=0
