### ISSUE TITLE
Generate a report for OpenStack cluster resource utilization over the available trend data

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#256]
Present Zabbix data for OpenStack to show usage patterns using the trend data.

Plotting trend data as graphs to display open stack utilization.

ideas:

1) total # users 
2) total #Projects opened/closed
3) total #VMs opened closed
4) total diskspace
5) average VM size (cpu, memory, disk)
6) 

Note:
    1) History data was completely missing for the past 90 days.  Trend data was found over the past year (minus the past 90 days).

**Comment by rob-baron** [comment]
Naved,

I want a csv file with each row having the full vm name, and the each column being a date.  There should be 1 csv for cpu usage, 1 for memory usage and 1 for disk usage (if available).

**Comment by msdisme** [comment]
was not running
