### ISSUE TITLE
Backup model for MOC and OIL repositories

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#258]
- [ ]  define what repositories should be backed up
- [ ]  define SLA needed for them
- [ ]  identify some solutions
- [ ] compare and decide how top do backups

An example is https://help.backhub.co/en/pricing-and-plans

Other details: https://stackoverflow.com/questions/5578270/fully-backup-a-git-repo

**Comment by larsks** [comment]
@msdisme what are we going for backups for data outside of GitHub? *Are* we backing up anything? Do we have access to any backup services from BU?

**Comment by larsks** [comment]
Part of #259
