### ISSUE TITLE
Identify what should be backed up

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#259]
What should we be backing up?

Helpful wiki page: https://github.com/CCI-MOC/moc/wiki/Kaizen-Backups-(SCC)-Overview

**Comment by larsks** [comment]
@naved001 and I came up with the following list:

- git repositories (maybe)
- switch configurations (maybe, or store them in version control)
- etcd on openshift
  - openshift on baremetal
  - openshift on power9
  - openshift on openstack
- databases on openstack
- mailing list archives, mailspool
- dns server configuration (or store in version control)
- hil database
- other non-version-controlled system configuration
- router configurations (kzn-rtr, kzn-vpn)
- onboarding system database (ask @knikolla  for more info)
- sso database (@knikolla)

**Comment by larsks** [comment]
Closing for now; we'll use this as a reference for a future issue.
