### ISSUE TITLE
Check if server neu-5-17 is plugged into 2 different PDUs

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#26]
The host and the BMC restarted for an unknown reason, just want to double check that it has redundant power supplies and that those are plugged into different rails. 

This is a 4U Fujitsu server in NEU cage.

**Comment by naved001** [comment]
@hakasapl If you could look at that next time you are the data center that would be helpful. We can then mark it done.

**Comment by hakasapl** [comment]
They are plugged into both PDUs and all PSUs have lights
