### ISSUE TITLE
Create RHEL 8 repository mirror

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#265]
We would like people spawning RHEL-8 based virtual machines (or containers) to be able to access packages. We should set up RHEL 8 mirrors much like our existing RHEL 7 mirrors.

See also https://osticket.massopen.cloud/scp/tickets.php?id=909

**Comment by naved001** [comment]
If this is going to be setup in RHEV, then we should use the `data` domain instead of `HA-NFS`. `HA-NFS` is backed by SSDs and smaller in size.
![image](https://user-images.githubusercontent.com/20113064/119185803-3931b200-ba45-11eb-90c5-3bba349a9d3b.png)

**Comment by msdisme** [comment]
@larsks @naved001 is it reasonable to pull this into current sprint?     Also, we can ask Mohammad if they have a needed timeframe.

**Comment by larsks** [comment]
Ask Mohammad first, and if they need it sooner rather than later we can add this to the sprint. Otherwise let's schedule this for the next one.
