### ISSUE TITLE
Enable separate management interface for nfs server

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#268]
Would it be possible to enable one of the 1Gb interfaces on the
TrueNAS server so that we can have ssh/web access that is separate
from the NFS service? I'd like to look into enabling LACP for the NFS
service, but before making any network changes we need to make sure
we're still able to access the system.

**Comment by naved001** [comment]
There's no separate 1GB management interface. We'll have to login using the IPMI console to manage it.
