### ISSUE TITLE
Add NVMe Drives to Peter Servers

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#27]
Request from Peter

For each server:
neu-5-41 (Amin-Ugur-D4N)
neu-17-41 (Amin-Ugur-D4N)
neu-19-41 (Amin-Ugur-D4N)
neu-15-41 (Mohammad-Vojtech-Immutable)
neu-3-41 (Mania-Kariz)

On hold, until high-profile PCIe brackets are available.

**Comment by pjd-nu** [comment]
tracking number 9405528206334149685046

**Comment by hakasapl** [comment]
This is done
