### ISSUE TITLE
Relocate MOC irc channels

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#273]
The freenode irc network was recently the target of a questionable change of control, and most projects are relocating to other networks. We should probably do the same thing with our channels, which include:

- `#moc`
- `#openinfralabs`
- `#openinfralabs-monitoring`

The choices are effectively:

- Just stay where we are.
- Move to [OFTC][]
- Move to [Libera][], created by ex-Freenode staff
- Abandon IRC for something else

OpenStack has moved over to  OFTC. Many other projects have moved over to Libera.

Any thoughts?

[OFTC]: https://www.oftc.net/
[Libera]: https://libera.chat

**Comment by tzumainn** [comment]
I think moving in parallel to OpenStack may make sense, if we want to try and attract additional contributors or people who may be interested in our work. But I don't know how likely that is.

**Comment by larsks** [comment]
@tzumainn a side benefit to following OpenStack is that if you need to interact with folks from OpenStack projects, you're already on the same network so it simplies your IRC config.

**Comment by tzumainn** [comment]
Agreed! That's definitely a plus. But to be honest, I also kinda expect to join fifty billion new IRC servers because communities are moving to different networks anyway.

**Comment by larsks** [comment]
We talked about this on our standup this morning; I think everyone is fine with moving to OFTC. Going to let this sit until Tuesday, just in case anyone wants to comment.

**Comment by larsks** [comment]
We're moving `#moc` over to the OFTC network.
