### ISSUE TITLE
Sync kaizen-users mailing list with current accounts

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#277]
Perform a one-time sync of the kaizen-users mailing with the list of active users (returned by, e.g., `openstack user list -f value -c Name | grep '@'`)? The list membership seems considerably smaller than the current list of users (499 on the list vs. around 1000 users).

**Comment by larsks** [comment]
Let's perform a one-time sync of the mailing list with kaizen users. @msdisme would like to preserve the list of users we add as part of the sync such that at some point in the future we can check again and see what has changed.

**Comment by msdisme** [comment]
Also cross ref with bulletins

also include openshift and power 9 openshift users

**Comment by msdisme** [comment]
Probably should open up a seperate discussion about what to do re. mail lists and onboarding eg;

- NERC solution
- this approach but with sync login
- ospurge that also removes them?
- Not sure what else

**Comment by larsks** [comment]
I've attached a tar file that contains the before and after lists of subscribers. The file is encrypted to me, @naved001 , and @knikolla .

[mailing-list-changes.tar.txt](https://github.com/CCI-MOC/ops-issues/files/6855782/mailing-list-changes.tar.txt)

**Comment by msdisme** [comment]
Thx!
________________________________
