### ISSUE TITLE
hw tests for cnv sporadic boot fails

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#28]
some machines, some times, fail to boot.   PCIE training problem, not reporting. 
HW tests - vendor? (ticket!!!)

**Comment by naved001** [comment]
The PCIe training error may be related to the RAID controller.

![image](https://user-images.githubusercontent.com/20113064/98964664-17c09e00-24d7-11eb-94ed-f970bebdd02e.png)

This thread says that re-seating the RAID controller may help. https://serverfault.com/questions/310041/dell-poweredge-pcie-training-error-what-to-do

We may wanna do that for all 9 servers used to CNV sandbox.

**Comment by msdisme** [comment]
Punting to archive since less of an issue
