### ISSUE TITLE
SSO outage

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#288]
SSO services were offline for about 16 hours, starting around 6pm on 6/21 until @knikolla and I restored service around 9am on 6/22. This was probably due to a faulty firewall configuration, which prevented the two sso nodes from synchronizing correctly.

**Comment by larsks** [comment]
We followed https://docs.mirantis.com/mcp/q4-18/mcp-operations-guide/tshooting/tshoot-mcp-openstack/tshoot-galera/restore-galera-cluster/restore-galera-manually.html for restoring the galera cluster.

We may want to implement some mysql health checks based e.g. on information in https://galeracluster.com/library/training/tutorials/galera-monitoring.html. I suspect there are pre-existing checks we could enable for this.

**Comment by knikolla** [comment]
It also makes sense to script out the process of manually restarting a galera cluster.

**Comment by larsks** [comment]
@knikolla I've create a separate issue for that suggestion, https://github.com/CCI-MOC/ops-issues/issues/294. I'm closing this issue since the SSO outage has been resolved.
