### ISSUE TITLE
Retire rocketchat

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#289]
Now that we have a premium slack subscription, we should stop maintaining our rocketchat instance (and arrange for any automation to talk to slack directly).

**Comment by naved001** [comment]
- [ ] send alerts directly to zabbix instead of via rocketchat
- [ ] port HIL node usage updates directly to slack.

With that we can retire rocketchat which is running on our proxmox cluster at px.massopen.cloud

**Comment by naved001** [comment]
I think we can retire it now. 

All I had to do was create a slack bot and then update the URL in the scripts that were making those alerts. Didn't have to change anything else.

**Comment by naved001** [comment]
okay, I powered off the rocketchat instance on the proxmox cluster and set it not start automatically. Does that mean we can close it then?
