### ISSUE TITLE
Access for Rubicon Team to power 9's

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#29]
Added to bitwarden in _MOC IL Team_ collection. 

ssh keys and other details is [here](https://docs.google.com/spreadsheets/d/1aGgSAy5wqdLoAiV09kOosslgv-BnCL7lVA3jJ2kt4RA/edit?skip_itp2_check=true&pli=1#gid=0). May only be visible to Lars and Naved.

Please add them to what they need to work on the power 9 systems - we can discuss in Friday standup.  

- [x] Get SSH keys and emails.
- [x] Add nodes to maas.
- [ ] Add team members to git with permissions 
- [ ] Email team with how-tos

**Comment by naved001** [comment]
I have added the 3 nodes to maas, but still running into a couple of issues:
1. Two of the nodes don't boot from the first ethernet nic, so I had to boot from the second one.
2. I could provision ubuntu on 1 server using MaaS, but I couldn't provision the other two with centos. Need to investigate this.

**Comment by naved001** [comment]
I have sent out an email with the details on how to access the power9 servers and a pxe host. Still need to sort out the networking issues.

**Comment by naved001** [comment]
closing this since they now have access and creating a different card for tracking the networking issues.
