### ISSUE TITLE
Order 202TB NESE node for Operate First et al

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#291]
after 20TB has been shown to be performant - ops-issues/#290

**Comment by larsks** [comment]
This depends on  https://github.com/CCI-MOC/ops-issues/issues/290

**Comment by larsks** [comment]
@msdisme would you update the description of this issue? Where will we be using the 202TB?

**Comment by msdisme** [comment]
if triple replication size may need to be larger
