### ISSUE TITLE
Define process/notifications for retiring power 9 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#292]
- [x] #407 
- [x] #521 
- [x] identify end of support date - october/nov 2021
- [x] identify potential users of systems (BCH, URI, Umass, MIT) 
- [x] #537
- [ ] #563
- [ ] #612
- [ ] Communicate with IBM about changes (appropriate tone, etc.)
- [ ] #609
- [ ] identify hw for that space?

**Comment by msdisme** [comment]
topics for 4/26 grooming - repurpose this or close and make a new ticket to transfer ownership.  
in either case, tasks to do (and be converted into tickets) 
- [ ] notify IBM folks
- [ ] #407 to identify people to notify
- [ ] write email for shutdown
- [ ] clarify who will disconnect, and get BCH items disconnected (assume 2)
- [ ] clarify who will move items to UMass Space, timing and access needs
- [ ] identify hw for that space/discusss with Wayne/Scott any repurposing

**Comment by joachimweyl** [comment]
This has become a Milestone and we can track it [here](https://github.com/CCI-MOC/ops-issues/milestone/17).
