### ISSUE TITLE
Review of Red Hat Interns Pen Testing doc and schedule

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#296]
Review plans, identify possible problems or improvements, in google docs linked in comments.  https://drive.google.com/drive/folders/1gzUf1xWkBCxnjwSEWINfyyQl2Nby-bDC?usp=sharing_eil_m&ts=60d4b000

**Comment by dystewart** [comment]
DRAFT Testing Schedule for the Red Hat Intern Security Project: [https://drive.google.com/drive/folders/1gzUf1xWkBCxnjwSEWINfyyQl2Nby-bDC](url)

Rules of Engagement: [https://drive.google.com/drive/folders/1MdS5fWNQc7p1vLNZuaiZQcCREWMFZ5iB](url)

**Comment by larsks** [comment]
@dystewart any chance you could put both documents in the *same* folder?

**Comment by TySheehan** [comment]
@larsks Sorry about that, I thought it would be easier with two. Here is a folder with them both and I apologize for the added confusion:
https://drive.google.com/drive/folders/167wTNzQZYa83zqS1o8kMJAC32VWBYvAp

**Comment by rob-baron** [comment]
Will need access to the document for the emergency contact list (I requested access to it in google docs).

**Comment by TySheehan** [comment]
@rob-baron Understood I will add it to the same folder now

**Comment by rob-baron** [comment]
I see no problem with this - I think it needs to be done.

Let me know if there is anything else I need to do to indicate my approval.

**Comment by naved001** [comment]
Looks good to me.

**Comment by larsks** [comment]
I've looked over both documents. I think they're fine. I've added a couple of comments to the rules of engagement document that should be easy to address.

**Comment by msdisme** [comment]
Anything we need to let network folks at MIT, NEU, BU etc. know about?

**Comment by larsks** [comment]
@msdisme We could send out an email mentioning that there may be some port scan activity over the next few weeks originating from the addresses that @TySheehan and @dystewart provided in the documents, with the potential for more targeted work in the future (in both cases only targeting hosts on MOC networks).
