### ISSUE TITLE
Configure xilinxlm.massopen.cloud

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#298]
Configure xilinxlm.massopen.cloud VM for FPGA work.    https://support.massopen.cloud/scp/tickets.php?id=930

**Comment by naved001** [comment]
We have to create a DNS entry for whatever floating IP they pick.

**Comment by naved001** [comment]
we added an A record. xilinxlicense.massopen.cloud --> 128.31.26.249
