### ISSUE TITLE
NESE GW Reliability Discussion

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#299]
Spinning up this ticket that we talked about last week.

### The Issue

NESE gives us a ceph key and information on ceph endpoints to connect to. Because we don't want to share the CEPH key, this team would need to control every system which directly connects to NESE (to start that system will be the UMass NESE gateway, and then in the future a discrete BU NESE gateway). Further, since you can only map a CEPH volume on one system at a time, there is no way to set up a high availability environment.

### Options

1. One primary node, one backup node. The backup node is configured identically to the primary node, except the volumes are not mapped by default, and its access IP is not set. If the primary goes down, an admin must manually map the volumes on the backup and set the IP, thus making the backup node the primary one. Can we do this switch automatically? Maybe the backup node can check ceph status and general stuff such as ping, and if anything fails trigger the primary to go down and the backup comes up?
1. Use a clustered file system on every rbd (CephFS, etc.), and directly serve something like NFS or SFTP from the gateways. In that case we'd have two gateways, and we'd need some third entity to manage the incoming traffic and round-robin between the gateways, and also detect when one node is down to avoid sending traffic to it.

That's all I can think of, feel free to add.

**Comment by larsks** [comment]
For option 1, you could probably automate the necessary failover semantics using pacemaker.

In option 2, it would probably be easiest to have the gateways configured as an active/passive pair, because in that case you'd only need to manage ip failover. Introducing a load balancer in front of those hosts means either (a) you've got a *new* single point of failure, or (b) you need to also set up an HA load balancer.

**Comment by hakasapl** [comment]
Makes sense. In that case, I'm leaning more towards option 2 and using a clustered filesystem with IP failover.

**Comment by larsks** [comment]
I've been testing out HA NFS using the NFS Ganesha project: https://github.com/larsks/ha-nfs-test
