### ISSUE TITLE
Add Zabbix (?) test of onboarding.massopen.cloud application credentials ui

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#3]
Something for @knikolla to look at.

**Comment by larsks** [comment]
So, to add some context for posterity: this issues stems from the fact that we discovered the application credentials UI is broken when we tried to use it for somebody, and we don't actually know when it was last working. It would be great if our monitoring environment could tell us about these things.

**Comment by knikolla** [comment]
With Kaizen being phased out, and the adjutant based onboarding system no longer being developed, this issue is no longer relevant.
