### ISSUE TITLE
MGHPCC: OCT 3 and 4 hardware that needs to be fixed

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#301]
Here are some nodes in those racks that have some issues.

- [x] OCT4-03: 10G adapter is not detected by the system (Checked it from centos that was installed to disk).
- [x] OCT4-17: No link detected on the 10G port.
- [x] ~OCT3-16: The Raid controller says "SSD State failed".~ Edit: fixed this one
- [x] ~OCT3-12: no 10G boot device detected, looked around in bios and device settings. Supposed to be an integrated broadcom~
- [x] OCT3-12: Gets stuck when trying to pxe boot. Reinsert/clean cable/fiber?
- [x] OCT3-15: no 10G boot device detected, looked around in bios and device settings. Supposed to be an integrated broadcom
- [x] OCT3-18: The IPMI controller is unreachable. haven't seen the ipmi mac in tcpdump either, nothing in dhcp leases that corresponds to this.
- [x] OCT3-30: "iDrac initialization error. Reconnect power". This prevents the system from starting up.

I am still in the middle of pxe booting the a bunch of OCT3 nodes, so there may be more stuff for later.

**Comment by naved001** [comment]
> OCT3-12: no 10G boot device detected, looked around in bios and device settings. Supposed to be an integrated broadcom

This one actually had a sfc card, so I fixed that one by booting it with sfcutils iso.

Also, I did go through and update the rest of the nodes.

**Comment by hakasapl** [comment]
OCT4-03: I swapped the NIC and the slot it was on, see if you can see the NIC now.
OCT4-17: Cable wasn't seated all the way - I see a link light now.
OCT3-12: This seems to be a NIC issue, I swapped the NIC, but the NIC may need a firmware update with SFCutils
OCT3-15: It didn't have a NIC, I added a solar flare card.
OCT3-18: This node should be marked broken - either iDrac is broken or some hardware
OCT3-30: Also mark as broken.

**Comment by naved001** [comment]
cool thanks, I verified that all the nodes you fixed can now boot.
