### ISSUE TITLE
Brocade-15-43 switch maybe going bad

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#309]
We first noticed that a NIC on a compute wasn't working (https://github.com/CCI-MOC/ops-issues/issues/237). The switchport and the nic detects connectivity but there was no traffic. That NIC was connected to the brocade switch at 15-43.

Then we noticed the same issue in neu-15-28 where its second nic was showing same connectivity issues.

Then Ugur reported that neu-15-26 had similar issues, and then this morning I noticed that openstack compute neu-15-34 is showing similar problems.  I am gonna spend a bit more time looking at these nodes to double check if these are all the same issues. 

All ~4~ ~5~ 6 of these nodes are connected to the same brocade switch. I will look more at the switch logs and interface errors. 

| Server | Problem Switchport | Allocation | Status |
|----------|----------------------------|----------|----------------|
| neu-15-26 | 2/0/12 | HIL/BMI node | not in any use |
| neu-15-28 | 2/0/15 | HIL/BMI node | not in use, both ports failed |
| "" | 2/0/16 | HIL/BMI node | not in use, both ports failed |
| neu-15-32 | 2/0/23 | HIL/BMI node | Ugur using with single nic |
| neu-15-33 | 2/0/26 | HIL/BMI node | Ugur using with single nic |
|neu-15-34 | 2/0/28 | Openstack Compute | compute disabled, node is vacated |
| neu-15-36 | 2/0/31 | Openstack Compute | compute disabled, node is vacated |
| " | 2/0/32 | Other nic of Openstack Compute | compute disabled, node is vacated |

 Edit: neu-15-32 also has similar issues
 Edit2: add neu-15-33 to the list

**Comment by naved001** [comment]
Few more switchports have stopped working. 

There are 3 more openstack compute nodes, 1 openstack controller, and 1 oVirt controller that are connected to this switch. 
@larsks I think at this point we should vacate the other 3 computes as well before they fail (we are still 20 days away from the shutdown). I am thinking of migrating stuff from the problem oVirt host too. What do you think?


@pjd-nu any thoughts on this switch issue?

**Comment by naved001** [comment]
Looks like switchports connected to the 2 computes now have connectivity! The restart probably helped. @ekaynar will check her nodes and let me know if work

**Comment by ekaynar** [comment]
Both nics on neu-15-28 and neu-15-32 are working fine.

**Comment by naved001** [comment]
I tested neu-15-33 and neu-15-26, and both nics on both nodes worked.
