### ISSUE TITLE
Identify machines for  DPU and GPU

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#312]
@hakasapl In the rack of 38 systems to use as workers for Operate First:
(Crosslinking this ticket with https://github.com/operate-first/support/issues/147 )
- [x] identify the 20 that will have the bluefield DPU's https://github.com/CCI-MOC/ops-issues/issues/239 and https://github.com/CCI-MOC/ops-issues/issues/212
- [x] if possible identify 1 that can support a DPU, GPU and FPGA (xylynx) if none can support all three, identify one which can support GPU and DPU
- [ ] check that the GPU's have arrived and update here: https://github.com/operate-first/support/issues/147  - I am not sure how many came in first batch
- [ ] #438

**Comment by msdisme** [comment]
as per Hakan OCT 3, 5 or 6. Expansion for operate first into 5 - DPU's there

**Comment by msdisme** [comment]
update based on various threads/discussions:
OCT 5 is expansion rack SMAUG - DPU’s going there (already configured for 100gb)
OCT 7 OCT General and Cloudlab-GPU’s there (~18 slolts free as of 12/9/21) R730’s

GPU's to OCT 7 due to need for larger chassis.

**Comment by msdisme** [comment]
Expect to be contacted by Kris Murphy at RH as per Hugh

**Comment by krmurph** [comment]
Can you provide an update on whether or not DPUs are in any servers? Looking at updates it looks like no?  And DPUs were not purchased, but servers that they could go into were identified?

**Comment by hakasapl** [comment]
Servers are identified (OCT5), no DPUs have arrived yet at the facility.

**Comment by krmurph** [comment]
How many watts of power do the PCIe slots provide in the identified servers?

**Comment by hakasapl** [comment]
From the Dell R630 Manual:
```
Non-Dell qualified peripheral cards and/or peripheral cards greater than 25 W are not supported
```
Looks like the limit is 25W. Is that sufficient?

- Hakan

**Comment by seroyer** [comment]
> From the Dell R630 Manual:
> 
> ```
> Non-Dell qualified peripheral cards and/or peripheral cards greater than 25 W are not supported
> ```
> 
> Looks like the limit is 25W. Is that sufficient?
> 
>     * Hakan

No, BlueField 2 DPUs require 75W slots

**Comment by hakasapl** [comment]
Looking around forums people report that 75W is possible on these servers, but I am reluctant to go this route given the recent troubles we've had with GPUs smoking in the larger dell R730 servers.

Do you know what kind of servers DPUs are being deployed in currently? Do they get all their power from the PCIe slot or is there an external power connector?

- Hakan

**Comment by seroyer** [comment]
I believe I've heard of them working correctly in R640 class servers.  I have tried to use one in an R630 and the card throws errors saying the slot is underpowered.

**Comment by seroyer** [comment]
As for slot vs aux power, it depends on the cards.  DPUs with integrated BMCs I believe use aux power connectors, but ones without do not.  The cards we have now do not have BMCs or aux power connectors.

**Comment by msdisme** [comment]
We've some other hw coming in, we will cross reference what those can support.

**Comment by krmurph** [comment]
Do you have server types that you normally plug GPUs into? I would think those server types are likely to have higher powered slots.

**Comment by hakasapl** [comment]
We only have R630s and R730s available. Both have the same line in the manual. We have also used R740xds for higher-power FPGA cards, but those have external PSU connections, and all those nodes are occupied.

I will look over the HW coming in and see if I can spot something that works.

- Hakan

**Comment by msdisme** [comment]
@zink@ecs.umass.edu

**Comment by joachimweyl** [comment]
This issue got too big. We are now tracking this milestone [here](https://github.com/CCI-MOC/ops-issues/milestone/19).
