### ISSUE TITLE
Figure out type of drives on MOC ceph clusters

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#313]
For Seagate discussion.  Request from Peter to run the following commands on one of the capacity OSD nodes it would probably identify the drive:

    hdparm -I /dev/sdX

where sdX is one of the capacity drives. That probably won’t work, because I assume it’s on the other side of a Dell PERC controller, in which case this command should work:

   smartctl -a /dev/sdX -d megaraid,0

(the latter may require installing the smartmontools package)

**Comment by naved001** [comment]
```
ssh 192.168.28.10 smartctl -a /dev/sdc -d megaraid,0 
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.0-1160.31.1.el7.x86_64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HGST
Product:              HUH721010AL5200
Revision:             LS17
Compliance:           SPC-4
User Capacity:        9,796,820,402,176 bytes [9.79 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
Formatted with type 2 protection
8 bytes of protection information per logical block
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000cca251384e84
Serial number:        7PGZYZ0C
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Mon Jul 19 21:19:07 2021 UTC
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled
```

**Comment by pjd-nu** [comment]
It's a WD. (they bought Hitachi Global Storage Technologies a while back) I don't think we're going to get any Seagate-specific information from it :-)

Although we might want to talk to Seagate about whether SMART telemetry would be useful, and how much overhead would be involved in collecting it. (one of the reasons for Seagate's new FARM format is the overhead of collecting SMART data)
