### ISSUE TITLE
Configure networking for ESI cluster

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#320]
We need to set up a few VLANs for the ESI openstack cluster. I would like:

- An internal network (e.g. not public, accessible from, say kzn-rtr, with outbound NAT access)
- An internal provisioning network (does not require any outbound access)
- A public network

The `internal` network doesn't need to be a new network if we already
have one that is appropriate. I'll be using this to log into the
undercloud, which doesn't need to expose any public services. I think
we could use vlan 201, which is what we used on the existing kaizen
undercloud?

I think that for the public network you were suggesting that we use 129.10.5.0/24, the NEU network. That should be fine.

That means we only need to create the provisioning network.

## Undercloud

- oct-4-00

On this host:

- nic1: internal network
- nic2: provisioning network

## Controllers

- oct-4-03
- oct-4-04
- oct-4-05

On these hosts:

- nic1: provisioning network
- nic2: public network

**Comment by naved001** [comment]
@larsks OCT4 nodes have a single 10G nic, so should I make the provisioning network the native, and then tag everything else?

**Comment by larsks** [comment]
Oh, huh. OpenStack really wants more than a single interface. Let me do a little research and see if that's even possible.

**Comment by larsks** [comment]
Part of https://github.com/CCI-MOC/esi/issues/103

**Comment by larsks** [comment]
@naved001 for now, let's just set it up like this:


- For the undercloud, make the primary vlan the internal network, and the provisioning vlan a trunked vlan.
- For the controllers, make the primary vlan the provisioning network, and the public network a trunked vlan.
