### ISSUE TITLE
Configure networking for OPF nodes on OCT-10 and OCT-3

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#329]
Naved,

For the operate first nodes (that's OCT10-00 through OCT10-02 and OCT3-00 through OCT3-31), let's put them all on the CSAIL /22 network with DHCP (I believe that's `128.52.60.0/22`).

Even if the nodes are dual-connected, we're only configuring the first interface right now.

**Comment by naved001** [comment]
@larsks I have connected the oct3 nodes to csail vlan 10 (128.52.60.0/22). I have a test virtual machine (running on oVirt) `root@128.52.62.226` on that network, might be useful to test things.

btw, OCT3 nodes also only have a single interface.

I am working on the oct10 nodes, will update this ticket once those are connected.

**Comment by naved001** [comment]
one NIC of each OCT10 nodes are also on the CSAIL VLAN 10.

**Comment by naved001** [comment]
Set the MTU of the OCT3 nodes to default (MTU 1554 bytes, IP MTU 1500 bytes)
