### ISSUE TITLE
Validate configuration of new Dell hardware

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#333]
There was some confusions over whether the configuration of the Dell hardware we purchased to use as OpenShift control nodes matched our expectations.

According to information available via the iDRAC, this is what  is physically present:

| Node      | Physical processors | Cores per processor | Total cores | RAM    |
|-----------|---------------------|---------------------|-------------|--------|
| oct-10-01 | 2                   | 24                  | 48          | 384 GB |
| oct-10-02 | 2                   | 24                  | 48          | 384 GB |
| oct-10-03 | 2                   | 24                  | 48          | 384 GB |
| oct-10-04 | 2                   | 24                  | 48          | 384 GB |
| oct-10-05 | 2                   | 24                  | 48          | 384 GB |
| oct-10-06 | 2                   | 24                  | 48          | 384 GB |

Does that match our expectations?

The difference we see in the discovered hardware information for the
assisted installer appears to be that hyperthreading is only enabled
on oct-10-01; it is disabled everywhere else.

**Comment by larsks** [comment]
I have disabled hyperthreading on oct-10-01 for now so that we have a consistent configuration on all the nodes.

**Comment by naved001** [comment]
![image](https://user-images.githubusercontent.com/20113064/129243647-47470d6d-6eaa-4322-9132-e380bd58dd40.png)

According to the pdf, we should have two 24-core processors, which is what we seem to have. I guess the right thing to do would be to enable hyperthreading on all hosts. 

Re: memory
![image](https://user-images.githubusercontent.com/20113064/129244213-dc213832-1e21-4f0c-b81d-9d61b79551fb.png)

72 sticks mean 12 stick per system for a total of 12*32 = 384 gigs of memory and that also seems consistent. But they also mention something similar
![image](https://user-images.githubusercontent.com/20113064/129244483-91835b33-1922-4970-aebf-d1cdab770230.png)
those are 6 of some memory module?

**Comment by larsks** [comment]
In fact, according to https://docs.openshift.com/container-platform/4.7/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#about_hyperthreading_for_low_latency_and_real_time_applications_cnf-master:

> Hyperthreading allows for better system throughput for certain workload types where parallel processing is beneficial. **The default OpenShift Container Platform configuration expects hyperthreading to be enabled by default.**

So enabling it seems to be the right choice.
