### ISSUE TITLE
Power supply problems on oct-03-06

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#337]
oct-03-06 is reported power supply problems and won't power up:

```
racadm>> getsel
-------------------------------------------------------------------------------
Record:      59
Date/Time:   08/18/2021 13:47:53
Source:      system
Severity:    Critical
Description: CPU 2 PLL PG voltage is outside of range.
-------------------------------------------------------------------------------
Record:      60
Date/Time:   08/18/2021 13:48:00
Source:      system
Severity:    Critical
Description: The system board fail-safe voltage is outside of range.
-------------------------------------------------------------------------------
```

**Comment by hakasapl** [comment]
This node should be marked broken for now. The voltage going into the node is fine, but I will need to try to swap the PSU.

**Comment by naved001** [comment]
we may have some spares, so we won't have to buy

**Comment by msdisme** [comment]
@hakasapl  - please let us know if we need to order one.

**Comment by hakasapl** [comment]
We do not have any spares for this PSU. I will get the exact model number this week.

**Comment by naved001** [comment]
![image](https://user-images.githubusercontent.com/20113064/186185435-3abbc739-61f3-44dc-85e2-bfcf98b0048b.png)

iDRAC says they are healthy 🤷
