### ISSUE TITLE
Decide how we will handle onboarding to the ocp-prod cluster

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#350]
How will we handle onboarding to the ocp-prod openshift cluster in the
short term? In the long term?

- Will we manually create projects/rolebindings/etc via the
  [moc-apps][] repository?

- Will the onboarding system provision projects and manage group
  membership?

- Something else?  Is Coldfront in our future?

[moc-apps]: https://github.com/CCI-MOC/moc-apps

**Comment by knikolla** [comment]
I can either work on connecting ColdFront to the OpenShift-Acct-Mgt microservice (which should take me a couple of days) or I can reconfigure Adjutant and the onboarding dashboard. The former is more future-proof and is work that we'd have to do anyway.

**Comment by rob-baron** [comment]
kristi, it is only more future-proof if we decide to go that direction.  My magic-8 ball says yes as this would be the easiest way to meet all of my foreseen requirements.

**Comment by knikolla** [comment]
It is future-proof in that that is the way the NERC is moving forward and what they are investing our resources in vs Adjutant.

**Comment by knikolla** [comment]
Not Lars, but I can discuss about this wrt how we're implementing this is NERC.

> Will we have to make coldfront work with git-ops?
No, people will use the ColdFront dashboard to manage users and resource allocations.

> Will some users want to use git-opts for creation of users and will others want to use coldfront?
We don't have any plans to support this for creation of users. Note, people can still use git-ops to create resources that they're able to and own within their namespace/project, such as pods, services, deployments, etc.

> Are you expecting managerial people to use git-ops - that is will everyone have to use git-ops?
No

> Is git-ops going to use for reporting on users?
No

> Are we going to expect user defined services, like open data hub (ODH), create users and projects within ODH using git-opts?
Not for user creation, but they can manage their manifests with it if they want. If not, not. We're not prescribing a method of deployment for anyone, we're just standardizing on how we do our own thing for our own services.

**Comment by rob-baron** [comment]
In my thinking, I consider git-ops, adjutant and coldfront to be competing front ends for creating users and projects on services. 

I would prefer to say to people developing services that they provide an endpoint and hook into and use services that we are doing anyways.  This way we can add their service in a relatively transparent way but also have a clear separation of responsibilities and billing.

**Comment by larsks** [comment]
We have a temporary solution in place pending the development of a more complete onboarding solution.
