### ISSUE TITLE
Deploy OCP 4.X with support for external ceph

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#36]
I did an initial deployment and tested it with kumo-ceph.

Important stuff (mainly hosts.yml) is here: https://gitlab.com/naved001/moc-cnv-sandbox

- [x] Upgrade Kaizen ceph to 4.X https://github.com/CCI-MOC/ops-issues/issues/1
- [x] Deploy OCP
- [x] get wildcard certs and enbale moc-sso, metalllb (just run Lars' playbooks)
- [x] Prepare the kaizen ceph cluster (things like pg autoscaler need to be enabled).
- [x] Configure networking on the OCP hosts so it talks to ceph.
- [ ] configure the ceph storage operator to use external ceph.
- [x] add a GPU host to this cluster.

**Comment by naved001** [comment]
Waiting on redhat support. 

https://access.redhat.com/support/cases/#/case/02854404

The option to deploy OCS in external mode is unavailable.

**Comment by msdisme** [comment]
Looks like they David may have suggested a workaround in the ticket yesterday.
