### ISSUE TITLE
Update Kaizen OpenStack Message

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#366]
Please put up this message: The Mass Open Cloud will no longer be supporting OpenStack VMs.  Please fill out this survey if you are interested in your VMs migrating to the NERC.

The link for the word survey is: https://docs.google.com/forms/d/e/1FAIpQLSch4Cv8IO_frA-J2TBYpTS4S-QoX9SX0zKVzE5_JEyluXexkw/viewform?usp=sf_link

**Comment by larsks** [comment]
I think we should be able to do this by replacing the existing Horizon image with a modified version. This may require manually restarting the Horizon containers (e.g., if we were to run a full re-deploy we would lose our changes), but it is otherwise reasonably risk free.

**Comment by larsks** [comment]
@msdisme message is up at https://kaizen.massopen.cloud/

**Comment by larsks** [comment]
@msd The survey is titled "Mass Open Cloud User Survey - Spring 2020"; that probably needs updating.
