### ISSUE TITLE
more brocade networking issues

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#374]
One of the cache server's NIC detects link but there's no traffic. it's connected to the switch that had failed but was fixed yesterday. 

I also notices a number of InterSwitch links in the brocade fabric are not connected. Missing links are between rbr-2 <-> rbr-5 and
rbr-7 <-> rbr-8.

**Comment by naved001** [comment]
I have disabled the compute nodes attached to this switch migrated the VMs from those, so we no user workloads on these hosts.,

**Comment by ekaynar** [comment]
This also impacts the cache server neu-15-41. Cache server neu-15-41 has a nic that is connected to this switch, and I cannot use the second nic on the cache server right now. This issue prevents us to run experiments using the cache server. I think we should either connect this server to another switch or try to fix the switch issue.

**Comment by naved001** [comment]
The brocade switch at 15-43 had failed again yesterday. None of its interfaces were working so it was isolated in the fabric, I could only login via the serial console.

As a last ditch effort, I decided to reinstall the firmware this morning. 

After the firmware reinstall, the switch did not join the fabric. I ran `show fabric islports` where I noticed this error
```
112	Fo 1/0/49        Up  	ISL segmented,(ESC mismatch, VCS Virtual Fabric Mode Conflict)(Trunk Primary) 
```

which then led me to this page: https://extremeportal.force.com/ExtrArticleDetail?an=000085594

which explained that there's some mismatch between the type of fabric. 
```
rbr-01# show virtual-fabric status
fabric is virtual-fabric enabled
Rbridge-Id          virtual-fabric status                   
============================================================
1                   enabled                                 
3                   enabled                                 
4                   enabled                                 
5                   enabled                                 
6                   enabled                                 
7                   enabled                                 
8                   enabled    
```
So I enabled virtual fabric on the newly flashed switch by running `vcs virtual-fabric enable` in `conf` mode and then it joined the fabric.

Maybe this buys us time until @ekaynar can finish her experiments. We need to replace this switch sooner rather than later.

**Comment by naved001** [comment]
>  Missing links are between rbr-2 <-> rbr-5 and
rbr-7 <-> rbr-8.

Link between rbr2 and rbr5 got fixed after the switch firmware was reinstalled.
And then I redid the configuration for the link between rbr7 and rbr8, and now it's reported as connected.

**Comment by naved001** [comment]
Looks like all ISL are up. 

One compute node (15-36) has connectivity issues. looking into that before I close this issue.

**Comment by naved001** [comment]
neu-15-36, which is a compute node, is exhibiting symptoms described here https://github.com/CCI-MOC/ops-issues/issues/309
i.e. ethtool and the switch both report connectivity, but there's no traffic :/ 

I have reconfigured the switchport but the problem persists. I hope this switch is also not going bad.

**Comment by naved001** [comment]
Closing this in favor of #385
