### ISSUE TITLE
Configure NFS vlan on smaug nodes

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#376]
In order to provide persistent storage to the smaug cluster, absent any communication from NESE, we need to connect it to the truenas NFS server . The affected nodes are:

- oct-03-00-compute
- oct-03-01-compute
- oct-03-03-compute
- oct-03-04-compute
- oct-03-07-compute
- oct-03-08-compute
- oct-03-09-compute
- oct-03-10-compute
- oct-03-11-compute
- oct-03-12-compute
- oct-03-13-compute
- oct-03-14-compute
- oct-03-15-compute
- oct-03-17-compute
- oct-03-19-compute
- oct-03-20-compute
- oct-03-21-compute
- oct-03-22-compute
- oct-03-23-compute
- oct-03-24-compute
- oct-03-25-compute
- oct-03-26-compute
- oct-03-27-compute
- oct-03-28-compute
- oct-03-29-compute
- oct-03-31-compute
- oct-10-04-control
- oct-10-05-control
- oct-10-06-control

We need to attach the NFS VLAN to an interface on these nodes.

(Part of https://github.com/operate-first/SRE/issues/379).

**Comment by naved001** [comment]
NFS VLAN 210 is now tagged to the same interface that has public VLAN.

OCT3 nodes only have a single NIC, so I had to tag the NFS VLAN.

OCT10 nodes do have an additional NIC, let me know if you want to put VLAN 210 untagged on the other nic, instead of having it tagged with the first one.

**Comment by larsks** [comment]
The NFS vlan is available on all smaug nodes but we've been unable to get NFS access working. Further details in https://github.com/operate-first/SRE/issues/386.
