### ISSUE TITLE
Configure NESE vlan on smaug nodes

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#378]
Hakan has started configuring the networking that will attach the
Smaug cluster to NESE. We need to attach VLAN 211 to the smaug worker
nodes (see #376), but ideally this will wait until #336 is complete so
that we can use the second interface on these systems.

**Comment by larsks** [comment]
This is effectively blocked on https://github.com/operate-first/SRE/issues/386, since presumably we'll encounter the same problems trying to configure networking for NESE access.

**Comment by naved001** [comment]
why don't we have this networking problem on the ocp-prod cluster then?

**Comment by larsks** [comment]
> why don't we have this networking problem on the ocp-prod cluster then?

The problem crops up on smaug because the CSI controller is running inside a pod network namespace and attempting to connect to the REST API on the truenas server.

I suspect that the Ceph client bits are all running in the host network namespace on ocp-prod (which is the same for the actual NFS bits on smaug).

**Comment by larsks** [comment]
We need to figure how we're going to handle ip address assignment on this network. It looks like we're going to want to run our own DHCP server, since the underlying network infrastructure doesn't appear to have that capability.

**Comment by larsks** [comment]
I've update the configuration on cnv-dhcp{1,2} so that instead of a static-only dhcp service built around dnsmasq, it's a highly available dynamic dhcp service using ISC DHCPd. The deploy playbooks are currently living in https://github.com/CCI-MOC/hadhcp.
