### ISSUE TITLE
Should we replace all out-of-warranty switches with new hardware

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#382]
From #379, @pjd-nu commented:

> And I apologize that we (Orran and I) have put you folks in the
> position of maintaining ancient gear that's starting to fail - we
> probably should have prioritized doing something about it long ago
> when they were still running fine.

What we might want to consider moving forward is ensuring that the
core network infrastructure is all running on under-warranty equipment
with support contracts in place. When one compute node out of 50 fails
in an openstack or openshift cluster that's no problem, but switch
failures having a much bigger blast readiusradius.

**Comment by msdisme** [comment]
Perhaps tied to discussion of ESI hardware, network ownership for ESI, etc.
