### ISSUE TITLE
Create a simple "getting started w/ openshift" doc

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#383]
We should probably have some sort of "how to openshift" document for
incoming classes -- or at least links to existing documentation, if
e.g. red hat already has something.

**Comment by msdisme** [comment]
1. Go to: `https://console-openshift-console.apps.ocp-prod.massopen.cloud/` 
<img width="1180" alt="Screen Shot 2021-09-29 at 5 36 18 PM" src="https://user-images.githubusercontent.com/6126065/135352778-f4a144b9-c9e6-46f8-9529-7ea6e9114a70.png">

2. select moc
<img width="798" alt="Screen Shot 2021-09-29 at 5 37 28 PM" src="https://user-images.githubusercontent.com/6126065/135352936-428e5232-435d-414b-8754-2541ef70ac8f.png">

3. select University Logins
<img width="1418" alt="Screen Shot 2021-09-29 at 5 39 56 PM" src="https://user-images.githubusercontent.com/6126065/135352967-b26bbf7f-4604-4801-aa9e-6638062b6f88.png">

4. Select your University (drop down list)


<img width="841" alt="Screen Shot 2021-09-29 at 5 40 56 PM" src="https://user-images.githubusercontent.com/6126065/135353162-5285f8fa-4efd-46b5-b418-bb2b61019b81.png">

5. Get usual University login validation, eg: 

<img width="577" alt="Screen Shot 2021-09-29 at 5 41 43 PM" src="https://user-images.githubusercontent.com/6126065/135353201-684c9a89-5369-41f5-a587-a70aae616c84.png">

**Comment by joachimweyl** [comment]
this will not be relevant soon.
