### ISSUE TITLE
Notify OCP 3.11 users about moving themselves to NERC

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#386]
Send out an email asking ocp3.11 users if they are still interested in having an openshift project and would they like to migrate to ocp4.

Related to https://github.com/CCI-MOC/ops-issues/issues/339
- [x] #558
- [x] #420
- [x] #421

**Comment by msdisme** [comment]
expansion to additional users blocked by https://github.com/CCI-MOC/ops-issues/issues/487

**Comment by joachimweyl** [comment]
Communication will be done [here](https://github.com/CCI-MOC/ops-issues/issues/816).
