### ISSUE TITLE
osticket connection to maill.massopen.cloud timing out

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#389]
Error message in ticket:https://support.massopen.cloud/scp/tickets.php?id=1016

This is the mail system at host mail2.dl.supportsystem.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<alerts>: connect to
    mail.massopen.cloud[34.204.145.35]:25: Connection timed out</alerts>

Delivered-To: mailer@moc.supportsystem.com
Received: by mail2.dl.supportsystem.com (Postfix)
	id 059F183E7; Tue, 28 Sep 2021 06:43:02 +0000 (UTC)
Date: Tue, 28 Sep 2021 06:43:02 +0000 (UTC)
From: MAILER-DAEMON@dl.supportsystem.com (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: mailer@moc.supportsystem.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="B12617441.1632811382/mail2.dl.supportsystem.com"
Message-Id: <20210928064302.059F183E7@mail2.dl.supportsystem.com>

**Comment by larsks** [comment]
The EC2 instance that hosts the mail server was shut down. In the logs, we see:

```
Sep 26 02:00:09 mail systemd-logind: Power key pressed.
```

This typically indicates the shut down was requested via the API (or via the web UI). Unfortunately, we don't have any sort of audit trail to identify the source of the request.

I was able to boot the instance without errors and it seems to be functioning normally.

**Comment by larsks** [comment]
I have temporarily enabled a cloudtrail log (https://console.aws.amazon.com/cloudtrail/home?region=us-east-1#/trails) to see what sort of data that captures. I *think* our usage of cloudtrail is covered by the free tier, although it stores logs in S3 which will result in some charges.

I'll revisit the log in a week to see what sort of data it collects and get a sense of how much data it generates.

**Comment by larsks** [comment]
Closing this issue for now since the mail server is back up.
