### ISSUE TITLE
Move Open Infra Lab content from Gitlab to Github

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#39]
By relocating our Gitlab content to Github we can track everything on a single project board.

- [x] discuss via openinfralabs mailing list

- [x] discuss openinfralabs irc channel - redirect to email

- [x] confirm web site may be driven from github 
- [x] - [ ] @larsks I added https://github.com/orgs/open-infrastructure-labs/teams/admins/members and put jimmy and fungi there so far. 
- [x] move content over

- [x] import issues - bring over discussions

- [x] import

- [x] redirect repositories to github

- [x] update openinfralabs web site - top level set up with pull request
- [x] update openinfralabs web site - need to do a second PR to include project Caerus and additional repositories. 

- [x]  schedule  website migration - pending us completing
- [x] add current users - what permissions?
     - [x] Hui (ID requested)
     - [x] bill (invite sent) 
     - [x] fungi (invite sent) - astanley
     - [x] allison

**Comment by larsks** [comment]
We've moved https://github.com/open-infrastructure-labs/moc-cnv-sandbox. I spent today merging all the open merge requests and dealing with any open issues that were actionable. I've left a few remaining issues open on gitlab and archived the gitlab repository.

**Comment by larsks** [comment]
@msd there are repositories on gitlab for [Caerus](https://gitlab.com/open-infrastructure-labs/caerus) and [Wenju](https://gitlab.com/open-infrastructure-labs/wenju) that don't appear to have seen any use.  Should we move those, or just archive them?

**Comment by msdisme** [comment]
I *think* move

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by msdisme** [comment]
But it should be much lighter because I don’t think any discussions really occurred there.

---
Michael Daitzman (He/Him)
msd@bu.edu
cell:978-201-9965



From: Daitzman, Michael S <msd@bu.edu>
Date: Wednesday, December 16, 2020 at 3:39 PM
To: CCI-MOC/ops-issues <reply@reply.github.com>, CCI-MOC/ops-issues <ops-issues@noreply.github.com>
Cc: Assign <assign@noreply.github.com>
Subject: Re: [CCI-MOC/ops-issues] Move Open Infra Lab content from Gitlab to Github (#39)
I *think* move

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by larsks** [comment]
I have moved the caerus, wenju, and openinfralabs-website repositories from gitlab to github, and archived the corresponding gitlab projects.

@msd I had to remove `Wenju demo.mp4` from the `wenju` repository because it exceeded Github's size limits. You can still grab it from gitlab if you want to host it in the youtube channel.

**Comment by msdisme** [comment]
@larsks is there a good way to find the folks who were on the archived projects?

**Comment by msdisme** [comment]
sent invites to  identified members
