### ISSUE TITLE
Process to make 1000 pods available for a cloud course project 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#391]
One of the OpenShift teams wants to use appx. 1000 pods. Need to discuss with Naved/Lars how to do this - we will likely need to move some worker nodes over and will be affected by number of pods per node. This will likely take us a few weeks to get in place.

More details below:

For our project, we were wondering what kind of burst usage of Openshift pods might be available to us?

Our project description mentions trying to achieve balanced usage of ~1000 pods for parallel access of a distributed key-value store. This is for deduplicating streaming data for storage.

https://github.com/yrrah/cs6620-fall21-intelligent-assignment-of-data-to-dedup-nodes#5-solution-concept

**Comment by larsks** [comment]
That's an unanswerable question without knowing the per-pod resource requirements. How much memory do they require? What sort of network bandwidth does this generate? Is the workload CPU intensive?

**Comment by larsks** [comment]
According to [this document](https://kubernetes.io/docs/setup/best-practices/cluster-large/) we shouldn't have more than 110 pods/node. If that's true, then our cluster is definitively too small for this request. I'm going to see if Red Hat support agrees with this value.

**Comment by larsks** [comment]
I've opened https://access.redhat.com/support/cases/#/case/03046789 with this request. 

While researching that, I came across [this scalability document](https://docs.openshift.com/container-platform/4.3/scalability_and_performance/planning-your-environment-according-to-object-maximums.html#cluster-maximums-major-releases_object-limits) which seems much more authoritative, and says that a conservative max. pods/node is 250, and possibly up to 500.

[This blog post](https://cloud.redhat.com/blog/500_pods_per_node) explores the changes required to get 500 pods/node running smoothly.

**Comment by larsks** [comment]
Assuming that 250 pods/node is a reasonable number, we ought to be able to service this request, with the caveat that it will eat about 50% of our cluster capacity -- and that's assuming that the pod resource requirements are such that our hardware can host 250 pods on a single worker.

Most of our nodes have 32 cores and around 380GB of memory, which works out to 1.5GB memory/pod and about 0.1 CPUs per pod (so hopefully they're not too CPU intensive).

**Comment by msdisme** [comment]
@pjd-nu we are assuming, since we haven't heard any more about this, that they found another solution.

**Comment by larsks** [comment]
Assuming this is no longer necessary.
