### ISSUE TITLE
Plan for next 3 - 4 deliveries of wayfair hw

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#394]
As a receiver of gifts for the MOC we would like a clear process for receiving and distributing the hardware before the Next delivery January.

**Comment by msdisme** [comment]
identified likely contact person, need to confirm.

**Comment by msdisme** [comment]
make an epic of this, move items around

**Comment by hakasapl** [comment]
Closing this and moving to [this](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics) epic.
