### ISSUE TITLE
Get Emilien (et al) access to Zero cluster hardware

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#397]
There is interest in the operate first organization in deploying a model OpenStack cluster, much like the Zero and Smaug OpenShift clusters. Now that the Zero cluster has been retired, folks would like to try the OpenStack deployment on that hardware.

We'll need to get one or more people access to the hardware, including console/ipmi access.

Part of https://github.com/operate-first/support/issues/403

**Comment by naved001** [comment]
it's not clear to me, but what's happening with the zero cluster hardware?

**Comment by larsks** [comment]
> it's not clear to me, but what's happening with the zero cluster hardware?

@naved001 I don't think anyone has made a clear decision about that. Maybe we need a "What do with zero cluster hardware" issue.
