### ISSUE TITLE
Expose NESE VLAN to cnv-dhcp[12]

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#398]
In order to provide DHCP server for the NESE VLAN (id 211,
10.0.120.0/22), I'd like to expose VLAN 211 to the pair of virtual
servers we originally created for the CNV network.

I'm going to reconfigure these as an HA DHCP pair (like
[this](https://kb.isc.org/docs/aa-00502)) so that we can run dynamic
DHCP on the NESE VLAN.

**Comment by naved001** [comment]
I had vlan211 imported into ovirt. So I added an interface to both of those machines. Let me know if there are any connectivity issues.

**Comment by larsks** [comment]
Connectivity looks good from both nodes. Thanks!
