### ISSUE TITLE
We are running out of space on mail.massopen.cloud

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#406]
`/var/lib/mailman/archives/private` is taking up 15GB of space.

The big ones are:
```
[root@mail private]# du -sh * |grep G
2.7G	alerts
1.3G	cephalerts
5.7G	rootmail
1.7G	rootmail.mbox
```

Is it worth keeping those or can we delete those?

**Comment by larsks** [comment]
I think it's safe to delete the archives. We should probably configure a cron job to expire things automatically (e.g., maybe we want to keep a month of data).

**Comment by larsks** [comment]
@naved001 I have added the [`prune_arch`](https://www.msapiro.net/scripts/prune_arch) script to the mailserver and set up a systemd template unit (`prune-mailman-archives@.service`) and associated timers to clean up the `rootmail`, `cephalerts`, and `alerts` list. Currently expiration is set to 14 days, but can be adjusted per list.
