### ISSUE TITLE
Spike: How to integrate openstack and openshift into a single pane of glass for monitoring. 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#41]
1. Single web view for all services - eg. Shift/Stack/CEPH/etc
2. Single API endpoint for  extracting machine-readable metrics (discussion about whether feasible)
3. Requirement to provide data necessary for reporting which reporting will store independently. 
Discuss/resource with - Jacob Chappel UKY

**Comment by rob-baron** [comment]
We need to define "A single pane of glass".
