### ISSUE TITLE
Plan MOC(/etc) network architecture

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#410]
Our existing network infrastructure has amalgamated organically over time. We should sit with a network architect and figure out how best to design the physical and logical structure of our network to be as flexible and robust as possible.

**Comment by msdisme** [comment]
Discussion doc currently here: https://docs.google.com/document/d/1nfFf0E4wyIoTkpHG0w-q6bf0jbmHqzhp5rSLTIZjbv4/edit

**Comment by joachimweyl** [comment]
planned.
