### ISSUE TITLE
Performance testing NESE storage

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#411]
Either run our own performance tests or find someone with existing experience evaluating openshift storage to perform the testing for us.

**Comment by larsks** [comment]
I put together a small project that runs [fio](https://fio.readthedocs.io/en/latest/fio_doc.html) against our two storage backends.

The tests run for 60 seconds, and produce the following metrics:

- `bw_mean` -- average bandwidth (larger is better)
- `iops` -- iops completed (larger is better)
- `clat_mean` -- completion latency (smaller is better)

My reading of the results is that the Ceph storage is comparable to the NFS storage.

I've included visualizations of these metrics below; these were produced using the [analyze.py](https://github.com/larsks/k8s-storage-profiler/blob/master/analyze.py) script from the project repository.

![bw_mean](https://user-images.githubusercontent.com/82622/139684381-7837e11f-d41a-44a0-8805-dea44d41bd71.png)
![clat_ns mean](https://user-images.githubusercontent.com/82622/139684382-4f3481da-af0f-43ea-aa65-afd50345eb60.png)
![iops](https://user-images.githubusercontent.com/82622/139684383-2da2e22f-5ab2-44b2-9550-7f3778f88d24.png)

**Comment by joachimweyl** [comment]
@larsks do we have a link to the project you created for this that would allow others to run the same test?

**Comment by larsks** [comment]
@joachimweyl yes, it's linked from [an earlier comment](https://github.com/CCI-MOC/ops-issues/issues/411#issuecomment-956264993): https://github.com/larsks/k8s-storage-profiler

**Comment by larsks** [comment]
@joachimweyl we should probably be having this discussion [here](https://github.com/OCP-on-NERC/operations/issues/6), since that issue is still open and is targeted at the NERC environment.
