### ISSUE TITLE
confirm with PI's recycle hardware or move to OCT

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#412]
Should deprecated hardware be recycled or moved to OCT? If we're not moving the hardware itself, are existing students able to move their work to OCT? - https://docs.google.com/document/d/1e530KMVEcr0sCyo9SfeoIVzA8e3q9SqsyWjOko3BhBE/edit

**Comment by joachimweyl** [comment]
@msdisme please make this an epic

**Comment by msdisme** [comment]
Closing, covered by flax/itrenew issue https://github.com/CCI-MOC/ops-issues/issues/803
