### ISSUE TITLE
incomplete project approvals in onboarding

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#413]
https://onboarding.massopen.cloud/management/
shows a number of incomplete invitations to join projects and new project creations.
https://onboarding.massopen.cloud/management/notifications/ makes me think it's a problem with email.

Assigning to Kristi for guidance/resolution.

https://support.massopen.cloud/scp/tickets.php?id=1187 contains all of the students in EC713, and Professor Coskun.

The similar issues for students invited are associated with the cloud computing courses and their TA's: https://support.massopen.cloud/scp/tickets.php?id=1190

**Comment by knikolla** [comment]
Mail queue was rejecting new mails  #406 

Projects were created and invitations should now have gone through
