### ISSUE TITLE
Discussion/Question from Gagan:  may we install/run curator project on the MOC OpenShift 4.x cluster.

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#415]
@gagansk please update this with details

**Comment by msdisme** [comment]
@gagansk and @skanthed - how much time would it take to present details - show us the reports it can produce; how it connects, etc. Hoping we can invite you to one of our daily standups to show it.

**Comment by skanthed** [comment]
Here we have a few reports attached from the Smaug cluster in this issue if that makes sense. 
Reports - https://github.com/operate-first/curator/issues/143

**Comment by larsks** [comment]
@skanthed access to those reports appears to be restricted.

**Comment by skanthed** [comment]
@larsks Can you try now one more time?

**Comment by larsks** [comment]
@skanthed that works for me. Will they be available to folks without Red Hat addresses?

**Comment by skanthed** [comment]
Not for now. But for them, we will create a folder in the drive and put files in that and will give access to everyone.

**Comment by skanthed** [comment]
For now, I have given access to @naved001 and @msdisme.

**Comment by naved001** [comment]
PR here: https://github.com/CCI-MOC/moc-apps/pull/123
