### ISSUE TITLE
MGHPCC: Check switchports of the supermicro server

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#416]
@pjd-nu's supermicro server has no links. Needs to be looked at either remotely or in-person.

**Comment by msdisme** [comment]
@hakasapl any updates?

**Comment by hakasapl** [comment]
I checked on this a few weeks back and everything is correct. If the link isn't coming up in the OS it would have to be a firmware issue. I can try switching it to a different port?
