### ISSUE TITLE
Configure netbox to authenticate against Keycloak

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#426]
We should configure Netbox to make use of Keycloak for authentication. One way of doing this is by setting up an oauth proxy in front of Netbox, and then configuring Netbox for remote authentication (`REMOTE_AUTH_ENABLED=True` and a number of related configuration options).

**Comment by naved001** [comment]
it's done.

**Comment by larsks** [comment]
Specifically, this was configured as part of https://github.com/CCI-MOC/moc-apps/commit/ac8ed4191dfd1a85c0f5b70b60ae4fd06fa15eef
