### ISSUE TITLE
Review MOC Security Audit Results

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#428]
Please review: [End of Research Presentation](https://docs.google.com/presentation/d/1I9JD2GA6qm6ktTLhxh85d2lqrF6DPaTSulI9T2DkvL8/edit?usp=sharing).  They plan to present it on 11/2.

You will probably need to request access to a number of the linked reports in the presentation.

- [ ] to ensure that all the information we are sharing is appropriate given that some meeting attendees may not be affiliated with the MOC or Redhat. 
- [ ] any comments we may want to include 
- [ ]  identify actions we may want to take based on the report

**Original Note from Dylan and Tyler:**
As you may know, Tyler Shehan and I spent our summer internship performing security tests on the MOC environment. Next week we have been tasked with presenting our findings at the Greater New England Research Interest Group meeting on Tuesday (11/2). 

Before presenting we need a representative from the MOC to look over our presentation: End of Research Presentation to ensure that all the information we are sharing is appropriate given that some meeting attendees may not be affiliated with the MOC or Redhat. 

Please review our presentation and let us know if there is any information or data therein that should be removed from the presentation prior to the meeting. 

If you have any questions please let me know. 

Thank you,
Dylan

**Comment by naved001** [comment]
I read the reports and it looks fine to me.
