### ISSUE TITLE
do we have a switch with some 40G ports in BOS or at MGHPCC?

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#43]
for the FPGA evaluation, Miriam is looking for a switch with some 40G ports. We only need 4 ports, and it’s for a local network, so a 10G switch with 40g uplinks might do.

Is there any chance that we have something like that laying around in Boston? If not, it’s probably easiest to buy something.

**Comment by naved001** [comment]
afaik, we have 2 FPGA nodes and the FPGA nics are connected to our cisco switches.

https://docs.google.com/spreadsheets/d/1kKNx2HKtuTL_UZFDsOMfKqk-9KJ3Yd46lvJRn6P-3Zc/edit#gid=0

Why do we need 4 40G ports?

**Comment by msdisme** [comment]
@naved001 - do we have one in Boston?  (@pjd-nu Naved is out till Friday).   If not Peter is planning to purchase one - this is going into an NEU rack so may not make sense to move one from MGHPCC - though Hakan will be out there this weekend. )

**Comment by naved001** [comment]
I think the servers @hakasapl racked on OCT3 are these ones? The mac addresses I am seeing are a bit different than what Hakan put out in the email. Since then I haven't looked at those again; so that's one thing I need to get done.

**Comment by msdisme** [comment]
@pjd-nu do you still need this info? @naved001 is making separate card for the OCT3 work

**Comment by pjd-nu** [comment]
We're all set.
