### ISSUE TITLE
Upgrade ocp-prod to OpenShift 4.9

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#430]
OpenShift 4.9 includes MetalLB support, which we want to provide a convenient mechanism for assigning public ips to CNV virtual machines.

**Comment by naved001** [comment]
the staging cluster is now running the latest 4.8 and can be migrated to 4.9.6, however looks like we need to make sure that certain v1beta APIs removed in kubernetes 1.22 should be migrated.

https://access.redhat.com/articles/6329921

on `ocp-staging` this is what I see:
```
naved@naved-MS-7984:~/moc-apps$ oc get apirequestcounts -o jsonpath='{range .items[?(@.status.removedInRelease!="")]}{.status.removedInRelease}{"\t"}{.metadata.name}{"\n"}{end}'
1.22	certificatesigningrequests.v1beta1.certificates.k8s.io
1.22	customresourcedefinitions.v1beta1.apiextensions.k8s.io
1.22	ingresses.v1beta1.extensions
```

on `ocp-prod`:
```
naved@naved-MS-7984:~/moc-apps$ oc get apirequestcounts -o jsonpath='{range .items[?(@.status.removedInRelease!="")]}{.status.removedInRelease}{"\t"}{.metadata.name}{"\n"}{end}'
1.22	certificatesigningrequests.v1beta1.certificates.k8s.io
1.22	customresourcedefinitions.v1beta1.apiextensions.k8s.io
1.22	ingresses.v1beta1.extensions
1.22	ingresses.v1beta1.networking.k8s.io
1.22	rolebindings.v1beta1.rbac.authorization.k8s.io
1.22	roles.v1beta1.rbac.authorization.k8s.io
```

**Comment by naved001** [comment]
I looked at what users are using the deprecated APIs on the `ocp-staging` cluster
```
naved@naved-MS-7984:~$ oc get apirequestcounts  |grep -E 'NAME|1.22'
NAME                                                                       REMOVEDINRELEASE   REQUESTSINCURRENTHOUR   REQUESTSINLAST24H
certificatesigningrequests.v1beta1.certificates.k8s.io                     1.22               0                       4
customresourcedefinitions.v1beta1.apiextensions.k8s.io                     1.22               172                     4351
ingresses.v1beta1.extensions                                               1.22               0                       647
prometheusrules.v1.monitoring.coreos.com                                                      4952                    122205
naved@naved-MS-7984:~$ oc get apirequestcounts  |grep -E 'NAME|1\.22'
NAME                                                                       REMOVEDINRELEASE   REQUESTSINCURRENTHOUR   REQUESTSINLAST24H
certificatesigningrequests.v1beta1.certificates.k8s.io                     1.22               0                       4
customresourcedefinitions.v1beta1.apiextensions.k8s.io                     1.22               172                     4351
ingresses.v1beta1.extensions                                               1.22               0                       647
naved@naved-MS-7984:~$ oc get apirequestcounts certificatesigningrequests.v1beta1.certificates.k8s.io -o jsonpath='{range ..username}{$}{"\n"}{end}' | sort | uniq
kube:admin
naved@naved-MS-7984:~$ oc get apirequestcounts customresourcedefinitions.v1beta1.apiextensions.k8s.io -o jsonpath='{range ..username}{$}{"\n"}{end}' | sort | uniq
system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa
naved@naved-MS-7984:~$ oc get apirequestcounts ingresses.v1beta1.extensions -o jsonpath='{range ..username}{$}{"\n"}{end}' | sort | uniq
system:kube-controller-manager
system:serviceaccount:open-cluster-management-agent-addon:klusterlet-addon-appmgr
system:serviceaccount:open-cluster-management-agent-addon:klusterlet-addon-search
```
Looks like it's mostly some `system` accounts except for `certificatesigningrequests.v1beta1.certificates.k8s.io` used by the `kube:admin` user.

**Comment by larsks** [comment]
I think if the usage is by system accounts we don't need to worry about it, because those will presumably be taken care of as part of the upgrade. I think the only use of the `kube:admin` account is interactive cli/console login, so that should also be okay. Let's go ahead with the upgrade on the staging cluster.

**Comment by naved001** [comment]
@larsks sounds good. opened a PR https://github.com/CCI-MOC/moc-apps/pull/101

**Comment by naved001** [comment]
on the production cluster, 
```
naved@naved-MS-7984:~$ oc get apirequestcounts certificatesigningrequests.v1beta1.certificates.k8s.io -o jsonpath='{range ..username}{$}{"\n"}{end}' | sort | uniq
naved001@bu.edu
```
I am somehow using that API. 
all others were used by system accounts.

**Comment by naved001** [comment]
We successfully upgraded our staging cluster to 4.9.6 and then installed metallb and openshift-cnv. For cnv to work we had to uninstall the standalone nmstate operator. I successfully launched a test VM on the staging cluster.

Now we need to this on the production cluster; hope to do it all today.

**Comment by msdisme** [comment]
@naved001 @larsks @rob-baron - I *know* we wrote this yesterday and yet neither Naved or I can find it, so rewriting:

We will be upgrading the OpenShift 4.8 cluster you are working on to OpenShift 4.9 .  This change should be transparent to users, though some long running processes may be affected.  

We will send a note when we start, and when the process is complete.  If you notice any issues after the "done" email please open a ticket at support.massopen.cloud.

**Comment by naved001** [comment]
I think that gets the point across.

**Comment by msdisme** [comment]
ok - pulling emails from openshift-projects, will probably lock them in a bitwarden note as a way to make them available to you etc.

**Comment by sleviim** [comment]
Hi all,
Our course starting date is just around the corner (Sun 21st), and it feels like things are not completely finished.
We can postpone the starting date, but can you please share with us the estimation of when the platform should be ready to use and get tested?
We appreciate your effort in doing it, and would appreciate your transparency with the dates and progress (as we also have the lecturers and students involved and we should let them know about the new date).
Thanks

**Comment by naved001** [comment]
@sleviim 

Apologies for the delay, we will be upgrading the production cluster and installing CNV on it today. If nothing breaks during that then you should have access to test the cluster by tomorrow (Nov 18th).


You can start by submitting a request here so we can create an account for you on our cluster: 
https://github.com/CCI-MOC/moc-openshift-projects

**Comment by sleviim** [comment]
Ack, thanks!

**Comment by naved001** [comment]
resolved by https://github.com/CCI-MOC/moc-apps/pull/109
