### ISSUE TITLE
Presentation as to what data OpenShift collects.

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/ops-issues#442]
Presentation as to what data OpenShift collects

**Comment by larsks** [comment]
Attached file  [metrics.json](https://github.com/CCI-MOC/ops-issues/files/7464167/metrics.json.txt) which is a list of all the metrics available in the `ocp-prod` cluster right now. It is possible to enable additional monitoring of [user defined projects](https://docs.openshift.com/container-platform/4.9/monitoring/enabling-monitoring-for-user-defined-projects.html) (see also the [following section of the docs](https://docs.openshift.com/container-platform/4.9/monitoring/managing-metrics.html#setting-up-metrics-collection-for-user-defined-projects_managing-metrics) which shows how to create `ServiceMonitor` resources).

**Comment by larsks** [comment]
The API endpoint for the openshift prometheus instance is https://prometheus-k8s-openshift-monitoring.apps.ocp-prod.massopen.cloud/api/v1. You'll need to get an auth token to interact with the API, e.g.:

```
curl  -H "Authorization: Bearer $(oc whoami -t)" \
    'https://prometheus-k8s-openshift-monitoring.apps.ocp-prod.massopen.cloud/api/v1/query?query=node_load5
```

There is an interactive query interface at https://console-openshift-console.apps.ocp-prod.massopen.cloud/monitoring/query-browser if you want to experiment with queries in your browser.

Typically you will not be asking for a single metric but will instead be making some sort of aggregate request. If you look at the dashboards available at https://console-openshift-console.apps.ocp-prod.massopen.cloud/monitoring/dashboards/, you can clink the `Inspect` link in the upper right of any graph to see the promql query used to generate that data. For example, the for "CPU Usage" graph of the "Kubernetes / Compute Resources / Cluster" dashboard, the query is:

```
sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=""}) by (namespace)
```

**Comment by larsks** [comment]
The OpenShift monitoring documenting starts [here](https://docs.openshift.com/container-platform/4.9/monitoring/understanding-the-monitoring-stack.html), which includes an architectural overview, configuration information, and the links I included in [my earlier comment](https://github.com/CCI-MOC/ops-issues/issues/442#issuecomment-958201804).

**Comment by rob-baron** [comment]
(https://docs.google.com/presentation/d/19RtBTJbi0Z952SqUIqzprU1xE8goaY4UZF8QdR1YaJs/edit#slide=id.gfd72101621_0_57)
