### ISSUE TITLE
Evaluate hw requirements for Jupyter Hub for January Courses

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#448]
Mark Crovella, Jonathan Apavoo and Orran all hope to use Jupyter Books in the January timeframe.    

That means a total of approximately 500 students.   We need to evaluate whether the MOC OpenShift 4.x  can support this number of users, what additional HW requirements look like,   etc. 

@okrieg setting proper expectations,   this will impact the same resources required to support ESI, migration to NERC, etc.   and so we need to make a priority call on this vs. those.

**Comment by msdisme** [comment]
Jonathan 250, Marc 150, Orran OS - 50

**Comment by msdisme** [comment]
Backup run on OpenShift on demand. . . .

**Comment by larsks** [comment]
> Backup run on OpenShift on demand. . . .

@msdisme can you unpack that one a bit?

**Comment by msdisme** [comment]
Sure: 
If we decide that supporting the class is important.
And MOC or NERC are not the right place to do it in Spring 2022.
Then we should explore running Jupyter Books on OpenShift on Demand.

**Comment by larsks** [comment]
Ah, thank you for the clarification. I thought it was a request for some sort of on-demand backup mechanism :)

**Comment by msdisme** [comment]
Being addressed via control of number of computes used by students.  closing as this will be handled under AWS for initial term.
