### ISSUE TITLE
Virtual ROSE on CNV requirements discussion

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#450]
This issue is a place to discuss the use of the MOC ocp-prod OpenShift cluster by the Virtual ROSE project.

**Comment by larsks** [comment]
@sleviim it occurs to me that if we can't get RDP working, you may just be able to use the console access already available in OpenShift (go the virtual machine details and select the "Console" tab).

The image you're using right now is a minimal image that does not include any desktop environment. You will either need to (a) configure each vm explicitly after creating it, or (b) create a custom base image and use that in place of the stock CentOS cloud image.

To manually create the desktop environment (including the RDP service, in case we're able to get that working), you would need to run:

```
yum -y upgrade
yum -y install epel-release
yum -y install @workstation
yum -y install httpd xrdp
systemctl enable --now xrdp
```

That would be relatively easy to automate using e.g. ansible, but I might just go ahead and create the necessary custom image in order to save you some time.

**Comment by larsks** [comment]
I have made several changes to the README document for https://github.com/larsks/virtual-rose-template that should help you batch create all your virtual machines.

**Comment by naved001** [comment]
can they change the port that [xrdp listens on](https://www.systutorials.com/docs/linux/man/5-xrdp.ini/)? For instance, port 3390 is open on the network.

**Comment by larsks** [comment]
@naved001 that's a good thought! Since the port is exposed through a `Service`, it doesn't matter what the actual application is listening on, we can expose it on any port.

**Comment by naved001** [comment]
oh right, service port 3390 maps to VM port 3389. so that require no change to the xrpd config either.

**Comment by larsks** [comment]
@sleviim I've uploaded a custom image that is configured to boot into a desktop environment by default and modified the template to use it.

**Comment by sleviim** [comment]
Great! Thanks!
I'll give it a try probably tomorrow

**Comment by larsks** [comment]
@sleviim per @naved001 's suggestion, we've configured things so that you can access RDP on port 3390.

**Comment by sleviim** [comment]
Thanks @naved001 @larsks !

**Comment by larsks** [comment]
@sleviim Just wanted to check in and see if you've had a chance to try things out.

**Comment by sleviim** [comment]
Hi, saw that but had no chance to try it yet

**Comment by sleviim** [comment]
@larsks, can you please share with us on the mail the meeting's recording?

**Comment by larsks** [comment]
@sleviim you should find the meeting recording attached to the calendar event for yesterday's call, but I'll email out a direct link as well.

**Comment by larsks** [comment]
Note that tomorrow (Wednesday 11/24) is the last day most of us will be around until Monday 11/29.

**Comment by larsks** [comment]
Note that tomorrow (Wednesday 11/24) is the last day most of us will be around until Monday 11/29.

**Comment by maayanf24** [comment]
@larsks - We have managed to create a single vm according to the template.
we have some questions:
1. is it possible to allow all our mentors to access all the vms without entering each mentor's public key to the template?
2. how can we login to console with user "centos" ? without having to access OCP console?

**Comment by larsks** [comment]
@maayanf24:

> is it possible to allow all our mentors to access all the vms without entering each mentor's public key to the template?

You could use a shared ssh key (generate a new private key, share it with your mentors, and put the corresponding public key in the template). I'm curious, why you don't want to put the individual public keys in the template?

> how can we login to console with user "centos" ? without having to access OCP console?

To log in to the *console* specifically you would need the "Console" tab in OCP (to which I believe everyone should have access).

If you're just looking for a GUI login, then as discussed [earlier](https://github.com/CCI-MOC/ops-issues/issues/450#issuecomment-975887447) you can connect with an RDP client using port 3390 (to the ip address assigned to the Service that was created along with the virtual machine).

Does that help? I'm not sure I followed your question exactly, so please let me know if my answers aren't addressing your question directly.

**Comment by larsks** [comment]
@sleviim that's interesting! I hadn't realized there was that sort of size limit. There are a variety of ways to work around that problem.

One solution would be to put the public keys online somewhere and then just fetch them with `curl` via a [runcmd](https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot) in your userdata script.

If everyone has configured their github accounts with public keys, you could just loop over a list of github usernames and fetch the keys from `https://github.com/<username>.keys`.

**Comment by larsks** [comment]
If you'd like help with any of the above I'd be happy to hop on a call and work through it with you.

**Comment by sleviim** [comment]
@larsks I can use some help :)
not sure how to use is / where to locate it in the yaml file (nocloud: userDataSecretRef: my-vm-userdata)

**Comment by larsks** [comment]
We need to update the template to create a [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) resource. The `objects` attribute of the template is a list of OpenShift resources to create, so we'll add the data there.

Let me update [the repository](https://github.com/larsks/virtual-rose-template) with an example; if you'd like to talk through it you can reach me on chat to set up a call.

**Comment by larsks** [comment]
You can see the updated template [here](https://github.com/larsks/virtual-rose-template/blob/2e66802c4afbdee08a6984387e25a08406b7f9e1/template/rose-integrated-template.yaml). I have not updated the template in OpenShift yet because I wasn't sure if you had made some of your own changes and I didn't want to overwrite anything.

**Comment by larsks** [comment]
And of course if you've already got your VMs up and running, it would be relatively easy (e.g. via an Ansible playbook) to automatically update the `authorized_keys` file in all the existing vms.

**Comment by sleviim** [comment]
> You can see the updated template [here](https://github.com/larsks/virtual-rose-template/blob/master/template/rose-integrated-template.yaml). I have not updated the template in OpenShift yet because I wasn't sure if you had made some of your own changes and I didn't want to overwrite anything.

AFAIK, no changes yet.
Need to create a "general" public key for all mentors (and share it among them).

If we have some VMs based on that template, we still need to update each one to use the secret, right?

**Comment by larsks** [comment]
@sleviim you don't need a "general" public key. Using the model I was showing in that last comment you avoid the space limitations that prevented you from putting the individual keys in place.

> If we have some VMs based on that template, we still need to update each one to use the secret, right?

Changes to the template will not effect existing virtual machines. You would either need to recreate them, or update the `authorized_keys` file (which is relatively easy to automate).

**Comment by naved001** [comment]
@larsks port 3389 is now unblocked. We probably don't wanna change ports at this stage, but now we know it works.

**Comment by larsks** [comment]
@sleviim we haven't heard from you in a few days, so I'm hoping everything is going fine. If you have additional questions, please open a ticket at https://osticket.massopen.cloud. Thanks!
