### ISSUE TITLE
Look at OCT-5 hardware

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#451]
* Figure out access to the nodes and what all needs to be done before the nodes can be used.
* Put the nodes on our IPMI network

**Comment by naved001** [comment]
| Server | Note |
|-|-|
| OCT5-08 | no drive |
| OCT5-10 | what's the IPMI password? |
| OCT5-30 | ipmi unreachable |
| OCT5-34 | no drive |
| OCT5-35 | ipmi unreachable |
| OCT5-38 | no drive  |

**Comment by naved001** [comment]
@hakasapl looks like I can't reach the IPMI of any node's in OCT5.

**Comment by naved001** [comment]
according to the [documentation](https://docs.massopen.cloud/en/latest/clusters/kaizen2/Kaizen-2.html#oct-umass-switch-management-vlan-207-10-1-0-0-24) it looks like the management switch is at 10.1.0.55 and it's not responding.

```
[naved@kzn-ipmi-gw ~]$ ping 10.1.0.55
PING 10.1.0.55 (10.1.0.55) 56(84) bytes of data.
^C
--- 10.1.0.55 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 999ms

[naved@kzn-ipmi-gw ~]$ ssh 10.1.0.55
ssh_exchange_identification: Connection closed by remote host
```

I can reach the data switch (10.1.0.15) just fine.

**Comment by hakasapl** [comment]
Should be reachable now

**Comment by naved001** [comment]
thanks. 

here's the current summary of the hardware in oct5. I guess this could be taken care of when you are working on oct5 hardware.

| Server | Note |
|-|-|
| OCT5-08 | no drive |
| OCT5-10 | what's the IPMI password? |
| OCT5-30 | ipmi unreachable |
| OCT5-34 | no drive |
| OCT5-35 | looks like it's broken |
| OCT5-38 | no drive  |

**Comment by msdisme** [comment]
On Site week of March 14.

**Comment by msdisme** [comment]
rack, except IPMI for some ready.   dual connection 10G can get started except for list above.

**Comment by naved001** [comment]
@hakasapl I took another look at this list and issues are still there. Here's an update.

| Server | Note |
|-|-|
| OCT5-08 | no drive,  |
| OCT5-10 | what's the IPMI password? |
| OCT5-30 | ipmi unreachable |
| OCT5-34 | no drive, idrac says "The storage BP1 SAS A0/B0 cable is not connected, or is improperly connected." |
| OCT5-35 | looks like it's broken, so nothing to do |
| OCT5-38 | no drive, idrac has same message as oct5-34  |

**Comment by naved001** [comment]
@hakasapl @msdisme should I try to get some of these looked at by tech square folks?

**Comment by naved001** [comment]
yes, they plan to do it after MGHPCC has power. So I will bug them on Thursday.

**Comment by joachimweyl** [comment]
@naved001 any follow-up from TechSquare?

**Comment by joachimweyl** [comment]
@naved001 according to your standup notes it sounds like we are still in communication with TechSquare about this? What update have they provided?

**Comment by naved001** [comment]
Techsquare provided an update on this yesterday, they are still working on it.
