### ISSUE TITLE
curator on ocp-staging cluster

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#456]
may need to spend some time with @skanthed on getting this done.

**Comment by naved001** [comment]
@skanthed now that the `koku-metrics-operator` is installed on ocp-staging cluster, and you have access to the namespace, is there anything else that needs to be done? Thanks!

**Comment by skanthed** [comment]
Not for now! Today I will deploy the database instance in that namespace and then the curator project. I will let you know if any further help is required.

**Comment by naved001** [comment]
closing this now that we have this up and running on ocp-staging.
