### ISSUE TITLE
Investigate syntax for selecting by issues present in a project

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/ops-issues#46]
Project here refers to a project board and should not be confused by repo. This syntax is necessary so that we can figure out the tasks that we haven't yet added to a sprint board and are to be groomed.

**Comment by msdisme** [comment]
Can't be filtered in project board by presence in other projects:  from: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/filtering-cards-on-a-project-board

Filter cards by author using `author:USERNAME`
Filter cards by assignee using `assignee:USERNAME or no:assignee`
    Filter cards by label using `label:LABEL, label:"MULTI-WORD LABEL NAME", or no:label`
    Filter by milestone by using `milestone:MY-MILESTONE`
    Filter cards by state using `state:open, state:closed, or state:merged`
    Filter by review status using `review:none, review:required, review:approved, or review:changes_requested`
    Filter by check status using `status:pending, status:success, or status:failure`
    Filter cards by type using `type:issue, type:pr, or type:note`
    Filter cards by state and type using `is:open, is:closed, or is:merged; and is:issue, is:pr, or is:note`
    Filter cards by issues that are linked to a pull request by a closing reference using `linked:pr`
    Filter cards by repository in an organization-wide project board using `repo:ORGANIZATION/REPOSITORY`

**Comment by msdisme** [comment]
see: https://github.com/CCI-MOC/sprint-tools  (whoohoo!)
