### ISSUE TITLE
Broken dns for hil.massopen.cloud

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#461]
I have an openshift install that is failing because lookups for ANYTHING.hil.massopen.cloud returns an answer:

```
$ host lskjlksjdfsdf.hil.massopen.cloud
lskjlksjdfsdf.hil.massopen.cloud has address 127.0.0.1
```

DHCP on VLAN 3803 configures the following search domains:

```
$ cat /etc/resolv.conf
search maas.massopen.cloud cnv.massopen.cloud hil.massopen.cloud maas kumo.massopencloud.org
```

So when the openshift attempts to validate that there are no conflicting wildcard dns entries, it sees the erroneous response for looking in hil.massopen.cloud and fails.

Can we either:

- Fix DNS for hil.massopen.cloud so it doesn't  return a result for all queries, or
- Fix DHCP on VLAN 3803 to remove hil.massopen.cloud from the list of search domains?

**Comment by naved001** [comment]
I dont know how to do either of those in MaaS. Let me look around, if I can't find that then I propose we just get rid of hil.massopen.cloud from MaaS DNS and configure those hosts directly in tld.massopen.cloud (there are like 3-4 active hosts)

**Comment by larsks** [comment]
What is the dns server for hil.massopen.cloud -- is that MaaS, or something else?

**Comment by naved001** [comment]
It is Maas
https://maas.massopen.cloud/MAAS/#/domain/4

**Comment by larsks** [comment]
There was a wildcard entry in MaaS mapping `*.hil.massopen.cloud` to `127.0.0.1`. Removing this wildcard entry fixes the errors in the installer.
