### ISSUE TITLE
Ask about lease changes for CSAIL-10 network

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#463]
During the [recent outage for the smaug cluster](https://github.com/operate-first/SRE/issues/430). some nodes lost their addresses because their DHCP leases expired while the network was offline. This means when the network was restored these nodes did not come back online without some manual intervention.

We should probably make some changes to DHCP on this network. There are two options:

1. Increase the DHCP lease time for all addresses. We would need to strike a balance here because we have some long-running servers on this network, but it's possible we would would also allocate addresses for more ephemeral systems from this same dynamic range. We want leases long enough that leases won't expire during the course of a minor outage, but at the same time short enough that booting a bunch of ephemeral hosts doesn't eat up all available addresses.
    I suggested a lease time of 12 hours in the issue.

2. We could instead make the leases static (a given address would only ever be assigned to a host with a specific MAC address, and a given host would always get the same address). This would allow us to set the lease time for the servers to be much longer than the lease time for other addresses.
    The downside to this option is that we would need to request a change ever time we add (or require) a server.

I guess I'm voting for option 1 right now, and perhaps looking at our options for configuring networking on the servers to behave differently in the event of a lease expiration.

**Comment by naved001** [comment]
Sent out an email asking about it.

**Comment by naved001** [comment]
> 
> I've increased the default lease time to 8 hours and increased the
> maximum lease time to 24 hours.

That should be sufficient I guess. Probably would require some client side configuration to request the max lease time of 24 hours if we wanted that.
