### ISSUE TITLE
Notification of standard biweekly maintenance window.

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#465]
Based on frequency of updates to OCP set a standard

**Comment by naved001** [comment]
> Hello OpenShift Users
> 
> From now on we will be updating our OpenShift4 cluster once every two weeks (on a Monday). We will no longer be sending any announcements before the updates since these updates will be largely unnoticed. 
> 
> We will continue to make announcements for maintenance that may cause service interruption. 
> 
> Thanks
> MOC Staff
>

**Comment by naved001** [comment]
@msdisme can I send this message to our openshift users?

**Comment by msdisme** [comment]
Lets say first and third monday of the month and add it as a mention on the web site status spot in a way that makes it continue to be visble.  Also, what time of day?


Hello OpenShift Users

    From now on we will be updating our OpenShift4 cluster on the first and third monday over every month at x:xx time EST.

 We will not send announcements before these updates since they should not be noticeable. 

    We will continue to make announcements for maintenance that may cause service interruption.

    Thanks
    MOC Staff

**Comment by naved001** [comment]
> add it as a mention on the web site status spot in a way that makes it continue to be visble

good Idea, don't know how to do it, but will take a look at that.

> Also, what time of day?

Let's say 10:00 AM.

So the final message becomes:

> Hello OpenShift Users
>
> From now on we will be updating our OpenShift4 cluster on the first and third monday over every month at 10:00 AM EST.  We will not send announcements before these updates since they should not be noticeable.
> 
> We will continue to make announcements for maintenance that may cause service interruption.
> 
> Thanks
> MOC Staff

**Comment by msdisme** [comment]
[drop link into the ticket ](https://github.com/CCI-MOC/moc-status) has details on how to create status items,  this has actual posts: https://github.com/CCI-MOC/moc-status/tree/gh_pages/_posts and this is the template.md:https://github.com/CCI-MOC/moc-status/blob/gh_pages/_posts/template.md

**Comment by naved001** [comment]
done.
