### ISSUE TITLE
Dual connect OCT4 nodes

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#474]
@DanNiESh [pointed out](https://github.com/CCI-MOC/esi/issues/176#issuecomment-995270271) that the undercloud (oct-00) and overcloud nodes (oct4-01, oct4-02, oct4-03)  need to have dual connections.

Would be best if all nodes have dual connections if we available switchports, but starting with those 4 nodes will unblock the ESI deployment.

**Comment by DanNiESh** [comment]
@hakasapl, hi! Do the nodes (oct4-01, oct4-02, oct4-03) have dual connectivity now?

**Comment by larsks** [comment]
@hakasapl is out of the country until 1/24. I think that means that we will need to wait until then for the changes at the datacenter, but I will check in with @msdisme to see if there are any other options.

**Comment by hakasapl** [comment]
These connections are all set, for the 2nd port on each NIC:
```
oct4-00 = port 20
oct4-01 = port 21
oct4-02 = port 22
oct4-03 = port 23
```
@naved001 can you set up those switchports and let me know if anything isn't working?

**Comment by naved001** [comment]
@hakasapl I tested OCT4-00 and it has connectivity. I'll take a look at the other nodes

**Comment by msdisme** [comment]
@hakasapl @hpdempsey  this is the ticket we were discussing.

**Comment by msdisme** [comment]
@DanNiESh added you to this issue, please advise if you have problems.  We believe the cablng part is done.

**Comment by DanNiESh** [comment]
@msdisme I don't have any network problems so far. Thanks!

**Comment by naved001** [comment]
@hakasapl is it possible to dual connect two more nodes in the same rack this wednesday?

oct4-04 and oct4-05.

**Comment by hakasapl** [comment]
4 and 5 are all set:
```
oct4-04 = port 24
oct4-05 = port 25
```

**Comment by naved001** [comment]
Thank you!
