### ISSUE TITLE
Replace drive in neu-5-15 (ceph OSD, dell poweredge r720)

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#477]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/20113064/149953171-75260417-38e1-4c58-9ffb-ca57d1bae944.png">

It'll take a 10TB drive, slot 1.

**Comment by hakasapl** [comment]
Drive replaced.

@msdisme we need to order more 10T drives I believe this was the last one.

**Comment by naved001** [comment]
thanks! I r[ecreated the OSD](https://github.com/CCI-MOC/ops-issues/issues/327#issuecomment-895424255), it is back up now.
