### ISSUE TITLE
Search to exclude esi from backlog search

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#478]
Seeing all the ESI project issues in our issue searches clutters things up and complicates things like backlog planning. Can we develop a search that excludes ESI issues?

**Comment by msdisme** [comment]
Probably as an additional search since we may be working more on esi in the future.

**Comment by joachimweyl** [comment]
@msdisme Are you referring to the "Add cards" search or something else?
if you are referring to the Add cards section I created some filters to exclude different repos
Add `-repo:CCI-MOC/esi -repo:CCI-MOC/python-esiclient -repo:CCI-MOC/esi-leap` to exclude esi repo
other repos we might want to exclude
`-repo:CCI-MOC/ocp-on-power9`
`-repo:CCI-MOC/flocx-market -repo:CCI-MOC/flocx-ui -repo:CCI-MOC/flocx`
`-repo:CCI-MOC/hil -repo:CCI-MOC/hil-vpn`
`-repo:CCI-MOC/zabbix-libvirt`

**Comment by msdisme** [comment]
Hi - I think in my brain I wanted it in the list of possible searches.  (top left)  But I think that is not necessary.

Re. the other repositories, ocp we can archive once we distribute the power 9 systems.  Some of the others may be worth keeping in since if something shows up in them we should know, though some (flocx?) should probably be archived.   Feels like a fun 2:30 topic.

**Comment by joachimweyl** [comment]
I can create one for the left that is a link like this.
[Issues that do not include esi repos and are in the backlog](https://github.com/orgs/CCI-MOC/projects/8?card_filter_query=-repo%3Acci-moc%2Fesi+-repo%3Acci-moc%2Fpython-esiclient+-repo%3Acci-moc%2Fesi-leap)
granted currently, there is only 1 issue from `CCI-MOC/esi` and none from the other 2 esi related repos I filtered out.

what are the requirements?

**Comment by joachimweyl** [comment]
flox & moc-forms ORE kumo-leasing giji-frontend giji-backend giji-rtwo django-giji-auth moc-pyslurm ui archive
power9, more after review

**Comment by joachimweyl** [comment]
@msdisme we have archived 23 repos and are hiding 5 repos from our **Add cards**. If you would like a **Useful filters** created to remove the same 5 repos [here](https://github.com/orgs/CCI-MOC/projects/8?card_filter_query=-label%3Aaccepted+is%3Aopen+-repo%3Acci-moc%2Fesi+-repo%3Acci-moc%2Fpython-esiclient+-repo%3Acci-moc%2Fesi-leap+-repo%3Acci-moc%2Focp-on-power9+-repo%3Acci-moc%2Fmoc-openstack-tools) it is. I am happy to add it or any other filters you want to the left side notes.

**Comment by joachimweyl** [comment]
I just realized there are a bunch more esi projects than I knew about, should I filter them from the **Add cards** as well?
esi, esi-leap, python-esiclient, esi-pilot, python-esileapclient, esi-pilot-cluster, esi-sandbox, esi-ha-config, esi-common.

**Comment by joachimweyl** [comment]
Found a few more we might want to hide or archive
CCI-MOC.github.io (5 years old)
moc (6 years old)
puppet-internal (6 years old), kilo-puppet (6 years old) , puppet-csail-examples (7 years old), puppetlabs-openstack (8 years old)

**Comment by joachimweyl** [comment]
puppet repos archived

**Comment by msdisme** [comment]
Looks good
