### ISSUE TITLE
Requirements for ESI testing

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#480]
The rack of hardware that has been assigned to the ESI Project contains a total of 13 nodes (3 controllers and 10 additional nodes, details [here](https://docs.google.com/spreadsheets/d/1V4_24MEQvpQaEIWOY9CT3zMeu_7llBagkYRxAIsJ1a4/edit#gid=748212895).

The switch is a Dell S4048.

Is this appropriate for the initial round of ESI testing?

**Comment by msdisme** [comment]
I would like us to talk about this, in the context of this testing doc: https://docs.google.com/document/d/12G4w9Os2bIUbL8ZadxCYVUSU0ZOo12_YW-6dAaWM0DA/edit  on fridays the 4th.

**Comment by larsks** [comment]
@gagansk @msd said there had been some discussion about hardware on Monday, and neither Naved nor I will able to attend that meeting. This issue has details about available hardware, and would be a good place for questions or commentary on the issue of hardware availability for ESI.

**Comment by joachimweyl** [comment]
closing as 216 covers this.
