### ISSUE TITLE
Add compute capacity to `smaug` openshift cluster

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#491]
@larsks are we running low on resources on the `smaug` cluster? Asking this so we can prioritize the rack preparation.

**Comment by naved001** [comment]
didn't know if there was an issue open somewhere else, but wanted to have this tracked somewhere.

**Comment by larsks** [comment]
I'll check in with the operate first folks.

**Comment by larsks** [comment]
But if the alternatives are "add nodes to smaug" vs "add nodes to ocp-prod", I would prioritize ocp-prod given the relative cluster sizes.

**Comment by joachimweyl** [comment]
Closing until more nodes are required.
