### ISSUE TITLE
create a github team to access certain private repo

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#493]
This came up because @joachimweyl does not have access to github.com/cci-moc/sprint-notes

**Comment by naved001** [comment]
I have added @joachimweyl directly so he's not blocked on it. Once we have a team, we can remove him.

**Comment by msdisme** [comment]
here are some examples where @joachimweyl is blocked:
https://github.com/orgs/CCI-MOC/projects/66#card-77812378
https://github.com/orgs/CCI-MOC/projects/66#card-77814356
https://github.com/orgs/CCI-MOC/projects/66#card-77810270

**Comment by larsks** [comment]
@msdisme it's not clear from those links in what way @joachimweyl is blocked. Can you update that comment with some details (or add comments to the issues)?

**Comment by larsks** [comment]
@joachimweyl is a member of the @CCI-MOC/ops team. That seems like it may be the right team to which we should grant access in most cases. What do other folks think?

**Comment by joachimweyl** [comment]
I also cannot edit any issues in xdmod-cntr

**Comment by larsks** [comment]
I think the `ops` team is the appropriate team in any case, so we can go ahead and close this issue.
