### ISSUE TITLE
Gather a guesstimate of the size of MOC for NERC migration

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#496]
- [x] @joachimweyl gather data from the survey
- [x] @joachimweyl learn enough OpenStack to gather the data below through CLI, according to @larsks [CLI script](https://github.com/joachimweyl/kaizen-stats) can pull at least server_count, flavor_ram, flavor_vcpus, volume_count, volume_size, floating_ips see [results spreadsheet](https://docs.google.com/spreadsheets/d/1tlYSmhvELI9Lz63u0WyhB3ntT7JAGsMhhATC8sz4TQQ/edit?usp=sharing) .
> - [x] How many projects there are? 22 (for now)
> - [x] How many instances need to be migrated?
> - [x] How many volumes need to be migrated?
> - [x] How many CPUs migrating projects are using?
> - [x] How much RAM migrating projects are using?
> - [x] FIP's used by each project?
> - [x] identify FPGA users/projects to migrate which may be non-BU or HU
> - [x] compare projects to data spreadsheet to provide only data for those 22 users, later we can get an updated list if needed when more clients reply to the survey
- [x] @joachimweyl provide data to NERC weekly meeting

**Comment by msdisme** [comment]
Separate topic, we should give them a heads up, we have a number of FPGA users from non BU/HU and are assuming other places to host them.

**Comment by joachimweyl** [comment]
Closing as Justin was happy with the data provided especially once we provided the spreadsheet with all of the data.
