### ISSUE TITLE
Figure out and document how to build windows server images for openstack

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#497]
A group from Harvard is interested in running windows on NERC openstack.

**Comment by larsks** [comment]
This might be useful: https://blog.oddbit.com/post/2014-11-15-creating-a-windows-image-for-o/

Because Windows is commercial software, we will also need to investigate the licensing issues involved in making it available in our cloud environments.

**Comment by naved001** [comment]
>  Alternately, we would need to figure out who is liable for license violations -- is the person running the image, or is it the cloud provider?

That is a good question. I guess we should be asking Microsoft this question?

**Comment by larsks** [comment]
> I followed the openstack documentation and was able to create a windows server 2022 image just fine.

But were you able to provision the administrative credentials from the cloud metadata? Because that's going to be the key feature we need if we're offering an image that other people can consume (rather than simply providing them with instructions how to create their own).

> That is a good question. I guess we should be asking Microsoft this question?

If BU has a microsoft rep, that would probably be the best place to start. @msdisme @joachimweyl is that something you folks can investigate?

**Comment by naved001** [comment]
> But were you able to provision the administrative credentials from the cloud metadata?

Yes, I tested this today. nova gave me the password for user `Admin` and then with that I could login via RDP. Looks like I had to explicitly allow RDP connections, so that's a change I'd have to make when preparing the image.

Yesterday I looked at the console and it asked me to create a password for the `Administrator` user and logged in that way.

**Comment by larsks** [comment]
My specific question is: If we provide a Windows cloud image for users of our cloud environment(s) to run, are *we* responsible for licensing Windows in that environment, or is the person deploying the image responsible for licensing the image?

**Comment by rob-baron** [comment]
I agree with larsks that we need to provide information as to how to obtain a valid license for our public cloud.

**Comment by msdisme** [comment]
The following makes it interesting - for BU users, currently, BU is actually an owner of the hardware.    Also, we are not officially a "public"  cloud in that it is not available to anyone.  

_Boston Universities licensing for Windows, Windows Server, SQL Server has a feature we call license portability. This allows BU to use your licenses on any hardware you own or is dedicated to BU’s use. Examples would be a VM cluster sitting in MGHPCC that only hosts BU workloads. Microsoft does not provide license portability to public cloud._

 I think how we ask this question is going to be important so @joachimweyl and @msdisme to discuss and capture here.

**Comment by msdisme** [comment]
@naved001 - is the issue that a group from harvard wants to do this on the MOC, or is the issue that Milson is asking what the appropriate thing to do is for NERC users?|

**Comment by naved001** [comment]
> or is the issue that Milson is asking what the appropriate thing to do is for NERC users?|

correct, that's what he's asking. And he was wondering how the MOC has handled in the past when we provided windows images.

**Comment by msdisme** [comment]
Discussed further with @joachimweyl , and reread the response.   
For Milson: Historically we have made images available, without licenses.  In order to use the images the user must provide a license.    This moves the "figure out the license" responsbility to the user who *should* have the most knowledge of their use case.

**Comment by naved001** [comment]
Milson documented this in detail here: 

https://nerc-project.github.io/nerc-docs/openstack/advanced-openstack-topics/setting-up-your-own-images/how-to-build-windows-image/
