### ISSUE TITLE
Connectivity on port 8880 between virtual machines in virtual rose project

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#499]
We spoke with @sleviim this morning about upcoming requirements for the virtual rose project. For their final session(s), they need students to be able to connect directly between virtual machines on port 8880. They've been unsuccessful doing this so far, so we need to investigate if we need to make any configuration changes to enable this connectivity.

**Comment by naved001** [comment]
sidenote: If their service is running on any other address besides the localhost, I imagine sshuttle could make it accessible.

**Comment by larsks** [comment]
@sleviim it *is* possible to connect directly between virtual machines, but you need to use the ip address of the [pod](https://kubernetes.io/docs/concepts/workloads/pods/) that contains the virtual machine, which is going to be a slightly non-obvious process: for a given virtual machine (say, "lars"), you would get the appropriate value by running:

```
kubectl -n vr2-fall2021-virtualrose2021 get pod -l kubevirt.io/domain=lars -o jsonpath='{.items[0].status.podIP}{"\n"}'
```

That's not terribly convenient.

A better solution is to modify the [Service](https://kubernetes.io/docs/concepts/services-networking/service/) objects we created and add port 8880 to the list of exposed ports. That is, we update the service definitions to include a new port definition:

```
- name: rose
  port: 8880
  protocol: TCP
  targetPort: 8880
```

I've modified all the existing services with the following steps:

1. I placed the following content in a file `patch.yaml`:

    ```
    spec:
      ports:
      - name: rose
        port: 8880
        protocol: TCP
        targetPort: 8880
    ```

2. I applied this patch to all the existing services by running:

    ```
    kubectl get service -o json |
      jq '.items[]|.metadata.name' -r |
      xargs kubectl patch --patch-file=patch.yaml service
    ```

With this change, you should be able to connect to port 8880 using the appropriate service name. For example, to access a service on the "lars" vm running on port 8880, we would connect to the hostname `lars-vm-service`:

```
$ curl lars-vm-service:8880
<pre>
# Virtual rose project test page

If you can see this content you have successfully connected to
the "lars" vm on port 8880.
__   __          _
\ \ / /_ _ _   _| |
 \ V / _` | | | | |
  | | (_| | |_| |_|
  |_|\__,_|\__, (_)
           |___/
</pre>
```

Let me know if you have any questions.

**Comment by larsks** [comment]
@sleviim just wanted to check in and see if you had a chance to test this out.

**Comment by sleviim** [comment]
Hi @larsks,
Thanks for checking :)
We had no chance to verify it yet, as we're thinking this is might not be completely what we meant to.
While running the competition, we have only 1 server session running on port 8880 (usually it was on my own laptop), and each student, from his machine, was able to connect my running server with the specified command:
./rose-client -s <my-ip> <the-student-driver-file>.py
So the students don't need to use the 8880 port on their machines and run the server as well - only connect to mine.

IIUC, by opening the 8880 port, the students can access the running server on the other machines, 
but we can't specify it using 'one single command on terminal' so student2 can connect to student's1 server with student's2 file, so both cars would run on "the same road- student's1 road".
In the competition phase, in case I'm connecting to one of the unused VMs and using server tunneling to broadcast the server, I think we still can't use the open service to allow the students to run their own file driver on that VM.
wdyt?

**Comment by larsks** [comment]
@sleviim I apologize; I'm not able to follow your last comment. It's unclear to me if things are configured the way you want or not, or if you've encountered some sort of difficulty. As things are configured right now, you are free to connect between all the virtual machines on port 8880. Is there something you're not able to do at the moment?

**Comment by sleviim** [comment]
@larsks I'm not sure how the configuration helps me to deal with the problem of running the file from 1 VM on the other VM where the server is actually running.

For example:
- The server is running on VM 128.52.61.139 with ./rose-server
- I can view the running server on my local comp by using:
  ssh -L 8880:127.0.0.1:8880 centos@128.52.61.139
- Player 1 wants to run his driver john.py on the running server on a different machine
  According to the readme, he should execute on his VM something like:
  ./rose-client -s 128.52.61.139 john.py
- Now the desired outcome should be john is running his client on a different server.
- After his turn is done, he needs to disconnect (ctrl+c) his client so the other competitor jane.py should be able to do the same.

**Comment by larsks** [comment]
> I can view the running server on my local comp by using:
> `ssh -L 8880:127.0.0.1:8880 centos@128.52.61.139`

This will tunnel port 8880, yes, but it's no longer necessary. For example, try connecting to http://128.52.61.134:8880; that's my test VM and you'll see you can access that service without any tunneling in place.

> Player 1 wants to run his driver john.py on the running server on a different machine (128.52.61.139)
> According to the readme, he should execute on his VM something like: 
> ```
> ./rose-client -s 128.52.61.139 john.py
> ```

This should work just fine.

**Comment by sleviim** [comment]
> This will tunnel port 8880, yes, but it's no longer necessary. For example, try connecting to http://128.52.61.134:8880; that's my test VM and you'll see you can access that service without any tunneling in place.
Cool :)

> This should work just fine.
I've tried that but it doesn't work for me (attached screenshot [1])
In this example, the server is running on http://128.52.61.139:8880/
Tried to run the driver file from VM 128.52.61.145
`./rose-client -s 128.52.61.139 mydriver.py`

As seen in the screenshot, the driver is not there.
[1] https://imgur.com/a/uiGlEpK

**Comment by larsks** [comment]
@sleviim can you install my ssh key (https://github.com/larsks.keys) on those hosts so that I can log in and take a look?

**Comment by sleviim** [comment]
@larsks added it to the ~/.ssh/authorized_keys file in those 2 VMs
(VM 145 is currently in use by the student so please avoid removing files :))

**Comment by larsks** [comment]
@sleviim I still don't understand the problem.

If I log into 128.52.61.139, there's nothing currently listening on port 8880.

On 128.52.61.145 I see that there is a service running, and I can access that from 128.52.61.139 without a problem:

```
$ ssh centos@128.52.61.139
[...]
[centos@ayenachew ~]$ curl maorg-vm-service:8880
<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8">
    <title>ROSE Game</title>
    <link rel="stylesheet" type="text/css" href="game.css">
  </head>
[...]
```

If I start a service on port 8880 on 128.52.61.139...

```
[centos@ayenachew ~]$ podman run --rm -p 8880:8080 docker.io/alpinelinux/darkhttpd
```

I can reach that service from 128.52.61.145 without a problem:

```
[centos@maorg ~]$ curl ayenachew-vm-service:8880
<html>
<head>
 <title>/</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
```

And I can reach both from home without a problem. Do you want to hop
on a call to explore this further? I feel like there must be some
miscommunication going on because I can reproduce any sort of problem
either connecting between virtual machines or connecting to virtual
machines from outside the cluster.

**Comment by larsks** [comment]
@sleviim the problem appears to be that in addition to the web service on port 8880, the game also communicates between the client and server on port 8888, and this port was blocked in your firewall configuration.

You will need to run the following command on all the virtual machines:

```
$ sudo firewall-cmd --zone=public --permanent --add-port=8888/tcp
$ sudo firewall-cmd --reload
```

With this change in place, I'm able to see a driver show up in my browser when I connect from one machine to another.

**Comment by sleviim** [comment]
Thanks, @larsks!
