### ISSUE TITLE
find out everything about engage1 hardware

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#5]
We need to figure the physical location of all engage1 hardware (switches, ceph nodes, the computes).

**Comment by msdisme** [comment]
from trello: BU rackspace but on csail - also in kaizen - discussion about how to approach - chris hill - engage 1 bu cage, MIT provides coverage. also garrett - discussion

**Comment by naved001** [comment]
part of this issue was addresses by: https://github.com/CCI-MOC/documentation/pull/94

Michael is opening a ticket for his comments.

Information about PDU and some broken severs is being tracked on a different issue: https://github.com/CCI-MOC/ops-issues/issues/23
