### ISSUE TITLE
Create team mailing list and use it

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#503]
Let's create a team mailing list and use that when we want to sent out email communications to the team, rather than relying on a Cc: list. It's easy to accidentally exclude someone from email when manually maintaining a list of recipients like that.

**Comment by joachimweyl** [comment]
@msdisme is this blocked by something if so what?

**Comment by joachimweyl** [comment]
ops-chat@lists.massopen.cloud currently gets sent to junk. we need to make sure everybody tells their mail system it is not junk.

**Comment by msdisme** [comment]
Kristi points out in junk, so we all need to fix that.  Question for 2:30 is why did it come from ops-chat <ops-chat-bounces@lists.massopen.cloud>.

**Comment by msdisme** [comment]
Working As Designed :-)
