### ISSUE TITLE
Platform for Shaw University

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#506]
Prof. Benjamin Branch at Shaw University is looking for a hosted Linux platform for a group of 5-10 students to get exposed to devops, software development, etc. They have asked us if we can provide an appropriate environment.

**Comment by msdisme** [comment]
@joachimweyl do we need a follow up discussion/demo or is this being done via email exchanges?

**Comment by joachimweyl** [comment]
Yes, I am in the process of scheduling a demo meeting. I need to push again to get avalability. Thank you for the nudge.

**Comment by larsks** [comment]
Demo was successful and we are moving forward with the project. Closing this issue for now; we can open more specific ones as necessary.
