### ISSUE TITLE
netbox pvc is low on space

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#514]
There's an alert:

> PVC netbox-pgha1-pmfh-pgdata utilization has crossed 85%. Free up some space or expand the PVC immediately.

@larsks is there a gitops way to expand PVC size?

If I change the size in the [original manifest](https://github.com/CCI-MOC/moc-apps/blob/master/netbox/overlays/ocp-prod/postgresclusters/netbox.yaml#L16) would it delete and recreate it?

**Comment by larsks** [comment]
@naved001 based on [this document](https://docs.openshift.com/container-platform/4.9/storage/expanding-persistent-volumes.html) I believe we can just update the size in the PVC manifest. That should be pretty easy to test, so I'm going to create a pvc and pod and test it out.

**Comment by larsks** [comment]
But! The PVC is already 15GB, and it seems unlikely that we're actually consuming that much space with netbox data. Investigating one of the database pods, I see:

```
bash-4.4$ cd /pgdata
bash-4.4$ ls
lost+found  pg13  pg13_wal
bash-4.4$ du -sh *
16K     lost+found
76M     pg13
8.4G    pg13_wal
```

So the actual data is only consuming about 76MB, and the remainder is postgres write-ahead logs. I'm still going to try the pvc resize experiment, but I suspect the solution here is to find the necessary configuration in the PGO operator to expire old WAL files.

**Comment by naved001** [comment]
> The PVC is already 15GB

that's `netbox-repo`. The 2 `netbox-pgha1` are 10GBs.

```
naved@Naveds-MacBook-Pro ~ % oc get pvc
NAME                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                           AGE
netbox-pgha1-pmfh-pgdata   Bound    pvc-0b594066-356d-4930-bbb6-2df67f4f371c   10Gi       RWO            ocs-external-storagecluster-ceph-rbd   122d
netbox-pgha1-pwpb-pgdata   Bound    pvc-724e4f25-a12d-4f4b-a839-66c973a0bb26   10Gi       RWO            ocs-external-storagecluster-ceph-rbd   122d
netbox-repo1               Bound    pvc-8f2f8599-65e5-42b1-9f58-7ad81b1d4220   15Gi       RWO            ocs-external-storagecluster-ceph-rbd   122d
redis-cache-data           Bound    pvc-524382c7-f3ab-48d4-a54b-f42806db7ed2   5Gi        RWO            ocs-external-storagecluster-ceph-rbd   128d
redis-data                 Bound    pvc-46466712-9266-44da-8643-e7f83efdfd91   5Gi        RWO            ocs-external-storagecluster-ceph-rbd   128d
```

> PGO operator to expire old WAL files.

okay, makes sense.

**Comment by larsks** [comment]
The out-of-space situation was caused by failing backups (so WAL files were never expired). Details and resolution in #515.
