### ISSUE TITLE
OCP deployed on Power 9

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#52]
- [ ] @naved and Rubicon on VLANs

**Comment by larsks** [comment]
@msdisme Is the task above "schedule a meeting between Naved and Rubicon team", or is it something else? And is this issue relevant? I wasn't clear if it was real or not based on this morning's meeting.

**Comment by naved001** [comment]
I think the VLAN stuff was just an example of what they might need help with. And for questions, I think they will be opening an issue on github instead of having a meeting for Q&A.

**Comment by larsks** [comment]
@naved001 so we should just get rid of this issue?

**Comment by naved001** [comment]
Yes, I'll go ahead and do that.
