### ISSUE TITLE
Review current mailing lists in mailman

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#523]
- [x] #524
- [x] #525
- [ ] #527
- [ ] #528
- [ ] #529

**Comment by joachimweyl** [comment]
@msdisme as this is already broken down into its individual parts, I would like to suggest adding the milestone label, closing this Issue, and letting the MOC MailMan List Review Milestone manage to hold these issues together. This Issue as far as I can tell no longer provides value.

**Comment by joachimweyl** [comment]
Closing as this is tracked by https://github.com/CCI-MOC/ops-issues/milestone/15
