### ISSUE TITLE
Generate list of all mailing lists in mailman

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#524]

**Comment by larsks** [comment]
We are currently hosting 38 mailing lists:

- `admin` - `Admin` list `used` for `service` registrations
- `alerts` - `All` Alerts List
- `bmi` - `BMI` devlist
- `bulletin` - `Global` notification `list` containing `users` and `other` lists
- `cephalerts` - `Ceph` alerts `from` all environments
- `CNV-Users` - `Mailing` list `for` users `of` the `MOC` CNV `sandbox` cluster.
- `Collab` - `Coordination` for Collaboratory
- `delivery` - `List` for `delivery` notifications
- `e1-notifications` - `Engage1` users notifications
- `esi` - `Mailing` list `for` Elastic `Secure` Infrastrucutre ```` team
- `floatingip` - `Mail` list `for` communication `of` floating `ip` changes
- `giji` - `The` interface `for` dummies
- `guss-details` - `[no` description available]
- `guss-discuss` - `[no` description available]
- `hil` - HIL
- `infra` - `Requests/Support` for `Engage1,` Kumo, `any` others `except` Kaiz
- `jobs` - `Jobs` postings
- `kaizen` - `Requests/support` for Kaizen
- `kaizen-users` - `Kaizen` users list
- `kaizenbm` - `List` for `Kaizen` bare `metal` communication
- `kumo` - `For` users `of` kumo `bare` metal environment
- `kumo-users` - `All` users `of` kumo `baremetal` are here
- `Lars-test-list` - `[no` description available]
- `Mailman` - `Mailman` site list
- `moc-core-partners` - `Partners` list
- `onboarding` - `Adjutant` notifications
- `openshift_i386` - `List` for `users` of `Kaizen` i386 openshift
- `openstackadmins` - `All` openstack `environments` administration related
- `Operate-first-users` - `[no` description available]
- `ops` - `OPS` Team
- `ops-chat` - `Operator` chat `(no` automated alerts)
- `osticket` - `List` for `full` ticket notifications
- `redhat-moc` - `See` list name
- `rootmail` - `Mail` send `to` root `on` nodes `-` logs,alerts,etc
- `seccloud` - `Secure` cloud
- `shiftalerts` - `List` name `says` it all
- `ssoalerts` - `Single` sign `on` alerts
- `team` - `MOC` team

**Comment by joachimweyl** [comment]
done.
