### ISSUE TITLE
Generate list of all people and links in each mailing list

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#525]
Generate list of all people and links in each mailing list

**Comment by larsks** [comment]
What do you mean by "links"?

**Comment by larsks** [comment]
List of all mailing lists, owners, and members (in MOC OPS shared drive): https://docs.google.com/document/d/1Xb1tfN6ODWunJTgYQDUxKLNI2ySDFCpB3evTo-2lTas/edit
