### ISSUE TITLE
identify mailing lists which may be removed

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#526]
identify mailing lists which may be removed

**Comment by joachimweyl** [comment]
@msdisme what is the status of this and can any of this be delegated to me?

**Comment by joachimweyl** [comment]
@msdisme this should be added to an epic. Please create the epic and add it.

**Comment by msdisme** [comment]
@naved001 I feel like you already did this as part of spring cleaning - close?

**Comment by naved001** [comment]
@msdisme I think it's mostly clean. We can revisit for another spring cleaning next year.
