### ISSUE TITLE
Create MOC Meeting Best Practices Document/s

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#530]
In an effort to maintain a homogeneous understanding of what we as a team expect the team as a team and as individuals will bring to each of our meetings. We wish to ensure that all ideas are heard, the team comes up with out-of-the-box resolutions, and that we are efficient. To that end here are some documents that we can use to stay on the same page.

- [x] @joachimweyl [Draft](https://docs.google.com/document/d/11qYvQ5c3nxHeyy8ByOzp4Wu1kewJNZOC_3gMTk5aMsU/edit?usp=sharing) a Meeting Best Practice document.
- [x] team reviews documentation review documentation
- [x] @joachimweyl implements ideas/suggestions/modifications
- [x] @joachimweyl break document into multiple documents to make them more streamlined
- [MOC Meeting Aspirations](https://docs.google.com/document/d/1BebM-XaiDXbktrDSfZTsfvEoxh63tx9zF1nwpTAg6hc/edit?usp=sharing)
- [MOC Meeting Best Practices](https://docs.google.com/document/d/1otPqUrKmEE-6JR2PPFRS9e4o4ImguEN00Lje8KsMbzk/edit?usp=sharing)
- [MOC Meeting Tools](https://docs.google.com/document/d/1BsI_sgE_f_Yo_Vt3OyoRm9EU3fcqI484EOVKGKQEtsA/edit?usp=sharing)
- [x] @joachimweyl decide with team where to put these
- [x] @joachimweyl put them there

**Comment by joachimweyl** [comment]
- [ ] @larsks - reviewed
- [ ] @rob-baron - reviewed
- [ ] @knikolla - reviewed
- [ ] @naved001 - reviewed
- [ ] @msdisme - to review by end of week

**Comment by larsks** [comment]
For these docs I would actually suggest our ops policy repository, https://github.com/CCI-MOC/ops-docs.

**Comment by joachimweyl** [comment]
https://github.com/CCI-MOC/ops-docs/specs has a lot of pre-formating. What are your thoughts on a second folder /practices with a less formatted template?

**Comment by msdisme** [comment]
that seems reasonable to me

**Comment by joachimweyl** [comment]
https://github.com/CCI-MOC/ops-docs/pull/18
