### ISSUE TITLE
Evaluate network connection Kaizen to NERC

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#533]
~~Work with Wayne and Scott to decide how best to optimize the network connection between Kaizen and NERC so that we facilitate a clean and fast transition for the Migration to NERC~~

Our current migration steps will require data to traverse a persons local (probably home) internet connection, which may be quite slow for larger volumes. Let's test the connectivity between Kaizen and NERC by running the migration from a virtual machine deployed in one of those two environments. Use the results from that tests to decide whether or not we need to make changes in connectivity between the two environments.

**Comment by larsks** [comment]
@joachimweyl verified that running the migration from a MOC-hosted VM is substantially faster than running the migration from home.
