### ISSUE TITLE
MOC to NERC Migration Documentation communication

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#535]
- [x] Blocked on #495
- [x] Blocked on #635
- [x] Review [responses](https://docs.google.com/spreadsheets/d/1WKhXo295n8vAI4Liqo2tRHyYnOFXxlv-ZjjLsy--llE/edit?usp=sharing)
- [x] Gather list of volume size/s for [Responces](https://docs.google.com/spreadsheets/d/1Ke1VaKgL3M7bOlg9bGAYtNDhJMV1zh01HVUpo1J1WNE/edit?usp=sharing)
- [x] @joachimweyl provide a current list of projects that want to migrate to the NERC based on indicated desire to move to the NERC in response to the survey.

**Comment by joachimweyl** [comment]
@msdisme this is on the NERC site do we want a reference to it on the MOC or OSticket?

**Comment by msdisme** [comment]
Add to Osticket as a link to NERC site to avoid versionitis, IMHO.  also, promoted osticket faq and make sure osticket faq can be viewed even if user does not log into osticket

**Comment by joachimweyl** [comment]
The knowledge base is available without logging in.
Here is the new [OSticket KB](https://osticket.massopen.cloud/kb/faq.php?id=27).

**Comment by msdisme** [comment]
Updated note: 
Subject: MOC Kaizen OpenStack Cluster Migration Survey

We launched the Mass Open Cloud (MOC) with a vision of creating a production cloud that would enable innovation by a broad industry and research community.  

The MOC has successfully supported hundreds of projects supporting thousands of users, transitioned research projects into upstream software artifacts, and formed a community of interrelated research projects.

One of those projects is the New England Research Cloud ([NERC](https://nerc.mghpcc.org/)), a production cloud with professional operations and a team of experienced facilitators.   The NERC supports OpenStack users today. With that in mind, the MOC Kaizen OpenStack Cluster will be phasing out of commission in August 2022.

If you are interested in relocating your projects to the NERC OpenStack Cluster please fill out this [user survey.](https://docs.google.com/forms/d/1Z_8eTmqnplIR-Q56UtgwiTVRFM38ZSZTIfpDAaJzcO8/edit)

Michael Daitzman

PS – If you were forwarded this email from a colleague and would prefer to receive these notifications directly, you may sign up for the kaizen-users mailing list by sending an email to: [kaizen-users-join@lists.massopen.cloud](mailto:kaizen-users-join@lists.massopen.cloud)

**Comment by joachimweyl** [comment]
@msdisme since we are still moving people one at a time because of the Swift issue, I would suggest that we don't update the MOC website with instructions on migrating and just let Milson manage the Migrations as he wishes. Thoughts?

**Comment by joachimweyl** [comment]
Break this down further and only keep the items you are going to do in this sprint.

**Comment by msdisme** [comment]
Seems reasonable

**Comment by joachimweyl** [comment]
Closing and opening multiple issues to resolve the last parts.
#674 , #675, #676, #677
