### ISSUE TITLE
Update massopen.cloud/people

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#536]
The page at https://massopen.cloud/people/ lists people who are no longer part of the organization and also has some placeholder values there that should probably just be removed. We should update this page to correctly represent the current members of the organization.

**Comment by msdisme** [comment]
test for tara notifications

**Comment by taramoran** [comment]
jen has been removed from this page. the rest of the page will be updated in an ongoing redesign of the website

**Comment by joachimweyl** [comment]
This will be managed by Tara in the overhaul.
