### ISSUE TITLE
Add process for FPGA MOC access MOC web page

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#538]
Wayne Gilmore Michael how does one go about getting access to OCT resources?  Do they just apply for an MOC project?
1:49 PM
msd:spiral_calendar_pad: nope, here are the details:
1:50 PM
https://cloudlab.us/ - click on Request an account (green button)

cloudlab.uscloudlab.us
CloudLab
Website for CloudLab
1:50 PM
I can also get you some videos on it.  if they are doing FPGA research, slightly different path
1:50 PM
Wayne Gilmore this is for FPGA (from engineering)
1:52 PM
msd:spiral_calendar_pad: Ahh-sorry.  They apply for an MOC account and list Suranga Handagala as a contact point.    Suranga ran a class on using the xilinx emulator from MOC account (I can get you a video I believe).
1:52 PM
if it is for intel fpga, a bit more handholding is involved
1:53 PM
and we just ask them to send mail to support@massopen.cloud and work on it.
1:53 PM
via Martin if they need assitance beyond “here is a machine with an fpga for you”
1:53 PM
the intel ones in MOC are older generation
1:54 PM
fpgas
1:54 PM
Wayne Gilmore he specifically mentioned OCT so perhaps these are the newer ones.
1:55 PM
msd:spiral_calendar_pad: (hmm.   I just created a github ticket (in my mind for the moment)to document this better and put it on the MOC page.  also need to make sure they have started trying the xilinx tools in openshift

**Comment by msdisme** [comment]
@Suranga Handagala <s.handagala@northeastern.edu> - I think we probably need an assist from you on how to do this, links to tutorials etc. Not sure of your github id

**Comment by msdisme** [comment]
@s.handagala@northeastern.edu, @pjd-nu we need an update on what to tell folks re. fpga

**Comment by surangamh** [comment]
We have the OCT tutorials [here](https://github.com/OCT-FPGA/OCT-Tutorials).

**Comment by joachimweyl** [comment]
remvoed
