### ISSUE TITLE
Update Documentation Link on Mass Open Cloud website

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#546]
https://massopen.cloud/
-User Resources > Documentation goes to https://docs.massopen.cloud/en/latest/home.html# should go to https://docs.massopen.cloud/en/latest/

**Comment by larsks** [comment]
I've corrected the link in the user resources menu.

**Comment by joachimweyl** [comment]
Holy cow that was fast, thank you for getting to this with lightning speed!
