### ISSUE TITLE
fix siteground nameservers for octestbed.org

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#549]
SiteGround
New DNS service for your site(s) now active
Hello Michael,
We have identified that some of your domains that are not registered with SiteGround may still be using legacy name servers that need to be updated as the support for your current name servers will be gradually discontinued starting next month. In order to avoid any downtime, please update your name servers as soon as possible.

New nameservers you need to use:

ns1.siteground.net (75.2.77.104)
ns2.siteground.net (99.83.229.113)
NOTE: Please use the IPs only if this is required by your registrar, in most cases only the name servers (ns1.siteground.net and ns2.siteground.net) are required.

Domains that need а name server update:
octestbed.org

Why is the update needed?
Last year we introduced a new central DNS service, which has a great impact on boosting our clients' website loading speed. Since the activation of this service, the recommended name servers for all our customers are ns1.siteground.net and ns2.siteground.net.
The name servers your domain name is currently using are based on the specific name of your host server, which is a legacy setup from the time before the central DNS. These legacy name servers will be gradually discontinued and we recommend that you update your name servers by May 31, 2022, as otherwise, you may start experiencing service interruptions when the old DNS stops working.
If you need assistance with updating your DNS settings, you may refer to our Help Center > Domain > I want to point my website to SiteGround.
Consider domain transfer to SiteGround
If you prefer to have such DNS changes handled automatically by us on your behalf, you may consider transferring your domain name from your current registrar to SiteGround. You can check if your domain can be transferred and start the transfer process at:
https://my.siteground.com/extras/domain-transfer
Thank you for your understanding and cooperation!
Regards,
The SiteGround Team
You are receiving this email because you are a SiteGround customer. 
SG Hosting Inc., 901 N. Pitt St, Suite 325, Alexandria, 22314 VA, USA

**Comment by msdisme** [comment]
currently octest hosted at godaddy.  May be worth moving to siteground, need to evaluate usagte etc./

**Comment by msdisme** [comment]
feedback from Hakan, perference to keep at godaddy.   @hakasapl did you already fix this?

**Comment by msdisme** [comment]
@hakasapl - is this ready to be closed?

**Comment by hakasapl** [comment]
This is fixed. Nameservers on the GoDaddy side have been updated
