### ISSUE TITLE
Look into the nodes in OCT4 racks

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#55]
Hakan has racked and connected a bunch of nodes in OCT4. I have the mac addresses for the ipmi controller, I need to make sure that everything works as expected.

**Comment by hakasapl** [comment]
Are these the intel nodes? I thought we had set those up already?

**Comment by naved001** [comment]
I mean, I have to take a look at it and make sure that things are all good. I haven't had the time to configure any of that. This is mostly on me for now.

**Comment by naved001** [comment]
I did the looking.

https://github.com/CCI-MOC/ops-issues/issues/220#issuecomment-819508669
