### ISSUE TITLE
Set up Account for massopen.cloud contacts email

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#555]
In order to make some changes for email addresses used by the website I would like to have access to the admin account on roundcube.

**Comment by naved001** [comment]
I don't think roundcube has an admin panel. 

I can give you access to the host that's running roundcube but don't know if it'd be of much help.

**Comment by msdisme** [comment]
A couple of use cases I am trying to solve for; 
1. a contact@massopen.cloud which forwards to supporpt@massopen.com.  I suppose we could use the support address but it is less "bueno".
2. An email account that forwards to a group of admins for when we sign up for asana, for example, so that they may all be notified.
3. An account for myself

Longer term, we should figure the site out a bit more and perhaps migrate once it is not central to so many of our processes, but that would be a different ticket.

**Comment by joachimweyl** [comment]
@msdisme please mark this as closed assuming we don't have a problem with "haven't figured out how to make it forward in RoundCube."
