### ISSUE TITLE
MGHPCC: Replace drives in neu-5-15

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#556]
2 drives need to be replaced on this host. These are 10TB drives. Drive that need to be replaced are in slot 7 and slot 10.

neu = Row3 Pod B.
5-15 = Cage 5 Unit 15. It's a dell poweredge R730XD (2U).

<img width="829" alt="image" src="https://user-images.githubusercontent.com/20113064/166126210-bada0148-fbac-484f-978a-1438052deff4.png">

**Comment by msdisme** [comment]
@hakasapl can you let us know where the 10tb drives are and we can have techsquare do the swap

**Comment by hakasapl** [comment]
The 10TB drives are in the MOC cage, in one of the boxes, there are a few boxes of drives there

**Comment by naved001** [comment]
Cool, the drives were replaced and I created the OSDs on those. All OSDs are up.

Sidenote: The replacement drive that's plugged into slot 7 is predicted to fail soon. 

```
[root@kzn-osd07 ~]# smartctl -a /dev/sdi -d megaraid,7
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.0-1160.31.1.el7.x86_64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HGST
Product:              HUH721010AL5200
Revision:             LS17
Compliance:           SPC-4
User Capacity:        9,796,820,402,176 bytes [9.79 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
Formatted with type 2 protection
8 bytes of protection information per logical block
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000cca26631e47c
Serial number:        7JGWEM0G
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Wed May  4 12:05:20 2022 EDT
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported

=== START OF READ SMART DATA SECTION ===
SMART Health Status: FAILURE PREDICTION THRESHOLD EXCEEDED: ascq=0xfd [asc=5d, ascq=fd]
```

![image](https://user-images.githubusercontent.com/20113064/166723883-b9e6ad53-9419-4d26-a9a0-4b1bbd673a45.png)


@msdisme @hakasapl Should we get a refund for this drive? It's running fine for now, but according to SMART it's predicted to fail soon.
