### ISSUE TITLE
Identify all SAIL projects

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#557]
Working with SAIL to attempt to identify all SAIL projects. [Here](https://bushare-my.sharepoint.com/:w:/g/personal/msd_bu_edu/EcdDihnUHkBBlje3pS-YGNYBOSsF5wHdKv7x8vu9NCN5Lg?e=Uffol7
) is a limited access SharePoint document for the SAIL team to provide a list of all email addresses associated with projects.

- [x] Gather a list of projects with the string "SAIL" in them.
- [x] Also list of project names
- [x] Gather a list of SAIL email addresses
- [x] Gather list of projects with SAIL in the description
- [x] provide list to SAIL

**Comment by msdisme** [comment]
@asadeg02@bu.edu @simeon@bu.edu @willtj@bu.edu - if you can add project names and SAIL historical employee to the sharepoint document above we can search.

**Comment by msdisme** [comment]
from Jeff:
The project names are as follows (though they may be called something different in GitHub).
fNIRS Cloud
BWWC Calculator
ABLE
SudTraining (test deployment)

There may be others, those are the ones Jeff is aware of.

**Comment by joachimweyl** [comment]
I could not find any projects with these names but I did find similar instance names under the SAIL project. 
FNIRS – active  
Calculator – active 
samsha – active 
BWHS – active 
ABLE-prod - shut off

**Comment by joachimweyl** [comment]
[Doc](https://bushare-my.sharepoint.com/:w:/g/personal/msd_bu_edu/EcdDihnUHkBBlje3pS-YGNYBOSsF5wHdKv7x8vu9NCN5Lg?e=Uffol7) updated with the project list.

**Comment by joachimweyl** [comment]
Waiting for confirmation from SAIL that this is what they wanted.

**Comment by joachimweyl** [comment]
sent another email to confirm this was the list they expected.

**Comment by joachimweyl** [comment]
Still no response from SAIL. Pretty sure I found all of the projects based on the information they provided. As this ticket is merely to identify the list I am going to consider this closed. We can deal with further communications from SAIL as they come.
