### ISSUE TITLE
google poll, "do you want to migrate" given OCP 3.11 going away. . . .

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#558]
Create google poll for users of OCP 3.11 users to identify if they are still active and want to migrate given kaizen is sunsetting roughly end of june.

**Comment by taramoran** [comment]
We are not anticipating a branding shift before May 20th.

**Comment by naved001** [comment]
> poll no longer needed.

@joachimweyl do we know why?

**Comment by joachimweyl** [comment]
> @joachimweyl do we know why?

It was a Backlog Grooming decision. I am trying to remember what the decision was based on. I honestly can't remember the reason. @msdisme as this was assigned to you is there any chance you remember why the backlog grooming decision would have been that we no longer needed the poll? Had we already communicated with users, had we already found out there were no users left?
`Note to self to add more details to closing comments.`
