### ISSUE TITLE
Investigate alerts from ocp-prod

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#559]
![image](https://user-images.githubusercontent.com/20113064/166510909-0a1069c6-6fc1-4c99-8dd1-de39bb05fd4a.png)

Even since I added the new nodes I have been receiving alerts from ocp-prod (PodDisruptionBudgetLimit).

**Comment by naved001** [comment]
Not sure if it's related to these alerts, but I decided to take a look at what's going on. There are bunch of pods in error state in `netbox` namespace with pgbackrest failing to start. Looking at the logs:
```
naved@Naveds-MacBook-Pro ~ % oc logs netbox-pgha1-bc2z-0 pgbackrest
ERROR: [048]: invalid command 'server'
```
let me to this thread here: https://github.com/CrunchyData/postgres-operator/issues/3187

**Comment by joachimweyl** [comment]
@naved001 is upgrading to `ubi8-2.38-0 image` an option for us?

**Comment by naved001** [comment]
I guess, that's what the thread I linked suggests. Maybe we'll do it once we have a functioning cluster back up.

**Comment by naved001** [comment]
all these alerts are of the form "X has disappeared from Prometheus target discovery". 

I am looking at one specific alert about kubelet disappearing that led me to this solution: https://access.redhat.com/solutions/6116721 which suggests the root cause is "clusterNetwork and serviceNetwork CIDR overlaps." but in our case they don't overlap so still figuring out.

**Comment by naved001** [comment]
I opened a sev4 support ticket with redhat https://access.redhat.com/support/cases/#/case/03261680

**Comment by naved001** [comment]
latest response form redhat support

> We've found the issue. Prometheus PV is 100% utilized for both the pods due to which new metrics are not getting scraped.
> 
> /dev/rbd1        49G   49G     0 100% /prometheus
> /dev/rbd0        49G   49G     0 100% /prometheus
> 
> I would suggest you to either cleanup the data /prometheus as a workaround or provision a new volumes with more size or reduce the retention of metrics.
> 
> Currently, you have not set any retention which means data is retained for 15 days. You configre the retention using below documentation:
> [-] https://docs.openshift.com/container-platform/4.9/monitoring/configuring-the-monitoring-stack.html#modifying-retention-time-for-prometheus-metrics-data_configuring-the-monitoring-stack
