### ISSUE TITLE
gracefully shutdown MOC services before MGHPCC shutdown

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#565]
there's an old document, but that doesn't cover all the services.

https://docs.massopen.cloud/en/archive-20220323/how-tos/MGHPCC-Shutdown.html?highlight=shutdown

**Comment by naved001** [comment]
@larsks :

smaug, moc-infra, openstack

@naved001 :

ocp-prod, ocp-staging, kumo nodes, all elastic nodes, maas nodes, research ceph, production ceph cluster.

**Comment by naved001** [comment]
@larsks 

I am planning on doing whatever this document says to turn off the openshift cluster, does that seem right? https://docs.openshift.com/container-platform/4.9/backup_and_restore/graceful-cluster-shutdown.html

**Comment by larsks** [comment]
@naved001 that seems fine! If we don't have a list of what hardware comprises the cluster, consider dumping the output of `oc get nodes` somewhere first.

**Comment by larsks** [comment]
I've powered off everything in smaug, moc-infra, and kaizen openstack.

**Comment by naved001** [comment]
cool, I have also shutoff whatever needs to be powered off. the ovirt hosts and the hosted engine VM are left powered on.

**Comment by joachimweyl** [comment]
@naved001 as this issue is just for the power down do we need another one to bring them back up? I believe this issue can be closed?

**Comment by naved001** [comment]
@joachimweyl sure. I'll create an issue for that.
