### ISSUE TITLE
MGHPCC: oct4-11's idrac does not launch

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#568]
I can issue commands using ipmitool. I have cold reset the idrac using ipmitool but that hasn't helped. It used to work but not anymore.

**Comment by naved001** [comment]
OCT4 sheets has this message associated with this.
"PCIe/backplane failures, no idrac, spitting out tons of errors".

**Comment by hakasapl** [comment]
Not sure what the replacement part for this would be. Doing some research

**Comment by naved001** [comment]
I added a comment on netbox about this node having issues and linked this PR.
