### ISSUE TITLE
Order TPM 2.0 chips

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#571]
Ordering 2 initially: https://www.newegg.com/p/1WK-0025-007A7

#375 

This says it's a TPM 2 chip and is compatible with dell r730 (and we have r730xd in OCT4 rack). If that's true then that is what we may need. Since it's only $20 we could order one to test it ourselves if we can't get a confirmation from dell.

**Comment by joachimweyl** [comment]
@msdisme have these been ordered? Do we expect them to arrive before the end of this sprint?

**Comment by joachimweyl** [comment]
sitting in the shipping area at MGHPCC.
