### ISSUE TITLE
MGHPCC: Replace power supply in OCT4-04

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#572]
One of the power supplies have failed. This machine is being configured as an openstack controller for ESI.

**Comment by joachimweyl** [comment]
@naved001 is this something TechSquare is going to do for us? Do we already have a ticket with them to replace this power supply?

**Comment by naved001** [comment]
This is blocked on #590. I looked thorough the OCT sheets to see if there's a broken server with a compatible PSU (1100W) to put into this but did not find any. Looks like we'll have to wait for @hakasapl to be back before this is done.

**Comment by hakasapl** [comment]
Confirmed to be broken, reseat did not help. Looking for spares, if not we will have to order.
