### ISSUE TITLE
Power MOC hardware back on

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#575]
Some things need to powered on in the following order:

0. power on the hosts neu-17-40 and neu-19-40 because these provide storage for a bunch of VMs on ovirt. IPMI network can be access via any of ovirt hosts.

1. then VMs on ovirt cluster in this order. you'll need to use password from bitwarden to login as local user because freeipa isn't up at this point.

- [x] foreman
- [x] freeipa
- [x] dns resolvers
- [x] kzn-ipmi-gw, kzn-vpn, kzn-rtr
- [x] VMs running DHCP
- [x] rest of the VMs that we need.

2. the production ceph cluster.
- [x] monitors
- [x] OSDs (except a couple of nVME drives)
- [x] RGWs, iSCSI gateways
- [x] unset various flags on ceph

3. Openstack and various openshift clusters, the BMI servers

4. research ceph cluster 
- [x] the monitors are virtual on ovirt
- [x] then the OSDs
- [x] cache servers

then everything else

**Comment by naved001** [comment]
In the process of powering on the ceph cluster, some OSDs haven't come up. 2 out of 10 nvme drives that make the performance root haven't come online.

**Comment by larsks** [comment]
I've powered up the operate first clusters:

- smaug
- moc-infra

I've brought up the kaizen openstack controllers, but as expected I need to poke at the database before they become functional.

**Comment by naved001** [comment]
Closing this as most of the stuff is up and separate issues are open for exceptions.
