### ISSUE TITLE
2 out of 10 nvme on production ceph hosts are not coming online

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#576]
This makes the performance root unhappy.

on host `kzn-osd10`

```
[root@kzn-osd10 ~]# journalctl |grep -i nvme
May 25 02:25:33 kzn-osd10.kzn.moc kernel: nvme nvme0: pci function 0000:06:00.0
May 25 02:25:33 kzn-osd10.kzn.moc kernel: nvme 0000:06:00.0: irq 37 for MSI/MSI-X
May 25 02:25:33 kzn-osd10.kzn.moc kernel: megaraid_sas 0000:03:00.0: NVMe passthru support        : No
May 25 02:26:34 kzn-osd10.kzn.moc kernel: nvme nvme0: Device not ready; aborting initialisation
May 25 02:26:34 kzn-osd10.kzn.moc kernel: nvme nvme0: Removing after probe failure status: -19
May 25 02:26:38 kzn-osd10.kzn.moc smartd[1099]: Monitoring 0 ATA/SATA, 12 SCSI/SAS and 0 NVMe devices
```

on host `kzn-osd08`
```
May 24 22:47:40 kzn-osd08.kzn.moc kernel: nvme nvme0: pci function 0000:05:00.0
May 24 22:47:40 kzn-osd08.kzn.moc kernel: nvme 0000:05:00.0: irq 37 for MSI/MSI-X
May 24 22:47:40 kzn-osd08.kzn.moc kernel: megaraid_sas 0000:03:00.0: NVMe passthru support        : No
May 24 22:47:41 kzn-osd08.kzn.moc kernel: nvme nvme0: Shutdown timeout set to 10 seconds
May 24 22:47:41 kzn-osd08.kzn.moc kernel: nvme nvme0: Could not set queue count (16390)
May 24 22:47:41 kzn-osd08.kzn.moc kernel: nvme nvme0: IO queues not created
```

**Comment by naved001** [comment]
```
[root@kzn-mon1 ~]# ceph -s
  cluster:
    id:     ed141a90-e501-481c-90c2-b9e24a7c9b54
    health: HEALTH_WARN
            Degraded data redundancy: 5 pgs undersized
            clients are using insecure global_id reclaim
 ```
 
 data is degraded but it's all available, we should fix/replace the drives before any more failures.

**Comment by naved001** [comment]
Just to rule out anything to do with the OS or kernel version, I booted these servers with a different kernel version and then live ubuntu disk and they all had the same issue. I suspect the system detects the nvme controller but the drive is probably bad. @pjd-nu  just tagging you here in case you have any thoughts before we start the replacement process.

@msdisme @hakasapl 

The model number of these drives is `INTEL SSDPEDKX080T7`. These are 8TB drives. I got the serial number of one of the working SSDs and checked it on [intet's site](https://supporttickets.intel.com/warrantyinfo) and according to that they may have coverage until next year.

If we pull out the drives from the system then we can check those specific serial numbers and maybe process a return/replacement.

**Comment by naved001** [comment]
The host `kzn-osd08` is `Row3-PodB-Cage3-Unit15` and `kzn-osd10` is `Row3-PodB-Cage17-Unit21`. These both are 2U Dell R730XD. 

We'll need to pull out the Intel PCIe nvme SSD from both these systems and get their serial numbers to start returns/replacement. We want to keep the drives since we will likely have to ship these back.

I will power off the systems one at a time since they belong to a ceph cluster and I don't want to take off two systems at the same time.

**Comment by joachimweyl** [comment]
@naved001 I believe @hakasapl is at MGHPCC today, once the systems are powered down he should be able to do this.

**Comment by adamdrucker** [comment]
Hi all,

This is Adam from TechSquare @ the MGHPCC. 

To confirm steps being asked:
* remove nvme ssd's from the two machines cited above and retrieve their serial numbers -- should the drives be returned to their hosts, or kept elsewhere?
* do you happen to know if the hostnames are labeled on each machine? just incase, do you have the serial numbers for these so I can double check if necessary before removing drives?
* lastly, if these have both been powered off and are ready to have the drives pulled, I can get to this right away. if it works, I will comment again with the respective serial numbers for each drive for each machine.

**Comment by naved001** [comment]
Hi @adamdrucker 

> should the drives be returned to their hosts, or kept elsewhere?

Ideally elsewhere so we don't have turn them off again in case we end up shipping them to process returns. I don't know if there's any specific space to keep these drives. @hakasapl do you know any place to keep them? 


> do you happen to know if the hostnames are labeled on each machine?

I don't think these machines are labelled. 

>  do you have the serial numbers for these so I can double check if necessary before removing drives?

`Row3-PodB-Cage3-Unit15` should have service tag `2ZD7V52`, 
`Row3-PodB-Cage17-Unit21` service tag is `2ZDCV52`.

> lastly, if these have both been powered off and are ready to have the drives pulled,

I can only power off 1 machine at a time. I powered off `Cage3-Unit15`. Once you are done with that I can then ready the other machine.

Thanks again!

**Comment by naved001** [comment]
@adamdrucker Now that I am filling out the support ticket with Intel it looks like they may want me to attempt to recover the drive first (some firmware updates I guess) or collect additional logs. 

If you could put the drive back in the system that'd be helpful. For the second system, after you gather the ISN just put  it back in the system and power the system on. Then I'll power off the previous system for the drive to be put back in.

**Comment by adamdrucker** [comment]
@naved001 The second drive was just removed from 2ZDCV52. Here are the details:

Same model
ISN: PHLF802400398P0EGN

I will start by putting this drive back into that node, then power it on. I'll send a quick reply here, wait until the first one has been powered off then will return the first drive and power that node back on.

**Comment by naved001** [comment]
@adamdrucker sounds good!

**Comment by adamdrucker** [comment]
@naved001 The drive has been returned to 2ZDCV52 and it has been powered on.

Standing by.

**Comment by naved001** [comment]
@adamdrucker I powered off the other system.

**Comment by adamdrucker** [comment]
@naved001 The drive has been returned to the first machine and powered on

**Comment by naved001** [comment]
Thanks @adamdrucker!

**Comment by naved001** [comment]
Attempted firmware updates but that didn't work, so collected some additional logs and opened tickets with intel.

**Comment by joachimweyl** [comment]
Blocked on awaiting Intel's response.

**Comment by naved001** [comment]
Intel have said that they'll RMA both drives. We will have to ship them in return labels that they will provide. Once they have it, they then will send us the replacements. And apparently they are out of stock, so the whole process may take up to a month. 

@msdisme I am waiting on the mailing address of the Data Center. I know the address, just not sure who it needs to be addressed to.

**Comment by msdisme** [comment]
Mass Open Cloud Alliance, Hakan or TechSquare
c/o: MGHPCC
100 Bigelow St
Holyoke, MA 01040

**Comment by naved001** [comment]
Intel has provided the shipping labels. 

| Case no       | Serial Number     | Machine                | Service Tag|
| --------------| ------------------| -----------------------|------------|
| SWR# 05484125 | PHLF8024003C8P0EGN| Row3-PodB-Cage3-Unit15 |  2ZD7V52   |
| SWR# 05484131 | PHLF802400398P0EGN| Row3-PodB-Cage17-Unit21|  2ZDCV52   |


The drives need to be shipped separately, with the correct Case number written on the box, and a copy of the email that intel sent me in the box along with the drive. 

I will send an email out to techsquare if they can ship it for me.

**Comment by naved001** [comment]
The drives have been extracted and packaged to be shipped today. I am going to close this issue and open another one to track putting in new drives and creating the OSDs on them.
