### ISSUE TITLE
Figure out what's up with the mac addresses of idrac with the FPGA nodes in OCT3 and setup the 10G networking if needed

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#58]
@hakasapl had racked a couple of nodes, but the mac addresses I see are different than what Hakan expects. Need to investigate this and close the loop.
Also, configure the VLANs on the 10G interfaces as required.

related to https://github.com/CCI-MOC/ops-issues/issues/43

**Comment by hakasapl** [comment]
Mike Zink said we should the iDracs on the cloudlab side - I can take care of that, I'll reply if we need to add to MOC.

**Comment by naved001** [comment]
I am gonna close this issue then; you can reopen if we need to add to MOC.
