### ISSUE TITLE
ocp-prod controller addresses are incorrect

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#582]
After the power shutdown on 5/24 (#575), nodes in the ocp-prod clusters appear to have changed addresses. Looking at the `haproxy` configuration on one of the controllers, we see the previous controller addresses (the file was last modified on 3/7):

```
backend masters
   option  httpchk GET /readyz HTTP/1.0
   option  log-health-checks
   balance roundrobin
   server oct10-01-control.ocp-prod.massopen.cloud 128.52.62.159:6443 weight 1 verify none check check-ssl inter 1s fall 2 rise 3
   server oct10-03-control.ocp-prod.massopen.cloud 128.52.62.249:6443 weight 1 verify none check check-ssl inter 1s fall 2 rise 3
   server oct10-02-control.ocp-prod.massopen.cloud 128.52.62.254:6443 weight 1 verify none check check-ssl inter 1s fall 2 rise 3
```

That gives us:

| Hostname | Address       |
|----------|---------------|
| oct10-01 | 128.52.62.159 |
| oct10-02 | 128.52.62.254 |
| oct10-03 | 128.52.52.249 |

But connecting to those addresses and running `hostname`, we see:

| Address       | Hostname |
|---------------|----------|
| 128.52.62.159 | oct10-02 |
| 128.52.62.254 | oct5-19  |
| 128.52.52.249 | oct10-02 |

It looks like DHCP lease expiration has killed the ocp-prod cluster.

**Comment by larsks** [comment]
@naved001 here's the information for the CSAIL folks:

| Hostname | IP Address    | Mac Address       |
|----------|---------------|-------------------|
| oct10-01 | 128.52.62.159 | b8:ce:f6:49:6f:32 |
| oct10-02 | 128.52.62.254 | b8:ce:f6:49:71:42 |
| oct10-03 | 128.52.62.249 | b8:ce:f6:49:71:8a |

In the event that there are conflicts, the existing lease should be
discarded and replaced with the static lease from this table.

**Comment by larsks** [comment]
https://console-openshift-console.apps.ocp-prod.massopen.cloud/dashboards is back up. Most of the nodes seem healthy:

```
NAME                                        STATUS     ROLES    AGE    VERSION
neu-15-4-compute.ocp-prod.massopen.cloud    Ready      worker   280d   v1.22.3+fdba464
neu-15-9-compute.ocp-prod.massopen.cloud    Ready      worker   280d   v1.22.3+fdba464
neu-17-12-compute.ocp-prod.massopen.cloud   Ready      worker   270d   v1.22.3+fdba464
neu-3-11-compute.ocp-prod.massopen.cloud    Ready      worker   280d   v1.22.3+fdba464
neu-5-10-compute.ocp-prod.massopen.cloud    Ready      worker   280d   v1.22.3+fdba464
neu-5-3-compute.ocp-prod.massopen.cloud     Ready      worker   280d   v1.22.3+fdba464
neu-5-4-compute.ocp-prod.massopen.cloud     Ready      worker   280d   v1.22.3+fdba464
oct10-01-control.ocp-prod.massopen.cloud    Ready      master   281d   v1.22.3+fdba464
oct10-02-control.ocp-prod.massopen.cloud    Ready      master   281d   v1.22.3+fdba464
oct10-03-control.ocp-prod.massopen.cloud    Ready      master   281d   v1.22.3+fdba464
oct5-02-compute.ocp-prod.massopen.cloud     Ready      worker   31d    v1.22.3+fdba464
oct5-03-compute.ocp-prod.massopen.cloud     Ready      worker   31d    v1.22.3+fdba464
oct5-04-compute.ocp-prod.massopen.cloud     Ready      worker   31d    v1.22.3+fdba464
oct5-05-compute.ocp-prod.massopen.cloud     Ready      worker   31d    v1.22.3+fdba464
oct5-06-compute.ocp-prod.massopen.cloud     Ready      worker   31d    v1.22.3+fdba464
oct5-07-compute.ocp-prod.massopen.cloud     Ready      worker   31d    v1.22.3+fdba464
oct5-09-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-11-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-12-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-13-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-14-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-15-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-16-compute.ocp-prod.massopen.cloud     NotReady   worker   30d    v1.22.3+fdba464
oct5-17-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-18-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
oct5-19-compute.ocp-prod.massopen.cloud     NotReady   worker   30d    v1.22.3+fdba464
oct5-20-compute.ocp-prod.massopen.cloud     Ready      worker   30d    v1.22.3+fdba464
```

One of those `NotReady` nodes is one that I explicitly shut down because it had acquired the address from oct10-01-control; now that we've fixed DHCP I'll bring it back up and see how things work.

**Comment by larsks** [comment]
I've opened https://access.redhat.com/support/cases/#/case/03233027 on the remaining issues:

- The multus, oauth, and etcd cluster operators are unhealthy
- There are a bunch of alerts (most probably related to the above)
- Cluster access is intermitten (ditto)

**Comment by joachimweyl** [comment]
resolved with BU to get static addresses.
