### ISSUE TITLE
Create reverse DNS records for curator cluster nodes

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#587]
We need to ask our upstream network provider (I believe that's Northeastern for the 192.12.185.0/24 network) to create reverse (`PTR`) records for the following hosts:

| Hostname                         | Address        |
|----------------------------------|----------------|
| os-ctrl-0.curator.massopen.cloud | 192.12.185.175 |
| os-ctrl-1.curator.massopen.cloud | 192.12.185.176 |
| os-ctrl-2.curator.massopen.cloud | 192.12.185.177 |

Related to #586 

BU ticket number is INC13552915

**Comment by naved001** [comment]
Earlier they offered to create `175.185.12.192.in-addr.arpa name = os-ctrl-0.curator.massopen.cloud.bu.edu`, which is under the bu.edu domain and that's not what we want. I responded that we want `175.185.12.192.in-addr.arpa name = os-ctrl-0.curator.massopen.cloud` and now I have been waiting for their response. 

I nudged them today again about this.

ticket number is INC13552915

**Comment by naved001** [comment]
their latest response:

> We are working on a solution for this. We have redirected the Authoritative NS Name server on our Test dns server "dns00.bu.edu" for the Subnet Zone 192.12.185. You should be able to create your own PTR records for the hostnames you've requested them for. Then, After the PTR configuration is pushed to the server dns00.bu.edu please update this ticket if it has been successful. If this works then we will proceed Update this Subnet Zone for the production dns servers

**Comment by naved001** [comment]
Looks like BU had, at some point, delegated reverse records to our name servers (ns1 and ns2). so I created the reverse records there (from tld.massopen.cloud) by first adding a new domain for reverse records, and then checking a box next to the A record which automatically creates the corresponding PTR record. But it still doesn't work, I am asking BU to see what's up.

I think I correctly configured out nameservers, because they respond with the right name
```
naved@Naveds-MacBook-Pro ~ % nslookup
> server ns1.massopen.cloud
Default server: ns1.massopen.cloud
Address: 34.204.145.35#53
> 192.12.185.175
Server:		ns1.massopen.cloud
Address:	34.204.145.35#53

175.185.12.192.in-addr.arpa	name = os-ctrl-0.curator.massopen.cloud.
> server ns2.massopen.cloud
Default server: ns2.massopen.cloud
Address: 129.10.5.41#53
> 192.12.185.175
Server:		ns2.massopen.cloud
Address:	129.10.5.41#53

175.185.12.192.in-addr.arpa	name = os-ctrl-0.curator.massopen.cloud.
```

But the BU dns server does not.
```
> server dns00.bu.edu
Default server: dns00.bu.edu
Address: 128.197.253.150#53
> 192.12.185.175
Server:		dns00.bu.edu
Address:	128.197.253.150#53

** server can't find 175.185.12.192.in-addr.arpa: NXDOMAIN
```

**Comment by naved001** [comment]
still no response, so I asked for an update.

**Comment by naved001** [comment]
The ticket has been put on hold.

**Comment by joachimweyl** [comment]
@naved001 what is the status of this Ticket?

**Comment by naved001** [comment]
I asked them for an update today.

**Comment by joachimweyl** [comment]
@naved001 any update on the ticket?

**Comment by naved001** [comment]
@joachimweyl BU IS&T closed the ticket without a resolution. I am going to close this issue too because this is more of a "nice to have". The curator cluster isn't even live anymore.
