### ISSUE TITLE
Inventory spare hardware at MGHPCC

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#590]
It would be nice to have a document of what we have at the data center so any maintenance tasks can move forwardly smoothly.

We should also compile a list of servers that don't function and figure out if it's possible to use them for spare parts (and what parts are actually useful).

**Comment by joachimweyl** [comment]
@hakasapl is this done or do you still have some items you want to inventory today?

**Comment by hakasapl** [comment]
The inventory is done but I am working on cleaning up the spreadsheet and ordering spare parts.

**Comment by hakasapl** [comment]
Duplicate of https://github.com/CCI-MOC/ops-issues/issues/611
