### ISSUE TITLE
Put new nvme SSDs in kzn-osd08 and kzn-osd10

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#591]
as we discovered in #576, the old drives are dead and need to be replaced.

Plan is to get new drives, install it in the systems and then create the OSDs in ceph.

Blocked on until we receive new drives.

**Comment by naved001** [comment]
@msdisme Intel received one of the drives yesterday, which they then immediately processed and shipped the replacement. According to the tracking number they provided, it's still waiting to be picked up.

They will receive the other faulty drive today and hopefully ship a replacement soon for that as well.

**Comment by msdisme** [comment]
that is great - very fast turnaround then!

**Comment by msdisme** [comment]
I added https://github.com/CCI-MOC/ops-issues/issues/599 to track updatign status

**Comment by naved001** [comment]
intel has shipped both replacement drives and should be delivered to MGHPCC by the end of the day tomorrow.

**Comment by naved001** [comment]
After the drives were installed I created the OSDs.

```
ceph osd destroy 277 --yes-i-really-mean-it
ceph-volume lvm zap /dev/nvme0n1
ceph-volume lvm create --osd-id 277 --data /dev/nvme0n1
```

All OSDs are now up and in.
