### ISSUE TITLE
Define AUP and/or EULA for NERC OpenShift

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#594]
[Define AUP and/or EULA for NERC OpenShift](https://app.asana.com/0/1201794020676107/1201802387286621/f)

**Comment by msdisme** [comment]
from: Due Date:
22-07-22
Link:
https://app.asana.com/0/1201794020676107/1201802387286621
Asana Link:
https://app.asana.com/0/0/1202470246475241/f
Section:

**Comment by joachimweyl** [comment]
Meeting on Friday (Oct 7) with Legal.

**Comment by msdisme** [comment]
pretty close on this,  fiddling with pandoc to convert it with internal links (or will recreate links)

**Comment by msdisme** [comment]
*The Mass Open Cloud Alliance (MOC Alliance) has developed a production
public cloud to provide domain researchers with predictable low-cost
resources and facilitator support while enabling academic researchers
and developers in the open source community to participate in close
interactions between research, development, and production operations.
Housed at the Boston University Hariri Institute for Computing and
Computational Science & Engineering, the MOC Alliance is a unique
collaborative effort between higher education, non-profit entities and
industry (MOC Alliance Collaborators). For a full list of the MOC
Alliance Collaborators, please visit* *[here](https://www.bu.edu/hic/centers-initiatives-labs/mocalliance/)*.

**MASS OPEN CLOUD ALLIANCE (MOC ALLIANCE) END USER LICENSE AGREEMENT**

This End User License Agreement (the “Agreement”) applies to all uses of
software and services rendered by and in relation to the Mass Open Cloud
Alliance (the “Services”). Each Service is provided and managed by the
MOC Alliance Collaborator(s) identified [here](#service_name) (each a
“Provider”).

1.  **Description of the Services**

The Services are a cloud-based system through which users can upload,
store, download, and share content from servers maintained by the
Provider. YOUR USE OF THE SERVICES CONSTITUTES AN ACCEPTANCE OF THIS
AGREEMENT AND THE TERMS AND CONDITIONS CONTAINED HEREIN. If you do not
agree to all of the terms of this Agreement, you may not use the
Services.

2.  **Intellectual Property**

The Services allow you to upload, store, download, access, and share
content (“User Content”). You retain ownership of any and all
intellectual property rights you hold in your User Content.

By using the Service, you give the Provider a nonexclusive, worldwide,
royalty-free license to host and store the User Content that you upload,
store, download, access, and share, as well as a license to perform
those tasks necessary to ensure continued operation of the Services.

The Provider retains all legal right, title, and interest in and to the
Services, including but not limited to graphics, user interface, the
scripts and software used to implement the Services, and any materials
provided to you as a part of and/or in connection with the Services,
including any and all intellectual property rights that exist therein,
whether registered or not, and wherever in the world they may exist.

3.  **Code of Conduct**

In exchange for your right to use the Services, you agree not to misuse
the Services or to help anyone else to do so. In particular, you agree
to not do any of the following with respect to the Services (unless
otherwise authorized in writing by the Provider for a specified research
purpose):

1)  probe, scan, or test the vulnerability of any system or network;

2)  breach or otherwise circumvent any security or authentication
    measures;

3)  willfully access, tamper with, or use non-public areas or parts of
    the Services, or shared areas of the Services you haven't been given
    access to;

4)  willfully interfere with or disrupt any user, host, or network, for
    example by sending a virus, overloading, flooding, spamming, or
    mail-bombing any part of the Services;

5)  access, search, or create accounts for the Services by any means
    other than the Provider’s publicly supported interfaces (for
    example, "scraping" or creating accounts in bulk);

6)  send unsolicited communications, promotions or advertisements, or
    spam;

7)  send altered, deceptive or false source-identifying information,
    including "spoofing" or "phishing";

8)  promote or advertise products or services without appropriate
    authorization;

9)  circumvent quotas, including computer, networking and storage
    limits;

10) sell the Services unless specifically authorized to do so;

11) publish or share materials that are unlawfully pornographic or
    indecent, or that contain extreme acts of violence;

12) advocate bigotry or hatred against any person or group of people
    based on their race, religion, ethnicity, sex, gender identity,
    sexual preference, disability, or impairment;

13) violate the law in any way, including storing, publishing or sharing
    material that is fraudulent, defamatory, or misleading;

14) violate the privacy or infringe the rights (including those rights
    granted under trademark and copyright law) of others;

15) use any component, function, or other facility of the Services to
    store, access, transmit, or share any “personal information” of
    individuals (as such term is defined in Section 1 of M.G.L. c. 93H);

16) If you are a covered entity, business associate, or representative
    of a covered entity or business associate (as those terms are
    defined by the Health Insurance Portability and Accountability Act
    of 1996 (“HIPAA”) at 45 C.F.R. § 160.103), use any component,
    function, or other facility of the Services to store, access,
    transmit, or share any “protected health information” (as such term
    is defined at 45 C.F.R. § 160.103) or use the Services in any manner
    that would make the Provider your or any third party’s business
    associate;

17) access the Services from sanctioned countries, per the list kept by
    the Bureau of Industry and Security of the U.S. Department of
    Commerce; or

18) use or access the Services in any way that would make the Provider
    subject to the law of any jurisdiction outside of the United States
    requiring the Provider to take affirmative steps in order to store,
    access, use, transfer, or otherwise process particular User Content
    that includes personal information of individuals or other sensitive
    information legally (e.g., the EU’s General Data Protection
    Regulation, China’s Personal Information Protection Law, the U.S.’s
    HIPAA).



4.  **Removal of Content**

The Provider assumes no liability for any content uploaded to or stored
on the Services by other parties. However, the Provider reserves the
right at all times to determine whether any content violates this
Agreement, and may pre-screen, move, refuse, modify, and/or remove
content at any time, without prior notice and in its sole discretion.

5.  **Copyright**

You agree to refrain from any and all copyright infringement in your use
of the Services. The Provider will respond to notices of copyright
infringement if they comply with the law, and such notices should be
reported using the Provider’s Digital Millennium Copyright Act
procedures, which are available [here](#service_name). The Provider reserves the right to
remove without notice any content that is alleged to be infringing and
to delete the accounts of repeat infringers. The designated agent for
notice of alleged copyright infringement on the Services is identified
here.

6.  **Enforcement**

If you violate any of the terms of this Agreement, or if your use of the
Services intentionally or unintentionally threatens the Provider’s
ability to provide the Services or other systems, the Provider may
immediately take any action necessary to ensure compliance with this
Agreement and the protection of the Services or the Provider’s systems,
up to and including termination or suspension of your access to the
Services and deletion of your content.

7.  **Provider’s Warranties and Disclaimers**

The Provider agrees to provide the Services using a reasonable level of
skill and care. However, other than as expressly set out in this
Agreement, the Provider makes no warranty, guarantee or promise relating
to the Services. For example, and without limitation, the Provider makes
no representations or commitments regarding the specific functions of
the Services, or their reliability, availability, or ability to meet
your needs. THE PROVIDER PROVIDES THE SERVICES ON AN “AS IS” AND “AS
AVAILABLE” BASIS.

The Services may be unavailable from time to time. While the Provider’s
goal is the keep the Services up and running, all online services suffer
occasional disruptions and outages, and the Provider is not liable for
any disruption or loss you may suffer as a result. The Provider
specifically makes no warranties related to “uptime” or your ability to
access content stored on the Services during any period that the
Services are unavailable. As such, the Provider recommends that you
regularly back up content stored on the Services to another storage
medium.

TO THE EXTENT PERMITTED BY LAW, THE PROVIDER DISCLAIMS ANY AND ALL
WARRANTIES NOT EXPLICITLY GRANTED HEREIN, INCLUDING, BUT NOT LIMITED TO,
ANY IMPLIED WARRANTIES OF FITNESS, MERCHANTABILITY, OR NON-INFRINGEMENT.

8.  **Personal Data and Other Confidential Information**

To the extent your use of the Services requires it, you are responsible
for providing notice to, and obtaining consents from, individuals
regarding the collection, processing, transfer and storage of their data
through your use of the Services.

You understand and agree that you are solely responsible for any
liabilities, fines and penalties arising from your failure to comply
with this Section 8 and any other provision of this Agreement.

9.  **Telemetry Data**

For the purposes of this Agreement, “telemetry data” shall mean any
information related to your utilization of the Services.

You acknowledge and agree that the Services will collect and transmit
telemetry data to MOC Alliance and its higher education, non-profit and
industry MOC Alliance Collaborators. MOC Alliance and its MOC Alliance
Collaborators may use telemetry data to operate and maintain (including
to improve) the Services and for scientific research purposes.

Telemetry data will generally not include personal, identifiable
information. You acknowledge that some of the telemetry data, such as IP
address, MAC address and email address, may qualify as personal data
identifying an individual under the laws of some jurisdictions.

Requests by third parties other than Provider and MOC Alliance
Collaborators to access telemetry data for any purpose must be reviewed
and approved by the MOC Alliance Data Governance Committee. MOC Alliance
may also post and make broadly available some telemetry data in an
anonymized manner on the Internet.

10. **Limitation of Liability**

The Provider will use reasonable security measures to protect content
stored on the Services. However, the Provider makes no guarantees that
the Services will be free from loss, corruption, attack, viruses,
interference, hacking, or other security intrusion, and the Provider
disclaims any liability relating thereto.

AS PERMITTED BY LAW, THE PROVIDER WILL NOT BE RESPONSIBLE FOR ANY LOST
PROFITS, REVENUES, OR DATA, FINANCIAL LOSSES OR INDIRECT, SPECIAL,
CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES CAUSED BY OR IN ANY WAY
ATTRIBUTABLE TO USE OF THE SERVICES. FOR THE SAKE OF CLARITY, THE
PROVIDER WILL NOT BE RESPONSIBLE FOR THE LOSS OR BREACH OF YOUR USER
CONTENT.

11. **Provider’s Right to Update Services**

The Provider reserves the right at any time to modify this Agreement and
to impose new or additional terms or conditions on your use of the
Services. Any material modifications and additional terms and conditions
will be communicated to you and, if accepted, will be effective
immediately and will be incorporated into this Agreement. In the event
that you refuse to accept such changes, the Provider will have the right
to terminate this Agreement pursuant to Section 12.

12. **Termination of the Agreement**

This Agreement may be terminated by you at any time by discontinuing
your use of the Service and deleting your User Content or by written
notice to the Provider’s technical/support contact listed [here](#service_name). In such
an event, the Provider may immediately delete your account, but it may
take up to 4 weeks to do so. You should ensure prior to termination that
you have transferred all data stored on the Services to another storage
medium.

This Agreement may be terminated by the Provider for any reason upon 48
hours’ notice to you. In such an event, you will be afforded a
reasonable opportunity to retrieve your User Content from the Services.
If your account access has been suspended pursuant to Section 6, you may
request to retrieve your User Content from the Services by emailing
Provider’s technical/support contact listed [here](#service_name). The Provider will take
reasonable steps to arrange for you to retrieve such content, provided
retrieval does not require an unreasonable amount of Provider’s time or
resources and that the content is not illegal; is not unlawfully
pornographic or indecent; does not depict extreme acts of violence; does
not advocate bigotry or hatred against any person or group of people
based on their race, religion, ethnicity, sex, gender identity, sexual
preference, disability, or impairment; and does not violate the privacy
or infringe the rights of others). Any such retrieval shall be at your
own expense.

13. **Severability**

If any part of this Agreement is declared unenforceable or invalid, the
remainder will continue to be valid and enforceable.

14. **Governing Law**

This Agreement, and the interpretation, construction and enforceability
hereof, and all rights and obligations of both you and the Provider,
whether arising under this Agreement or otherwise, shall be governed by
and construed in accordance with the laws of the Commonwealth of
Massachusetts, without giving effect to its principles of conflict of
laws. The sole and exclusive jurisdiction and venue for resolution of
any disputes under this Agreement shall be in the state and federal
courts located in Boston, Massachusetts, and you hereby submit to, and
waive objection to, the jurisdiction and venue of such courts.

**<u>Information to be provided at link (example)</u>**:

<table style="width:100%;">
<colgroup>
<col style="width: 14%" />
<col style="width: 9%" />
<col style="width: 8%" />
<col style="width: 17%" />
<col style="width: 15%" />
<col style="width: 20%" />
<col style="width: 12%" />
</colgroup>
<thead>
<tr class="header">
<th><span id="service_name" class="anchor"></span>Resource Service
(URL)</th>
<th>Resource Service Manager</th>
<th>Resource Host Owner</th>
<th>Copyright Infringement Contact</th>
<th><p>Technical Support Contact</p></th>
<th>General Contact</th>
<th>Link to Relevant Policies</th>
</tr>
</thead> 
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><a href="https://nerc.mghpcc.org/">NERC</a></td>
<td><p>Trustees of Boston University</p>
<p>and</p>
<p>President and Fellows of Harvard College</p></td>
<td><p>Trustees of Boston University</p>
<p>and</p>
<p>President and Fellows of Harvard College</p></td>
<td><p>Eric Jacobsen</p>
<p>Boston University</p>
<p>111 Cummington Mall</p>
<p>Boston, MA 02215</p>
<p>Email: dmca AT bu.edu</p>
<p>http://www.bu.edu/tech/services/security/cyber-security/dmca/copyright/</p>
<p>And</p>
<p>Tracy Walden</p>
<p>Harvard University Information Technology</p>
<p>784 Memorial Drive</p>
<p>Cambridge, MA 02139</p>
<p>Email: <a href="mailto:dmca@harvard.edu">dmca@harvard.edu</a></p>
<p><a
\\https://dmca.harvard.edu</a></p></td>
<td><a href="mailto:dmca@harvard.edu"><a
href="https://mghpcc.supportsystem.com/">Contact the NERC Help Desk</a>
for assistance or <a
href="mailto:help@nerc.mghpcc.org?subject=Reporting%20Issues%20on%20NERC">email
us</a>.</a></td>
<td><a href="mailto:dmca@harvard.edu"><a
href="https://mghpcc.supportsystem.com/">Contact the NERC Help Desk</a>
for assistance or <a
href="mailto:help@nerc.mghpcc.org?subject=Reporting%20Issues%20on%20NERC">email
us</a>.</a></td>
<td><p><a
\https://www.bu.edu/policies/conditions-of-use-policy-computing-ethics/ </a></p>
<p><a
https://docs.rc.fas.harvard.edu/kb/category/policy/</a></p></td>
</tr>
<tr class="odd">
<td><a href="mailto:dmca@harvard.edu"><a
href="https://nese.mghpcc.org/">NESE</a></a></td>
<td><a >President and Fellows of Harvard
College</a></td>
<td><a >President and Fellows of Harvard
College</a></td>
<td><p><a >Tracy Walden</p>
Harvard University Information
Technology</a></p>
784 Memorial Drive</a></p>
Cambridge, MA 02139</a></p>
<p>Email: <a href="mailto:dmca@harvard.edu">dmca@harvard.edu</a></p>
<p><a >And</a></p>
<p><a >Eric Jacobsen</a></p>
<p><a >Boston University</a></p>
<p><a >111 Cummington Mall</a></p>
<p><a >Boston, MA 02215</a></p>
<p><a >Email: dmca AT bu.edu</a></p></td>
<td><a >help@nese.mghpcc.org</a></td>
<td><a >href="mailto:help@nese.mghpcc.org</a></td>
<td></td>
</tr>
</tbody>
</table>

**Comment by msdisme** [comment]
@culbertj, @knikolla not sure where this belongs for coldfront/NERC[=

**Comment by msdisme** [comment]
Also, just spotted some glitchy text and missig text in table.

**Comment by msdisme** [comment]
2 changes - change delete account to terminate your account.    Also number of "business days" - call it 10 business days.

**Comment by msdisme** [comment]
@syockel@g.harvard.edu - for NESE should we remove BU DMCA contacts?

**Comment by joachimweyl** [comment]
There is a PR for this [here](https://github.com/nerc-project/nerc-eulas/pull/2).
