### ISSUE TITLE
Note to users/status update about backing up and current risky state of perf. cluster

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#595]
SSIA 

- [x] Create email text
- [x] team review text
- [x] update [status page](https://github.com/CCI-MOC/moc-status/pull/12)
- [x] send email

**Comment by joachimweyl** [comment]
possible email text

Subject: Performance Ceph cluster backup reminder

Hello Mass Open Cloud users,

It is always a good time to back up your data. If you are using the performance ceph cluster now is an even better time. 2 of the 10 drives have failed and it will be several weeks before the replacements are available. If additional drives are lost data could be lost.

Michael Daitzman

PS – If you were forwarded this email from a colleague and you would prefer to receive these notifications directly, you may sign up to the [kaizen-users mailing list](https://mail.massopen.cloud/mailman/listinfo/kaizen-users).
