### ISSUE TITLE
OP1st Mailing list for mghpcc ops type mail

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#597]
Guidance from mghpcc is that we should create a mailing list that we add to their distro and then let op1st folks subscribe to ours.  Alternative might be the slack channel but it seems like it may not get all same mail.

**Comment by msdisme** [comment]
@larsks I've asked that the mailing list be added.  OK to close, or do you prefer to wait until the first mail comes through?

**Comment by larsks** [comment]
@msdisme also, confirm that the list is configured to receive mail *from* MGHPCC. By default, a mailman mailing list will reject mail from people who are not members of the mailing list, so a list that is expected to receive and redistribute messages from another mailing list needs to be explicitly configured for that behavior. What will be the source address of messages coming from MGHPCC?

**Comment by msdisme** [comment]
subscribe via mail appears to not be working. . . . . Need to try other methods

**Comment by larsks** [comment]
@msd it looks like the list still doesn't accept messages from MGHPCC.  E.g., I have an approval request in my email from yesterday:

```
As list administrator, your authorization is requested for the
following mailing list posting:

    List:    op1st-dc-alerts@lists.massopen.cloud
    From:    [mghpcc-alerts@mghpcc.org](mailto:mghpcc-alerts@mghpcc.org)
    Subject: [mghpcc-alerts] MGHPCC Utility Power Sag Tuesday July 12 at 5:52 PM
    Reason:  Message has implicit destination

At your convenience, visit:

    https://mail.massopen.cloud/mailman/admindb/op1st-dc-alerts

to approve or deny the request
```

**Comment by msdisme** [comment]
k- probably will need an assist with this - 2 problems appear to be there.

**Comment by msdisme** [comment]
Hi,
We have set up a mailing list, op1st-dc-alerts@lists.massopen.cloud, so you may receive notificatrion of data center issues may affect the smaug cluster.

Probably the easiest way to join is to send a piece of email to op1st-dc-alerts-join@lists.massopen.cloud.  The traffic is usually very light. 

Regards,
Michael Daitzman
