### ISSUE TITLE
Set up repo server for scott Yockel

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#60]
Follow up on email from hugh

**Comment by larsks** [comment]
I've set up a RHEL 6 repository mirror at http://repomirror6.massopen.cloud/repos/. The packages are still syncing right now, but should finish overnight.

**Comment by msdisme** [comment]
Thanks Lars!

________________________________

**Comment by larsks** [comment]
As currently configured we're now mirroring the following repositories:

- rhel-6-server-rpms
- rhel-6-server-eus-rpms
- rhel-6-server-eus-optional-rpms
- rhel-6-server-eus-rhn-tools-rpms
- rhel-6-server-eus-supplementary-rpms
- rhel-6-server-extras-rpms

Everything has completed syncing. I've added a yum repository configuration at http://repomirror6.massopen.cloud/repos/moc-rhel6.repo; this can be dropped into `/etc/yum.repos.d` on a RHEL 6 system to enable all of these repositories.

At the moment the server is globally accessible, but I've asked Scott's team for the necessary information to put some CIDR-based restrictions in place.

**Comment by larsks** [comment]
FYI, the configuration for this is in https://github.com/CCI-MOC/repomirror-rhel-6.
