### ISSUE TITLE
Investigate cinder volume backup errors

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#600]
Milson reports:

> We have one issue while doing migration from MOC to NERC
> 
> ```
> [centos@mm-mirrormoc2nerc openstack]$ openstack --os-cloud moc volume backup create --force --container moc-milson-backup 5bac0142-f294-41f7-8a7f-2ca98b9e5a64
> +-------+--------------------------------------+
> | Field | Value                                |
> +-------+--------------------------------------+
> | id    | 45fe859d-39b2-4477-8926-a6fc9a047718 |
> | name  | None                                 |
> +-------+--------------------------------------+
> 
> [centos@mm-mirrormoc2nerc openstack]$ openstack --os-cloud moc volume backup list
> +--------------------------------------+------+-------------+-----------+------+
> | ID                                   | Name | Description | Status    | Size |
> +--------------------------------------+------+-------------+-----------+------+
> | 45fe859d-39b2-4477-8926-a6fc9a047718 | None | None        | error     |  200 |
> ```
> 
> I verified with the user - they have sufficient quota for volume and volume storage at MOC

**Comment by larsks** [comment]
Backups have worked successfully for smaller volumes (~20GB), but this volume is 200GB.

**Comment by larsks** [comment]
The backup appears to be going very...slowlly....so I will check in on the progress later today.

**Comment by larsks** [comment]
It failed, with the following error:

```
$ openstack volume backup show daa11628-3fe2-4541-a23a-bec15ed315b9 -f json | jq .fail_reason
"('Connection aborted.', error(\"(32, 'EPIPE')\",))"
```

**Comment by joachimweyl** [comment]
@larsks would this benefit from opening a RedHat ticket?

**Comment by larsks** [comment]
@joachimweyl we need to take a look at the service logs and see if they contain any useful diagnostic information (which probably means creating a new backup and waiting for it to fail first).

**Comment by joachimweyl** [comment]
@naved001 does this feel like it is in your wheelhouse? @larsks if it is would this be welcome to free you up to focus on OpenShift more or was this going to be a nice way to not focus on OpenShift for a little bit?

**Comment by larsks** [comment]
I am entirely happy if someone else wants to investigate this.

**Comment by naved001** [comment]
@joachimweyl I can look at this after I am done working on: https://github.com/CCI-MOC/esi/issues/247 unless you think one should be prioritized over the other.

**Comment by joachimweyl** [comment]
Thank you @naved001 assuming https://github.com/CCI-MOC/esi/issues/247 is relatively small that makes sense since you already started work on it. On the other hand, if it is a larger issue and you find a good stopping point as this one is small it might be worth jumping on this one first.

**Comment by naved001** [comment]
@larsks I am assuming I would look at the logs of `cinder_backup`.

I was doing `docker logs -f cinder_backup` on all 3 controllers, and did not see any logs when I start a volume backup. 

Anyway, I started 2 backups (50G volume from size pool, and 60G from performance pool) and both of those got created very slowly. I am going to try a bigger volume now.

**Comment by naved001** [comment]
copying a 200gig volume failed after running for a while, and this time there's a more descriptive error

```
(osc) naved@Naveds-MacBook-Pro ~ % openstack volume backup show 0a57a383-90cb-45da-9665-7a7d6d074c62 -f json | jq .fail_reason
"Object PUT failed: https://kzn-swift.massopen.cloud/swift/v139e8239fcbce4a4895ca5197efaa0349/naved-container/volume_1f9dab1f-6091-4082-81ad-06f41ec28aec/20220630155047/az_nova_backup_0a57a383-90cb-45da-9665-7a7d6d074c62-03535 401 Unauthorized   AccessDeni"
```

nothing in the logs of `cinder_backup` container. I am going to look around a bit more, maybe swift/rgw logs.

**Comment by larsks** [comment]
@naved001 was it able to successfully put some objects before failing with that error?

**Comment by knikolla** [comment]
OpenStack tokens have a limited validity, which [by default is 1 hour](https://github.com/openstack/keystone/blob/7c2d0f589c8daf5c65a80ed20d1e7fbfcc282312/keystone/conf/token.py#L22). When a service needs to communicate with another service, as in this case Cinder needs to communicate with Swift/RGW, it will forward the user's token alongside the requests that it subsequently makes.

To solve the issue of long-running operations between services failing, [Keystone implemented support for allowing expired tokens to work, if forwarded from one services to another](https://specs.openstack.org/openstack/keystone-specs/specs/keystone/ocata/allow-expired.html). The feature should work automatically on all OpenStack services that rely on Keystonemiddleware, however, my guess is that RGW's implementation does not support that, and refuses to validate the token as it should regardless of expiration.

**Comment by knikolla** [comment]
Additional note: Just noticed that this is between two different OpenStack deployments. In that scenario, I don't think there's much you can do except increase the lifetime of all tokens on the RGWs Keystone. Since the Cinder making the request is in a different OpenStack deployment than RGW, the extended validity will not apply anyway.

**Comment by joachimweyl** [comment]
@knikolla correct me if I am wrong but I believe at the point of the process the backup is only on the MOC OpenStack, the transfer to the NERC OpenStack has not happened yet.

**Comment by larsks** [comment]
@joachimweyl you are correct; the failure happens between two components on Kaizen.

**Comment by naved001** [comment]
the RGW logs confirm that the token expiration is what's causing this.

right after 1 hour it failed. 
```
2022-06-30 15:25:14.316 7ff34706e700  1 beast: 0x7ff459d96690: 127.0.0.1 - 39e8239fcbce4a4895ca5197efaa0349 [30/Jun/2022:15:25:14.299 -0400] "PUT /swift/v139e8239fcbce4a4895ca5197efaa0349/naved-container/volume_1f9dab1f-6091-4082-81ad-06f41ec28aec/20220630182522/az_nova_backup_34d7da50-a7ed-4f7d-b3ad-4954b8b68f5f-03641 HTTP/1.1" 201 50976 - "python-swiftclient-3.5.1" - latency=0.0169996s
2022-06-30 15:25:15.272 7ff3738c7700  0 req 1311626 0.258s swift:put_obj got expired token: naved001:naved001@gmail.com expired: 1656617115
2022-06-30 15:25:15.273 7ff3fe9dd700  1 beast: 0x7ff459d96690: 127.0.0.1 - - [30/Jun/2022:15:25:15.013 -0400] "PUT /swift/v139e8239fcbce4a4895ca5197efaa0349/naved-container/volume_1f9dab1f-6091-4082-81ad-06f41ec28aec/20220630182522/az_nova_backup_34d7da50-a7ed-4f7d-b3ad-4954b8b68f5f-03642 HTTP/1.1" 401 12 - "python-swiftclient-3.5.1" - latency=0.258994s
```
I think a temporary solution might be to just run the backup command again if we can confirm that it continues where it left off.

```
5f-03642 HTTP/1.1" 401 12 - "python-swiftclient-3.5.1" - latency=0.258994s
2022-06-30 15:33:45.846 7ff37c0d8700  0 req 1311823 0.256s swift:create_bucket validated token: naved001:naved001@gmail.com expires: 1656621218
2022-06-30 15:33:45.885 7ff37c0d8700  1 beast: 0x7ff459d96690: 127.0.0.1 - 39e8239fcbce4a4895ca5197efaa0349 [30/Jun/2022:15:33:45.590 -0400] "PUT /swift/v139e8239fcbce4a4895ca5197efaa0349/naved-container HTTP/1.1" 202 0 - "python-swiftclient-3.5.1" - latency=0.29499s
2022-06-30 15:33:48.851 7ff3e49a9700  1 beast: 0x7ff459d96690: 127.0.0.1 - 39e8239fcbce4a4895ca5197efaa0349 [30/Jun/2022:15:33:48.249 -0400] "PUT /swift/v139e8239fcbce4a4895ca5197efaa0349/naved-container/volume_1f9dab1f-6091-4082-81ad-06f41ec28aec/20220630193345/az_nova_backup_1125f75d-86ed-4168-827f-ff6abfd13be5-00001 HTTP/1.1" 201 38047848 - "python-swiftclient-3.5.1" - latency=0.60098s
2022-06-30 15:33:50.329 7ff3a1923700  1 beast: 0x7ff459d96690: 127.0.0.1 - 39e8239fcbce4a4895ca5197efaa0349 [30/Jun/2022:15:33:49.884 -0400] "PUT /swift/v139e8239fcbce4a4895ca5197efaa0349/naved-container/volume_1f9dab1f-6091-4082-81ad-06f41ec28aec/20220630193345/az_nova_backup_1125f75d-86ed-4168-827f-ff6abfd13be5-00002 HTTP/1.1" 201 4370171 - "python-swiftclient-3.5.1" - latency=0.444986s
```

**Comment by naved001** [comment]
running the command again doesn't work. it started with a new backup
```
(osc) naved@Naveds-MacBook-Pro ~ % openstack volume backup list
+--------------------------------------+------+-------------+----------+------+
| ID                                   | Name | Description | Status   | Size |
+--------------------------------------+------+-------------+----------+------+
| 1125f75d-86ed-4168-827f-ff6abfd13be5 | None | None        | creating |  200 |
| 34d7da50-a7ed-4f7d-b3ad-4954b8b68f5f | None | None        | error    |  200 |
+--------------------------------------+------+-------------+----------+------+
```

**Comment by larsks** [comment]
@knikolla can we change the default expiration time of keystone tokens to work around this issue?

**Comment by knikolla** [comment]
> @knikolla can we change the default expiration time of keystone tokens to work around this issue?

Yes, the configuration option is in `/etc/keystone.conf` as `[token] expiration` and is inputted in seconds.

**Comment by naved001** [comment]
okay, I updated the keystone config files so the tokens will expire in a day.

```
2022-07-01 10:29:12.927 7fcf4ed99700  0 req 36737 0.256s swift:create_bucket validated token: naved001:naved001@gmail.com expires: 1656772139
```

**Comment by joachimweyl** [comment]
@naved001 excited to hear how the backup goes now 👍

**Comment by naved001** [comment]
it has been 3 hours, and it's still going. I'll look around to see why it's this slow.

**Comment by naved001** [comment]
It finished successfully. I had accidentally ran the command twice so it created 2 backups.

```
(osc) naved@Naveds-MacBook-Pro ~ % openstack volume backup list
+--------------------------------------+------+-------------+-----------+------+
| ID                                   | Name | Description | Status    | Size |
+--------------------------------------+------+-------------+-----------+------+
| 05e97a6d-1727-4490-968e-cb9075f67209 | None | None        | available |  200 |
| e1216251-7f3e-473d-b1eb-a361de8f2417 | None | None        | available |  200 |
+--------------------------------------+------+-------------+-----------+------+
```

**Comment by Milstein** [comment]
Backup now working fine - issue arise when trying to Restore volume to NERC:
`openstack --os-cloud nerc volume backup restore 370920b0-36c8-438d-8309-b6ca33f574a3 vitis20201-mocbackup `

**Comment by joachimweyl** [comment]
Justin is working on the NERC backup restore part. Please see the slack conversation [here](https://massopencloud.slack.com/archives/CNMSRMDA5/p1657825672887319).
