### ISSUE TITLE
Cannot view pod logs on ocp-prod

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#601]
```
naved@Naveds-MacBook-Pro moc-apps % oc logs netbox-repo-host-0 pgbackrest
error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log netbox-repo-host-0))
```

I have a support ticket open with redhat.

https://access.redhat.com/support/cases/#/case/03244434

**Comment by larsks** [comment]
Requesting pod logs results in the following message in the journal:

```
Jun 15 16:30:01 neu-15-4-compute.ocp-prod.massopen.cloud hyperkube[2804]: E0615 16:30:01.131322    2804 server.go:273] "Unable to authenticate the request due to an error" err="verifying certificate SN=574876947775586318, SKID=, AKID=ED:0C:B6:9E:E5:25:CD:4D:2C:9E:A1:64:A1:BD:31:C3:52:38:48:65 failed: x509: certificate signed by unknown authority"
```

**Comment by naved001** [comment]
this looks relevant: https://access.redhat.com/solutions/5417871

**Comment by larsks** [comment]
We have two systems with the same address:

```
$ oc get nodes -o wide | grep 254
oct10-02-control.ocp-prod.massopen.cloud    Ready    master   300d   v1.22.3+fdba464   128.52.62.254   <none>        Red Hat Enterprise Linux CoreOS 49.84.202202081504-0 (Ootpa)   4.18.0-305.34.2.el8_4.x86_64   cri-o://1.22.1-14.rhaos4.9.git7486bc8.el8
oct5-19-compute.ocp-prod.massopen.cloud     Ready    worker   50d    v1.22.3+fdba464   128.52.62.254   <none>        Red Hat Enterprise Linux CoreOS 49.84.202202081504-0 (Ootpa)   4.18.0-305.34.2.el8_4.x86_64   cri-o://1.22.1-14.rhaos4.9.git7486bc8.el8
```

This is probably why node 5-19 was in `NotReady` state, which in turn was probably why we had a degraded machineconfigpool.

I'm not sure why things seem to be working now, because the worker node still has the wrong address. I haven't been successful in trying to  get the system to acquire a different address.

**Comment by larsks** [comment]
I've powered off the node for now. It's not clear to me if it's possible to change the address of this node, or if we should remove it from the cluster and re-install it. Something we can talk about tomorrow.

**Comment by naved001** [comment]
@larsks okay, I will close the ticket with redhat then because it's looks like there's nothing for them to do at this point.
