### ISSUE TITLE
Order replacement parts for FC430s

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#602]
These are in R1-PA-C08 FX2

We want to utilize the warranty for the FX2's to fix
- USB broken - has a note on the server that says broken USB - requires Warranty
- wrk-12 (unit 9 bay 3a), wrk-65 (unit 23 bay 1b), wrk-70 (unit 23 bay 3c) show only 96GB RAM and not able to read a4 and b4 slots.

We also need to check to see if we have replacement parts for the issues below, if not we will need to order replacements
- 1Gb Module instead of 10Gb like the rest of the FX2's
- small SSDs upgraded to the proper size for this server, compared to other servers for proper size
  - Check the size of the SSD's in the other servers to know what size it should be

**Comment by hakasapl** [comment]
The workers which have only read 96 GB of RAM only have 96GB of RAM. Will check inventory if we have any spare RAM we can add to them to complete the set.

**Comment by hakasapl** [comment]
All but 5 of these blades have 2x200GB SSDs. The SSD model is `Dell THNSF8200CAME`. These are **1.8"** drives, which are non-standard. If we purchase any they have to be 1.8" form factor

**Comment by hakasapl** [comment]
Serviot is able to get us both the 1.8" SSDs and the E14M switch module. In the process of getting a quote.

**Comment by hakasapl** [comment]
Quote to forward onto the NERC team is attached. It contains the additional SSDs (1.8") to complete the set, and replacements for the 1G chassis switches with 10G variants.

[07.06.2022 - Hakan - BU - SP 310594.pdf](https://github.com/CCI-MOC/ops-issues/files/9057649/07.06.2022.-.Hakan.-.BU.-.SP.310594.pdf).

**Comment by msdisme** [comment]
@hakasapl are the SSDs refurb dell brand or new?

**Comment by hakasapl** [comment]
When the drives are not new Serviot marks them as such on the quote, but I just emailed Serviot to confirm this just to make sure.

**Comment by hakasapl** [comment]
@msdisme these are confirmed to be new

**Comment by msdisme** [comment]
I am slow walking this while we look at how many fc430s are coming in next WF delivery.  Dependency on a HIC resource.

**Comment by msdisme** [comment]
@hakasapl working with techsquare to coordinate new hardware delivery requirements.

**Comment by msdisme** [comment]
moved to product backlog till additional hw from wayfair delivered

**Comment by msdisme** [comment]
@hakasapl lets discuss- my instinct is to swap parts out from the truckload next week rather then spend money on these systems specifically - WDYT

**Comment by hakasapl** [comment]
@msdisme These are parts that are missing, not broken, so unless there are extra parts arriving with the new shipment, or if we are cannibalizing some of the incoming hardware, we'll need to purchase regardless.

Is your preference to do one big order once we have everything here?

**Comment by hakasapl** [comment]
We will wait until both rounds of wayfair gear arrive. We are planning to cannibalize some nodes, and we will get a quote for any parts needed by the end of it.
