### ISSUE TITLE
idrac on wrk-35.nerc-ocp-prod.rc.fas.harvard.edu is inaccessible

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#603]
We are unable to access the idrac on host `wrk-35.nerc-ocp-prod.rc.fas.harvard.edu`. We need to determine whether this is a connectivity problem (switch port misconfigured?) or a power problem (not plugged in?) or if it's actually just broken.

The system is a PowerEdge FC430 in an FX2 in R1-PA-C08. If We have the correct data in our [hardware.csv](https://github.com/OCP-on-NERC/docs/blob/main/architecture/hardware.csv) then this is unitnumber 15 bay 1d

Other devices in the same chassis appear to be responding (at least, there are no other hosts that exhibit the same problem).

**Comment by joachimweyl** [comment]
Service Tag: 50H4LH2

https://wrk-35-obm.nerc-ocp-prod.rc.fas.harvard.edu/start.html

**Comment by hakasapl** [comment]
This looked to be resolved, the idrac is reachable now.
