### ISSUE TITLE
Openshift cluster ocp-prod broken

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#604]
When the controller oct10-02 is up, authentication breaks and the cluster is unusable. 

To keep things running, we will keep the problematic controller powered off while we work with Redhat on this.

Redhat ticket: https://access.redhat.com/support/cases/#/case/03245646

This started happening after we deleted the worker node oct5-19.

**Comment by larsks** [comment]
I've attached a must-gather to the case. I'm generating another one now that we've powered of oct10-02. I note from the output of `oc get nodes` that oct10-02 looks like it may be running a revision behind everything else; look at the `VERSION` column:

```
NAME                                        STATUS     ROLES    AGE    VERSION
oct10-01-control.ocp-prod.massopen.cloud    Ready      master   301d   v1.22.3+fdba464
oct10-02-control.ocp-prod.massopen.cloud    NotReady   master   301d   v1.22.1+d8c4430
oct10-03-control.ocp-prod.massopen.cloud    Ready      master   301d   v1.22.3+fdba464
```

**Comment by naved001** [comment]
Redhat support person asked us to delete the following pods and that resolved our issues.

```
# oc delete pod -l app=sdn -n openshift-sdn
# oc delete pod --all -n openshift-authentication-operator
# oc delete pod --all -n openshift-authentication
```
