### ISSUE TITLE
organize Power 9 removal, bch and UMass

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#609]
Work with MGHPCC, Hakan, and/or techsquared to remove the power 9's.

**Comment by hakasapl** [comment]
@msdisme what's the status of these? Are users still using them or can I disconnect them?

**Comment by msdisme** [comment]
good to go - plz see Rudolph's note. @hakasapl

**Comment by hakasapl** [comment]
I removed every cable from that rack. Next step is to begin the process for moving it.

**Comment by hakasapl** [comment]
BCH will meet me at MGHPCC on Wednesday to pick up the 2x 1TB nodes and associated cables.

**Comment by hakasapl** [comment]
BCH has obtained the nodes. At this point the cabinet is disconnected but still in BU space. Moving this workload to UMass, who will swap the cabinet with one in R1.
