### ISSUE TITLE
review and comment on abstract for ESI Submission for Red Hat Summit 2021

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#61]
by 12/4//2020

**Comment by naved001** [comment]
Just putting the link in the comments since links in titles can't be clicked on.

https://docs.google.com/document/d/1kDUy79Go1UbjNlfEj-BxEdRW0IUJzVY3MLlqrl2242I/edit?usp=sharing

**Comment by msdisme** [comment]
Thx !

________________________________
