### ISSUE TITLE
neu-15-35 has a bunch of errors on screen (but not in iDrac)

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#616]
![image](https://user-images.githubusercontent.com/20113064/175662395-008e26c2-bbe1-4fa0-9f52-8f322f4b3116.png)

this is an openstack compute node.

**Comment by naved001** [comment]
I am going to start with a refreshing ice cold power cycle to the node and see what happens.

**Comment by naved001** [comment]
well, this machine has now disappeared. will need to pull the power in and out at the data center to see if it works.

**Comment by naved001** [comment]
I can see the console, but it's showing the original error "iDrac initialization error".

**Comment by hakasapl** [comment]
Issues with iDrac itself involve a main board replacement, which is not a part readily available, and we may as well buy a new server before getting a replacement main board. The workflow on this server should be moved to another server long-term, but it looks like the console itself is working for now. I will create a separate ticket for this server and put it in icebox for now
