### ISSUE TITLE
Gather and document Service Tag information for NERC OpenShift Hosts

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#617]
The list of Hosts is [here](https://github.com/OCP-on-NERC/docs/blob/main/architecture/hardware.csv).
The static information is stored [here](https://github.com/OCP-on-NERC/nerc-ansible/tree/main/inventory/00-static).
 
- [ ] gather the service tag information for each host at the MGHPCC
- [ ] add that information to the static ansible information
- [ ] pull that information into the hardware list.

**Comment by larsks** [comment]
@joachimweyl the service tags are already part of the hardware inventory (for the NERC ocp hosts). I would not store these in the inventory files because they can be queried directly from the nodes.

**Comment by joachimweyl** [comment]
I see the `sku` in the [hardware.csv](https://github.com/OCP-on-NERC/docs/blob/main/architecture/hardware.csv) is actually the `service tag`. Thank you for the clarification.
This issue can be closed.
