### ISSUE TITLE
Allocation of OpenShift based VMs for a course

### ISSUE THREAD

**Issue by pazbenitzhak** [CCI-MOC/ops-issues#620]
Hi,
I would like your help with the allocation of 25 OpenShift based VMs.
The VMs are needed for a course taking place next week. It is a course similar to the previous ROSE course, where a similar allocation was done several months ago.
I'm attaching a link for a discussion regarding the previous ROSE allocation:
https://github.com/CCI-MOC/ops-issues/issues/450
Thank you for your help,
Guy

**Comment by msdisme** [comment]
@pazbenitzhak - what is the lifetime of this project?  Also, can you let us know more about the specifics of your requirements?  It's been a while since we did it, and I want to make sure it is clear.

**Comment by pazbenitzhak** [comment]
Well, we need an allocation of 25 OpenShift based VMs for students to use on next week's course.
Therefore, we would really appreciate it if they could be ready for tomorrow so we can test them before the beginning of next week (work week here ends on Thursday).
As for other technical aspects, I believe they could be understood from the previous discussion (#450).
For further information from your side you I believe you can consult @larsks and @naved001 (who worked on the previous request).
Thank you for your help

**Comment by pazbenitzhak** [comment]
I'm attaching 2 other links that may be useful:
https://github.com/CCI-MOC/ops-issues/issues/430
https://github.com/CCI-MOC/ops-issues/issues/499

**Comment by msdisme** [comment]
I had a quick discussion with Idan.  RH contacts are Guy - [gpazbeni@redhat.com](mailto:gpazbeni@redhat.com) and Maayan Friedman ([maafried@redhat.com](mailto:maafried@redhat.com)). Maayan and Guy both have MOC slack access, though they UTC +3, or  7 hours ahead of Boston

**Comment by larsks** [comment]
@pazbenitzhak I need your email address, and then I need:

- The email addresses of anyone else who is an instructor for the course
- The email addresses of all participants in the course

You are welcome to email them to me (lars@redhat.com) instead of posting them in this ticket.

**Comment by pazbenitzhak** [comment]
Ok I'm going to send you first the instructors' email addresses and than check about the participants' addresses

**Comment by larsks** [comment]
@pazbenitzhak thanks. Would you also provide the ssh public keys for yourself and anyone else who should be able to log in to the student virtual machines?

**Comment by larsks** [comment]
@pazbenitzhak best to keep questions about this issue here, rather than on irc/slack/etc. The issue was closed automatically because of comments in an associated pull request; it's not completed yet. I'm working on preparing the virtual machine disk image and templates right now.

Can you please provide me with your ssh public key? I'll be adding this as part of the virtual machine template.

Also, do you care what operating system is used for these virtual machines? Previously we used CentOS 8, but that no longer exists. I'm planning on using Fedora 36 right now unless you have an alternative preference.

**Comment by pazbenitzhak** [comment]
I believe my ssh public key is:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC01DutJQ022PzD8lKeAgwZSEu++moUOgZb/G08e8x1WQYepAGeW1wAaA7QzpmqAS/Py0z3vkDtGVUAlfs1FMyiP8bQMPRqgYzXtCfP8N/VQZWyWcsZaVxx3i3Y0gQUpnWjNevDw0a6ldwoqlgvIsCqNavnjLlZoHq49g0hJ/G8h0m9zjcWNWvTGzgc8Wm6AvdLPgsnKyXbnJl9M7oIaufw0EfODQiuLtBsMuQgBgJvqP9izqldCl6SeqfOkiaMbs3MCp4LwRUTEId1QF+JZOu6/DguIFaPj8uJHYcsqTICc0+7IJquwerj0KIAPfUvP+aXrqDaUI3hNn2V6aW52N8eAoWf3ejDHdFjK3p205glcXBQVLaNACzDfAYwLIKXVqa4oRrUoj33WgPn1s2KxuFOQaYlzLwP+7+k5mbdtXs1BEF4jiCuyskhN8SFk+g0wBonVICmAck/Qk2lV+Mw6MBzd720jCJTMmeftg41E5CK0LHxhlSyJ71KvpxxTVxRlVE= guypazbenitzhak@gpazbeni-mac


As for the second question: well, I'm actually not sure about which version of Linux operating system to use.
I'm tagging @maayanf24 who might be able to answer.

**Comment by larsks** [comment]
@pazbenitzhak We've mostly got things in place. I think this information can be found in the other issues to which you've provided a link, but to summarize:

- Everything is hosted on our production OpenShift cluster, https://console-openshift-console.apps.ocp-prod.massopen.cloud/. You can log in using your Red Hat google credentials.
- Everything is contained in the `summer2022-virtualrose` project.
- To create a new virtual machine, you will need the `oc` command line tool, which can be downloaded from [here](https://console-openshift-console.apps.ocp-prod.massopen.cloud/command-line-tools).
- There is a [Template](https://docs.openshift.com/container-platform/4.10/openshift_images/using-templates.html) available in the `summer2022-virtualrose` project named `rose-integrated-template` that can be used to create a VM and some associated resources, like this:

  ```
  oc process rose-integrated-template NAME=username SSHKEY="$(cat /path/to/sshkey)"
  ```

  This will create:

  1. A virtual machine named username-vm
  2. A [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) named userdata-username
  3. A [Service](https://kubernetes.io/docs/concepts/services-networking/service/) named username-vm-service

The `Service` shows the IP address you can use to access the virtual
machine. We expose ports 22, 80, 443, 3389, and 3390.  For example, I
use the template to create a virtual machine for myself...

```
oc process rose-integrated-template NAME=lars SSHKEY="$(cat ~/.ssh/id_rsa.pub)"
```

Then I will find:

```
$ oc project summer2022-virtualrose
$ oc get vm lars-vm
NAME      AGE    STATUS    READY
lars-vm   6m7s   Running   True
$ oc get service lars-vm-service
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                 AGE
lars-vm-service   LoadBalancer   172.30.83.50   128.52.61.130   22:32471/TCP,80:31304/TCP,443:32658/TCP,3389:31328/TCP,3390:30849/TCP   6m17s
```

And I can log into the virtual machine using ssh like this:

```
$ ssh fedora@128.52.61.130
```

It looks like there are some issues with RDP access right now that I will need to debug later this evening.

**Comment by larsks** [comment]
Fixed the problems with the image; now everything should be working. I've updated my previous comment with some additional information.

**Comment by pazbenitzhak** [comment]
Terrific @larsks! I'll start to go over it right now.
Thank you so much for you help! Much appreciated!

**Comment by pazbenitzhak** [comment]
Hi @larsks,
Could you please give @yaacov (yzamir@redhat.com) the same authorizations given to me?
Thank you in advance

**Comment by larsks** [comment]
@pazbenitzhak everyone you listed as instructors in your email to me should now have the same permissions that you do in openshift.

**Comment by larsks** [comment]
Closing this for now because I believe things are up and running.
