### ISSUE TITLE
MGHPCC: Replace memory in host neu-3-15

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#621]
![image](https://user-images.githubusercontent.com/20113064/177375062-a7c29eb6-4ca0-4b71-87a4-eea39aa7daa8.png)

This is a ceph host, so I'll power it off only when we are ready to replace this. 

Service tag: 2ZD7V52
Location: Row3-PodB-Cage3-Unit15
Server: Dell PoweEdge R730XD

It isn't critical yet.

**Comment by hakasapl** [comment]
@naved001 can you get the model number of this RAM when you get a chance?

**Comment by naved001** [comment]
```
Handle 0x110F, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x1000
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 64 bits
	Size: 16384 MB
	Form Factor: DIMM
	Set: 4
	Locator: B4
	Bank Locator: Not Specified
	Type: DDR4
	Type Detail: Synchronous Registered (Buffered)
	Speed: 2133 MT/s
	Manufacturer: 00CE00B300CE
	Serial Number: 404CD738
	Asset Tag: 00151630
	Part Number: M393A2G40DB0-CPB
	Rank: 2
	Configured Memory Speed: 2133 MT/s
	Minimum Voltage: 1.2 V
	Maximum Voltage: 1.2 V
	Configured Voltage: 1.2 V
```

**Comment by hakasapl** [comment]
DIMM replaced - powering back up @naved001

**Comment by hakasapl** [comment]
@naved001 is this all set?
