### ISSUE TITLE
What to do with R440 in OCT10

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#627]
There is a Dell R440 in OCT10 which has been off for a little under a year. How can we make use of the node?

**Comment by msdisme** [comment]
from: https://docs.google.com/document/d/1siTgDdhHXEKeq7ujX1eX-s9OecLXjASi2WqYNZKrgoE/edit#heading=h.4y9mfsn3xemj

Management Hub
One low-end system per rack for management/ipmi/etc access (“OBM+MGMT: $5k/ea”)
Min. 16G RAM, 2 ethernet interfaces

**Comment by msdisme** [comment]
@hakasapl are we set with this?

**Comment by hakasapl** [comment]
It's still not being used for anything, but it could be a management hub like you're saying

**Comment by naved001** [comment]
The plan is to use as the undercloud for ESI, it barely meets the minimum requirements for an undercloud host.

https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/13/html/director_installation_and_usage/chap-requirements#sect-Undercloud_Requirements
