### ISSUE TITLE
R1-PA-C08 Requirements

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#628]
Facility requirements for this rack:

- [ ] 60 A PDU Installation (Can we confirm this is necessary?)
- [ ] Re-key Rack with MOC keyring

**Comment by joachimweyl** [comment]
According to Nick, new PDUs are not required for the current setup but if we add any more systems to this rack we will need to upgrade.

**Comment by msdisme** [comment]
Let's raise to scott wayne, thogh I believe based on the next round of expected hw (_me: needs to make separate ticket_) we are gonna want to do this in several places.
