### ISSUE TITLE
Number of U's needed for additional johnonnot hw

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#629]
Can you take a look at this spreadsheet: https://docs.google.com/spreadsheets/d/1QSsbxFLUdYLEMd_GAjmmPKRPo3lWTsPp/edit#gid=183800325 and figure out the total number of U's needed for what is expected to come from the first delivery.  Some are blade servers so they end up in chassis.  We have the two palletes  and while still discussions going on around whether going into BU or UMass racks I'd like to see if we can get them delivered and in temp racks in the meantime.

**Comment by msdisme** [comment]
I added a column for # of U's

**Comment by hakasapl** [comment]
For everything marked "Johonnot", there are 48U total
