### ISSUE TITLE
Send MOC to NERC Migration Form/Survey in an email

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#635]
We launched the Mass Open Cloud (MOC) with a vision of creating a production cloud that would enable innovation by a broad industry and research community.

The MOC has successfully supported hundreds of projects supporting thousands of users, transitioned research projects into upstream software artifacts, and formed a community of interrelated research projects.

One of those projects is the New England Research Cloud ([NERC](https://nerc.mghpcc.org/)), a production cloud with professional operations and a team of experienced facilitators. The NERC supports OpenStack users today. With that in mind, the MOC Kaizen OpenStack Cluster will be phasing out of commission on August 17, 2022, at 5 pm.

If you are interested in relocating your projects to the NERC OpenStack Cluster, please fill out this [user survey](https://docs.google.com/forms/d/1Z_8eTmqnplIR-Q56UtgwiTVRFM38ZSZTIfpDAaJzcO8/edit) (even if you have filled one of these out previously.)

If you have questions please open a ticket at https://support.massopen.cloud/ or email [support@massopen.cloud](mailto:support@massopen.cloud).

Thanks!

Michael Daitzman

PS – If you were forwarded this email from a colleague and would prefer to receive these notifications directly, you may sign up for the kaizen-users mailing list by sending an emailto: [kaizen-users-join@lists.massopen.cloud](mailto:kaizen-users-join@lists.massopen.cloud)

v.4 minor tweaks, added link to support@massopen.cloud

**Comment by joachimweyl** [comment]
@msdisme please review/update.

**Comment by joachimweyl** [comment]
@Milstein please review/update the email communication above.

**Comment by msdisme** [comment]
Paused sending pending more details on NESE reconfig mention` – For the Mass Open Cloud (MOC) teams who are trying to migrate their projects to NERC, please contact us to facilitate the migration steps.`

**Comment by msdisme** [comment]
@milstein - please review note above.

**Comment by msdisme** [comment]
Please note - we will be keepign these alive after August 17th, but that will get folks to get started.

**Comment by joachimweyl** [comment]
Mail sent.
