### ISSUE TITLE
transfer donation information from pdf into spreadsheet

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#636]
Assumption - scraping from pdf is harder then having a person do the copying manually.

We have this format for data about  donations:  https://docs.google.com/spreadsheets/d/1QSsbxFLUdYLEMd_GAjmmPKRPo3lWTsPp/edit?usp=sharing&ouid=111874645414752393627&rtpof=true&sd=true  and a set of new wipe reports which are pdf: https://drive.google.com/drive/folders/14fVQf1_JURGcirvpsVBkevRsLKM-4ZKB?usp=sharing .  Make a set of instructions for a non-technical person (likely an undergrad) to add the relevant data from the pdf to a new spreadsheet - https://docs.google.com/spreadsheets/d/1OunNy0wBjGsHR1eYCxC9KMUFkz0g19Iq/edit?usp=sharing&ouid=111874645414752393627&rtpof=true&sd=true

The donation information is under NDA and access to pdfs will need to be granted. 

Rebecca in HIC may be available to help with manual migration of information.

**Comment by hakasapl** [comment]
I was able to write a script to ingest the PDF data. The spreadsheet [here](https://docs.google.com/spreadsheets/d/1OunNy0wBjGsHR1eYCxC9KMUFkz0g19Iq/edit?usp=sharing&ouid=105283757055503559914&rtpof=true&sd=true) is filled in.

It looks like we're expecting about 8 cabinets worth of systems. @msdisme

**Comment by msdisme** [comment]
Nice!

**Comment by msdisme** [comment]
closed too soon :-)  Are chassis identified in reports?  _me:goes to look_

**Comment by hakasapl** [comment]
Chassis are not identified in the PDFs, but ordering by chassis serial gets you that info (talked about in team check-in last week)
