### ISSUE TITLE
Check then fix network connections on wrk-[79-87]

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#637]
All of these nodes have down links.
needs a switch swap.

**Comment by hakasapl** [comment]
wrk80-87 are members of the chassis with 1G NICs, which are **not** currently connected to the switch. wrk-79 has a good link as far as I can tell from the link lights on the chassis switch. Can we confirm if wrk-79 is experiencing network issues? If so, can I see an output of `ip a` or `ifconfig` on the node?

**Comment by hakasapl** [comment]
New chassis switches are installed, will contact Nick Amento about the cabling

**Comment by joachimweyl** [comment]
@hakasapl any update from Nick?

**Comment by hakasapl** [comment]
This was done a while ago
