### ISSUE TITLE
Certificate renewal for SSO host

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#640]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/20113064/182149184-de648c8d-f2bb-4603-a2e3-05f32873c098.png">

only a couple of days left before these expire.

**Comment by knikolla** [comment]
Thanks for creating the issue! It's been on the back of my mind, I'll get on to it today, however since it requires a good 15 minutes of downtime at least, I'll be doing it tonight.

**Comment by naved001** [comment]
![image](https://user-images.githubusercontent.com/20113064/194135339-e87ce33a-d5a9-4437-84fc-9036d0f6e0d2.png)

these are up for renewal again.

**Comment by naved001** [comment]
@knikolla bumping this up your priorities list before this breaks.

**Comment by naved001** [comment]
@knikolla certs are up for renewal again.

**Comment by knikolla** [comment]
@naved001 Thanks! Added a note to do this on the 17th.

**Comment by knikolla** [comment]
Done, next expiration is April 17. Made a calendar note to renew on March 16.

**Comment by naved001** [comment]
> Made a calendar note to renew on March 16.

@knikolla the certs will expire on April 17th, I don't think the certs were renewed.

![image](https://user-images.githubusercontent.com/20113064/228326911-61f26b29-ed3f-45fa-a67a-c6517e863c3e.png)

**Comment by knikolla** [comment]
All set until July 10th.

**Comment by naved001** [comment]
@knikolla these are up for renewal again

**Comment by knikolla** [comment]
```
systemctl stop httpd
yes 1 | sudo certbot certonly -d sso.massopen.cloud -d onboarding.massopen.cloud -d adjutant.massopen.cloud
sudo systemctl start httpd
```

**Comment by naved001** [comment]
renewed the certs to be valid until 31 Dec 2023
