### ISSUE TITLE
Fix certificate management on rgw servers

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#643]
The certificate on the ceph rgw servers was updated by certbot as expected, but haproxy did not restart as a result of that change and continued to use the expired certificate. There is a systemd `.path` unit that is supposed to take care of the restart; figure out what's going on or rewrite the logic involved in handling certificate updates.

**Comment by naved001** [comment]
looks like the restart service `haproxy-restart.service` had `type=oneshot` instead of `Type=oneshot` (capital T) and due to that it was invalid.

```
Sep 12 12:47:10 kzn-rgw-j-01 systemd[1]: [/etc/systemd/system/haproxy-restart.service:2] Unknown lvalue 'type' in section 'Service'
```
After I fixed it, it would restart haproxy when I would make changes to the certificates.
