### ISSUE TITLE
Get high level list of likely FPGA users from Miriam and Suranga

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#644]

**Comment by msdisme** [comment]
@surangamh - Miriam indicated on a call yesterday that she had a good idea of which folks are using FPGA's. Could you coordinate with her and get a list of their email addresses and add them here.  We want to cross-reference to make sure we do not miss anyone.

**Comment by surangamh** [comment]
Here's the list:
https://docs.google.com/spreadsheets/d/1iixUE2BWj6IFVY1w20TqVKHuj6z9vspmUF05g2GK0Ck/

**Comment by msdisme** [comment]
thanks @surangamh ! @joachimweyl can you pull a list of their  @projects?

**Comment by joachimweyl** [comment]
All users except Vikram Narayanan had projects associated with them. Some of the emails did not match projects but after tracking down possible other addresses I was able to find projects with Michael Zink, Mert Cevik, Huang Kai & Suranga Handagala. [Here](https://docs.google.com/spreadsheets/d/1AYjAy-Gims6SCyuW-8-lAXWqdqgHt01iY9Al9wOo2FQ/edit?usp=sharing) is the list. I am working on gather the list of Projects with FPGA not in this list.

**Comment by joachimweyl** [comment]
added Volume size/s for more details.
@surangamh confirmed this list looks good and includes all FPGA projects.
