### ISSUE TITLE
Research ceph OSD continues to fail

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#648]
After replacing the drive, I destroyed the OSD and zapped the new drive, I then created the OSD again but it fails to run.

```
[root@neu-15-21 ~]# /usr/bin/ceph-osd -f --cluster ceph --id 46 --setuser ceph --setgroup ceph
starting osd.46 at - osd_data /var/lib/ceph/osd/ceph-46 /var/lib/ceph/osd/ceph-46/journal
*** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd
 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
2022-08-04 17:15:41.010 7f48c6659b80 -1 *** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd

 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

  -337> 2022-08-04 17:15:41.010 7f48c6659b80 -1 *** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd

 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

  -337> 2022-08-04 17:15:41.010 7f48c6659b80 -1 *** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd

 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

Segmentation fault
```

The error message isn't exactly helpful...

**Comment by msdisme** [comment]
Bad cable?
________________________________
From: Naved Ansari ***@***.***>
Sent: Thursday, August 4, 2022 5:19:08 PM
To: CCI-MOC/ops-issues ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CCI-MOC/ops-issues] Research ceph OSD continues to fail (Issue #648)


After replacing the drive, I destroyed the OSD and zapped the new drive, I then created the OSD again but it fails to run.

***@***.*** ~]# /usr/bin/ceph-osd -f --cluster ceph --id 46 --setuser ceph --setgroup ceph
starting osd.46 at - osd_data /var/lib/ceph/osd/ceph-46 /var/lib/ceph/osd/ceph-46/journal
*** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd
 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
2022-08-04 17:15:41.010 7f48c6659b80 -1 *** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd

 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

  -337> 2022-08-04 17:15:41.010 7f48c6659b80 -1 *** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd

 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

  -337> 2022-08-04 17:15:41.010 7f48c6659b80 -1 *** Caught signal (Segmentation fault) **
 in thread 7f48c6659b80 thread_name:ceph-osd

 ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)
 1: (()+0xf630) [0x7f48ba99a630]
 2: (BlueStore::read(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ghobject_t const&, unsigned long, unsigned long, ceph::buffer::list&, unsigned int)+0x7c) [0x558a612325cc]
 3: (OSD::read_superblock()+0xf1) [0x558a60db78a1]
 4: (OSD::init()+0x6cb) [0x558a60de34ab]
 5: (main()+0x23d2) [0x558a60cc6f62]
 6: (__libc_start_main()+0xf5) [0x7f48b99a5555]
 7: (()+0x378e20) [0x558a60d9ee20]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

Segmentation fault


The error message isn't exactly helpful...

**Comment by naved001** [comment]
I purged this OSD from ceph so it's not in the crush map at least.

**Comment by naved001** [comment]
closing this as we no longer have this cluster.
