### ISSUE TITLE
Track down model for the TOR Switch's for NERC Infra Worker & Controller

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#660]
Infra Workers live here R1-PA-C08
Infra Controllers live here R7-PC-C03

| Job | Rack | Data Switch Model | Mgmt Switch Model | Changing? |
| - | - | - | - | - |
| Workers | R1-PA-C08 | Nexus9000 C9336C-FX2 | Cisco WS-C4948E-F | no time soon |
| Controlers | R7-PC-C03 | Nexus9000 C93180YC-FX | Dell N3048 | Yes, moving to get LACP support |

**Comment by joachimweyl** [comment]
R7-PC-C03 used to be a Cisco Nexus9000 C93180YC-FX for data and a Dell N3048 for mgmt is that still the case?
worth noting that for NERC Test network in rack R7-PB-C19 they were dual cisco Nexus9000 C93180YC-EX in a vPC and a Dell N3048

**Comment by joachimweyl** [comment]
There were plans for a pair of Nexus9000 C9336C-FX2's is that what ended up in there?

**Comment by msdisme** [comment]
@jtriley - an issue for the switch info

**Comment by joachimweyl** [comment]
@jtriley - "the controllers are likely going to move given that their current location doesn't support LACP (both infra and prod). probably worth waiting on the controller TOR details until after the move"
Until they move the information in the body of this Issue will be correct. Once they move it could change.

**Comment by msdisme** [comment]
@zaoxing - this is the tracking issue for the top of rack switches

**Comment by joachimweyl** [comment]
Blocked on finding out if the switches will change when we move the controllers since the current location does not support LACP.

**Comment by joachimweyl** [comment]
Closing until we find out if the move actually changes the switches.
