### ISSUE TITLE
Move engage1 public networks someplace else

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#661]
These networks come from 2 engage1 switches (which are a part of 4 node brocade fabric in Row4PodA Cage 2 and Cage 4) and they seem to be failing. 

Some details of their earlier failure are described here: https://github.com/CCI-MOC/ops-issues/issues/588

@hakasapl we should plan to move these network to a more reliable set of switches.

**Comment by hakasapl** [comment]
@naved001 is this something we'd need to buy new switches for? Or did you have a different set of switches in mind to move the connections to?

**Comment by naved001** [comment]
Sent out an email to CSAIL to inform them of us moving the network to a different set of switches. 

@hakasapl and I think the best place would be move these to the OCT HUB switches in Row 6, but that may require a bit of planning.

**Comment by naved001** [comment]
@hakasapl plans to do this sometime around the week of 26th.

@joachimweyl we will need to inform operate first folks, and the MOC openshift users (ocp-prod).

**Comment by hakasapl** [comment]
Will happen during OCT downtime on the 26th

**Comment by joachimweyl** [comment]
@naved001 this will be an outage of their network for the 26th? Or are there other pieces that they will need to be aware of?

**Comment by naved001** [comment]
@joachimweyl yeah, this is what will affect them, and maybe some other things in that rack that @hakasapl has planned.

I gave them a heads up in my comment here: https://github.com/CCI-MOC/ops-issues/issues/691#issuecomment-1246829586

**Comment by naved001** [comment]
Both links to CSAIL were moved to the Row6 hub switches. They are part of port-channel `1000` on `OCT-HUB-1` and `OCT-HUB-2`.
