### ISSUE TITLE
Compile Wayfair donation for director level review

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#662]
Compiling hw into a more understandable set of information so directors and above may digest it.
- Pull out systems with large memory, GPUs, etc. 
- For homegenous, convert it to Standard Racks 38u; 
- generate CPU hours per month or year. 
- Cores eg.48 real not virtual 
	- Memory per core
	- Convert to a rack unit - 
Also, a Rack will require this much power and cooling

**Comment by hakasapl** [comment]
I made a [spreadsheet](https://docs.google.com/spreadsheets/d/16jYOReAY5OOkmLGDvPNKf3nIH-4EzD8CZDbA2dY-Kfw/edit#gid=0) with rack layout proposals

**Comment by msdisme** [comment]
@hakasapl 
The rack layout is nice for a quick understanding of how this equipment can be organized and what each rack would provide/require. 

A short spreadsheet (even an additional sheet in the existing workbook) with specifics on each machine type would be great (CPU type, memory, nic interfaces, etc).

EG: we want to be able to say we have 5.3 racks worth of server X, where server X has Y cores of compute and Z GB of memory.  and then a short description fo other kinds of servers we have, e.g., with GPUs…

Hoping to have wed AM so we can get Orran/Wayne to take another pass for feedback.

**Comment by msdisme** [comment]
also add the original data spreadsheet to this as a tab

**Comment by msdisme** [comment]
@hakasapl does this give you the necessary power and heat info: https://www.dell.com/support/manuals/en-us/poweredge-fm120/fx2ownersmanual/power-specifications?guid=guid-ce74709c-7ed1-4845-a975-7b3960ed667c&lang=en-us and https://www.dell.com/support/manuals/en-us/poweredge-fm120/fx2ownersmanual/environmental-specifications?guid=guid-cb32b282-fe4d-48b6-a3d1-f2a4b8d5d99e&lang=en-us

**Comment by hakasapl** [comment]
I've added a "Hardware Details" sheet to the spreadsheet, and copied over the full inventory in the "Hardware Inventory" sheet.

As for the power, this doesn't help too much because the wattage will vary greatly based on configuration. We're not sure what kind of PSUs are on the FX2s currently coming from wayfair, but that information would help.

**Comment by waygil** [comment]
Dell has a power planning tool located here - https://www.dell.com/en-us/dt/corporate/social-impact/advancing-sustainability/sustainable-products-and-services/energy-efficiency/energy-tools.htm

You can configure the FX nodes to match the wayfair ones to get an idea of power usage based on config.

**Comment by hakasapl** [comment]
I didn't know about that tool, super useful, thanks!

**Comment by hakasapl** [comment]
I've added some power metrics to the spreadsheet. It looks like most of the racks in the proposal are around 28kW, which is a bit too high for the current pods we have, especially if the cabinets are in the same pod.

If we were to spread out the hardware to more racks to reduce power density, we would be looking at about 14-15 racks of equipment (proposal has only 11), each of which at 19-21 kW each, which puts us in the sweet spot that the facility likes to keep average rack consumption at, 20 kW.

**Comment by msdisme** [comment]
@hakasapl plz see email subject: Re: MOC-A donation follow up from John Goodhue.

**Comment by hakasapl** [comment]
Waiting for reply from Dell to confirm power numbers...

**Comment by hakasapl** [comment]
Closing this for now
