### ISSUE TITLE
Spike:what to do with engage 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#69]
Decide on use for Engage systems
- a few options come to mind:
1. repurpose to support operate first projects
- [ ]  Openstack or Openshift ?
- []

**Comment by larsks** [comment]
See https://docs.massopen.cloud/en/latest/clusters/engage1/Engage1-Network-Documentation.html for information on engage environment,

**Comment by knikolla** [comment]
Being terrible at everything ops, I'd love to play around with developing some automated test environment hooked up to GitHub where we can test the playbooks before running them on production services.

**Comment by msdisme** [comment]
Will be part of : https://github.com/CCI-MOC/ops-issues/issues/365
