### ISSUE TITLE
OCT Downtime Planning and Execution

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#691]
Week of the 26th

**Comment by naved001** [comment]
@tumido @humairak @durandom we are planning to do some maintenance, and part of it is to move the public network for SMAUG to a different set of switches. There will be downtime and we will add more details soon. Thanks!

**Comment by naved001** [comment]
It's going to be the 26th of September (Monday).

**Comment by HumairAK** [comment]
from @naved001 in slack: 

>  it is possible that the network maintenance will happen either later today or end up being pushed until tomorrow. Something else came up which is delaying things. Sorry for the late update.

**Comment by naved001** [comment]
The network maintenance is still on-going, and will continue today. Hopefully there will be no noticeable downtime at all if all goes well (famous last words).

**Comment by hakasapl** [comment]
Maintenance complete
