### ISSUE TITLE
Send communication to MOC OpenShift users about engage1 Move

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#692]
---
due: 2022-09-26
---

This is the communication for #661
- [x] Create communication
- [x] Have Naved and Michael review
- [x] Create Status update
- [x] work with @msdisme to ensure communication is sent
- [x] confirm email sent
- [x] fix date to be for the 27th
- [x] update status to be severity 1 on the morning of the 27th
- [x] remove active status

**Comment by joachimweyl** [comment]
Subject: ocp-prod cluster network maintenance
Sep 19, 2022

Hello Mass Open Cloud OpenShift users,

September 26th the ocp-prod will be offline due to network maintenance. During this time ocp-prod will be unreachable.

Thank you for your understanding and patience as we replace the switches for this network.

Michael Daitzman

**Comment by joachimweyl** [comment]
@msdisme @naved001 please review the communication above.

**Comment by naved001** [comment]
@joachimweyl I am not sure if the date is actually 26th, it's the week of 26th and I don't know if @hakasapl has settled on a date yet.

**Comment by joachimweyl** [comment]
@naved001 based on @hakasapl comment [here](https://github.com/CCI-MOC/ops-issues/issues/661#issuecomment-1246814091) it sounded like it was happening on the 26th during an already scheduled OCT downtime. If I misunderstood this comment please let me know.

**Comment by naved001** [comment]
@joachimweyl oh yeah, you are right. the 26th it is then. The rest of the message looks good too.

**Comment by msdisme** [comment]
only mod is that I will specify this as ocp 4.x as well as the name.

**Comment by msdisme** [comment]
@joachimweyl updated to reflect mail sent.  Please could you verify the mail went and update the status page?

**Comment by joachimweyl** [comment]
@msdisme mail received. The status page [PR](https://github.com/CCI-MOC/moc-status/pull/20) is awaiting review.
