### ISSUE TITLE
Establish a release workflow  for docker images

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#693]
On the team check-in today, @knikolla expressed a preference for using commit hashes from the main branch as image tags rather than using branch names (to ensure that a deployment continues to use the same image unless it is *explicitly* changed). This becomes slightly problematic when the same repository houses both the Docker image sources and the openshift deployment manifests.

Kristi suggested an alternative approach using semantic versioning and named tags. There are a number of ways to automate this process; we would like to collect some examples of existing workflows so we can pick one that works well for our projects.

We can collect pointers to good example repositories (and generally discuss the topic of automated release workflows) here in this issue.

**Comment by knikolla** [comment]
https://github.com/CCI-MOC/ops-docs/pull/22

**Comment by larsks** [comment]
@knikolla is this the source of workflow you envisioned? https://github.com/cci-moc/image-workflow-example

**Comment by knikolla** [comment]
I'm assuming you meant 'sort of workflow', yes. Nice touch on also tagging `vX` and `vX.Y` on a new `vX.Y.Z` release!

**Comment by larsks** [comment]
Great, then let's discuss some details. :)

That workflow is triggered by pushing a tag, which is simple, but has some disadvantages -- primarily, it requires direct commit access to the repository, and bypasses any existing review process.

In some of my non-image repositories, I do things effectively "in reverse": a commit to a specific file triggers a release workflow, which then extracts the release version from the repository and generates a release.

I like this model, but I haven't tried adapting it to a container image (where we often want per-commit images as well as release images).

**Comment by knikolla** [comment]
As discussed in backlog grooming, for now, I think requiring push access to creating releases sounds like a good compromise in keeping things simple.

**Comment by larsks** [comment]
I think this can be closed.

**Comment by larsks** [comment]
I think this can be closed.
