### ISSUE TITLE
How we handled courses as a project for Kaizen

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#695]
Whenever possible we had the TA or the teacher create the projects, invite the user, and close out the project at the end of the course.   We also asked that they make a point of doing the development in a way that made redeploying a simple and standard part of the process.   In case this was overlooked haveing the course number and date was a way to identify projects we could close out. 

The info below is from an osticket canned response:

How to create MOC openstack projects for the course:

1.  include the course number and year at the start of the name - eg. CS4XX_fall2020_groupname.  (some projects are tied to the individual user in which case use )
2.  Go to this link: [https://onboarding.massopen.cloud/signup/](https://onboarding.massopen.cloud/signup/ "https://onboarding.massopen.cloud/signup/") to request projects – I will need to approve them so let me know when you have finished entering them via slack and I will approve them.
3.  Once they are approved (you should receive mail and I will also tell you) Go to this link: [https://support.massopen.cloud/kb/faq.php?id=22](https://support.massopen.cloud/kb/faq.php?id=22 "https://support.massopen.cloud/kb/faq.php?id=22") to invite the students for each project.
4.  Students, if you make them project administrators, should be able to use this link: [https://support.massopen.cloud/kb/faq.php?id=22](https://support.massopen.cloud/kb/faq.php?id=22 "https://support.massopen.cloud/kb/faq.php?id=22") to invite mentors and professors, though if you have those details you may invite them as well. I should not need to approve these.

For Openshift 4.x Containers:

1.  your github ID’s must be added to the moc-project-makers group (got them and will be adding them (or maybe Lars will)
2.  Please use the same naming convention from above include the course number and year at the start of the name - eg. CS4XX_fall2020_groupname.
3.  Once added follow the instructions here: [https://github.com/CCI-MOC/moc-openshift-projects](https://github.com/CCI-MOC/moc-openshift-projects "https://github.com/CCI-MOC/moc-openshift-projects")﻿

For Openshift 3.x it was more of a give us a spreadsheet with user names and identified admins and Rob ran a script.

**Comment by joachimweyl** [comment]
@msdisme I will start work on the Google doc based on this information. Thank you for providing it.

**Comment by msdisme** [comment]
@milstein the details on course projects are above.  Let me know if you need more.

**Comment by joachimweyl** [comment]
Here is the [google doc](https://docs.google.com/document/d/1qK143Zi1LzhyEdnz0UbrHuXool3PbUjbnwZerZDHtSk/edit?usp=sharing).
