### ISSUE TITLE
spike: event travel - where and criteria

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#699]
What event travel are planning to attend and who is attending them in 2023.      @knikolla to create a list of relevant events for all to review.  Attendance is likely to include a. participation/talk, b. representing the MOC Alliance, c. trip report after the event.

**Comment by okrieg** [comment]
no feedback now

**Comment by msdisme** [comment]
@knikolla I proposed this for jan 18 sprint

**Comment by knikolla** [comment]
The following are the conferences of interest for 2023

# FOSDEM 2023 (Brussels, Belgium) - Feb 4-5, 2023 - https://fosdem.org/
This is one of the largest open source conferences in the world and the largest in the EU. In the context of new EU investments in open source and cloud computing it made sense for me to attend. See [trip report](http://kristi.nikolla.me/2023/02/24/a-fosdem-2023-trip-report/). 

# KubeCon + CloudNativeCon Europe 2023 (Amsterdam, Netherlands) - April 18-21, 2023 - https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/
Kubernetes (via OpenShift) is one of the pillars of our cloud platforms. A lot of the investment in the area of cloud platforms is happening in the Kubernetes space. It makes a ton of sense for us to have a presence and get a feel for the direction of the community.

# Open Infrastructure Summit 2023 (Vancouver, Canada) - June 13-15, 2023 - https://openinfra.dev/summit/vancouver-2023/
Previously known as the OpenStack Summit, it has as of late rebranded to cater more towards open source infrastructure and not just OpenStack, but primarily focuses on OpenStack still. I have a talk accepted about our contributions to Single Sign on in Keystone and our experiences with it.

# KubeCon + CloudNativeCon NA 2023 (Chicago, USA) - November 6-9, 2023 - https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/
Same justification as KubeCon Europe above, but we should start brainstorming proposal talks for this one.
