### ISSUE TITLE
Identify Intern projects for RH interns

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#70]
what skillsets do we want, etc. 

student/intern Individuals working on branches or fork and commit - issue around permissions - discussion on fork and pull req

**Comment by msdisme** [comment]
https://docs.google.com/document/create?usp=drive_web&ouid=111874645414752393627&folder=0AFwtFO2rpolNUk9PVA

**Comment by larsks** [comment]
We need to make sure that all tasks in the intern document have corresponding cards in the backlog.

**Comment by larsks** [comment]
@larsks will take care of correlating intern doc + backlog

**Comment by gagansk** [comment]
@msdisme Need access to view the document.

**Comment by msdisme** [comment]
added gagan and heidi to doc
