### ISSUE TITLE
Replace failed drive in neu-5-22

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#702]
This server belongs to the research ceph cluster. Drive in slot 5 has failed. It will take a 600 Gig HDD. After the drive is replaced I will rebuild the OSD.

![image](https://user-images.githubusercontent.com/20113064/191966364-d2f6a9bc-fd9b-49f0-8aef-e541d61da243.png)

Service tag is 1P0XFX1

**Comment by hakasapl** [comment]
I will swap this on Monday

**Comment by naved001** [comment]
@joachimweyl Is there a reason why you changed the estimate to 1?

I set the estimate to 2 because after replacing the drive when we create the OSD in ceph, it sometimes it runs into weird issues. See https://github.com/CCI-MOC/ops-issues/issues/648 for reference and I wanted to take that into account.

**Comment by naved001** [comment]
no worries! thank you. I guess I should have put that in the description.

**Comment by hakasapl** [comment]
Drive replaced

**Comment by naved001** [comment]
recreated the OSD, and it's good now.
