### ISSUE TITLE
create system reports from johonnot wipe reports

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#709]
8-31 wipe reports here:  https://drive.google.com/drive/folders/1G9l0RHw22KLPkijahQveJG2THlCjifez

**Comment by hakasapl** [comment]
Sheets marked "room 2" here: https://docs.google.com/spreadsheets/d/16jYOReAY5OOkmLGDvPNKf3nIH-4EzD8CZDbA2dY-Kfw/edit#gid=52455875
