### ISSUE TITLE
MGHPCC: Replace failed drive

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#71]
Replace drive in neu-5-21. Needs a 600Gig drive. According to iDRAC it is "Physical Disk 0:1:5, Slot 5". Should be hot swappable.

neu = R3 Pod B.
5-21 = Cage 5 Unit 21. It's a dell poweredge server (1U).

@hakasapl

**Comment by hakasapl** [comment]
drive replaced
