### ISSUE TITLE
create rack plans from system reports in #709

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#710]

**Comment by msdisme** [comment]
in this [report](https://docs.google.com/spreadsheets/d/16jYOReAY5OOkmLGDvPNKf3nIH-4EzD8CZDbA2dY-Kfw/edit#gid=52455875) from #710 is there a  key to the colors used in the spreadsheet?

**Comment by hakasapl** [comment]
Red = Nodes that are EOL
Yellow = Nodes that are not EOL, but that do not fit with what we already have (homogeneity wise)
