### ISSUE TITLE
MGHPCC 2023 Shutdown Letter

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#719]
Create a letter to send to clients about the MGHPCC 2023 Shutdown.
[Here](https://github.com/CCI-MOC/ops-issues/issues/562#issuecomment-1122920992) is a link to the 2022 letter.

- [x] Set due date for first letter (May 22nd)
- [x] Draft Letter
- [x] Team review of the letter
- [x] Send Letter 2 weeks prior (May 22nd)

**Comment by joachimweyl** [comment]
Should we remove the parts about VM's since we plan to have all MOC OpenStack offline by then?
---------------------------------
Hello Mass Open Cloud users,

Due to a scheduled power outage at the MGHPCC data center, MOC services will be unavailable from Tuesday, June 6th, 2023 at 3 AM through Friday, June 9th, 2023 at 12 PM.

Please shut down your virtual machines, containers, and any bare metal systems by 6 PM on Monday, June 5th, so that the Mass Open Cloud team may begin preparing for the outage. If you do not shut them down yourself, you run the risk of losing data.

The MOC has dependencies on several services which also run at the data center. Based on previous experience we recommend not scheduling critical events the week of June 5th.

We will notify you when MOC services are available by updating the MOC status website at https://status.massopen.cloud/ and by sending an email to this distribution list. Once services are back online it will be your responsibility to restart any virtual machines, containers, or other systems.

If you will need access to any MOC hosted data during this outage, please make sure to obtain copies of that data prior to Monday, June 5th. During the outage, the data center will be completely without power and access to MOC hosted services will be impossible.

As always, if you have questions feel free to open a ticket at https://support.massopen.cloud/. The ticketing system will be available throughout the outage.

Thanks,

Michael Daitzman

PS – If you were forwarded this email from a colleague and you would prefer to receive these notifications directly, you may sign up to the kaizen-users mailing list: https://mail.massopen.cloud/mailman/listinfo/kaizen-users.

**Comment by joachimweyl** [comment]
@naved001, @knikolla, @hakasapl, @rob-baron, @larsks please review shutdown letter above.
Should we remove the parts about VM's since we plan to have all MOC OpenStack offline by then?

**Comment by rob-baron** [comment]
I would keep it in just in case the MOC OpenStack is not offline by then.  

It also might help someone's memory.

**Comment by naved001** [comment]
> Should we remove the parts about VM's 

No, we should keep it because someone may be running a VM somewhere else besides MOC OpenStack.

**Comment by joachimweyl** [comment]
@msdisme the letter is ready to send. Please send it today.

**Comment by joachimweyl** [comment]
broke this into 2 issues so that it does not spread out over 2 sprints just to wait to send the followup note.
