### ISSUE TITLE
Move Intel Servers from OCT 4 to new (TBD) location 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#721]
Discussed with Heidi - plan is to put the 4 chassis (32 blades) into OCT 4 (ESI testbed) but have most of the machines on an MOC address. 2-4 may be used to test out ESI interactions.

Goal is to do this by Oct 28th, 2022

Note from Parul: 

Hey Michael,

I am working with another student on two of the machines. The IP addresses are 172.16.100.209 and 10.128.24.103. 

We are working both working on different projects for the next week or so. So, please feel free to move them whenever you want. 

Thanks for reaching out.

Parul 

On Fri, Oct 14, 2022 at 1:42 PM Daitzman, Michael S <msd@bu.edu> wrote:
Hi Parul,

We want to coordinate moving the servers Intel loaned us in a way which will not affect your work.  Are you (or are others, eg. grad students or collaborators at RH) actively using them?

Thanks!

Michael

PS – Context – we want to move some systems into that rack so they may work with ESI

**Comment by naved001** [comment]
@hakasapl honestly any location as long as we can keep the same VLANs should be okay.

**Comment by msdisme** [comment]
do we already have space in current MOC racks or should we look to the [deprecate list](https://docs.google.com/document/d/1e530KMVEcr0sCyo9SfeoIVzA8e3q9SqsyWjOko3BhBE/edit#heading=h.ia04duy6ggj6)

**Comment by hakasapl** [comment]
These machines will move to R6-PB-C02 (OCT10), and we will add additional 10G NICs to the machines to support the switches in the rack

**Comment by msdisme** [comment]
@hakasapl plan is to do this on thursday, or friday?  (giving
 grad students to this so they will know.)

**Comment by hakasapl** [comment]
Thursday - I can send out that email, I assume the same people on the thread with the intel nodes before will work?

**Comment by msdisme** [comment]
that would be great, most of them also looking here so we should be good.

**Comment by hakasapl** [comment]
All 3 machines were moved to R6-PB-C02 (OCT10). Networking is verified and nodes are running again. A new solarflare 10G nic was added OCT-45
