### ISSUE TITLE
Identify location (network and physical) for Intel Servers currently in OCT 3 & Move to new location

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#722]
for the blocked issue, need to move the intel servers from OCT 4 so that we have room for 8u of FX2 chassis.

**Comment by msdisme** [comment]
for blocked issue, need to move the intel servers from OCT 4 so that we have room for 6u of FX2 chassis.

**Comment by msdisme** [comment]
6 u's of hardware in Intels - cabinet in Row 4-cabinet 23 - does it have a switch, if so does it have rj45's. 
if 10 or 25 gig can adapt. 

Or OCT 10- need to bring a switch from oct 3 or oct 6 or install NICs in intel nodes.   Preference around moving and adding NICS. 

HW - potentially a differetn MAC Address.

**Comment by hakasapl** [comment]
R4-PA-C23 - check if rack is actually empty and check for empty switchports

**Comment by hakasapl** [comment]
There is no space in R4-PA-C23

**Comment by msdisme** [comment]
So that would mean moving to OCT 10;  @naved001 should we use one of the additional brocade switches for now?

**Comment by naved001** [comment]
> should we use one of the additional brocade switches for now?

Sure, I don't know if we have any spares sitting out, but we could pull some out of engage1 and move it to OCT10.

**Comment by msdisme** [comment]
sorry I confused us. oct10 is just about adding different NICS.
