### ISSUE TITLE
Install 4 FX2's into OCT 4

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#723]
8x FC430's per FX2 = 32 Nodes

**Comment by hakasapl** [comment]
4x FX2 = 32x FC430s in total. Currently blocked on moving intel nodes. Both the intel issue and this issue should be completed next week

**Comment by msdisme** [comment]
Expectation is that these will move in the next 10 days and that the [provisioning](https://github.com/CCI-MOC/ops-issues/issues/758) will happen shortly after that..

**Comment by hakasapl** [comment]
4x FX2 machines (32 FC430s total) have been installed in R1-PC-C16 (OCT4).

**Comment by tzumainn** [comment]
@hakasapl hi! Does this mean that these machines are available for MOC ESI? If so, are the details available somewhere? Thanks!

**Comment by hakasapl** [comment]
Hi @tzumainn, no this issue was just for the installation. The issue tracking the provisioning of these nodes is [here](https://github.com/CCI-MOC/ops-issues/issues/758). Hoping to continue on that issue next week.

**Comment by tzumainn** [comment]
Gotcha, thanks!

**Comment by joachimweyl** [comment]
@hakasapl where in [R1-PC-C16](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/63/) did these end up?

**Comment by hakasapl** [comment]
4 FX2 chassis (2U each) going from U 1 to U 8
