### ISSUE TITLE
Letter to communicate 27th Kaizen OpenStack shutdown

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#725]
---
due: 2022-10-18
---

- [x] Draft Letter
- [x] Review Letter
- [x] Send Letter

## Subject

Oct 27th MOC Kaizen OpenStack Cluster Shutdown Reminder

## Body Option 1

Hello Kaizen Users,

We launched the Mass Open Cloud (MOC) with a vision of creating a production cloud that would enable innovation by a broad industry and research community.

The MOC has successfully supported hundreds of projects supporting thousands of users, transitioned research projects into upstream software artifacts, and formed a community of interrelated research projects.

One of those projects is the New England Research Cloud (NERC), a production cloud with professional operations and a team of experienced facilitators. The NERC supports OpenStack users today. **With that in mind, on October 27th MOC Kaizen OpenStack Cluster virtual machines will be shut down.**

If you are planning to migrate and are already communicating with Milson Munakami (mmunakami@g.harvard.edu) please continue to work toward migrating off of Kaizen. If you have not responded to Milson’s emails please do so immediately.

If you missed the previous communications about relocating your projects and wish to do so, please fill out this user survey immediately so we can begin your process as quickly as possible.
If you have questions please open a ticket at If you have questions, please open a ticket at https://mghpcc.supportsystem.com/ or email help@nerc.mghpcc.org.
Thanks!
Michael Daitzman

PS – If you were forwarded this email from a colleague and would prefer to receive these notifications directly, you may sign up for the kaizen-usersmailing list by sending an email to: kaizen-users-join@lists.massopen.cloud

## Body Option 2

Hello Kaizen Users,

**On October 27th MOC Kaizen OpenStack Cluster virtual machines will be shut down.**

If you are planning to migrate and are already communicating with Milson Munakami (mmunakami@g.harvard.edu) please continue to work toward migrating off of Kaizen. If you have not responded to Milson’s emails please do so immediately.

If you have questions please open a ticket at If you have questions, please open a ticket at https://mghpcc.supportsystem.com/ or email help@nerc.mghpcc.org.

Thanks!
Michael Daitzman

PS – If you were forwarded this email from a colleague and would prefer to receive these notifications directly, you may sign up for the kaizen-usersmailing list by sending an email to: kaizen-users-join@lists.massopen.cloud

**Comment by msdisme** [comment]
Minor tweaks:
## Subject

Oct 27th MOC Kaizen OpenStack Cluster Shutdown Reminder

## Body Option 1

Hello Kaizen Users,

**On October 27th MOC Kaizen OpenStack Cluster virtual machines will be shut down.**

We launched the Mass Open Cloud (MOC) with a vision of creating a production cloud that would enable innovation by a broad industry and research community.

The MOC has successfully supported hundreds of projects supporting thousands of users, transitioned research projects into upstream software artifacts, and formed a community of interrelated research projects.

The New England Research Cloud (NERC)is one of those projects a production cloud with professional operations and a team of experienced facilitators. The NERC supports OpenStack users today. **With that in mind, on October 27th MOC Kaizen OpenStack Cluster virtual machines will be shut down.**

If you are planning to migrate and are already communicating with Milson Munakami (mmunakami@g.harvard.edu) please continue to work toward migrating off of Kaizen. If you plan to migrate and have not responded to Milson’s emails please do so immediately.

If you missed the previous communications about relocating your projects and wish to do so, please fill out this user survey immediately so we can begin your process as quickly as possible.
If you have questions please open a ticket at If you have questions, please open a ticket at https://mghpcc.supportsystem.com/ or email help@nerc.mghpcc.org.

Thanks!

Michael Daitzman

PS – If you were forwarded this email from a colleague and would prefer to receive these notifications directly, you may sign up for the kaizen-users mailing list by sending an email to: kaizen-users-join@lists.massopen.cloud
