### ISSUE TITLE
MGHPCC 2023 Shutdown Post Testing

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#727]
With NERC
- [x] Test NERC Onboarding Login
- [x] Test NERC Onboarding Account Creation
- [x] Test NERC opc-prod nodes are up and running
- [x] Test logging into NERC via GitHub
- [x] Test NERC dashboard works

Us
- [x] MOC Ocp-prod cluster is reachable
- [x] Test SSO Nodes

**Comment by larsks** [comment]
I've verified that all of the `ocp-prod` nodes are up and running, login via github works, and access to the dashboard works.

I'm not sure what this means:

>- Test NERC ocp-prod controller addresses
>
>  Find out if this will be swapped to NERC network by then

**Comment by joachimweyl** [comment]
Updated to reflect new tests and remove less clear tests.
Removed curator test as it was not installed yet.

**Comment by joachimweyl** [comment]
@larsks can you test the public networks and SSO nodes?

**Comment by larsks** [comment]
@joachimweyl I'm not sure what exactly is covered by "the public networks", but I have verified access to both the nerc-ocp-prod and MOC ocp-prod clusters.

I have verified that MOC sso servers are working -- I can log into the ocp-prod console using sso credentials.
