### ISSUE TITLE
Remove labels from OCT nodes

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#729]
I'd like to relabel the OCT nodes to start at 01 instead of 00 (to match the U number). I'd like to then remove the labels that are printed on the nodes physically to reflect this.

**Comment by joachimweyl** [comment]
@hakasapl can you please include what labels are being removed and why?

**Comment by hakasapl** [comment]
I'd like to relabel the OCT nodes to start at 01 instead of 00 (to match the U number). I'd like to then remove the labels that are printed on the nodes physically to reflect this. Moving this to icebox for now, not a priority
