### ISSUE TITLE
Policy for removing "done" cards from main backlog

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#73]
When an issue is closed, cards move to the "Done" column in the spring backlog and in the main backlog. Should these done issues ever be removed from the main backlog? If not, over time the "done" column in the main backlog may grow large enough to be unwieldy.

**Comment by msdisme** [comment]
Proposal - remove from backlog after 1 week.

**Comment by larsks** [comment]
Closed via cci-moc/sprint-tools#28
