### ISSUE TITLE
Kaizen 2023 October 27th VM Shutdown

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#737]
Please shut down all VMs on Kaizen except those that are listed as "Partially Migrated" in the "Migration Status" column on the "Raw Form Data" sheet on [this worksheet](https://docs.google.com/spreadsheets/d/1Ke1VaKgL3M7bOlg9bGAYtNDhJMV1zh01HVUpo1J1WNE/edit?usp=sharing) at time of shutoff. You can use the "Project Name" column to find the name of the project you should not disable. Please also confirm with @joachimweyl that there are no updates to the "Awaiting Client Response" items. If he is not available reach out to Milson.
Execute the shutdown at 5 pm EST.

Ensure that the way in which the VMs are disabled is easy to enable. In case clients reach out once they notice it is shut down.

Please slack the coredev channel when the process starts and when it ends.

**Comment by naved001** [comment]
Instances are off and locked, except those that belong to the projects that are still migrating.
