### ISSUE TITLE
swap GPU rack with empty rack location 

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#743]
Scott has a location in mind.  This rack has 13 GPU's, we also should look at puttig some of these GPU's into OCT.  @hakasapl will add more details on the need their (eg. 740's and GPU's)

**Comment by hakasapl** [comment]
OCT uses Dell R740xds for the FPGA nodes, so it would be great if at least some of these nodes made it into OCT as hybrid GPU/FPGA nodes. There are currently 13 of them (2 arriving tomorrow), so 15 R740xds total. Some other HP gear has nvidia cards in them but we are not sure what they are at this point.

**Comment by msdisme** [comment]
@scott.yockel@g.harvard.edu - what location and can we give Hakan access.   Do you have a switch to put at TOR; do you need @hakasapl to update the firmware etc. or is that something you want to do?

**Comment by hakasapl** [comment]
@msdisme Will I be managing the lifecycle for these servers and do the initial firmware updates and such? If so, I'll need key access to R2-PC-C6

Is this rack empty currently and ready to be swapped? If so I can coordinate with the facility who will do the initial swap, I'll also need the approval of whoever owns that cabinet.

**Comment by msdisme** [comment]
@jtriley - Duplicating this from above: @[scott.yockel@g.harvard.edu](mailto:scott.yockel@g.harvard.edu) - what location and can we give Hakan access. Do you have a switch to put at TOR; do you need @hakasapl to update the firmware etc. or is that something you want to do?      These may be connected to the test cluster we want RHODS to use prior to being made generally available to NERC OpenShift.

**Comment by msdisme** [comment]
Initially make available to test cluster, then migrate to available to NERC.  Longer term, ESI for the hardware to enable migration.

**Comment by msdisme** [comment]
@hakasapl to confirm that 2-c-6 is empty.   if it has top of rack switches already Hakan to check with Nick A

**Comment by hakasapl** [comment]
After checking rack and w/ Nick, cc: Scott and Brian White

**Comment by joachimweyl** [comment]
@hakasapl where are these GPU servers currently?

**Comment by hakasapl** [comment]
Will be at MGHPCC tomorrow to check the rack key access and see if it's empty. If yes, I'll start the process with the facility for installing the rack.

**Comment by hakasapl** [comment]
The rack only has 2 switches and dangling cables, no nodes.

At U43: `MGHPCC-RC-2-C-6-SW2`
At U38: `MGHPCC-RC-2-C-6-SW1`

Who manages these switches and will they be in the GPU rack? If so, I'm happy to move them out of this rack and into the GPU rack, then do the rack swap. Looks like the PDUs in this rack will also work with the GPU nodes.

**Comment by hakasapl** [comment]
Email sent to Nick and Christian at Harvard networking, awaiting response

**Comment by hakasapl** [comment]
Rack is now empty - email sent to Kevin at MGHPCC to request the rack be swapped.

**Comment by hakasapl** [comment]
Rack swapped. Havard networking will install the switching, and some combination of them, techsquare, and I will do the cabling
