### ISSUE TITLE
Create reproducer for mariadb performance investigation

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/ops-issues#744]
In order to investigate the mariadb performance issues, we need a mechanism to reliably reproduce the behavior we're trying to investigate. This should include a set of deployable manifests and any necessary docker images to allow someone to deploy mariadb and xdmod, import test data, and produce timing results for those operations.

**Comment by joachimweyl** [comment]
notes from Rob's Standup
- was able to run the benchmarks (TPC and TPROC), neither finished
- adjusting the parameters of the benchmark to see what size will finish
- Haven’t gotten to the results
- Metrics are NOPM and TPM (Transactions per minute)
- runs long enough that we should be able to see a difference
- work on the pexpect script to run the benchmark in a job
- work on the job yaml
- find parameters that will permit the benchmark to finish.

**Comment by rob-baron** [comment]
Still having some difficulty getting things to finish, however got some data out of ocp-staging:

```
10170 MariaDB tpm
9516 MariaDB tpm
9246 MariaDB tpm
9984 MariaDB tpm
10230 MariaDB tpm
Vuser 1:Rampup 1 minutes complete ...
11190 MariaDB tpm
10326 MariaDB tpm
10140 MariaDB tpm
9552 MariaDB tpm
9288 MariaDB tpm
9600 MariaDB tpm
Vuser 1:Rampup 2 minutes complete ...
Vuser 1:Rampup complete, Taking start Transaction Count.
Vuser 1:Timing test period of 5 in minutes
9690 MariaDB tpm
9492 MariaDB tpm
9840 MariaDB tpm
10350 MariaDB tpm
10074 MariaDB tpm
9804 MariaDB tpm
Vuser 1:1 ...,
9576 MariaDB tpm
9492 MariaDB tpm
9294 MariaDB tpm
10080 MariaDB tpm
10254 MariaDB tpm
10092 MariaDB tpm
Vuser 1:2 ...,
10650 MariaDB tpm
10134 MariaDB tpm
10506 MariaDB tpm
10170 MariaDB tpm
9720 MariaDB tpm
9936 MariaDB tpm
Vuser 1:3 ...,
9390 MariaDB tpm
9912 MariaDB tpm
9630 MariaDB tpm
9138 MariaDB tpm
10140 MariaDB tpm
10380 MariaDB tpm
Vuser 1:4 ...,
10890 MariaDB tpm
9204 MariaDB tpm
9846 MariaDB tpm
9564 MariaDB tpm
9618 MariaDB tpm
9822 MariaDB tpm
Vuser 1:5 ...,
Vuser 1:Test complete, Taking end Transaction Count.
Vuser 1:1 Active Virtual Users configured
Vuser 1:TEST RESULT : System achieved 4278 NOPM from 9898 MariaDB TPM
Vuser 1:FINISHED SUCCESS
Vuser 1:RUNNING
Vuser 1:Ssl_cipher 
Vuser 1:Beginning rampup time of 2 minutes
Warning: a running Virtual User was terminated, any pending output has been discarded
Vuser 1:FINISHED FAILED
ALL VIRTUAL USERS COMPLETE
Vuser 1:RUNNING
Vuser 1:Ssl_cipher 
Vuser 1:Beginning rampup time of 2 minutes
Warning: a running Virtual User was terminated, any pending output has been discarded
Vuser 1:FINISHED FAILED
Vuser 2:FINISHED SUCCESS
Vuser 2:RUNNING
Vuser 2:Ssl_cipher 
Vuser 2:Processing 10000000 transactions with output suppressed...
Warning: a running Virtual User was terminated, any pending output has been discarded
Vuser 2:FINISHED FAILED
Vuser 2:RUNNING
Vuser 2:Ssl_cipher 
Vuser 2:Processing 10000000 transactions with output suppressed...
Warning: a running Virtual User was terminated, any pending output has been discarded
Vuser 2:FINISHED FAILED
9360 MariaDB tpm
```

So for an approximate baseline on  ocp-staging  System achieved 4278 NOPM from 9898 MariaDB TPM

**Comment by joachimweyl** [comment]
Hello @rob-baron,
What are the next steps for this reproducer?

**Comment by rob-baron** [comment]
The next steps are to:
1) deploy it as is on the NERC to see if we get a lower TPM on the nerc.
2) if we do get a lower TPM, work on a job that cleanly runs this task.

**Comment by joachimweyl** [comment]
Hello @rob-baron,
Based on your notes in Coredev this weekend it sounds like you were able to get past these issues and complete the testing. Does this also mean we have a reproducer?

**Comment by rob-baron** [comment]
This is completed as there are jobs defined in cci-moc/k-hammer to run hammerdb against mariadb backed by a PV and backed by an ephemeral disk.

**Comment by rob-baron** [comment]
from 27-NOV-2022:

Got clean runs from hammerdb, here are the results:
```
ocp-staging PV (persistent volume from ceph)
System achieved 2598 NOPM from 6098 MariaDB TPM

ocp-staging ephemeral disk (local disk)
Vuser 1:TEST RESULT : System achieved 9820 NOPM from 22831 MariaDB TPM

nerc PV (persistent volume from NESSE)
TEST RESULT : System achieved 231 NOPM from 536 MariaDB TPM

nerc ephemeral disk (local disk)
TEST RESULT : System achieved 13531 NOPM from 31481 MariaDB TPM
```

So, mariadb using the persistent volumes on the NERC is 11 times slower than the persistent volumes on the ocp-staging.  This also correlates well with the difference I see in run times of the shredder/ingestor between ocp-staging and on the NERC.

I am also ran it with mysql using an ephemeral disk.  The increase in disk speed accelerated the processing 58x.
It causes me to wonder why NESSE storage is that much slower than our ceph.  Is there a configuration issue or is it being throttling.

I also got clean runs from hammerdb.
