### ISSUE TITLE
Research "Unauthenticated email from massopen.cloud is not accepted due to domain's DMARC policy." in OSticket

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#748]
Multiple tickets in OSticket recently have had this issue.
https://osticket.massopen.cloud/scp/tickets.php?&number=001184
https://osticket.massopen.cloud/scp/tickets.php?&number=001185
https://osticket.massopen.cloud/scp/tickets.php?&number=001186

**Comment by naved001** [comment]
[This site](https://dnschecker.org/dmarc-record-validation.php) says our DMARC records look good.

![image](https://user-images.githubusercontent.com/20113064/201180226-ec5a10eb-f194-421b-a1c0-1fc485421db6.png)

I am sure there's more to it than that.

**Comment by msdisme** [comment]
Hello Michael,

Thank you for your email and I hope you're doing well. 

This is occurring as you currently have SMTP disabled for the address which means our mail servers are sending mail on your behalf, however, this is currently failing as you do not have an SPF record configured. 

You can resolve this by simply enabling SMTP for the address by going to Admin Panel > Emails > click on the email > go to the Outgoing (SMTP) Tab > Enable and configure SMTP then save changes. 

Please let us know if we can be of any assistance. 



-- 
Chloé Bowman
Controller of Chaos 

Enhancesoft 
parent company of


osTicket & SupportSystem
Alexandria, Louisiana 71301
phone: +1 (318) 290-3674
fax: +1 (318) 542-7958

**Comment by msdisme** [comment]
@larsks this is the ticket about mail will discuss with @naved001 tomorrow

**Comment by larsks** [comment]
That is pretty much the answer I predicted, and the solution is what we have previously discussed: we need to update our SPF records to include what addresses our osticket instance is using for sending out email.

**Comment by naved001** [comment]
@larsks Our current SPF record looks like
`"v=spf1 include:spf.massopen.cloud include:spf.protection.outlook.com ~all"`

I guess we will need to stick `ip4=<osticket's mail server>` into this? 

@msdisme can we ask supportsystem how they'd like us to configure our SPF records to allow their mail servers to send emails on our behalf?

**Comment by naved001** [comment]
```
naved@computer ~ % nslookup -type=TXT spf.massopen.cloud
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
spf.massopen.cloud	text = "v=spf1 ip4:209.85.192.0/19 ip4:34.204.145.35 ip4:104.47.32.0/19 ip6:2a01:110::/31 ip4:128.197.228.0/24 ip4:18.7.68.32/29 ip4:216.32.180.0/22 ip4:209.85.128.0/17 ip4:40.107.64.0/19 ip4:129.10.116.0/24 include:spfa.massopen.cloud ~all"
```

I don't understand why we have so many more ranges permitted.

**Comment by knikolla** [comment]
The above response seems to indicate you can `include`, and a very quick Google search seems to suggest that as well. Perhaps we can include `spf.supportsystems.com`.

**Comment by naved001** [comment]
@knikolla there's a text record, but it doesn't look like an SPF record
```
naved@computer ~ % nslookup -type=TXT spf.supportsystems.com
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
spf.supportsystems.com	canonical name = domainmarket-production-802845301.us-east-1.elb.amazonaws.com.

Authoritative answers can be found from:
us-east-1.elb.amazonaws.com
	origin = ns-1119.awsdns-11.org
	mail addr = awsdns-hostmaster.amazon.com
	serial = 1
	refresh = 7200
	retry = 900
	expire = 1209600
	minimum = 60
```

Where did you get it from?

**Comment by larsks** [comment]
> I guess we will need to stick ip4=<osticket's mail server> into this?

That's correct.

> I don't understand why we have so many more ranges permitted.

If only we managed DNS in git and had a change history! :)

> The above response seems to indicate you can include, and a very quick Google search seems to suggest that as well. Perhaps we can include spf.supportsystems.com.

That doesn't necessarily make sense (email from our ostick instance may not originate from the same systems that supportsystems.com uses for their own email). We should probably, as @naved001 suggests, contact supportsystems for the authoritative answer.  We could of course start by just examining one of the emails that osticket has sent out to determine the origin server.

**Comment by msdisme** [comment]
@naved001 How to contact them: https://supportsystem.com/contact-us/

**Comment by naved001** [comment]
@msdisme is testing this now

**Comment by msdisme** [comment]
Sent email to support@massopen.cloud and it does not appear to be getting to the database.

**Comment by msdisme** [comment]
sent mail to Kim at his gmail account, bounded: 
https://support.massopen.cloud/scp/tickets.php?id=1589 .  We need to get this addressed before we send the [openshift mail](https://github.com/cci-moc/ops-issues/issues/816)

**Comment by msdisme** [comment]
using https://support.massopen.cloud/scp/emailtest.php - sending mail from each account to joachim's email address.  
<img width="507" alt="Untitled 2" src="https://user-images.githubusercontent.com/6126065/221916371-83d1dcb2-c6cc-409e-9377-3b571da77431.png">

**Comment by joachimweyl** [comment]
That first one worked
![image](https://user-images.githubusercontent.com/28782106/221917333-59b892ff-3fcb-49f5-a026-61a6b3d9f603.png)

**Comment by joachimweyl** [comment]
support@moc.supportsystem.com worked
![image](https://user-images.githubusercontent.com/28782106/221919957-3c2084e9-7cd0-42c3-aa83-1883edf32f7c.png)

**Comment by joachimweyl** [comment]
alerts@moc.supportsystem.com also came through but went to spam

**Comment by joachimweyl** [comment]
neither of the messages from `@massopen.cloud` came through even the second time.

**Comment by msdisme** [comment]
they appear to have a problem primarily with gmail or gmail hosted accounts.  The error and link to [how to address](https://support.google.com/mail/answer/2451690) with google are below;

<joachim.weyl>: host gmail-smtp-in.l.google.com[142.251.116.27] said:
    550-5.7.26 Unauthenticated email from massopen.cloud is not accepted due to
    550-5.7.26 domain's DMARC policy. Please contact the administrator of
    550-5.7.26 massopen.cloud domain if this was a legitimate mail. Please
    visit 550-5.7.26  https://support.google.com/mail/answer/2451690 to learn
    about the 550 5.7.26 DMARC initiative.
    j1-20020aca1701000000b00383db99cd81si15103587oii.3 - gsmtp (in reply to end
    of DATA command)

Ref-Mid: B647c26-wz0A9-AAAAAAAAAAAAAAAAP547DUS1[-noreply@massopen.cloud](mailto:-noreply@massopen.cloud)</joachim.weyl>

**Comment by naved001** [comment]
Over email, supportsystems mentioned that they no longer support DKIM and only SPF, so if our DMARC policy requires DKIM then that could be the cause of failure. I think our DMARC policy requires DKIM, but I am still learning about it.

Other thing I noticed is that when I updated our SPF record to include supportsystems servers, it caused the number of DNS lookup to be more than 10, which is not allowed, so I need to figure out how to trim that down. Supportsystem's SPF record entry itself causes 6 DNS lookups! Maybe there's some trick to flatted DNS records which doesn't require us to manually update the TXT record with right IPs.

Still looking into this. I am going to find out why we have so many other IP ranges in our SPF records first.

**Comment by joachimweyl** [comment]
Hello @naved001,
In our testing [noreply@moc.supportsystem.com](mailto:noreply@moc.supportsystem.com) & [support@moc.supportsystem.com](mailto:support@moc.supportsystem.com) worked without going into spam. Would it work to use say [support@moc.supportsystem.com](mailto:support@moc.supportsystem.com) instead and that way it will not go to spam?

**Comment by msdisme** [comment]
Once we finalize this we should send a notification of changes to bulletins and put it on status page.

**Comment by naved001** [comment]
> In our testing [noreply@moc.supportsystem.com](mailto:noreply@moc.supportsystem.com) & [support@moc.supportsystem.com](mailto:support@moc.supportsystem.com) worked without going into spam.

Emails from those addresses also went into my spam folder. I asked supportsystem's support about why emails from their domain landed in my spam folder and this was their response:

> will say that we can be put on blacklists pretty easily due to the sheer volume of mail sent from our servers as well as the fact that we are a multi-tenant environment. This is why we do not recommend relying on our servers and instead recommend setting up your own SMTP for best email deliverability.

so I don't know what's a fool proof way to prevent emails going to spam.

> Would it work to use say [support@moc.supportsystem.com](mailto:support@moc.supportsystem.com) instead

All things considered, I would say yes because emails from their domain pass both, DMARC and SPF, checks.

**Comment by joachimweyl** [comment]
The plan is to set osTicket Admin>Emails>Settings
Default System Email to `support@moc.supportsystem.com`
Default Alert Email to `alerts@moc.supportsystem.com`
Once the [communication email](https://github.com/CCI-MOC/ops-issues/issues/841) is reviewed and signed off on being sent we will make this change.

**Comment by joachimweyl** [comment]
outgoing addresses updated. Communication was sent out. The status page was updated.
