### ISSUE TITLE
Provision FX2 FC430 machines in OCT4 for OKD & ESI

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#758]
1. 32 nodes
   1. 21 for OKD
   1. 10 for ESI testing
   1. 1 spare

**Comment by hakasapl** [comment]
Blocked on MGHPCC swapping PDUs in this rack

**Comment by hakasapl** [comment]
The machines are cabled up other than power. Hoping for a PDU swap next week

**Comment by larsks** [comment]
@msdisme to follow up on whether this happens or not this week.

**Comment by hakasapl** [comment]
PDU swap is scheduled for next week, I will comment again once they have been swapped.

**Comment by naved001** [comment]
@msdisme good point, it's mostly the ESI developers who are currently using it and they should be notified. 

@tzumainn there will be some planned downtime when PDUs are swapped for the OCT4 rack (which hosts the ESI hardware).

**Comment by tzumainn** [comment]
ah, thanks for the heads up! is this happening early next week?

@DanNiESh just an FYI

**Comment by hakasapl** [comment]
I'll update you with the exact day once I find out, I'm checking in with the team doing the swap today. It should be this week, although nothing but the management network (ipmi) should be affected since everything is on dual psu.

**Comment by hakasapl** [comment]
@tzumainn is now/the next hour a good time for the IPMI network to go down in the ESI rack? I am not expecting any downtime on the nodes themselves and the data connections should stay live, however, if there's anything critical going on these nodes currently I'd like to wait until a less critical time.

**Comment by hakasapl** [comment]
@tzumainn this is now scheduled for tomorrow morning. Let me know if we should hold off briefly downing the IPMI network during that time.

**Comment by tzumainn** [comment]
That should be fine - thanks!

**Comment by hakasapl** [comment]
PDUs have been swapped. I'm planning on provisioning the FX2 nodes the week of the 23rd of January.

**Comment by joachimweyl** [comment]
need to have groups in sets of groups of 8

**Comment by hakasapl** [comment]
For posterity for future FX2:
* Remove CMC and apply jumper on password reset pin
* Plug in server
* Use [this cable](https://www.amazon.com/dp/B0769DVQM1?psc=1&ref=ppx_yo2ov_dt_b_product_details) at baud rate 115200 8N1 config
* `root` and `calvin`
* `racadm racresetcfg` to restore factory defaults
* *wait for reset*
* Login again with default credentials and run `racadm setniccfg -d` to enable dhcp and `racadm getmacaddress` to get the mac address for the dhcp server
* Power off the server and remove the CMC, remove jumper, reinsert into server and plug in power and network to the CMC
* In the CMC UI, factory reset each individual idracs for the servers and reset them to DHCP

**Comment by msdisme** [comment]
Michelle asks in [#okdmoca](https://massopencloud.slack.com/archives/C04ESBF09RD): `we are excited to begin work trying to wire things up from our end. What's the best way for MOC folks to hand our team API specs and credentials?`

**Comment by hakasapl** [comment]
OKD control node ready, ESI nodes enrolled but has some issues with inspection.

**Comment by hakasapl** [comment]
ESI node issues tracked here: https://github.com/CCI-MOC/esi/issues/357
OKD node is ready and awaiting users. Closing this ticket for now
