### ISSUE TITLE
Migrate HIL & BMI Grad students to the new project locations

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#761]
Once we decide where we will be migrating the HIL & BMI projects we need to facilitate that move.

**Comment by knikolla** [comment]
Some students have experiments that are running until some point in March and don't want to move. We need to provide a deadline and coordinate getting initial access and documentation.

**Comment by tzumainn** [comment]
@knikolla is there someone I can talk to regarding how they currently use HIL/BMI? If so, I can start tailoring documentation towards their needs.

**Comment by joachimweyl** [comment]
@tzumainn please see my comment [here](https://github.com/cci-moc/ops-issues/issues/783#issuecomment-1448338909) about someone to talk to.
