### ISSUE TITLE
Decide where to move the HIL & BMI projects to

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#762]
The plan is to close down the HIL & BMI Service. We currently have 4 Grad students with projects on these nodes. The plan is to move them off of these nodes onto other nodes. One idea so far is to take the same nodes they are currently using and move them over to ESI and start them up again on those.
This issue is to track the decision we make and to raise ideas of how best to migrate them off of the current HIL & BMI Nodes.

**Comment by naved001** [comment]
> The plan is to close down the HIL & BMI Nodes.

Is that accurate? I think we only want to shut off HIL & BMI service, but not the nodes. The only nodes we would want to decommission would be the Cisco nodes (mostly in Sahil's projects).

> One idea so far is to take the same nodes they are currently using and move them over to ESI and start them up again on those.

Yes, I think that's what we should do, move the non-cisco nodes to be controlled by ESI. We would have to write a switch driver for Brocade and Cisco switches for ESI for this to work. That'd also allow us to add the OpenStack nodes (once it's shut down completely) to ESI in future.

**Comment by msdisme** [comment]
@okrieg thought you would like to see this. It means moving grad students to ESI instead of to cloudlab, at least initially, as a way to get more hours on ESI.

**Comment by joachimweyl** [comment]
@okrieg agrees with ESI

**Comment by joachimweyl** [comment]
Decision has been made to go with ESI
