### ISSUE TITLE
Github for tracking OKD

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#770]
Hi @derekhiggins @rdoxenham and @LorbusChris.  Would you prefer to use one of your existing GitHub repositories for tracking work with the MOC Alliance or have us create one for tracking?

We figure that ops-issues is probably a lot of noise for you guys:-).

**Comment by derekhiggins** [comment]
Hi @msdisme , I'm ok with anything which ever works out best for you, Once I'm tagged on the issue it doesn't matter which repository its on.

**Comment by LorbusChris** [comment]
+1 to what @derekhiggins said :) 
Let me know if you want me to create a repo in https://github.com/okd-project

**Comment by msdisme** [comment]
I think we'll create one in the MOC and make you guys admins if that is ok with you!

**Comment by LorbusChris** [comment]
sure, that works just as well!

**Comment by msdisme** [comment]
@LorbusChris  I misread your initial suggestion let's go ahead and do it at OKD and we will wrap it into our zenhub board so it shows up on our todolists :-).   Can you please add the following  people to the repository so you may assign us stuff: @hakasapl, @naved001, @larsks , @msdisme , @joachimweyl ,@knikolla,  @rob-baron

**Comment by LorbusChris** [comment]
I've created https://github.com/okd-project/moc and invited all of you to the org and MOC team on OKD :)
