### ISSUE TITLE
Write documentation for how to add/invite people to ZenHub and related boards

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#773]
Steps to include
1. Adding them to the appropriate GitHub Repos
1. Sharing a link to the appropriate ZenHub Workspace
1. Steps to create a ZenHub Account if you don't have one
1. Steps to linking ZenHub to GitHub
1. Steps to create your own ZenHub Workspace if you wish
make sure to use GitHub and ZenHub documentation as much as possible so it shows users where to get information in the future.
[Document](https://docs.google.com/document/d/1eribTLT9TaD--pEF4Jf42kdqQDYFbrZjMuEtvY88Ick/edit?usp=sharing)

**Comment by taramoran** [comment]
@joachimweyl I'll take a look when this meeting ends at 2:30!

**Comment by joachimweyl** [comment]
Wow, thank you!

**Comment by taramoran** [comment]
@joachimweyl looks good! I made a few small spelling/formatting edits, but content-wise I think it's very clear and easy to follow.

**Comment by joachimweyl** [comment]
Much appreciated!

**Comment by joachimweyl** [comment]
Will close issue once we have someone new test it out.

**Comment by joachimweyl** [comment]
steps used by Peter.
