### ISSUE TITLE
Write ansible switch driver for brocade switch to make HIL hardware available in ESI

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#777]
This is the fastest way to move people from HIL to ESI as good chunk of servers in the MOC racks are connected using brocade switches.

**Comment by naved001** [comment]
@tzumainn just a heads up that I am planning to do this sometime next week. I will ask you for your review.

**Comment by knikolla** [comment]
Does this include getting the driver merged upstream?

**Comment by naved001** [comment]
@knikolla yes, that's where I will submit it. We have done that in the past for a couple of other switches and they are quick to review/respond.

**Comment by knikolla** [comment]
> @knikolla yes, that's where I will submit it. We have done that in the past for a couple of other switches and they are quick to review/respond.

Awesome!

**Comment by naved001** [comment]
PR here: https://github.com/ansible-network/network-runner/pull/73

**Comment by joachimweyl** [comment]
done. PR approved but not merged.
