### ISSUE TITLE
order cables for data center

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#782]
@tara please order 8 of these: https://www.fs.com/products/36009.html for delivery to the mghpcc, attention Hakan Saplakogu

**Comment by joachimweyl** [comment]
@taramoran have these been ordered?

**Comment by taramoran** [comment]
@joachimweyl they were ordered but delivered late on Friday, waiting for Hakan to confirm he has them before I close the ticket!

**Comment by taramoran** [comment]
confirmed receipt!
