### ISSUE TITLE
Assist Grad student/s in learning ESI so they can manage the machines previously on HIL & BMI

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#783]
We need to train them on the bare metal tools as well as the OS provisioning system. To help them translate what ESI provides it might help to let them know that the ESI bare metal tools are like HIL and the OS provisioning system is like BMI.

- [x] Track down if we have any documentation that would help train the grad students how to use ESI.
- [ ] Work with Grad students to migrate them to ESI nodes

**Comment by joachimweyl** [comment]
documentation here https://esi.readthedocs.io/en/latest/

**Comment by joachimweyl** [comment]
provided links to grad students specifically pointing to the parts that will help them recreate their projects in ESI based on their HIL and BMI experience.

**Comment by joachimweyl** [comment]
@naved001 do we have some of the HIL nodes that are not in use that we could move over to ESI so that the grad students could have an ESI sandbox to get a feel for how it works? bu-23-101, neu-03-10, neu-03-12, neu-05-12, neu-15-11, neu-17-25, neu-17-34, neu-17-35, neu-17-38, neu-19-34, neu-19-38, neu-19-7 are not currently in use and would be a good starting set of nodes for the sandbox.

**Comment by naved001** [comment]
@joachimweyl thanks for that list of nodes. That's kind of what I had in mind:

| server | status | comment |
| -------|-------|----------|
| bu-23-101 | pending| need to register it's switch first |
| neu-3-10 | migrated | - |
| neu-3-12 | didn't migrate | not booting in ESI, solarflare nic is not detected in ipxe |
| neu-5-12 | didn't migrate | solarflare nic may not get detected in ipxe |
| neu-15-11 | migrated | - |
| neu-17-25 | pending | it's cisco, should I even migrate it?| 
| neu-17-34 | didn't migrate | not booting in ESI, solarflare nic is not detected in ipxe |
| neu-17-35 | didn't migrate | not booting in ESI, solarflare nic is not detected in ipxe |
| neu-17-38 | didn't migrate | the node is broken, random boot failures |
| neu-19-34 | migrated | - |
| neu-19-38 | migrated | ESI inspection fails, needs some work |
| neu-19-7 | didn't migrate | the node is broken, random boot failures |

So there are 2 more nodes that can be migrated, and 1 of those nodes requires the registration of its switch into ESI first. 

I guess all in all, we'll have 6 nodes from HIL available in ESI.

**Comment by joachimweyl** [comment]
@hakasapl do we have NICs we know that work in ESI that we can put in the Nodes with solarflare NICs?
@naved001 is the cisco question because we are planning to decommission the cisco nodes?

**Comment by hakasapl** [comment]
We should be able to get the solarflare cards to pxe boot, we make use of these nics in OCT gear and have to enable some features in the boot menu for pxe to work. @naved001 do you mind if I take care of looking at the NICs for those 4 nodes? I assume they are offline at this point and I can reboot them as I wish?

**Comment by naved001** [comment]
@joachimweyl The weird thing is, as far as I can remember all these solarflare NICs would work with ipxe just fine but now all of a sudden they don't show up. We could swap out the NICs but that should be the last resort. 

re: cisco node, yeah that was my thought but I went ahead and registerd it in ESI, let's see if it passes inspection.

**Comment by naved001** [comment]
@hakasapl The nodes pxe boot just fine. The problem starts after they load ipxe. Within ipxe, the solarflare NICs aren't visible so it can't continue the chain-booting process.

In the past when making things work for BMI, I snuck in [changes to ipxe ](https://github.com/ipxe/ipxe/compare/master...naved001:ipxe:add-sfc-9020)to make it support some of the solarflare NICs. However, that doesn't make it work with all solarflare NICs, for instance, neu-3-12 has a similar NIC
```
ubuntu@proper-liger:~$ lspci |grep -i sfc
04:00.0 Ethernet controller: Solarflare Communications SFC9020 10G Ethernet Controller
04:00.1 Ethernet controller: Solarflare Communications SFC9020 10G Ethernet Controller
```
though it's model number is SFC6122, and I guess that's different enough. I thought the "SFC9020" device ID is the same as the other one so it would work, but it didn't :(

You could take a look around if you want, the machines aren't registered in ESI though. But you could boot ipxe from an ISO or I can pxe boot if you have some ideas. 

cc: @tzumainn @larsks

**Comment by naved001** [comment]
@tzumainn for the nodes that have issues with ipxe, can we change boot interface so that it does the regular pxe boot over tftp? That would make iSCSI boot unavailable for those nodes, but I think that should still make them functional.

**Comment by tzumainn** [comment]
The boot_interface can be set to 'pxe' for an Ironic node; I'm not entirely sure if it'll result in what you want, but it sounds like it may be worth testing?

**Comment by naved001** [comment]
@tzumainn I tried that with node neu-17-34, and it seems to still boot ipxe.lrkn and then run into the same problem described earlier. I feel it's not worth wasting our time over at this point.

**Comment by joachimweyl** [comment]
@naved001 5 nodes are a good start. What do we need to do to provide access to these nodes in ESI to the Grad Students?

**Comment by naved001** [comment]
I guess @tzumainn can setup an account for people to test ESI.

**Comment by tzumainn** [comment]
Yep, that's something I can do! I'm just hoping to have some communication first regarding what they'd expect, so I can make sure the documentation is prepared appropriately.

**Comment by joachimweyl** [comment]
@tzumainn the students that will need accounts are in the email I just sent to you. Feel free to respond to that email to gather information, although that chain is pretty long so it is worth just checking with me to see if they already answered your question further back in the chain so you don't have to read the whole chain.

**Comment by tzumainn** [comment]
@joachimweyl hi! I'm trying to parse the thread, and right now it sounds like:

* Amin Mosayyebzadeh has specialized machine needs that may not be met by the nodes currently in MOC ESI
* Sahil Tikale will be done "soon" (as of January) and maybe feels no need to use ESI since he's almost done with his experiments and will be graduating?
* Tommy Unger may be a good candidate for ESI 
* Eric Munson, Ali Raza, Mania Abdi, Han Dong are question marks

Does this sound about right?

**Comment by joachimweyl** [comment]
@tzumainn that sounds correct to me. The slight modification I would make is that Amin's needs are currently met by the HIL/BMI hardware he has so if we migrate that hardware to ESI he would have the hardware he needs. The outstanding question there is if there is a way to migrate without losing information on the hard drives.

**Comment by tzumainn** [comment]
@joachimweyl do you think I should reach out to specific students directly, or do so by replying to the entire chain?

**Comment by tzumainn** [comment]
Will do - thanks!

**Comment by joachimweyl** [comment]
@tzumainn do you feel the grad students know ESI well enough to use it for their projects?

**Comment by joachimweyl** [comment]
will leave this open until we have more research nodes ready for them and then we will see how they do migrating to them.

**Comment by joachimweyl** [comment]
so far all researchers have migrated without issue. closing.
