### ISSUE TITLE
Move HIL Hardware over to ESI

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#788]
HIL hardware needs to be migrated to ESI so that the grad students can use ESI to manage their hardware.

- [ ] Gather a list of switches that this hardware resides on
- [ ] Ensure switches are ready for hardware "move"
- [ ] Swap hardware in this [list](https://docs.google.com/spreadsheets/d/1CE6WxrRywmlqE6UBtbJFb9JEB7tzPftAldHfdtyQ4P8/edit?pli=1#gid=792619724) with no associated project to ESI
- [ ] Swap hardware associated with projects as the project leads say they can have downtime on their project

**Comment by joachimweyl** [comment]
This should be broken down into batches of hardware as it will take more time than originally expected.

**Comment by joachimweyl** [comment]
@naved001 Thank you for moving some of the HIL/BMI hardware. I know some of the hardware proved difficult and some impossible to migrate. Do we know of a way to test which hardware will migrate and which will not?

**Comment by naved001** [comment]
> Do we know of a way to test which hardware will migrate and which will not?

I think some hardware that I know which will work easily are the cisco servers, though I may need to register a couple of cisco switches (shouldn't be that hard) to migrate all the cisco servers. I *think* most cisco servers are used by Sahil.

Other nodes that should work right out of the box are the ones that use non-solarflare NICs, so I could write a script which will query HIL for each node's mac address and find out which of those NICs are not using Solarflare cards.

**Comment by joachimweyl** [comment]
@naved001 that sounds like a great way to gather the information remotely, great idea. A few nodes that I know off to top of my head that the Grad Students are hoping will migrate easily are the ones with SSD
1. neu-03-12 - Intel(R) GbE 4P I350-t rNDC
1. neu-05-10 - Intel(R) GbE 4P I350-t rNDC
1. neu-05-12 - Intel(R) GbE 4P I350-t rNDC
1. neu-05-30 - Intel Corporation Ethernet Controller 10-Gigabit X540-AT2
1. neu-17-34 - Intel(R) GbE 4P I350-t rNDC
1. neu-17-35 - Intel(R) GbE 4P I350-t rNDC
1. neu-17-38 - BRCM 10G/GbE 2+2P 57800 rNDC

and some with nvme & SSD
1. neu-03-41 - Intel Corporation I350 Gigabit Network Connection
1. neu-05-41 - Intel Corporation I350 Gigabit Network Connection
1. neu-15-41 - Intel Corporation I350 Gigabit Network Connection
1. neu-17-41 - Intel Corporation I350 Gigabit Network Connection
1. neu-19-41 - Intel Corporation I350 Gigabit Network Connection

and some desired for other reasons
1. neu-03-03 - BRCM 10G/GbE 2+2P 57800 rNDC
1. neu-03-04 - BRCM 10G/GbE 2+2P 57800 rNDC
1. neu-05-09 - Intel(R) GbE 4P I350-t rNDC
1. neu-05-11 - Intel(R) GbE 4P I350-t rNDC
1. neu-15-01 - BRCM 10G/GbE 2+2P 57800 rNDC
1. neu-15-03 - Intel(R) GbE 4P I350-t rNDC
1. neu-15-10 - Intel(R) GbE 4P I350-t rNDC
1. neu-15-16 - Intel X520-DA2 10 Gbps 2 port NIC
1. neu-17-37 - BRCM 10G/GbE 2+2P 57800 rNDC

**Comment by naved001** [comment]
> Intel(R) GbE 4P I350-t rNDC

This is an integrated 1GbE NIC, and those are not connected. Anything 1GbE in the neu racks is basically not connected.

The inventory sheet captured all the NICs (if that's where you got this from), you'll notice that there are 4 columns for NICs (Network 1 to Network 4), and sometimes the non-integrated NICs show up in other columns and those maybe the ones of interest.

> Intel Corporation Ethernet Controller 10-Gigabit X540-AT2
> BRCM 10G/GbE 2+2P 57800 rNDC

These are the good NICs. So those servers will most likely boot with ESI. Are these servers ready to be migrated?

**Comment by naved001** [comment]
> 
    neu-03-41 - Intel Corporation I350 Gigabit Network Connection
    neu-05-41 - Intel Corporation I350 Gigabit Network Connection
    neu-15-41 - Intel Corporation I350 Gigabit Network Connection
    neu-17-41 - Intel Corporation I350 Gigabit Network Connection
    neu-19-41 - Intel Corporation I350 Gigabit Network Connection


This was brought up in the email thread, but I think it's not really worth migrating this to ESI right now, as their use case is very static. They are neither doing any rapid provisioning on these machines nor are they manipulating networks on those nodes.

Also, I am sure those machines are installed to disk, so registering those in ESI will wipe out the disk (unless there's some trick @tzumainn knows to prevent that).

**Comment by joachimweyl** [comment]
> Are these servers ready to be migrated?

Not yet, but it is great to know they can be migrated easily.

**Comment by joachimweyl** [comment]
We are deprecating HIL hardware and spinning up a whole new Rack for Research use.
