### ISSUE TITLE
Decide where to install the Pre-NERC version of RHODS

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#789]
Discussion with Erwan Granger, Orran Krieg, Heidi & Michael

**Comment by joachimweyl** [comment]
Decision was made to use the NERC Test cluster

**Comment by knikolla** [comment]
@joachimweyl Which one is the NERC Test Cluster?

**Comment by joachimweyl** [comment]
The current test cluster is installed [here](https://console-openshift-console.apps.nerc-ocp-test.rc.fas.harvard.edu/). RH team is going to reinstall OpenShift since the version there currently is 4.8.
