### ISSUE TITLE
Update U numbers for OCT9

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#799]
They are missing info in this doc: https://docs.google.com/spreadsheets/d/1V4_24MEQvpQaEIWOY9CT3zMeu_7llBagkYRxAIsJ1a4/edit#gid=26142192

**Comment by hakasapl** [comment]
Already in netbox

**Comment by hakasapl** [comment]
Need to check OCT9 U numbers still

**Comment by hakasapl** [comment]
@joachimweyl I've updated the U numbers in the oct inventory spreadsheet

**Comment by joachimweyl** [comment]
> Already in netbox

half of them are but the rest are not in Netbox yet.
