### ISSUE TITLE
Add function to generate a report for usage through XDMOD

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#801]
Rob: One useful thing that is probably easy is to generate a report that lists projects, cpu hours, memory used and who is starting those resources.  Currently all of those things exist as I see them in the interface.

Data dump through the UI.
UI should have a repeated report option.

**Comment by joachimweyl** [comment]
@hakasapl is this a high enough priority that you plan to get to this issue this sprint?

**Comment by hakasapl** [comment]
I will likely get to this towards the end of this sprint, I'm planning on pulling something else out though because I won't have time

**Comment by joachimweyl** [comment]
@hakasapl are you planning to finish this for this sprint? If not we should pull it out and put it into next sprint.

**Comment by hakasapl** [comment]
I'll circle back to this on Monday

**Comment by hakasapl** [comment]
Closing this for now, will reopen if the issue comes up again
