### ISSUE TITLE
Dell/Lenovo repurachase option for hardware

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#802]
Option for exchangeing old hardware for newer hardware.
Related to: #796 and #803

**Comment by joachimweyl** [comment]
@waygil did we get a response from Dell?

**Comment by joachimweyl** [comment]
@waygil how did your conversation with Dell go?

**Comment by msdisme** [comment]
@waygil Got initial feedback from Dell - price structure is such that it does not make sense at this time.
