### ISSUE TITLE
OKD team migration to ESI for hardware

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#806]
- [x] https://github.com/CCI-MOC/esi/issues/360
- [x] https://github.com/CCI-MOC/ops-issues/issues/706
- [x] https://github.com/CCI-MOC/ops-issues/issues/713
- [x] https://github.com/CCI-MOC/ops-issues/issues/758
   - [x] https://github.com/CCI-MOC/esi/issues/357
- [x] https://github.com/CCI-MOC/ops-issues/issues/805 
- [x] OKD team successfully installs OKD on the ESI provisioned hardware

**Comment by joachimweyl** [comment]
@msdisme based on what is involved in this it sounds to me like it is essentially represented by the [OKD on ESI](https://github.com/CCI-MOC/ops-issues#workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTExNDA3) Epic. Thoughts?
