### ISSUE TITLE
IPMI Query to gather missing serial numbers for netbox

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#809]
As I work through Netbox I will add new nodes here that are missing their serial numbers.

or is there a way to automatically scan all our nodes? or at least all nodes in one cage?

1. [bu-23-11, 15, ](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/57/)
1. [neu-3-1 - 14, 21 - 29](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/49/)
1. [neu-5-1 - 13, 21 - 29](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/50/)
1. [neu-15-1 - 11](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/51/)
1. [neu-15-16 - 23, 26 - 33](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/51/)
1. [neu-17-6 -10](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/52/)
1. [neu-17-12](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/489/)
1. [neu-17-23 - 40](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/52/)
1. [neu-19-8](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/530/)
1. [neu-19-6 - 8, 23 - 32](https://netbox.apps.ocp-prod.massopen.cloud/dcim/racks/53/) 
1. All the blades in [kumo_dell_blades](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/347/device-bays/)
1. there are probably more

There are also some that have a serial of 0123456789

1. [neu-3-41](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/331/)
1. [neu-5-41](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/329/)
1. [neu-15-41](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/330/)
1. [neu-17-41](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/327/)
1. [neu-19-41](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/328/)

**Comment by naved001** [comment]
For the systems that we have their serial numbers for, I was able to get those [from within the operating system](https://github.com/CCI-MOC/moc-ansible-netbox/blob/main/register-system.yaml#L36) because those machines had an OS that we could access. 

There maybe a way to get this using iDrac (for dell systems), but I want to understand the need for gathering the serial number or asset tags before trying to figure out if it can be done or not.

**Comment by joachimweyl** [comment]
This is not a high-priority issue. It is one more thing to consider, how we want to keep track of them.

**Comment by joachimweyl** [comment]
all of this will be deprecated soon.
