### ISSUE TITLE
Create an External to NERC MariaDB Instance with NESE Backing Store

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#810]
In order to continue evaluating mariadb performance issues in NERC, we should deploy an instance of mariadb outside of nerc, but still use NESE as the storage. This will allow us to eliminate NERC/openshift as a variable and also work on fine tuning mariadb parameters in a live test environment before committing changes to NERC.

This will require reaching out to Milan to get an "moc-general" allocation sized at around 1 TB. It will then be deployed in a VM in ovirt.

**Comment by hakasapl** [comment]
Pools have been created. 2 1TB pools in NESE for testing purposes, one is named `moc-rbd-general-replicated` and the other ` moc-rbd-general-erasure`. One is a replicated rbd, the other erasure coded. It would be valuable to test the latency of both. The ceph key will be in bitwarden with name `nese moc-rbd-general`

**Comment by msdisme** [comment]
who is doing the perf testing against this?

**Comment by hakasapl** [comment]
Initial performance tests are here: https://github.com/OCP-on-NERC/operations/issues/6

I will work on hammerdb in a different ticket
