### ISSUE TITLE
Ensure RHODS is using BU AWS licenses

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#818]
Work with Gerard to get our licenses used so we are not paying for capabilities we already own.

**Comment by gshockbu** [comment]
I would suggest 5 licenses to mitigate the current number of clusters. I'd expect us to settle back to 3 (Dev/test/Prod) in the future.

**Comment by LEgregius** [comment]
@msdisme What do you mean by both use cases?  By moving them to ROSA and back? I'm sure you will have to contact Red Hat sales in both cases.

**Comment by msdisme** [comment]
@LEgregius great, thanks!

**Comment by joachimweyl** [comment]
@msdisme what are the next steps for this issue?

**Comment by msdisme** [comment]
Heidi discussing with Hugh. Cannot move back so need to decide worth doing

**Comment by joachimweyl** [comment]
@msdisme who do we need to get together to make this decision?

**Comment by joachimweyl** [comment]
@msdisme I belive the decision was to not move the licenses. What are the next steps for this issue?

**Comment by msdisme** [comment]
end of semester, did not get resolved, lower priority then other stuff
