### ISSUE TITLE
Determine best endpoints for a dual link to Harvard/NERC

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#823]
Ideally, this connection would be at least 80G (2x40G), and ideally to 2 different switches on the Harvard side. On the OCT side the connection should connect to 2 out of 4 of the hub switches.

THis is to enable access to the FABRIC project.  So, for example Layer 2 can cross multiple data centers.

**Comment by msdisme** [comment]
Ideally the endpoints at HU should be in a place which allows for ESI control to ensure future compatability.

**Comment by msdisme** [comment]
Need to gather details for presentation Nick

**Comment by hakasapl** [comment]
Here is a network diagram which is up-to-date with the OCT network (which also has non-OCT things in it)

[OCT-overview - Page 1 (2).pdf](https://github.com/CCI-MOC/ops-issues/files/10807471/OCT-overview.-.Page.1.2.pdf)

**Comment by joachimweyl** [comment]
> @joachimweyl Need to gather details for presentation

I will review with @hakasapl & @jtriley to get further details on this.

**Comment by hakasapl** [comment]
The [FABRIC](https://fabric-testbed.net/) project is an ongoing NSF-supported project which aims to connect different testbeds and clouds across the country. The idea is that a user could make an allocation in NERC at MGHPCC, and also make an experiment at CloudLab Utah, and both instances can be on the same L2 network. FABRIC already has an installation at MGHPCC connected to the OCT network. They are just now starting to get this working with OCT on the UMass end, but have expressed interest in doing the same for NERC once it's up and running fully.

**Comment by hakasapl** [comment]
Document to outline spec for link: https://docs.google.com/document/d/1waxt2U3wh_strc2YJacumOC9VTtx9wv0bcCV5GfN-uw/edit#

**Comment by joachimweyl** [comment]
@hakasapl are we still working on this or is this process in somebody else's hands for a while? If so let's push this out of the current sprint and pull it back in when we have something we can do on it.

**Comment by hakasapl** [comment]
I'm still working on this on and off this sprint

**Comment by hakasapl** [comment]
Closing this because requirements for this have changed and new issues will be made.
