### ISSUE TITLE
Add OCT TORS into ansible switch repo

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#828]
The following switches need YAML configurations created:
* `CL-SW-TORS`
* `OCT1-SW-TORS`
* `OCT2-SW-TORS`
* `OCT3-SW-TORS-A`
* `OCT4-SW-TORS`
* `OCT5-SW-TORS-A`
* `OCT5-SW-TORS-B`
* `OCT6-SW-TORS-A`
* `OCT7-SW-TORS`
* `OCT8-SW-TORS`
* `OCT9-SW-TORS-A`
* `OCT9-SW-TORS-B`

**Comment by joachimweyl** [comment]
@hakasapl what are the next steps for the creation of the YAML?

**Comment by hakasapl** [comment]
I have a PR for this already: https://github.com/CCI-MOC/ansible-switches/pull/21, I wanted Naved to take a last pass at it so I'm waiting until next week to merge.
