### ISSUE TITLE
DISC Training Sharing

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#837]
Please share your DISC evaluations via: https://myeverythingdisc.com/MyAccount.aspx

![Untitled.png](https://images.zenhubusercontent.com/62b0bcb4ba912dbb31713c09/8f7f5ca6-b17b-40ae-bf8c-410f02047c71)

The second item, Auto-Accept is what keeps you from needing to log in all the time.

**Comment by naved001** [comment]
Done. Is this something that BU mandates?

**Comment by knikolla** [comment]
Done.

**Comment by rob-baron** [comment]
Done.

**Comment by hakasapl** [comment]
Done
