### ISSUE TITLE
neu-17-38 will sporadically fail to boot

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#84]
IPMI controller reports that the system is in "Critical State". 

![image](https://user-images.githubusercontent.com/20113064/101780701-d6ff7900-3ac4-11eb-90db-75b84bb427e3.png)

Investigate what's wrong with it. This system is being used for Ilana's CNV deployment.

**Comment by larsks** [comment]
The system is logging a memory error when it boots.

**Comment by naved001** [comment]
I ran some diagnostic tests that are available in the lifecycle controller but they don' return anything (the screen goes blank).

It seems to fail to boot for different reasons:
1. PCIe system error
2. PCIe training error
3. idrac reports CPU1 has issues
4. Some memory issues, but I think it's not worth replacing the bad DIMMs because the other issues.

We probably want to keep it for parts because I can't think we can fix it without spendin $$$ on this machine.
