### ISSUE TITLE
Fix access for mghpcc

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#840]
- [x] Naved
- [x] key 7 for  Simon Leary from UMass on the keyring, who is a student working with Mike Zink in OCT. He needs to work on some hardware in OCT8

**Comment by msdisme** [comment]
@hakasapl  did Simon get the access he needed?   Do I need to revoke it at any time?

**Comment by hakasapl** [comment]
He hasn't tried yet - I was waiting for confirmation from you that the key access was approved.

**Comment by joachimweyl** [comment]
@hakasapl assuming @msdisme's comment is the confirmation can we check with Simon to confirm he has the needed access? Can we also confirm if we need to revoke his access or if it will automatically be revoked?

**Comment by hakasapl** [comment]
He should keep access for the time being, he'll have some work to do in OCT. We can reevaluate in a few months, but I suspect just not renewing his access at the end of the year will be fine.

**Comment by joachimweyl** [comment]
@msdisme closing this issue with the assumption that end-of-year removal of access is sufficient. if that is not the case please let me know and I will create a new issue to track the removal of access.
