### ISSUE TITLE
Create communication to ensure users email does not put our support emails into spam

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#841]
we are going to switch from using osticket@massopen.cloud as our outgoing mail server for our osticket support tickets to using support@moc.supportsystem.com. We need to let our users know to make sure that one they know and two they are not sending messages from support@moc.supportsystem.com to their spam.

- [x] Draft an email
- [x] Get email reviewed
- [x] Send an email
- [x] Draft a status update
- [x] Create a PR for the update
- [x] Get [PR](https://github.com/CCI-MOC/moc-status/pull/32) approved

**Comment by joachimweyl** [comment]
Blocked by #748

**Comment by joachimweyl** [comment]
Subject: New Outgoing Support Email Address


Hello Kaizen Users,
The old support email address osticket@massopen.cloud has been replaced with support@moc.supportsystem.com. Please check your email accounts to ensure that your spam filter will not block support@moc.supportsystem.com
If you have any additional questions, please create a ticket [here](https://osticket.massopen.cloud/login.php).

Thanks!
Michael Daitzman
PS – If you were forwarded this email from a colleague and would prefer to receive these notifications directly, you may sign up for the kaizen-usersmailing list by sending an email to: kaizen-users-join@lists.massopen.cloud

**Comment by joachimweyl** [comment]
@naved001 @msdisme @larsks @knikolla @rob-baron @hakasapl can 2 of you please review the communication above so that we can communicate the update to our support outgoing mail?

**Comment by naved001** [comment]
looks fine to me.

**Comment by joachimweyl** [comment]
@msdisme let's review this together in our 1:1 today.
