### ISSUE TITLE
Discuss plan for connecting MOC A related testbeds (OCT, Colliseum, MOC, FABRIC) together and organize notes from meeting

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#845]
This is a placeholder for a discussion we hope happens at or near the date of the workshop (setting up BOF).  The attached graphic will likely only make sense to Heidi and I :-).

@mikezink who is coming from fabric ?  a.gosain@neu.edu as well.  ![togaparty.jpg](https://images.zenhubusercontent.com/62b0bcb4ba912dbb31713c09/cea93778-6b1e-46bc-9e5f-0a779e1265ad)

**Comment by mikezink** [comment]
FABRIC will be represented by Paul Ruth.
________________________________

**Comment by joachimweyl** [comment]
Once we create more definition this can become an Epic or maybe even a Project with multiple Epics.

**Comment by hpdempsey** [comment]
This has been partly taken on by Hakan, but probably is in icebox

**Comment by msdisme** [comment]
Colliseum is beign connected to Fabric which is a big step in getting testbeds connected.   @hakasapl do we/should we have an issue about Fabric to ESI?

**Comment by hakasapl** [comment]
Fabric and ESI is already linked. I am working with NEU and fabric to connect Colosseum to FABRIC. The plan to connect is defined so I'm closing this
