### ISSUE TITLE
Plan out updating the cisco switch firmware

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#856]
The cisco switches (`cisco Nexus 5672UP Chassis`) in NEU racks, [19-42](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/252/) and [17-42](https://netbox.apps.ocp-prod.massopen.cloud/dcim/devices/251/), are running an older version of nx-os (`system:    version 7.0(1)N1(1)`) that does not support some features used by the ansible networking driver (getting outputs of various commands in json being the blocker). This blocks us  from registering these switches into ESI.

We had done a similar upgrade to the cisco Nexus3500 C3548P-10G switch in kumo (R4-PA-C23), and it is now running `NXOS: version 9.2(3)`.

We should figure out what the impact of updating these switches will be and figure out a time to do so.

**Comment by naved001** [comment]
@hakasapl when is the next MGHPCC shutdown? maybe we should do it around that time.

**Comment by naved001** [comment]
Here's the link for the most up-to date firmware for these switches: https://software.cisco.com/download/home/286221337/type/282088129/release/7.0(5)N1(1)

So, the latest version they support is nx-os 7.0(5)N1(1) and not nx-os9. I looked at the [release notes](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus6000/sw/release/notes/7x/Nexus6000_Release_Notes_7x.html#73158) and it looks like the piping to json feature was added which means the existing ansible-networking driver should work. 

Additionally, they also added support for NX-API and there are ansible modules to use that, so in theory an ansible-networking driver could be written that uses the API instead of the CLI. This can be plan B.

**Comment by joachimweyl** [comment]
plan to do this 5th after 9am

**Comment by naved001** [comment]
The update is complete.
```
MOC-NEU-PODB-R3C19-1# show version |grep system
  system:    version 7.3(11)N1(1)
```

```
MOC-NEU-PODB-R3C17-1# show version |grep system
  system:    version 7.3(11)N1(1)
```

And now the json filter is available (which is used by the ansible driver)
```
MOC-NEU-PODB-R3C17-1# show switchname | json
{
  "hostname": "MOC-NEU-PODB-R3C17-1"
}
```

Here's the brief summary of the steps involved in the update process:



1. Get the firmware files. For this switch we needed the system image and the kick start file, checkout https://cios.dhitechnical.com/Nexus/Nexus5K_6K/

2. Enable scp server on the switch with
```
MOC-NEU-PODB-R3C17-1(config)# feature scp-server
```
that lets us copy the firmware files to the switch

3. Copy the firmware files to the switch and examine those are there
```
MOC-NEU-PODB-R3C17-1# dir bootflash: |grep n6000
   37433344    Jun 05 15:31:52 2023  n6000-uk9-kickstart.7.1.5.N1.1.bin
   34306048    Jun 05 16:09:59 2023  n6000-uk9-kickstart.7.3.11.N1.1.bin
  307749111    Jun 05 15:31:12 2023  n6000-uk9.7.1.5.N1.1.bin
  334412259    Jun 05 16:09:55 2023  n6000-uk9.7.3.11.N1.1.bin
```

4. Check compatibility issues with:
```
MOC-NEU-PODB-R3C17-1# show incompatibility system bootflash:n6000-uk9.7.3.11.N1.1.bin
No incompatible configurations
```

5. Check install impact with:
```
show install all impact system bootflash:n6000-uk9.7.3.11.N1.1.bin kickstart bootflash:n6000-uk9-kickstart.7.3.11.N1.1.bin
```

6. Install the new firmware
```
install all system bootflash:n6000-uk9.7.3.11.N1.1.bin kickstart bootflash:n6000-uk9-kickstart.7.3.11.N1.1.bin
```

7. Delete the old firmware files with `delete bootflash:path-to-old-firmware`
