### ISSUE TITLE
Create a meeting scaffolding for Workshop retrospective

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#860]
Learning from the creation of the workshop

- [x] create scaffolding
- [x] update scaffolding

**Comment by joachimweyl** [comment]
# Combination

## Notes
1. Pre-meeting questionnaire can help speed up the meeting.
   1. Ask all the questions on the Agenda so people can think about and answer questions early.
1. Send out the meeting Agenda early.
   1. Must have recap/action items section.
1. Rules
   1. Keep it objective.
   1. Don’t name anyone or assign blame.
   1. The moderator will ask that we refocus at times when the conversation goes down a rabbit hole
1. Shared google doc that is also displayed during the meeting of the Agenda.
1. Assign a Moderator
1. Designate a note taker different from the moderator to ensure both jobs are done correctly.
1. Create a Post-mortem document that summarizes what we learned and lists action items of how we plan to solve some of the issues as well as what went well and should be repeated.

## Agenda
1. Start by celebrating wins, the project is done let the team soak that in!
1. Recap of Initial Expectations
Give a brief synopsis of the project. Include aspects like plans, timelines, and deliverables if applicable.‍
1. Questions:
   1. What changes/issues in our process would you like to talk about during the meeting?
   1. What do you think went well on the project?
   1. What was the single most frustrating part of the project?
   1. Were the goals of the project clear to you?
   1. Were you given adequate resources to achieve those goals?
   1. Were deadlines realistic and tied to specific goals? Was there room for unexpected delays?
   1. On a scale of 1-5 how complete do you think the project planning was before we kicked everything off?
      1. How long before our next project should we plan the Pre-mortem meeting?
   1. Have we documented everything we need for this project to be complete?
   1. How can we better manage unexpected delays?
   1. What made tasks difficult to execute on a day-to-day basis?
   1. How does management impede workflow?
   1. What are the drawbacks to our main methods of communicating?
   1. Why did we miss our primary goal?
   1. In what ways can we improve our team meetings?
   1. How can we improve our communication with stakeholders?
   1. Anything else this questionnaire didn’t ask?
   1. Raise the questions brought up in question 3.i.
1. Action Items

**Comment by msdisme** [comment]
For participation perhaps also @mikezink 

My instinct is to do a questionnaire to gather feedback from:
- students who presented and did posters
- PI's
- other speakers
- people who did BOF
- people who attended 
- 
Similar questionaire to attendees.

**Comment by taramoran** [comment]
@joachimweyl IMO I think the retrospective meeting should focus on the actual organizers. I'd love feedback from the folks you listed (survey questions are being listed [here](https://docs.google.com/document/d/1iRfLseQp8_ShjW-I4jIfcPs2nt9V6WpD6BhBJdbRH9M/edit)), but for the meeting itself I would have me, Michael, Nancy, Ken, Orran, Peter, Mike Zink, and possibly Sophia.

**Comment by joachimweyl** [comment]
Update to [Agenda](https://docs.google.com/document/d/17BkyTA-a7x_jjKWxGFjdvx4hFX4TkAzzUjV2Nezac-E/edit?usp=sharing) to simplify, updated survey doc to remove all scaffolding, and moved it to Agenda.
