### ISSUE TITLE
Swap OCT3 with Cabinet 16 from Wayfair

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#862]
The purpose of the swap is for a chameleon testbed inside OpenCloud Testbed. Cabinet 16 in [this spreadsheet](https://docs.google.com/spreadsheets/d/16jYOReAY5OOkmLGDvPNKf3nIH-4EzD8CZDbA2dY-Kfw/edit#gid=1629376151) should be swapped with OCT7.

OCT7 existing hardware will either be:

* Recycled
* Added to the pool of hardware for flax

The existing hardware is 19x Dell R730xd

**Comment by msdisme** [comment]
added comment to [this spreadsheet](https://docs.google.com/spreadsheets/d/16jYOReAY5OOkmLGDvPNKf3nIH-4EzD8CZDbA2dY-Kfw/edit#gid=1629376151) that 16 is going to oct7 and linked to this ticket

**Comment by hakasapl** [comment]
Request submitted

**Comment by hakasapl** [comment]
Swap will happen the week of the 2nd

**Comment by hakasapl** [comment]
Swap confirmed
