### ISSUE TITLE
Storage on ESI provisioned nodes

### ISSUE THREAD

**Issue by craychee** [CCI-MOC/ops-issues#870]
Could you describe the storage available on ESI-provisioned nodes?
The OKD work requires a couple of hundred GBs of ephemeral storage for builds. Is there local storage or something like an existing Ceph service available that we could use?

cc/ @joachimweyl

**Comment by joachimweyl** [comment]
@hakasapl, @naved001 & @tzumainn wanted to bring this to your attention.

**Comment by hakasapl** [comment]
Each node should have dual 120G ssds

**Comment by joachimweyl** [comment]
@LorbusChris does this answer your question? Will this be enough local storage for what you had in mind?

**Comment by LorbusChris** [comment]
It's on the lower end, but it should suffice, thanks!
