### ISSUE TITLE
Schedule followups on BOF discussions if they involve us directly

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#879]
eg. BOF about #845

**Comment by joachimweyl** [comment]
@msdisme how many follow-ups do we have left?

**Comment by msdisme** [comment]
Email sent to BOF coordinators; the only ones which currently involve use appear to be MOC A as the fireproof library of alexandria (being addressed in research setting with Orran), connecting testbeds (addressed in ESI network redesign,).  I will close this and open a new one for inclusion of summaries for MOC mailings by Tara
