### ISSUE TITLE
DHCP issue OCT-43

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#883]
OCT-43 doesn't pick up an IP from DHCP anymore. @naved001 what is the DHCP server responsible for its IP? Statically assigning still allows users to reach the nodes so connectivity is still good. For now the node has a static IP so users can continue to use.

At this point I don't see any other nodes affected.

**Comment by naved001** [comment]
if it's VLAN 277 then it the's MaaS server at maas.massopen.cloud that's providing DHCP.

https://netbox.apps.ocp-prod.massopen.cloud/ipam/vlans/166/

**Comment by joachimweyl** [comment]
@hakasapl what are the next steps for this?

**Comment by hakasapl** [comment]
I'll have to find out why the dhcp server isn't work on the MAAS server.

**Comment by hakasapl** [comment]
Resolved with a reboot to the maas VM - verified on OCT43
