### ISSUE TITLE
Connect Flax Sandbox to ESI

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#885]
Currently the Flax sandbox has an Arista switch for which ESI drivers have not been written, @er1p will  add in a Dellz9100 so the ESI team may test out the Open Compute hardware with ESI. 

Please connect the sandbox to the ESI controllers.

**Comment by msdisme** [comment]
@hpdempsey not sure if the sandbox has a clean way to connect to Row 1 Pod C Cabinet 6 - do you have a preference for connecting to the existing ESI controllers?  if so Hakan will see what is possible.

**Comment by hpdempsey** [comment]
Whatever is the simplest thing Hakan can put together should be OK.  Need both console and data plane connections and multiple VLANS we can enable/disable on the same port.

**Comment by hakasapl** [comment]
Submitted ticket to MGHPCC to inquire about current network connectivity to the sandbox

**Comment by hakasapl** [comment]
Moving this to icebox since we're not dealing with the whitebox switches for the initial deployment

**Comment by hakasapl** [comment]
No longer a requirement
