### ISSUE TITLE
Research IT query about requirement to wipe drives and tools to do so

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#888]
As we explore shutting down and recycling the current Kaizen OpenStack and OpenShift nodes does IT or Research IT have a process for sanitizing drives prior to disposing of hardware?

**Comment by msdisme** [comment]
As we remove older hardware from the data center, how are we handling hard drives so that we do not inadvertently expose user data?

    Should we sanitize them ourselves?
    Is there a service we can use that will sanitize them prior to re-use (or destroy them)?

**Comment by msdisme** [comment]
from Wayne:  We don't currently have a process on the RCS side for wiping drives before decommissioning compute servers although you bring up a good point and it may be something we want to do going forward.  For research data storage we are starting to utilize keep your own drive to comply with CMMC lvl1 requirements that we are trying to meet in the SCC.  In the case of Kaizen you may want to wipe the drives before decommissioning to be on the safe side.  I don't think you need to tear out the drives unless you were supporting restricted data sets (HIPPA, etc).

**Comment by msdisme** [comment]
Cost from Johonnot is $6 a drive with attestation - this meets CMMC (https://www.bitraser.com/article/cmmc-media-sanitization-requirement.php) defense deparment requirements.

**Comment by joachimweyl** [comment]
@msdisme I believe the decision was that we can just write the drives with 0 and generate a report that provides information about the drive and that it was wiped.
Does that resolve this specific issue? Do we need to create a new issue to track the creation of the wipe/report script?
