### ISSUE TITLE
Create proposals for option 1 and option 2 for network redesign

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#891]
Create proposals/diagrams for 1 and 2 in [this document](https://docs.google.com/document/d/12sAJDlUaoA7OnS8a93IafUTqaLD2sHlxTTOhSgDeVxg/edit)

**Comment by joachimweyl** [comment]
Hakan, I belive you already finished this, are there any other steps we need to do before closing this issue?

**Comment by hakasapl** [comment]
This is done. A new section was added to the end of the [straw-man proposal](https://docs.google.com/document/d/1XkIHLCTTzF5Hbejln-o9UBScO_1ip5XqXD7ZWIA0wxo/edit)
