### ISSUE TITLE
Check with FLAX about a high single-thread server & 2-4 modern nodes

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#892]
For FPGA builds on OCT

**Comment by hakasapl** [comment]
Sent an email to Erik

**Comment by hakasapl** [comment]
Erik says he may be able to find something, waiting for a response about options

**Comment by joachimweyl** [comment]
@hakasapl what are the next steps for this issue?

**Comment by hakasapl** [comment]
Still awaiting a response from FLAX about it, I will ping today.

**Comment by hakasapl** [comment]
Moving to request quotes from FLAX.

**Comment by joachimweyl** [comment]
@hakasapl any update on this request?

**Comment by hakasapl** [comment]
We're waiting for a formal quote from Flax

**Comment by joachimweyl** [comment]
@hakasapl can we nudge them again on this?

**Comment by joachimweyl** [comment]
@msdisme if you have a chance during your meeting with @er1p please bring this up with him.

**Comment by er1p** [comment]
hi Kim - just sent these quotes in email - would suggest the newly-added AMD server as potentially the best option - being used by one of our California customers

**Comment by joachimweyl** [comment]
@er1p Hakan would like to know "Thanks for these. Could you create a different quote for the server that is the high single-threaded performance one? I think that’s the Xeon gold one with 1024GB ram? That quote should be for Northeastern university instead of BU. (Same info for the quote that you gave to Peter for the switches)."

**Comment by joachimweyl** [comment]
@hakasapl  with Erik's email from this morning are we ready to order the nodes we want for the research rack?
We need to keep these in mind when we consider heat and power for the research rack.

**Comment by hakasapl** [comment]
We have the quotes at this point so I'm closing this. We will have to decide what to buy and where to put them.

**Comment by joachimweyl** [comment]
@msdisme is this something we need Orran's input for or will you make this decision? Originally these were expected to go into the research rack.
