### ISSUE TITLE
Write trip report for KubeCon Europe 2023

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/ops-issues#893]
I attended KubeCon and I should write a trip report about it.

**Comment by joachimweyl** [comment]
From your standup notes yesterday it sounds like you might be done with this. Are we ready to close this issue?

**Comment by knikolla** [comment]
Done and published here https://kristi.nikolla.me/2023/06/20/kubecon-amsterdam-2023-trip-report/

There were some talks which I haven't found the time to watch and summarize yet that I really wanted and on my own time I'll eventually expand the post.
