### ISSUE TITLE
Communicate network plans and gather feedback

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#894]
We have proposals for options to configure the network, get decision, present schedule (this is, frankly, msd representing Naved and Hakan plans- this will include moving them to more visibility for their work.)

**Comment by joachimweyl** [comment]
Since we don't have the meeting to discuss the plans Hakan put together until next spring I am going to push this to the next sprint.

**Comment by msdisme** [comment]
impacted by travel; not a blocker for proceeding. 

@hakasapl let me know if addition of network appliance is a dependency for this?

**Comment by msdisme** [comment]
msd to add note to doc so starting can go no

**Comment by msdisme** [comment]
Moving ahead with this.  Feedback will develop as implementation detaiils
