### ISSUE TITLE
Setup IPMI proxy in MOC ESI

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/ops-issues#896]
OKD requires IPMI access to ESI nodes. Giving direct access is dangerous (and also requires nodes to be on the IPMI network, which may not be possible). An IPMI proxy that calls Ironic may be sufficient.

**Comment by tzumainn** [comment]
Derek suggested that modifying https://github.com/openstack/virtualbmc/blob/master/virtualbmc/vbmc.py may make this task easier.

**Comment by tzumainn** [comment]
@derekhiggins Hi! Just wanted to give you a quick update on this (and ask a few questions). I've hacked the code a bit - it turns out to be a bit more complicated than just updating `vbmc.py`, since there's a bit of libvirt code entwined with the manager - but it seems to be working on a test basis now. I can start the manager, add a node with some virtual bmc config, and start the virtual bmc instance for the node. Afterwards I can call `ipmitool` on the virtual bmc instance, and have it successfully call the Ironic API to do things like retrieve and control the node's power state.

A few questions:

* I'm a bit confused by the boot device functions, and how to translate Ironic settings to whatever IPMI requires. Would you be able to give any advice here?
* Would you want the IPMI proxy to be run from a central MOC ESI location, or to run it locally yourself? It feels like the latter might be better, because it gives you full control over access.
* Do you know if there's a good way to fork opendev repositories? I kinda want to persist my changes as a branch on a fork, but I can't figure out how to fork in opendev.

**Comment by derekhiggins** [comment]
the power management progress sounds promising

to set the boot device via ironic I believe you can toggle this with (although I've never used it)
```
baremetal node boot device set <NODE> pxe
baremetal node boot device set <NODE> disk
```

having the service running locally would be preferable if possible

**Comment by tzumainn** [comment]
Okay! We're in the process of figuring out how to fork the opendev repository; after that, ideally you'd be able to check out code from that fork and run it yourself - hopefully this should be done in the next few days.

**Comment by tzumainn** [comment]
Also, can you give some examples of the IPMI commands used to set the boot device, and their expected output?

**Comment by derekhiggins** [comment]
> Also, can you give some examples of the IPMI commands used to set the boot device, and their expected output?

Yup, here is a list taken from a ironic log during a normal provisioning
# Get the "Manufacturer Name" (Unknown in fine here)
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin mc info

# Power commands
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin power status
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin power on
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin power off

# Set network boot (vbmc probably  ignores the first command in the sequence)
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin raw 0x00 0x08 0x03 0x08
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin raw 0x00 0x08 0x05 0xa0 0x04 0x00 0x00 0x00

# Set local boot (vbmc probably  ignores the first command in the sequence)
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin raw 0x00 0x08 0x03 0x08
ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6234 -U admin raw 0x00 0x08 0x05 0xe0 0x08 0x00 0x00 0x00

**Comment by naved001** [comment]
Is there a reason why we would send raw commands for changing bootdevice?

This is how I would set the bootdevice using ipmitool

```
[root@kzn-ipmi-gw ~]# ipmitool -I lanplus -U mocadmin -P `cat ipmipass` -H 10.0.3.13 chassis bootdev pxe
Set Boot Device to pxe
[root@kzn-ipmi-gw ~]# ipmitool -I lanplus -U mocadmin -P `cat ipmipass` -H 10.0.3.13 chassis bootdev pxe options=persistent
Set Boot Device to pxe
[root@kzn-ipmi-gw ~]# ipmitool -I lanplus -U mocadmin -P `cat ipmipass` -H 10.0.3.13 chassis bootdev disk options=persistent
Set Boot Device to disk
```

More boot options:
```
[root@kzn-ipmi-gw ~]# ipmitool -I lanplus -U mocadmin -P `cat ipmipass` -H 10.0.3.13 chassis bootdev
bootdev <device> [clear-cmos=yes|no]
bootdev <device> [options=help,...]
  none  : Do not change boot device order
  pxe   : Force PXE boot
  disk  : Force boot from default Hard-drive
  safe  : Force boot from default Hard-drive, request Safe Mode
  diag  : Force boot from Diagnostic Partition
  cdrom : Force boot from CD/DVD
  bios  : Force boot into BIOS Setup
  floppy: Force boot from Floppy/primary removable media
  ```

**Comment by tzumainn** [comment]
It sounds like this is working right now, so closing this issue!
