### ISSUE TITLE
Secret in nerc/nerc-ocp-infra/xdmod/nerc-ocp-prod-xdmod-reader no longer valid?

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/ops-issues#904]
The OpenShift/XDMoD job is failing with "error: The token provided is invalid or expired". @naved001, do you know if it needs to be updated?

**Comment by naved001** [comment]
@tzumainn most likely, I wonder if there's a way to get a token with a longer validity?

**Comment by tzumainn** [comment]
oh, I had the impression that the token only expired because there was a redeploy at some point in march, I think?

**Comment by tzumainn** [comment]
@naved001 oh, I pinged you on this because the token is contained in the vault - `nerc/nerc-ocp-infra/xdmod/nerc-ocp-prod-xdmod-reader` - and last time you were the one who had access to update it. Is that something you can do again, or is there some way for me to do it... ?

**Comment by naved001** [comment]
ah, you are probably right that the redeploy made the old token invalid. I'll generate a new token and update the secret.

**Comment by naved001** [comment]
I have updated the token/secret in vault

If you need to generate it then you'll need access to the nerc-ocp-prod cluster, and then there this command will give us the token which is then placed in vault.

```
oc --as system:admin get secrets xdmod-reader-token-m6s2m -o yaml | yq .data.token  -r | base64 -d
```
