### ISSUE TITLE
MGHPCC 2023 Shutdown Website Banner

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#911]
- [x] Draft
- [x] Add to Wordpress
- [x] confirm live

Since the [main page](https://massopen.cloud/) no longer links to the status page to display status we will need to add a "status" banner (or something similar) on the main page to communicate that MGHPCC will be down. We need to link to the [Status page](https://status.massopen.cloud/) in the banner.
---
## Banner information Option 1
Due to the annual scheduled maintenance power outage at the MGHPCC data center, MOC services will be unavailable from Tuesday, June 5th, 2023 at 6 PM through Friday, June 12th, 2023 at 12 AM.

Please shut down your virtual machines, containers, and any bare metal systems by 6 PM on Monday, June 5th, so that the Mass Open Cloud team may begin preparing for the outage. If you do not shut them down yourself, you run the risk of losing data.

The MOC has dependencies on several services which also run at the data center. Based on previous experience we recommend not scheduling critical events the week of June 5th.

We will notify you when MOC services are available by updating the MOC status website at https://status.massopen.cloud/ and by sending an email to this distribution list. Once services are back online it will be your responsibility to restart any virtual machines, containers, or other systems.

If you will need access to any MOC-hosted data during this outage, please make sure to obtain copies of that data prior to Monday, June 5th. During the outage, the data center will be completely without power and access to MOC-hosted services will be impossible.

As always, if you have questions feel free to open a [support ticket](https://support.massopen.cloud/).
The ticketing system will be available throughout the outage.

---
or it could be shorter and link to the status page, something like
---
## Banner information Option 2
Due to the annually scheduled maintenance power outage at the MGHPCC data center, MOC services will be unavailable from Tuesday, June 5th, 2023 at 6 PM through Friday, June 12th, 2023 at 12 AM.

For further information please see the [status page](https://status.massopen.cloud/)

**Comment by taramoran** [comment]
@joachimweyl I think there's still a check status section on the front page of the website. is that link not what you guys want included there?

**Comment by joachimweyl** [comment]
There used to be a live banner that provided the current status that it pulled from the status page. The plan is to get that back eventually but that plan is not until later in the summer so the interim idea was to add a static banner at the top of the main page that provides a status and links to the the status page. We would need to be able to remove it once the Shutdown was finished.

**Comment by taramoran** [comment]
@joachimweyl yeah not a problem at all! it takes about a day for some website updates to go live, do you want to wait to post it on the 4th or do you want an advanced warning banner on the homepage now?

**Comment by joachimweyl** [comment]
@taramoran I was thinking we would post it now and go with option 2 since it is smaller and links to the status page where we can update and make changes to the specifics but the banner won't need to change until we take it down. Sound good?

**Comment by taramoran** [comment]
@joachimweyl sounds good! we have a link to check the status on the homepage now but I'll move it above the "join" section and link to the specific page you sent above

**Comment by joachimweyl** [comment]
@taramoran I think we can leave the current link that is under User Resources. No need to move that. The banner can be separate and have its own link to the status page. That way when we remove the banner the old link to status remains.

**Comment by joachimweyl** [comment]
@taramoran looks great, with even less detail than I had planned, and looks even better, thanks.

**Comment by joachimweyl** [comment]
@taramoran please let me know when you push this update

**Comment by taramoran** [comment]
@joachimweyl it's live now, will hopefully be pushed by Wordpress by tomorrow morning
