### ISSUE TITLE
Get the mapping of openstack volumes to ceph rbd volumes

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#919]
Basically take some database dump that holds this information. I imagine our goal would be find the rbd volumes that map to openstack volumes for a given project.

**Comment by larsks** [comment]
I've attached `volumes.csv` that contains the fields `id`, `pool`, and `rbd`, where `id` is the openstack volume id, `pool` is the name of the ceph pool, and `rbd` is the corresponding rbd name.

There are three volumes that don't appear to exist in our ceph storage; these are marked with `-` in the `pool` and `rbd` columns.

[volumes.csv](https://github.com/CCI-MOC/ops-issues/files/11479744/volumes.csv)

**Comment by joachimweyl** [comment]
What are the next steps for this issue?

**Comment by larsks** [comment]
I think this issue can be cloised: we have the required data.
