### ISSUE TITLE
Create MVP tool to generate OpenStack billing on CPU SU

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#922]
We are looking into ways to be able to provide data for showback. We must prepare for the possibility that XDMoD will not be able to provide this data on time.
The rules for gathering data can be found [here](https://docs.google.com/document/d/1SHCMidWQmazACGqzYOlRHQqnsg4KjmeW8ShGiEptR2Q/edit?pli=1).
1. This data will eventually exist in XDMoD
   1. Currently we are able to show CPU and average RAM
   1. Still working on GPU & Storage
1. If we cannot get all of this information from XDMoD in time what are our alternatives?
   1. Pull directly from OpenStack ColdFront & Keycloak for just this information

**Comment by joachimweyl** [comment]
please use this [script](https://github.com/CCI-MOC/xdmod-cntr/blob/main/moc_openstack_api_reporting.py) to start finding out if we can find OpenStack information for the items below

1. OpenStack (broken down by VM and grouped by Project)
   1. Time Frame (Months)
   1. Project Name (ColdFront - OpenStack)
   1. PI (from ColdFront)
   1. Institution (from ColdFront)
   1. vCPU (VM Flavor)
   1. Memory (VM Flavor)
   1. Storage (VM Flavor)
   1. vGPU (VM Flavor)
   1. Container Hours (in the Time Period)

We are looking for the quickest method possible. This is only for billing not for tracking, monitoring, or alerting. Purely a data dump (preferably csv) of this data broken down by Project or PI whichever is easier.

**Comment by joachimweyl** [comment]
Useful Links
1. [Current NERC Flavors](https://nerc-project.github.io/nerc-docs/openstack/create-and-connect-to-the-VM/flavors/#2-memory-optimized-tier)
1. [Billing Data Mock-up](https://docs.google.com/spreadsheets/d/1HTc-VJjp4hPDyjTC94TJLM0r2l5r-4zIExAOE9B9t9M/edit?usp=sharing)

**Comment by knikolla** [comment]
I have all the above listed data working for instances, in the coming days I'll work on collecting storage data.

**Comment by joachimweyl** [comment]
@knikolla as this continues to grow it sounds like breaking it into more issues would be a good way to track this. The first thing that comes to mind is to name this one "Create MVP tool to generate OpenStack billing on CPU SU" and create a few new ones such as "Update OpenStack billing tool to include GPU SUs", "Update OpenStack billing tool to include Storage". What are your thoughts?

**Comment by joachimweyl** [comment]
@knikolla for the storage section there has been a request to look into ColdFront requests as a way to track storage. Are we currently able to gather timestamps for when a storage request is fulfilled and when a storage request is requested? The idea is that we should be able to bill storage based on starting when a storage request is fulfilled for increases and stoping based on requests for decreases.
For example:
My initial request is for 5 CPU SU so I now have 100 GB of storage. I have that for a while then I request 6 TB at 5am on Sunday 1st of July, then that request is fulfilled at 8am 3rd of July (at which point I should be billed for 6,100 GB). Then I request to to back down to 3TB at 9am on the 7th (at which point billing should go back down to 3TB, independent of when the NERC fulfills that request). I would be billed 100 GB for the first amount of time, 6,100 GB from 8am 3rd - 9am 7th, and 3 TB until the next change request is sent or fulfilled.

**Comment by joachimweyl** [comment]
Now that the extra pieces are broken out into #1001 & #1002 is this issue ready to be closed?

**Comment by joachimweyl** [comment]
tool is ready and waiting for future DBs
