### ISSUE TITLE
update spreadsheet with hardware identified for removal

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#923]
In this [spreadsheet ](https://docs.google.com/spreadsheets/d/1wsrwPlGDqvKA_aePr8yUEJCv7tqhlzSWnwU3lEAP5P8/edit?pli=1#gid=0) change the new marked for removal column to yes for the hardware actually marked for removal.

Marked for current spring since it may be a blocker for removal;  should we instead rely on FLAX for that information since we already have a discrepancy.

**Comment by hakasapl** [comment]
@msdisme I've updated that info in the donated sheet as they are physically marked today in the datacenter, as well as the machines in R4-PA-C02 and C04 (@naved001 does that check out with you)?

**Comment by naved001** [comment]
@hakasapl sounds fine, are we taking the 4TB drives out of those systems or not?

**Comment by hakasapl** [comment]
Would they be useful elsewhere? If not we probably don't need to keep them, they're probably old enough by now. I assume you mean the engage nodes.

**Comment by naved001** [comment]
>  assume you mean the engage nodes.

yes

> Would they be useful elsewhere? If not we probably don't need to keep them, they're probably old enough by now.

I can't think of an immediate use case of keeping those drives, but I want to double check with @msdisme if we should get rid of the drives because having to buy a bunch of 4TB drives isn't exactly inexpensive. 

P.S I can definitely find some personal usecases if we decide to throw them away :D

**Comment by joachimweyl** [comment]
@hakasapl I noticed 3 discrepancies between "Deprecate?" column and "Marked for Removal". 1x ProLiant DL380Gen9, 3x ProLiant DL560Gen9, and 4x ProLiant DL580Gen9. Have we confirmed with @waygil & @syockel that these should be deprecated? If so let's update the "Depricate?" column.
