### ISSUE TITLE
Add FX2's in Rack R4-PA-C21

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#925]
Put in a request with Kevin to move the most powerful racked donated FX2's that we do not plan to have FLAX take away into Rack R4-PA-C21. Flax will install Dell switch, cables optics etc. once the FX2's are in R4-PA-C21.

**Comment by hakasapl** [comment]
Cabinet marked for swap with paper in machine room. Email sent to Kevin
