### ISSUE TITLE
Add Flax team members to MOC Keyring

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#926]
Please work with Erik Riedel to get him and his team access to the MOC Keyring
Ahmed Ewing
Harlan McCanne
Peter Vacca
David Bahi
Shannon Rasimas

- [x] Share the template with Erik
- [x] Recieve documents from Erik for his team
- [x] Request Keyring access through MGHPCC
- [ ] Confirm they are added

**Comment by joachimweyl** [comment]
Erik - "I checked in with my crew, and all this badge info is in the directory now."

**Comment by joachimweyl** [comment]
There was some missing data and had to reach out to gather it.
We have all their data and are sending it to MGHPCC right now.

**Comment by msdisme** [comment]
confirming last two today

**Comment by msdisme** [comment]
Erik Riedel, er1p@flaxadvisors.com
Ahmed Ewing, ahmed@flaxadvisors.com
Harlan McCanne, harlan@flaxadvisors.com
Peter Vacca, vacca@flaxadvisors.com
David Bahi, bahi@flaxadvisors.com
Shannon Rasimas, shannon@flaxadvisors.com 

added
