### ISSUE TITLE
HDD erasure for non HIPAA data when hardware deprecated

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#927]
1. Feedback from Lilly lhdd- write 0's is fine since this is not HIPAA data, rather operational/logs and files
1. Additional requirements:
   1. please log the erasure, 
   1. hw details and date and time so we have a record
   1. Ability to generate a report and on the report, please include a description of the data on the systems-eg. logs and os files.

**Comment by joachimweyl** [comment]
@joachimweyl convert to epic

**Comment by joachimweyl** [comment]
Duplicate of https://github.com/CCI-MOC/ops-issues/issues/888
