### ISSUE TITLE
Wipe or destroy drives and generate a report of what drives were wiped

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#933]
- [ ] writes zero to drives OR destroy drives
- [ ] captures drive details including serial number
- [ ] generates a report of every drive that was wiped

OR
pay someone else to do this.

**Comment by joachimweyl** [comment]
an alternative option was to get a hardware-based hard drive wiping tool so we don't have to have all of these servers on to do the wipe. This does require pulling the hard drives out of the servers though.
Another possible alternative to writing code to erase them is to see if maas has something already written for this purpose.

**Comment by msdisme** [comment]
@hakasapl which device of the 4 on this page: https://www.amazon.com/StarTech-com-Hard-Drive-Eraser-SDOCK1EU3P2/dp/B073X3YZNL/ref=sr_1_1?crid=2914JNHE78F15&keywords=hdd%2Bwiper&sprefix=hdd%2Bwiper%2Caps%2C92&sr=8-1&ufe=app_do%3Aamzn1.fos.ac2169a1-b668-44b9-8bd0-5ec63b24bcb5&th=1

**Comment by msdisme** [comment]
@naved001 to explore MAAS options when time permits - may end up bumping to another person due to billing prioritization

**Comment by larsks** [comment]
While the redfish firmware on the openstack hosts advertises a "SecureErase" action:

```

{
  "@odata.context": "/redfish/v1/$metadata#Drive.Drive",
  "@odata.id": "/redfish/v1/Systems/System.Embedded.1/Storage/Drives/Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1/",
  "@odata.type": "#Drive.v1_3_0.Drive",
  "Actions": {
    "#Drive.SecureErase": {
      "target": "/redfish/v1/Systems/System.Embedded.1/Storage/Drives/Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1//Actions/Drive.SecureErase"
    }
  },
.
.
.
```

It doesn't look like this action is actually supported on our hardware. Attempting to use it results in:

```
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "Message": "Unable to complete the operation.",
        "MessageArgs": [],
        "MessageArgs@odata.count": 0,
        "MessageId": "IDRAC.1.6.STOR006",
        "RelatedProperties": [],
        "RelatedProperties@odata.count": 0,
        "Resolution": "Retry the operation. If the issue persists, contact your service provider.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.2.GeneralError",
    "message": "A general error has occurred. See ExtendedInfo for more information"
  }
}
```

The [documentation](https://www.dell.com/support/manuals/en-us/poweredge-r730/idrac8_redfishapiguide_2.70.70.70/supported-action-secureerase?guid=guid-0597e7cf-6f63-43fb-83e6-46ed71936dee&lang=en-us) says "This action is used to perform instant Secure Erase on ISE-compliant HDDs, SEDs, SSDs, and NVME SSDs. It does not require any input parameters.", and I'm not sure what counts as an "ISE-compliant" drive.

**Comment by joachimweyl** [comment]
Decision made to pay for these to be wiped.
Awaiting Wipe report

**Comment by joachimweyl** [comment]
@msdisme please add the contact information and name of the company that will be doing the destruction of these drives.

**Comment by msdisme** [comment]
query out with data center, else will be Flax vendor.  Will add names her.

**Comment by joachimweyl** [comment]
Flax will be destroying the drives.

**Comment by joachimweyl** [comment]
I will reach out to Erik to get the contact at IT Renew for the destruction report

**Comment by joachimweyl** [comment]
IT Renew will be destroying the drives. They will send us a bill and the destroy list.

**Comment by msdisme** [comment]
@er1p do you have an eta on wipe reports/invoice?

**Comment by joachimweyl** [comment]
reached out to @er1p on Slack to try to get focus on this issue

**Comment by joachimweyl** [comment]
[report](https://drive.google.com/file/d/1AJ_by4ue7bBgj8F7jlx4LjlYwpG_Eu8b/view?usp=sharing)
