### ISSUE TITLE
MGHPCC 2023 Shutdown communicate with teams the email does not reach

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#936]
What teams are not reached by mailing list?

- [ ] double-check with Marcel on SMAUG cluster

**Comment by msdisme** [comment]
@durandom - we have not yet shut down the smaug cluster (unless you did).  We know the okdmoca guys are still using it (they are migrating off. )  Are you aware of any other groups still using it?  If so, we want to communicate to them that the data center will be down.

**Comment by msdisme** [comment]
updated team via slack channel;  Christian from OKD team will be shutting things down.
