### ISSUE TITLE
convert identified hardware needs from March from document to Epics and Issues

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#939]
In this document: https://docs.google.com/document/d/1dGQdq9NN7g8doFIPCdxp-CDb6gMfvxf0cnWvshpxm8k/edit# we identified expected hw needs.  Convert to issues and if necessary epics so that it may be reviewed and implemented.

**Comment by joachimweyl** [comment]
@msdisme this something you can delegate to me.

**Comment by msdisme** [comment]
prioritized behind getting the 500 servers online

**Comment by msdisme** [comment]
Overtaken by events - this is all happening.
