### ISSUE TITLE
PRB to CCDS datacenter move

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#941]
Did some work around planning it, but this wasn't being tracked.

**Comment by naved001** [comment]
@msdisme All the servers in PRB are using C14 plug to connect to the PDUs. We also have a box with a bunch more of those in the same room.

 The PSUs support all voltages (100V-240V), but I didn't see a switch on those to change input voltages.

**Comment by msdisme** [comment]
@naved001 so that should mean they are voltage autosensing.   Re. c14 - I think this means we do not need to order any :-)

**Comment by joachimweyl** [comment]
@naved001 do we have any more that we need to do for this?

**Comment by naved001** [comment]
@joachimweyl probably not. The move will happen tomorrow, so let's keep this issue open until the servers are actually moved. Maybe something move related might come up. 

At some point we'll have to setup those servers, but that's a different issue.

**Comment by msdisme** [comment]
closing, new issue being created to track network connections and missing rails.
