### ISSUE TITLE
Open DNS resolvers on openshift

### ISSUE THREAD

**Issue by naved001** [CCI-MOC/ops-issues#952]
We got reports about the following hosts:

128.52.62.238  -> oct-03-22-compute (smaug)
128.52.62.195 -> oct-03-17-compute (smaug)
128.52.62.175 -> neu-17-12-compute (ocp-prod)
128.52.62.191 -> neu-5-10-compute (ocp-prod)

cc: @larsks

**Comment by naved001** [comment]
```
[core@oct-03-17-compute ~]$ sudo netstat -tulpn |grep ":53"
tcp6       0      0 :::53                   :::*                    LISTEN      3365/coredns
udp6       0      0 :::53                   :::*                                3365/coredns
[core@oct-03-17-compute ~]$ sudo ps -p 3365 -o cmd
CMD
/usr/bin/coredns --conf /etc/coredns/Corefile
```

**Comment by larsks** [comment]
Note that coredns on **all** of the workers appears to be acting as an open resolver; not just on these few nodes. E.g:

Tested with:

```
kubectl -n openshift-kni-infra get pod -l app=kni-infra-mdns \
    -o go-template='{{range .items}}{{.status.hostIP}}{{"\n"}}{{end}}'  |
  while read ip; do echo === $ip ===; dig +short @$ip google.com; done
```

We do expect `coredns` to be running, but I don't think we expect it to be an open resolver.

**Comment by larsks** [comment]
@naved001 in the short term we should probably just ask CSAIL to block inbound port 53 (udp/tcp) for these networks, since there's no reason for that to be open.

**Comment by naved001** [comment]
CSAIL's response when I asked them if they can block port 53 for the entire network.

> Not easily, because it's outside the firewall.

Our plan now is to have our own firewall for the compute nodes in the cluster.

**Comment by naved001** [comment]
closing because the network and cluster do not exist anymore
