### ISSUE TITLE
Write emails referencing birds of a feather summaries for use in marketing mail

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#961]
Summaries are in this directory: https://drive.google.com/drive/u/0/folders/1HEPjD4Oh0wkKWCG0WB8mURcr48PXFd0D  though some may not have summaries due to either not happening or people moving to new roles. 

The goal is to write emails which may be used to help connect the community together.  
- write summary email or emails (ask for feedback form @kkrudolph @taramoran @neclinton )
- use them as outreach to community

**Comment by joachimweyl** [comment]
@msdisme is this more in @taramoran 's plate or are you still working on parts of this?

**Comment by joachimweyl** [comment]
@msdisme is this the issue you mentioned today you wanted to close?

**Comment by joachimweyl** [comment]
never got to it.
