### ISSUE TITLE
Network connectivity for servers moved from PRB to CCDS

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/ops-issues#962]
- [x] #1036
- [ ] Network connectivity set up with Beck once rails in place. 

This is follow up from https://github.com/CCI-MOC/ops-issues/issues/941

**Comment by msdisme** [comment]
Sending a photo on July 5 -

**Comment by naved001** [comment]
>  Network connectivity set up with Beck once rails in place.

I got the networking configured when I connected the ARM machine. So we know which ports have public VLANs. For any other specific network configuration we will open new tickets.
