### ISSUE TITLE
Prepare for OpenInfra Summit

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/ops-issues#965]
This includes 

- [x] Finishing my talk titled "A complete guide to OpenID Connect with OpenStack" that is scheduled for Tuesday.
- [x] Prepare for attending the OpenInfra board meeting on Monday
- [x] Prepare for moderating the Technical Committee + Community Leaders forum session
- [x] Create a schedule for other sessions of interest

**Comment by joachimweyl** [comment]
@knikolla Hope, the OpenInfra Summit was great!

**Comment by joachimweyl** [comment]
@knikolla looks like this is probably complete.

**Comment by knikolla** [comment]
Summit went well, and the slides of my talk are available here https://kristi.nikolla.me/2023/06/14/slides-for-a-complete-guide-to-openid-connect-with-openstack-talk-at-openinfra-summit-vancouver-2023/
