### ISSUE TITLE
Work with Flax to add 2 z9100 Switches to the top of the Research Rack (R4-PA-C21)

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#977]
We will need to wire up the Research rack for 25GB networking.
Dell z9100 should do the trick.

- [x] order z9100/s from Flax
- [ ] install in the new Research Rack- R4-PA-C21

**Comment by joachimweyl** [comment]
@hakasapl how many z9100 are needed to wire up the whole rack at 25GB?

**Comment by hakasapl** [comment]
2 - they have already arrived and FLAX is scheduled to install them.

**Comment by hakasapl** [comment]
These are installed and cabled up. Uplink is there now as well which connects to the moved Cisco switches in R4-PA-C02 and C04
