### ISSUE TITLE
Create a pool on the Production Ceph Cluster for Researchers and move data from Research Ceph

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#979]
We will be taking down the research Ceph cluster to create a new Research Ceph Cluster and need to have somewhere to have them move their data.

- [x] Gather how much space the researchers need (July 3rd)
- [x] create pools on the production Ceph cluster according to their total size request (July 5th)
- [x] Confirm researchers can access the production Ceph pools successfully
- [x] assist in moving data (July 6th-7th)

**Comment by naved001** [comment]
we already have a production ceph cluster, we just need to create a pool on it which we can do once the researchers tell us how much space they need.

**Comment by naved001** [comment]
why was my comment deleted?

**Comment by joachimweyl** [comment]
I updated the issue to reflect your changes.

**Comment by joachimweyl** [comment]
Make sure they delete what they can prior to requesting migration so that we move as little as possible.
ask about other grad students that might have storage on the research Ceph cluster. Include Peter & Orran.

**Comment by joachimweyl** [comment]
The last steps for this will be finished in a [separate issue](https://github.com/CCI-MOC/ops-issues/issues/1042).
