### ISSUE TITLE
Research 2 modern Open Compute Platform nodes from Flax slated for the Researchers

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#981]
- [x] Price out machines with Flax for [Open Compute Platform](https://www.opencompute.org/) nodes with the following criteria
   - modern (last 2 years) processors
   - 384GB RAM
   - dual 25GB or 100GB NICs
- [x] review quotes
- [x] request new quotes
- [x] review qutoes
- [x] request new quotes
- [x] review quotes
- [x] request new quotes
- [x] review quotes

**Comment by joachimweyl** [comment]
@okrieg any feedback about the drives you want here would be helpful.

- [ ] RAID
- [ ] SSD
- [ ] NVMe

**Comment by joachimweyl** [comment]
@msdisme we should get Flax to order these without storage information. We will assume SSD storage and if we need NVMe we can add them later.

**Comment by msdisme** [comment]
@okrieg - any paper deadlines we need to take into account on this hardware installation

**Comment by hakasapl** [comment]
From FLAX:

```
Wiwynn SV310G4 - dual IceLake - approx $12,500 per node (note: this is extremely big memory)
dual CPU Icelake Xeon Platinum 8352V (36-core, 2.1 GHz base, 3.5 GHz turbo) + 2,048GB memory + up to 100TB NVMe flash
Wiwynn SV328 - dual Ampere ARM - appox $17,500 per node (note: this is the newest model, only just released)
dual CPU Ampere Altra Q80-30 (80-core, 3.0 GHz base) + 1,024 GB memory + up to 100TB NVMe flash
```

@msdisme is there a preference for x86 vs arm?

**Comment by msdisme** [comment]
Preference for intel for the researchers.   Need to confirm how much memory we actually need in it, etc.

**Comment by joachimweyl** [comment]
at least 384GB RAM was requested. all of these have that and more.

**Comment by joachimweyl** [comment]
@joachimweyl discuss with @er1p next steps.

**Comment by joachimweyl** [comment]
@er1p provided multiple Quotes. @hakasapl & @msdisme are deciding which model to order.

**Comment by msdisme** [comment]
RAM and Storage are probably going to be much lower - double checking.

**Comment by joachimweyl** [comment]
@er1p Please post here when you have emailed the quote for the AMD and Intel modern systems you talked to Eric about.

**Comment by joachimweyl** [comment]
I reached out to @er1p in Slack to see what the next steps are.

**Comment by joachimweyl** [comment]
@er1p "I have details set for the AMD server, trying to get the Intel variant buttoned up today or tomorrow to get a final quote"

**Comment by joachimweyl** [comment]
@msdisme now that we have the new quotes are we ready to order the 2 (1 AMD & 1 Intel) of them?

**Comment by joachimweyl** [comment]
@msdisme are we waiting for another quote based on the lower system requirements?

**Comment by msdisme** [comment]
yes

**Comment by joachimweyl** [comment]
@er1p do you have an expected turnaround time for the new quotes?

**Comment by joachimweyl** [comment]
New quotes provided @msdisme are we happy with the new quotes? Are we ready to order them?

**Comment by joachimweyl** [comment]
Agreed with the most recent quote. closing this issue to move on to the ordering issue.
