### ISSUE TITLE
Update 2 of the FX2s in the Research Rack (R4-PA-C21) with 25GB NICs and FC430s

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#982]
LSVD research needs access to 16 compute nodes
2 x 8 FC430s is 16 nodes.
they will need 25GB NICs added as well
We will use 2 FX2s and 16 FC430 blades from the donated hardware
make sure they are the 2016 CPUs not the 2014.

- [x] Get 25GB NICs (Start by asking Flax)
- [x] [Locate 2 FX2s](https://github.com/CCI-MOC/ops-issues/issues/925)
- [x] Locate 16 FC430 blades with 2016 CPUs
- [x] Install systems in the new Research Rack

**Comment by joachimweyl** [comment]
R4-PA-C21 is currently full of FX2s. We need to rearrange the blades to confirm at least 16 of them are FC430s with CPUs 2016 or newer.

**Comment by msdisme** [comment]
Why only two ?  I think goal is upgrade all the systems to 25GB in all FX2 racks.

**Comment by joachimweyl** [comment]
@msdisme in the discussion wtih @okrieg he mentioned 2 specifically had to have 25GB NICs and the rest would be best if they did but it was less critical. Hence we have 2 Issues for this. The current one for the 2 that must have 25GB and the [rest](https://github.com/CCI-MOC/ops-issues/issues/983).

**Comment by hakasapl** [comment]
All 830s in this rack are 25G now, 430s are 10G.
