### ISSUE TITLE
Fill the rest of the Research Rack (R4-PA-C21) with FX2s

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#983]
Staying with in heating and power guidelines fill the rest of the Research Rack (R4-PA-C21) with FX2s. They can have FC430s or FC830s or some combination of the two. If we can load them all with 25GB NICs that would be best but it is more important to get this up and running quickly.

- [ ] Get 25GB NICs (Check first with Flax) if possible
- [x] [Locate enough FX2s to fill the rest of the Rack](https://github.com/CCI-MOC/ops-issues/issues/925)
- [x] Locate FC430s and/or FC830s to fill the FX2s (Make sure CPUs are 2016 or newer)
- [x] Install into the Research Rack (R4-PA-C21) (Flax or TechSquare?)

**Comment by joachimweyl** [comment]
This rack already has FX2s. We need to make sure the blades all have CPUs 2016 or newer and swap out enough space to accommodate the new [2-4 modern nodes](https://github.com/CCI-MOC/ops-issues/issues/981).

**Comment by hakasapl** [comment]
This rack is full of FX2s and cabled now.
