### ISSUE TITLE
Wire the new Research Rack (R4-PA-C21)

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#984]
Wire the new Research Rack (R4-PA-C21) with 25GB cabling.

**Comment by msdisme** [comment]
Has Flax already wired and did they use 25GB compatible?  Discussion for jun 23

**Comment by hakasapl** [comment]
Flax has finished the cabling.

**Comment by joachimweyl** [comment]
Flax did not include one of the switches.

**Comment by joachimweyl** [comment]
@hakasapl what is the status on the switch Flax needs to include?

**Comment by hakasapl** [comment]
Done, rack is cabled and networked. Closing this
