### ISSUE TITLE
Move Researchers over to the new Research Rack (R4-PA-C21)

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#986]
In order to free up the old BMI nodes we need to move the Researchers over to the new Research Rack (R4-PA-C21).

- [x] Move Amin's project
- [x] Move Sahil's project (if still live)
- [x] Move Han's project
- [x] Move Mania's project
- [x] Move Ugur's project (if still live)

**Comment by joachimweyl** [comment]
@tzumainn I heard you have been working with some of the Researchers to get them onto the new nodes in the Research Rack that are on ESI. Which researchers have you helped move over to ESI on the research rack?

**Comment by tzumainn** [comment]
I've only worked with Eric Munson on the UKL project; I'd be happy to help others if they're ready!

**Comment by joachimweyl** [comment]
@tzumainn as soon as we are comfortable with the ESI setup on the nodes we can start to move researchers over.

**Comment by tzumainn** [comment]
Do we want to wait for the new MOC ESI controllers that @naved001 is setting up?

**Comment by naved001** [comment]
@tzumainn I think we should let the researchers start using the current deployment. Once we have the new deployment, we can plan the migration.

**Comment by tzumainn** [comment]
Okay! Do we have a policy on how nodes are assigned, or can it be a bit free-for-all right now?

**Comment by joachimweyl** [comment]
For the current researchers let's go with the free-for-all approach. The Policy is in the works but we should get this group of researchers up and running prior to completion of the policy.
@naved001 or @hakasapl did we end up getting any of the FC430s added to ESI in the Research Rack?

**Comment by naved001** [comment]
@joachimweyl the FC430s are registered in ESI but they don't work because we need to manually update the firmware (see issue https://github.com/CCI-MOC/ops-issues/issues/1131) which we decided not to because we wanted to prioritize the FC830s

**Comment by tzumainn** [comment]
Sounds good! What's the best way to prod the researchers? I think I emailed a bunch of them a while ago and got responses ranging from "too busy right now" to "these machines aren't right for me".

**Comment by naved001** [comment]
@msdisme any thoughts on this issue? FC430 vs FC83 for researchers

**Comment by joachimweyl** [comment]
@tzumainn yea, an email to that same chain would probably make sense to let them know the nodes are ready for those who wish to have access. it is worth noting those who do not wish to use these nodes so that we can remove them from the list that we need to move.

**Comment by tzumainn** [comment]
Okay - based on naved's comment it sounds like maybe I should wait for michael to weigh in on the FC430 vs FC830 issue?

**Comment by joachimweyl** [comment]
@tzumainn the plan is to get many of the 430s up and running and turn off some of the 830s. So yes let's hold off on moving researchers over until we can offer them the 430s.
@hakasapl when do we think we can update the firmware on the 430s so that they can be made available in ESI leasing?

**Comment by joachimweyl** [comment]
@naved001 how much effort is updating the FC430s firmware so that they can be used by the researchers? Would you like that to have its own Issue?

**Comment by joachimweyl** [comment]
@tzumainn can you please update the list above with any students already migrated to ESI. We can update more based on once the 430s become available.

**Comment by tzumainn** [comment]
I *think* Han's project is moved; he has three nodes, with two being active. I guess I can't say for certainty that he's not using any non-ESI nodes?

**Comment by joachimweyl** [comment]
We are not concerned with what they have elsewhere just that they are now using ESI. Thank you, I will check Han off.

**Comment by joachimweyl** [comment]
@tzumainn it sounds like all but 2 of the 430s are ready for use. Can you help the other Researchers migrate or confirm they are all done with their projects and do not require migraiton?

**Comment by tzumainn** [comment]
I don't actually think the number of usable nodes has changed all that much, unless I'm unaware of some of the fixes that have been made... ?

**Comment by joachimweyl** [comment]
@naved001 Have the FC430s from [this issue](https://github.com/CCI-MOC/ops-issues/issues/1154) been added to ESI?

**Comment by naved001** [comment]
@joachimweyl I think they are added to ESI but haven't been made available because they failed inspection due to the NIC firmware issue. Once that's done, those nodes will need to be inspected/enrolled to be made available for use.

**Comment by joachimweyl** [comment]
LSVD project became it's own issue.
