### ISSUE TITLE
Find out which racks on the even side of R3-PB we can use (ideally 2)

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#988]
These are UPS enabled racks, at least some of them, and we should make sure the use of this space is prioritized appropriately. 

We are in the process of moving nodes to make space for clearing out old nodes and making even more space for more moves. The hope is that if we can free up enough racks we can get this process moving on multiple fronts.
We need to know what Racks/Cages we can use on the Even side of Row 3 Pod B.

**Comment by msdisme** [comment]
@pjd-nu Hi Peter - can we confirm the number  or racks we may use and the number which are UPS enabled?  

We want to plan the ceph and other infrastructure which would benefit from UPS and realized we needed more details.

**Comment by msdisme** [comment]
@hakasapl did you get the details on this from Greg already?

**Comment by hakasapl** [comment]
No racks are available as of yet. Reorganizing what will happen during the maintenance...
