### ISSUE TITLE
Determine if FPGA/GPUs should be kept for: neu-15-08, neu-17-08, neu-15-12, neu-17-12 and move accordingly

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#989]
Are we keeping the FPGA from neu-15-08 & neu-17-08?
Are we keeping the Tesla P100 (GPU) from neu-15-12 & neu-17-12?

**Comment by hakasapl** [comment]
@msdisme Do we have an answer for this?

**Comment by msdisme** [comment]
re. fpgas - need to check with Ahmed and Martin - will be a delay  - have we a home for them in oct?  Re. Tesla yes - do we have a location to install on the rack we hooked up to NERC?  If so we should coordiante with them and get it there :-).

**Comment by hakasapl** [comment]
We don't have a home to keep them up, but if we want to keep these we just have to leave them on a "not for flax" pallet is all, they don't need to be online.

**Comment by hakasapl** [comment]
@msdisme we have an answer for the FPGAs - how about the GPUs?

**Comment by joachimweyl** [comment]
@hakasapl the P100s should be moved to the open cloud testbed.

**Comment by msdisme** [comment]
Systems going to BU CCDS lab;  @naved001 @asanaull@redhat.com - should we move the entire systems to the basement computer room?

**Comment by hakasapl** [comment]
Scheduled to give the servers on the 8th
