### ISSUE TITLE
Flax:Order switches from FLAX for FX2 racks

### ISSUE THREAD

**Issue by hakasapl** [CCI-MOC/ops-issues#992]
What to Order:
* 10 z9100-ON (Reverse Airflow PSU to Ports) - 2 per rack = 5 racks (initially 5 so 10 switches-msd5/26
* 4 z9100-ON (Normal Airflow Ports to PSU) - Core https://github.com/CCI-MOC/ops-issues/issues/740
* 5 s3048-ON (Reverse Airflow PSU to Ports) - 1 per rack = 5 racks
* 2 s3048-ON (Normal Airflow Ports to PSU) - Core

Requirements:
* Dell OS9
* L3 enabled

**Comment by joachimweyl** [comment]
@hakasapl did these get ordered before you left?

**Comment by joachimweyl** [comment]
@msdisme do we need to meet with Erik prior to ordering these switches?

**Comment by msdisme** [comment]
part of discussion with Eric is going to be moving things to 25 gb and switches

**Comment by msdisme** [comment]
Feedback from Scott - he's ok.  Nick also mentioned cisco switches.    Plan is to order the Dell switches which may be flashed to open source if we head in that direction.

**Comment by msdisme** [comment]
targeting July 10 for racks ready may be end of day on July 11th.

**Comment by hakasapl** [comment]
@msdisme do we know when the switches will arrive?

**Comment by joachimweyl** [comment]
@hakasapl Eric - "we expect to have those early next week & we will bring them to the data center"

**Comment by joachimweyl** [comment]
all switches are at the MGHPCC
