### ISSUE TITLE
Update OpenShift billing tool to include GPU SUs

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/ops-issues#999]
Based on the work done in issue #907 we need to now include the two GPU SUs as described in the [Billing Requirements Documentation](https://docs.google.com/document/d/1SHCMidWQmazACGqzYOlRHQqnsg4KjmeW8ShGiEptR2Q/edit?pli=1).

**Comment by joachimweyl** [comment]
We will calculate GPU SU to use up as many pods as we can to get to the GPU SU size and then charge the rest as CPU SU.
For example
we have 20 Pods, Pod0 uses an A100 GPU and runs for 30 hours. It also has 8 CPU and 32 GB of RAM
Pods1-17 sum up to have another 16 CPU and 64 GB of Ram they run for 730 hrs
Pods18-19 sum up to 2 CPU and 8 GB RAM and ran for 730 hrs
The charge would be for 30 hrs A100 GPU SU, 700 hrs of 16 CPU at 64 GB RAM which is 16 CPU SU, and 730 hrs of 2 CPU and 8 GB RAM which would be 2 CPU SU.

**Comment by naved001** [comment]
I should have closed this earlier, but yes we include GPU SUs.
